from typing import Any

class DropTargetArea(IntEnum):
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    NODE_GRAPH: DropTargetArea = ...
    SHELF: DropTargetArea = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ToolBarArea(IntEnum):
    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

def activateMainWindow(*args, **kwargs) -> Any: ...
def addTab(*args, **kwargs) -> Any: ...
class autosaveReset:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class autosaveTriggered:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def backgroundJobCaption(*args, **kwargs) -> Any: ...
def backgroundJobIDs(*args, **kwargs) -> Any: ...
class backgroundJobsRunning:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def blockSignals(*args, **kwargs) -> Any: ...
class canceledProcessing:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def canvasHeight(*args, **kwargs) -> Any: ...
def canvasWidth(*args, **kwargs) -> Any: ...
def captureDesktop(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def clearScriptOutput(*args, **kwargs) -> Any: ...
def commandPortEnabled(*args, **kwargs) -> Any: ...
def commandPortNumber(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createCustomDisplayWidget(*args, **kwargs) -> Any: ...
def createToolBar(*args, **kwargs) -> Any: ...
def currentMeshPathInGeoLoader(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def decryptString(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
def deleteToolBar(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def enableCommandPort(*args, **kwargs) -> Any: ...
def encryptString(*args, **kwargs) -> Any: ...
class endingProcessing:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def executeDialog(*args, **kwargs) -> Any: ...
def exit(*args, **kwargs) -> Any: ...
class exiting:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def findToolBar(*args, **kwargs) -> Any: ...
class fullScreenChanging:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def geometry(*args, **kwargs) -> Any: ...
def getGeoPluginAttribute(*args, **kwargs) -> Any: ...
def hasPendingPortCommands(*args, **kwargs) -> Any: ...
def inRestrictedVersion(*args, **kwargs) -> Any: ...
def inTerminalMode(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isBackgroundJobFinished(*args, **kwargs) -> Any: ...
def isFullScreen(*args, **kwargs) -> Any: ...
def isMaximized(*args, **kwargs) -> Any: ...
def isMinimized(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isProcessing(*args, **kwargs) -> Any: ...
def isQuickItemType(*args, **kwargs) -> Any: ...
def isRunning(*args, **kwargs) -> Any: ...
def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def lastDropData(*args, **kwargs) -> Any: ...
def launchArgs(*args, **kwargs) -> Any: ...
def launchDir(*args, **kwargs) -> Any: ...
class layoutLoaded:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class layoutSaved:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def loadLayout(*args, **kwargs) -> Any: ...
def log(*args, **kwargs) -> Any: ...
def logFileName(*args, **kwargs) -> Any: ...
def maximize(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def minimize(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def numProcessingSteps(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class onProgress:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def popupsAllowed(*args, **kwargs) -> Any: ...
def processEvents(*args, **kwargs) -> Any: ...
def progress(*args, **kwargs) -> Any: ...
def progressDescription(*args, **kwargs) -> Any: ...
class progressDescriptionChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def quit(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerCustomDropMimeType(*args, **kwargs) -> Any: ...
def registerGeoPluginWidget(*args, **kwargs) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeTab(*args, **kwargs) -> Any: ...
def restore(*args, **kwargs) -> Any: ...
def restoreCursor(*args, **kwargs) -> Any: ...
def resumeProcessing(*args, **kwargs) -> Any: ...
def saveLayout(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setActiveTab(*args, **kwargs) -> Any: ...
def setCommandPortNumber(*args, **kwargs) -> Any: ...
def setFixedCanvasSize(*args, **kwargs) -> Any: ...
def setFullScreen(*args, **kwargs) -> Any: ...
def setGeoPluginAttribute(*args, **kwargs) -> Any: ...
def setGeometry(*args, **kwargs) -> Any: ...
def setNukeConnectionActive(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProgress(*args, **kwargs) -> Any: ...
def setProgressDescription(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setSuppressPopups(*args, **kwargs) -> Any: ...
def setWaitCursor(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startProcessing(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class startingProcessing:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class staticMetaObject:
    class Call(Enum):
        BindableProperty: Call
        CreateInstance: Call
        CustomCall: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call

    class Connection(Object):
        def swap(self, *args, **kwargs) -> Any: ...

    def cast(self, *args, **kwargs) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, *args, **kwargs) -> Any: ...
    def classInfoCount(self, *args, **kwargs) -> Any: ...
    def classInfoOffset(self, *args, **kwargs) -> Any: ...
    def className(self, *args, **kwargs) -> Any: ...
    def connectSlotsByName(self, *args, **kwargs) -> Any: ...
    def constructor(self, *args, **kwargs) -> Any: ...
    def constructorCount(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def disconnectOne(self, *args, **kwargs) -> Any: ...
    def enumerator(self, *args, **kwargs) -> Any: ...
    def enumeratorCount(self, *args, **kwargs) -> Any: ...
    def enumeratorOffset(self, *args, **kwargs) -> Any: ...
    def indexOfClassInfo(self, *args, **kwargs) -> Any: ...
    def indexOfConstructor(self, *args, **kwargs) -> Any: ...
    def indexOfEnumerator(self, *args, **kwargs) -> Any: ...
    def indexOfMethod(self, *args, **kwargs) -> Any: ...
    def indexOfProperty(self, *args, **kwargs) -> Any: ...
    def indexOfSignal(self, *args, **kwargs) -> Any: ...
    def indexOfSlot(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def metaType(self, *args, **kwargs) -> Any: ...
    def method(self, *args, **kwargs) -> Any: ...
    def methodCount(self, *args, **kwargs) -> Any: ...
    def methodOffset(self, *args, **kwargs) -> Any: ...
    def newInstance(self, *args, **kwargs) -> Any: ...
    def normalizedSignature(self, *args, **kwargs) -> Any: ...
    def normalizedType(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def propertyCount(self, *args, **kwargs) -> Any: ...
    def propertyOffset(self, *args, **kwargs) -> Any: ...
    def superClass(self, *args, **kwargs) -> Any: ...
    def userProperty(self, *args, **kwargs) -> Any: ...

def stepProgress(*args, **kwargs) -> Any: ...
def stopProcessing(*args, **kwargs) -> Any: ...
def suppressPopups(*args, **kwargs) -> Any: ...
def suspendProcessing(*args, **kwargs) -> Any: ...
def tabNames(*args, **kwargs) -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def toggleFullScreen(*args, **kwargs) -> Any: ...
def toolBar(*args, **kwargs) -> Any: ...
class toolBarsCreated:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def tr(*args, **kwargs) -> Any: ...
def version(*args, **kwargs) -> Any: ...
def wasProcessingCanceled(*args, **kwargs) -> Any: ...
