from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class DropTargetArea(IntEnum):
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    NODE_GRAPH: DropTargetArea = ...
    SHELF: DropTargetArea = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ToolBarArea(IntEnum):
    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def activateMainWindow(self, *args, **kwargs) -> Any: ...
def addTab(self, *args, **kwargs) -> Any: ...
def autosaveReset(self, *args, **kwargs) -> Any: ...
def autosaveTriggered(self, *args, **kwargs) -> Any: ...
def backgroundJobCaption(self, *args, **kwargs) -> Any: ...
def backgroundJobIDs(self, *args, **kwargs) -> Any: ...
def backgroundJobsRunning(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def canceledProcessing(self, *args, **kwargs) -> Any: ...
def canvasHeight(self, *args, **kwargs) -> Any: ...
def canvasWidth(self, *args, **kwargs) -> Any: ...
def captureDesktop(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def clearScriptOutput(self, *args, **kwargs) -> Any: ...
def commandPortEnabled(self, *args, **kwargs) -> Any: ...
def commandPortNumber(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def createCustomDisplayWidget(self, *args, **kwargs) -> Any: ...
def createToolBar(self, *args, **kwargs) -> Any: ...
def currentMeshPathInGeoLoader(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def decryptString(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def deleteToolBar(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def enableCommandPort(self, *args, **kwargs) -> Any: ...
def encryptString(self, *args, **kwargs) -> Any: ...
def endingProcessing(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def executeDialog(self, *args, **kwargs) -> Any: ...
def exit(self, *args, **kwargs) -> Any: ...
def exiting(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findToolBar(self, *args, **kwargs) -> Any: ...
def fullScreenChanging(self, *args, **kwargs) -> Any: ...
def geometry(self, *args, **kwargs) -> Any: ...
def getGeoPluginAttribute(self, *args, **kwargs) -> Any: ...
def hasPendingPortCommands(self, *args, **kwargs) -> Any: ...
def inRestrictedVersion(self, *args, **kwargs) -> Any: ...
def inTerminalMode(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isBackgroundJobFinished(self, *args, **kwargs) -> Any: ...
def isFullScreen(self, *args, **kwargs) -> Any: ...
def isMaximized(self, *args, **kwargs) -> Any: ...
def isMinimized(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isProcessing(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isRunning(self, *args, **kwargs) -> Any: ...
def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def lastDropData(self, *args, **kwargs) -> Any: ...
def launchArgs(self, *args, **kwargs) -> Any: ...
def launchDir(self, *args, **kwargs) -> Any: ...
def layoutLoaded(self, *args, **kwargs) -> Any: ...
def layoutSaved(self, *args, **kwargs) -> Any: ...
def loadLayout(self, *args, **kwargs) -> Any: ...
def log(self, *args, **kwargs) -> Any: ...
def logFileName(self, *args, **kwargs) -> Any: ...
def maximize(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def minimize(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def numProcessingSteps(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onProgress(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def popupsAllowed(self, *args, **kwargs) -> Any: ...
def processEvents(self, *args, **kwargs) -> Any: ...
def progress(self, *args, **kwargs) -> Any: ...
def progressDescription(self, *args, **kwargs) -> Any: ...
def progressDescriptionChanged(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def quit(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def registerCustomDropMimeType(self, *args, **kwargs) -> Any: ...
def registerGeoPluginWidget(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeTab(self, *args, **kwargs) -> Any: ...
def restore(self, *args, **kwargs) -> Any: ...
def restoreCursor(self, *args, **kwargs) -> Any: ...
def resumeProcessing(self, *args, **kwargs) -> Any: ...
def saveLayout(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setActiveTab(self, *args, **kwargs) -> Any: ...
def setCommandPortNumber(self, *args, **kwargs) -> Any: ...
def setFixedCanvasSize(self, *args, **kwargs) -> Any: ...
def setFullScreen(self, *args, **kwargs) -> Any: ...
def setGeoPluginAttribute(self, *args, **kwargs) -> Any: ...
def setGeometry(self, *args, **kwargs) -> Any: ...
def setNukeConnectionActive(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProgress(self, *args, **kwargs) -> Any: ...
def setProgressDescription(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setSuppressPopups(self, *args, **kwargs) -> Any: ...
def setWaitCursor(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startProcessing(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def startingProcessing(self, *args, **kwargs) -> Any: ...
def stepProgress(self, *args, **kwargs) -> Any: ...
def stopProcessing(self, *args, **kwargs) -> Any: ...
def suppressPopups(self, *args, **kwargs) -> Any: ...
def suspendProcessing(self, *args, **kwargs) -> Any: ...
def tabNames(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def toggleFullScreen(self, *args, **kwargs) -> Any: ...
def toolBar(self, *args, **kwargs) -> Any: ...
def toolBarsCreated(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def version(self, *args, **kwargs) -> Any: ...
def wasProcessingCanceled(self, *args, **kwargs) -> Any: ...
