from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class Stage(IntEnum):
    ALPHA: Stage = ...
    BETA: Stage = ...
    DEV: Stage = ...
    RELEASE: Stage = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def date(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def feature(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def info(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isLinux(self, *args, **kwargs) -> Any: ...
def isMac(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def isWindows(self, *args, **kwargs) -> Any: ...
def iteration(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def major(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def minor(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def number(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def qt(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def revision(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def stage(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def string(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def time(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
