from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntEnum
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import Layer
from mari import Metadata

class AdvancedBlendComponent(IntEnum):
    BLUE_BLEND: AdvancedBlendComponent = ...
    GREEN_BLEND: AdvancedBlendComponent = ...
    GREYSCALE_BLEND: AdvancedBlendComponent = ...
    LUMINANCE_BLEND: AdvancedBlendComponent = ...
    RED_BLEND: AdvancedBlendComponent = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class BlendMode(IntEnum):
    ADD: BlendMode = ...
    ADD_NORMAL_MAPS: BlendMode = ...
    BURN_HIGHLIGHTS: BlendMode = ...
    BURN_MIDRANGE: BlendMode = ...
    BURN_SHADOWS: BlendMode = ...
    CLEAR: BlendMode = ...
    COLOR: BlendMode = ...
    COLOR_BURN: BlendMode = ...
    COLOR_DODGE: BlendMode = ...
    CONTRAST: BlendMode = ...
    COPY: BlendMode = ...
    COPY_RGB: BlendMode = ...
    CUSTOM: BlendMode = ...
    DARKEN: BlendMode = ...
    DECONTRAST: BlendMode = ...
    DIFFERENCE: BlendMode = ...
    DIVIDE: BlendMode = ...
    DODGE_HIGHLIGHTS: BlendMode = ...
    DODGE_MIDRANGE: BlendMode = ...
    DODGE_SHADOWS: BlendMode = ...
    EXCLUSION: BlendMode = ...
    HARD_LIGHT: BlendMode = ...
    HARD_MIX: BlendMode = ...
    HUE: BlendMode = ...
    INVERSE_DIFFERENCE: BlendMode = ...
    INVERT: BlendMode = ...
    LIGHTEN: BlendMode = ...
    LUMINANCE: BlendMode = ...
    MIX: BlendMode = ...
    MIX_NORMAL_MAPS: BlendMode = ...
    MULTIPLY: BlendMode = ...
    NUDGE_FLOW_VECTORS: BlendMode = ...
    NUDGE_NORMAL_VECTORS: BlendMode = ...
    OVERLAY: BlendMode = ...
    PAINT_FLOW_VECTORS: BlendMode = ...
    PAINT_NORMAL_VECTORS: BlendMode = ...
    PIN_LIGHT: BlendMode = ...
    REORIENTED_NORMAL_MAPPING: BlendMode = ...
    SATURATION: BlendMode = ...
    SCALE_VECTORS: BlendMode = ...
    SCREEN: BlendMode = ...
    SOFT_LIGHT: BlendMode = ...
    SPONGE_DESATURATE: BlendMode = ...
    SUBTRACT: BlendMode = ...
    VIVID_LIGHT: BlendMode = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class BlendType(IntEnum):
    ADVANCED_BLEND: BlendType = ...
    BASIC_BLEND: BlendType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MaskType(IntEnum):
    FROM_ALPHA: MaskType = ...
    FROM_SELECTION_GROUP: MaskType = ...
    HIDE_ALL: MaskType = ...
    REVEAL_ALL: MaskType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class SwizzleDestination(IntEnum):
    SWIZZLE_DST_ALPHA: SwizzleDestination = ...
    SWIZZLE_DST_BLUE: SwizzleDestination = ...
    SWIZZLE_DST_GREEN: SwizzleDestination = ...
    SWIZZLE_DST_RED: SwizzleDestination = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class SwizzleSource(IntEnum):
    SWIZZLE_SRC_ALPHA: SwizzleSource = ...
    SWIZZLE_SRC_BLUE: SwizzleSource = ...
    SWIZZLE_SRC_GREEN: SwizzleSource = ...
    SWIZZLE_SRC_ONE: SwizzleSource = ...
    SWIZZLE_SRC_RED: SwizzleSource = ...
    SWIZZLE_SRC_ZERO: SwizzleSource = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def advancedBlendComponentName(*args, **kwargs) -> Any: ...
@staticmethod
def blendModeName(*args, **kwargs) -> Any: ...
@staticmethod
def blendTypeName(*args, **kwargs) -> Any: ...
@staticmethod
def colorTagNames(*args, **kwargs) -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
def activeCacheUpToHereParents(self, *args, **kwargs) -> Any: ...
def advancedBlendComponentStr(self, *args, **kwargs) -> Any: ...
def bake(self, *args, **kwargs) -> Any: ...
def bakedResult(self, *args, **kwargs) -> Any: ...
def blendAmount(self, *args, **kwargs) -> Any: ...
def blendAmountChanged(self, *args, **kwargs) -> Any: ...
def blendAmountEnabled(self, *args, **kwargs) -> Any: ...
def blendComponentChanged(self, *args, **kwargs) -> Any: ...
def blendMode(self, *args, **kwargs) -> Any: ...
def blendModeChanged(self, *args, **kwargs) -> Any: ...
def blendModePath(self, *args, **kwargs) -> Any: ...
def blendModeStr(self, *args, **kwargs) -> Any: ...
def blendType(self, *args, **kwargs) -> Any: ...
def blendTypeChanged(self, *args, **kwargs) -> Any: ...
def blendTypeStr(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def cacheLayer(self, *args, **kwargs) -> Any: ...
def cacheStateChanged(self, *args, **kwargs) -> Any: ...
def cacheUpToHere(self, *args, **kwargs) -> Any: ...
def cacheUpToHereParents(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def close(self, *args, **kwargs) -> Any: ...
def colorTag(self, *args, **kwargs) -> Any: ...
def colorTagChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def convertedToPaint(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteBakedResult(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def getAdvancedBlendComponent(self, *args, **kwargs) -> Any: ...
def getLayerBelowBlendLut(self, *args, **kwargs) -> Any: ...
def getThisLayerBlendLut(self, *args, **kwargs) -> Any: ...
def groupStack(self, *args, **kwargs) -> Any: ...
def hasBakedResult(self, *args, **kwargs) -> Any: ...
def hasCacheUpToHere(self, *args, **kwargs) -> Any: ...
def hasLayerCache(self, *args, **kwargs) -> Any: ...
def hasMask(self, *args, **kwargs) -> Any: ...
def hasMaskCustomProcedural(self, *args, **kwargs) -> Any: ...
def hasMaskStack(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def hash(self, *args, **kwargs) -> Any: ...
def imageHash(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isAdjustableLayer(self, *args, **kwargs) -> Any: ...
def isAdjustmentLayer(self, *args, **kwargs) -> Any: ...
def isBakePointLayer(self, *args, **kwargs) -> Any: ...
def isBakedResultUpToDate(self, *args, **kwargs) -> Any: ...
def isCachedUpToHere(self, *args, **kwargs) -> Any: ...
def isChannelLayer(self, *args, **kwargs) -> Any: ...
def isChildOfActiveCacheUpToHere(self, *args, **kwargs) -> Any: ...
def isChildOfCacheUpToHere(self, *args, **kwargs) -> Any: ...
def isCustomProceduralLayer(self, *args, **kwargs) -> Any: ...
def isGraphLayer(self, *args, **kwargs) -> Any: ...
def isGroupLayer(self, *args, **kwargs) -> Any: ...
def isLayerCached(self, *args, **kwargs) -> Any: ...
def isLocked(self, *args, **kwargs) -> Any: ...
def isMaskEnabled(self, *args, **kwargs) -> Any: ...
def isModifiable(self, *args, **kwargs) -> Any: ...
def isMultiChannelGroupLayer(self, *args, **kwargs) -> Any: ...
def isMultiChannelMaterialLayer(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPaintableLayer(self, *args, **kwargs) -> Any: ...
def isProceduralLayer(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSelected(self, *args, **kwargs) -> Any: ...
def isShaderLayer(self, *args, **kwargs) -> Any: ...
def isShared(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isVisible(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def layerNode(self, *args, **kwargs) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def makeCurrent(self, *args, **kwargs) -> Any: ...
def makeMask(self, *args, **kwargs) -> Any: ...
def makeMaskCustomProcedural(self, *args, **kwargs) -> Any: ...
def makeMaskStack(self, *args, **kwargs) -> Any: ...
def maskCreated(self, *args, **kwargs) -> Any: ...
def maskCustomProceduralNode(self, *args, **kwargs) -> Any: ...
def maskImageSet(self, *args, **kwargs) -> Any: ...
def maskRemoved(self, *args, **kwargs) -> Any: ...
def maskStack(self, *args, **kwargs) -> Any: ...
def maskStackCreated(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def parents(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeMask(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def selectedChanged(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setAdvancedBlendComponent(self, *args, **kwargs) -> Any: ...
def setBlendAmount(self, *args, **kwargs) -> Any: ...
def setBlendAmountEnabled(self, *args, **kwargs) -> Any: ...
def setBlendMode(self, *args, **kwargs) -> Any: ...
def setBlendType(self, *args, **kwargs) -> Any: ...
def setCachedUpToHere(self, *args, **kwargs) -> Any: ...
def setColorTag(self, *args, **kwargs) -> Any: ...
def setLayerBelowBlendLut(self, *args, **kwargs) -> Any: ...
def setLayerCached(self, *args, **kwargs) -> Any: ...
def setLocked(self, *args, **kwargs) -> Any: ...
def setMaskEnabled(self, *args, **kwargs) -> Any: ...
def setMaskImageSet(self, *args, **kwargs) -> Any: ...
def setMaskStack(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setName(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setSelected(self, *args, **kwargs) -> Any: ...
def setSwizzle(self, *args, **kwargs) -> Any: ...
def setThisLayerBlendLut(self, *args, **kwargs) -> Any: ...
def setUseBaked(self, *args, **kwargs) -> Any: ...
def setVisibility(self, *args, **kwargs) -> Any: ...
def siblingSharedLayerList(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def swizzle(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def uncacheLayer(self, *args, **kwargs) -> Any: ...
def uncacheUpToHere(self, *args, **kwargs) -> Any: ...
def useBaked(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
