from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntEnum
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import LayerStack
from mari import Metadata

class ClearSelectionFlag(IntEnum):
    CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
    CLEAR_GROUPS: ClearSelectionFlag = ...
    CLEAR_MASK_STACKS: ClearSelectionFlag = ...
    DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ConvertOption(IntEnum):
    CONVERT_ALL: ConvertOption = ...
    CONVERT_CHANNEL_ONLY: ConvertOption = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class LayerCreateFlag(IntEnum):
    CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
    DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
    INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
    INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
    MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
    SELECT_NEW_LAYERS: LayerCreateFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class LayerImportOption(IntEnum):
    CREATE_NEW_LAYERS: LayerImportOption = ...
    OPTION_NOT_SPECIFIED: LayerImportOption = ...
    SKIP_LAYERS: LayerImportOption = ...
    UPDATE_LAYERS: LayerImportOption = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ResizeMetric(IntEnum):
    RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
    RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
    RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def adjustmentLayerTypeList(*args, **kwargs) -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
@staticmethod
def proceduralLayerTypeList(*args, **kwargs) -> Any: ...
@staticmethod
def transferLayers(*args, **kwargs) -> Any: ...
def bakeTo(self, *args, **kwargs) -> Any: ...
def bleed(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def channelNode(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def clearSelection(self, *args, **kwargs) -> Any: ...
def colorspaceConfig(self, *args, **kwargs) -> Any: ...
def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def convertColorSpaceTo(self, *args, **kwargs) -> Any: ...
def convertColorspaceTo(self, *args, **kwargs) -> Any: ...
def createAdjustmentLayer(self, *args, **kwargs) -> Any: ...
def createBakePointLayer(self, *args, **kwargs) -> Any: ...
def createChannelLayer(self, *args, **kwargs) -> Any: ...
def createCustomProceduralLayer(self, *args, **kwargs) -> Any: ...
def createGraphLayer(self, *args, **kwargs) -> Any: ...
def createGroupLayer(self, *args, **kwargs) -> Any: ...
def createMaterialLayer(self, *args, **kwargs) -> Any: ...
def createMultiChannelGroupLayer(self, *args, **kwargs) -> Any: ...
def createPaintableLayer(self, *args, **kwargs) -> Any: ...
def createProceduralLayer(self, *args, **kwargs) -> Any: ...
def createShaderLayer(self, *args, **kwargs) -> Any: ...
def createSnapshot(self, *args, **kwargs) -> Any: ...
def currentLayer(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def deleteSnapshot(self, *args, **kwargs) -> Any: ...
def depth(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def duplicateLayers(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportImages(self, *args, **kwargs) -> Any: ...
def exportImagesFlattened(self, *args, **kwargs) -> Any: ...
def exportSelectedPatches(self, *args, **kwargs) -> Any: ...
def exportSelectedPatchesFlattened(self, *args, **kwargs) -> Any: ...
def exportToGeoChannel(self, *args, **kwargs) -> Any: ...
def fileSpace(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findLayer(self, *args, **kwargs) -> Any: ...
def findSnapshotWithID(self, *args, **kwargs) -> Any: ...
def flatten(self, *args, **kwargs) -> Any: ...
def geoEntity(self, *args, **kwargs) -> Any: ...
def groupLayers(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def hash(self, *args, **kwargs) -> Any: ...
def height(self, *args, **kwargs) -> Any: ...
def imageHash(self, *args, **kwargs) -> Any: ...
def importImages(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isLocked(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPtex(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isShaderStack(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def layer(self, *args, **kwargs) -> Any: ...
def layerList(self, *args, **kwargs) -> Any: ...
def layerMadeCurrent(self, *args, **kwargs) -> Any: ...
def lock(self, *args, **kwargs) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def makeCurrent(self, *args, **kwargs) -> Any: ...
def mergeLayers(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def metricResize(self, *args, **kwargs) -> Any: ...
def moveLayer(self, *args, **kwargs) -> Any: ...
def moveLayerBelow(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeLayers(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def resize(self, *args, **kwargs) -> Any: ...
def revertToSnapshot(self, *args, **kwargs) -> Any: ...
def scalarColorspaceConfig(self, *args, **kwargs) -> Any: ...
def scalarColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setBleed(self, *args, **kwargs) -> Any: ...
def setColorspaceConfig(self, *args, **kwargs) -> Any: ...
def setCurrentLayer(self, *args, **kwargs) -> Any: ...
def setDepth(self, *args, **kwargs) -> Any: ...
def setFileSpace(self, *args, **kwargs) -> Any: ...
def setLocked(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setName(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setScalarColorspaceConfig(self, *args, **kwargs) -> Any: ...
def shareLayer(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def snapshotAdded(self, *args, **kwargs) -> Any: ...
def snapshotList(self, *args, **kwargs) -> Any: ...
def snapshotRemoved(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def ungroupLayers(self, *args, **kwargs) -> Any: ...
def unlock(self, *args, **kwargs) -> Any: ...
def updateUvImageSizes(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
def width(self, *args, **kwargs) -> Any: ...
