from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def colorspaceConfig(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def depth(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def fileSpace(self, *args, **kwargs) -> Any: ...
def fileTemplate(self, *args, **kwargs) -> Any: ...
def fillColor(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def height(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def path(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def scalarColorspaceConfig(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setColorspaceConfig(self, *args, **kwargs) -> Any: ...
def setDepth(self, *args, **kwargs) -> Any: ...
def setFileSpace(self, *args, **kwargs) -> Any: ...
def setFileTemplate(self, *args, **kwargs) -> Any: ...
def setFillColor(self, *args, **kwargs) -> Any: ...
def setHeight(self, *args, **kwargs) -> Any: ...
def setName(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPath(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setScalarColorspaceConfig(self, *args, **kwargs) -> Any: ...
def setShader(self, *args, **kwargs) -> Any: ...
def setSize(self, *args, **kwargs) -> Any: ...
def setWidth(self, *args, **kwargs) -> Any: ...
def shader(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def size(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def width(self, *args, **kwargs) -> Any: ...
