from typing import Any

def canvas() -> Any: ...
def channel() -> Any: ...
def geo() -> Any: ...
def geoVersion() -> Any: ...
def layer() -> Any: ...
def light() -> Any: ...
def nodeGraph() -> Any: ...
def nodeSelection() -> Any: ...
def project() -> Any: ...
def projector() -> Any: ...
def shader() -> Any: ...
def tool() -> Any: ...
