from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntEnum
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import GroupNode
from mari import Metadata
from mari import Node

class CustomProceduralType(IntEnum):
    CUSTOMPROCEDURAL_TYPE_COLOR: CustomProceduralType = ...
    CUSTOMPROCEDURAL_TYPE_MASK: CustomProceduralType = ...
    CUSTOMPROCEDURAL_TYPE_SCALAR: CustomProceduralType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class PortListMode(IntEnum):
    PORT_LIST_COLLAPSED: PortListMode = ...
    PORT_LIST_EXPANDED: PortListMode = ...
    PORT_LIST_GROUPED: PortListMode = ...
    PORT_LIST_ONLY_CONNECTED: PortListMode = ...
    PORT_LIST_T2B: PortListMode = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
@staticmethod
def readMetadataFromCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def readSystemMetadataFromCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def readTagsFromCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def readThumbnailFromCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def writeMetadataToCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def writeTagsToCustomProceduralFile(*args, **kwargs) -> Any: ...
@staticmethod
def writeThumbnailToCustomProceduralFile(*args, **kwargs) -> Any: ...
def addCustomProceduralTag(self, *args, **kwargs) -> Any: ...
def addCustomProceduralTags(self, *args, **kwargs) -> Any: ...
def addNodeContext(self, *args, **kwargs) -> Any: ...
def addTag(self, *args, **kwargs) -> Any: ...
def attachViewer(self, *args, **kwargs) -> Any: ...
def bake(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def bypassInput(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def childNodeGraph(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def connectSignals(self, *args, **kwargs) -> Any: ...
def convertToCustomProcedural(self, *args, **kwargs) -> Any: ...
def createKnob(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def customProceduralTags(self, *args, **kwargs) -> Any: ...
def customProceduralType(self, *args, **kwargs) -> Any: ...
def deleteKnob(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportCustomProcedural(self, *args, **kwargs) -> Any: ...
def exportToGeoChannel(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def focusInNodeGraph(self, *args, **kwargs) -> Any: ...
def geoChannels(self, *args, **kwargs) -> Any: ...
def getNodeGraphViewContextMeta(self, *args, **kwargs) -> Any: ...
def groupInputNode(self, *args, **kwargs) -> Any: ...
def groupOutputNode(self, *args, **kwargs) -> Any: ...
def hasChanged(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def hasTag(self, *args, **kwargs) -> Any: ...
def hash(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def inputConnection(self, *args, **kwargs) -> Any: ...
def inputNode(self, *args, **kwargs) -> Any: ...
def inputNodeChanged(self, *args, **kwargs) -> Any: ...
def inputPortCount(self, *args, **kwargs) -> Any: ...
def inputPortName(self, *args, **kwargs) -> Any: ...
def inputPortNames(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isBackdropNode(self, *args, **kwargs) -> Any: ...
def isBakePointNode(self, *args, **kwargs) -> Any: ...
def isEnabled(self, *args, **kwargs) -> Any: ...
def isGeoChannelNode(self, *args, **kwargs) -> Any: ...
def isGroupNode(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPaintNode(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSelected(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def knobList(self, *args, **kwargs) -> Any: ...
def linkKnobs(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def missingGeoChannels(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def nodeContext(self, *args, **kwargs) -> Any: ...
def nodeContextNames(self, *args, **kwargs) -> Any: ...
def nodeGraphPosition(self, *args, **kwargs) -> Any: ...
def nodeGraphSize(self, *args, **kwargs) -> Any: ...
def nodeInformation(self, *args, **kwargs) -> Any: ...
def nodePath(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def outputNodes(self, *args, **kwargs) -> Any: ...
def outputPortCount(self, *args, **kwargs) -> Any: ...
def outputPortName(self, *args, **kwargs) -> Any: ...
def outputPortNames(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def parentNodeGraph(self, *args, **kwargs) -> Any: ...
def pathKey(self, *args, **kwargs) -> Any: ...
def portListMode(self, *args, **kwargs) -> Any: ...
def printVersionHashSource(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeCustomProceduralTag(self, *args, **kwargs) -> Any: ...
def removeCustomProceduralTags(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def removeNodeContext(self, *args, **kwargs) -> Any: ...
def removeTag(self, *args, **kwargs) -> Any: ...
def renameKnob(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setBypassInput(self, *args, **kwargs) -> Any: ...
def setCustomProceduralTags(self, *args, **kwargs) -> Any: ...
def setCustomProceduralType(self, *args, **kwargs) -> Any: ...
def setEnabled(self, *args, **kwargs) -> Any: ...
def setInputNode(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setName(self, *args, **kwargs) -> Any: ...
def setNodeGraphPosition(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPortListMode(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setSelected(self, *args, **kwargs) -> Any: ...
def setTypeID(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def tagList(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def typeID(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
