from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntEnum
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import Light
from mari import Metadata

class CubeImageType(IntEnum):
    TYPE_2D_CROSS: CubeImageType = ...
    TYPE_2D_LATLONG: CubeImageType = ...
    TYPE_3D_CUBEMAP: CubeImageType = ...
    TYPE_GUESS: CubeImageType = ...
    TYPE_NONE: CubeImageType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class FixedTo(IntEnum):
    CAMERA: FixedTo = ...
    SCENE: FixedTo = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ImageUpAxis(IntEnum):
    AXIS_UP_X: ImageUpAxis = ...
    AXIS_UP_Y: ImageUpAxis = ...
    AXIS_UP_Z: ImageUpAxis = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class RotationMode(IntEnum):
    MODE_ROTATE: RotationMode = ...
    MODE_STATIC: RotationMode = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def canvasBlur(self, *args, **kwargs) -> Any: ...
def canvasBlurChanged(self, *args, **kwargs) -> Any: ...
def canvasDisplay(self, *args, **kwargs) -> Any: ...
def canvasDisplayChanged(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def clearCubeImageCache(self, *args, **kwargs) -> Any: ...
def clearLightCache(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def cubeImage(self, *args, **kwargs) -> Any: ...
def cubeImageFilename(self, *args, **kwargs) -> Any: ...
def cubeImageFilenameChanged(self, *args, **kwargs) -> Any: ...
def cubeImageResolution(self, *args, **kwargs) -> Any: ...
def cubeImageResolutionChanged(self, *args, **kwargs) -> Any: ...
def cubeImageType(self, *args, **kwargs) -> Any: ...
def cubeImageTypeChanged(self, *args, **kwargs) -> Any: ...
def cubeImageUpAxis(self, *args, **kwargs) -> Any: ...
def cubeImageUpAxisChanged(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def fixedTo(self, *args, **kwargs) -> Any: ...
def fixedToChanged(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def intensity(self, *args, **kwargs) -> Any: ...
def intensityChanged(self, *args, **kwargs) -> Any: ...
def isEnvironmentLight(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isOn(self, *args, **kwargs) -> Any: ...
def isPointLight(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def printLightCacheKeys(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def rotationUp(self, *args, **kwargs) -> Any: ...
def rotationUpChanged(self, *args, **kwargs) -> Any: ...
def rotationUpMode(self, *args, **kwargs) -> Any: ...
def rotationUpModeChanged(self, *args, **kwargs) -> Any: ...
def rotationUpSpeed(self, *args, **kwargs) -> Any: ...
def rotationUpSpeedChanged(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setCanvasBlur(self, *args, **kwargs) -> Any: ...
def setCanvasDisplay(self, *args, **kwargs) -> Any: ...
def setCubeImage(self, *args, **kwargs) -> Any: ...
def setCubeImageResolution(self, *args, **kwargs) -> Any: ...
def setCubeImageType(self, *args, **kwargs) -> Any: ...
def setCubeImageUpAxis(self, *args, **kwargs) -> Any: ...
def setFixedTo(self, *args, **kwargs) -> Any: ...
def setIntensity(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setOn(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setRotationUp(self, *args, **kwargs) -> Any: ...
def setRotationUpMode(self, *args, **kwargs) -> Any: ...
def setRotationUpSpeed(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
