from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class EventCoordinateSpace(IntEnum):
    APPLICATION_SPACE: EventCoordinateSpace = ...
    CANVAS_SPACE: EventCoordinateSpace = ...
    DESKTOP_SPACE: EventCoordinateSpace = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class EventType(IntEnum):
    KEY_PRESS: EventType = ...
    KEY_RELEASE: EventType = ...
    MOUSE_DOUBLE_CLICK: EventType = ...
    MOUSE_MOVE: EventType = ...
    MOUSE_PRESS: EventType = ...
    MOUSE_RELEASE: EventType = ...
    TABLET_ENTER_PROXIMITY: EventType = ...
    TABLET_LEAVE_PROXIMITY: EventType = ...
    TABLET_MOVE: EventType = ...
    TABLET_PRESS: EventType = ...
    TABLET_RELEASE: EventType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class KeyboardModifier(IntEnum):
    ALT_MODIFIER: KeyboardModifier = ...
    CONTROL_MODIFIER: KeyboardModifier = ...
    GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
    KEYPAD_MODIFIER: KeyboardModifier = ...
    META_MODIFIER: KeyboardModifier = ...
    NO_MODIFIER: KeyboardModifier = ...
    SHIFT_MODIFIER: KeyboardModifier = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MouseButton(IntEnum):
    LEFT_BUTTON: MouseButton = ...
    MIDDLE_BUTTON: MouseButton = ...
    NO_BUTTON: MouseButton = ...
    RIGHT_BUTTON: MouseButton = ...
    X_BUTTON_1: MouseButton = ...
    X_BUTTON_2: MouseButton = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPlaying(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def playbackComplete(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def recordPlay(self, *args, **kwargs) -> Any: ...
def recordStart(self, *args, **kwargs) -> Any: ...
def recordStop(self, *args, **kwargs) -> Any: ...
def recordString(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def sendKeyEvent(self, *args, **kwargs) -> Any: ...
def sendMouseEvent(self, *args, **kwargs) -> Any: ...
def sendTabletEvent(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
