from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import Metadata

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def colorspace(self, *args, **kwargs) -> Any: ...
def colorspaceChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def depth(self, *args, **kwargs) -> Any: ...
def depthChanged(self, *args, **kwargs) -> Any: ...
def deserializeFromString(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def errorStringList(self, *args, **kwargs) -> Any: ...
def errorStringListChanged(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportEnabled(self, *args, **kwargs) -> Any: ...
def exportEnabledChanged(self, *args, **kwargs) -> Any: ...
def exportedImagesUniform(self, *args, **kwargs) -> Any: ...
def exportedImagesUniformColor(self, *args, **kwargs) -> Any: ...
def fileOptions(self, *args, **kwargs) -> Any: ...
def fileOptionsChanged(self, *args, **kwargs) -> Any: ...
def fileOptionsString(self, *args, **kwargs) -> Any: ...
def fileTemplate(self, *args, **kwargs) -> Any: ...
def fileTemplateChanged(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def geoEntity(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def imageExported(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def itemExported(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onFileOptionsChanged(self, *args, **kwargs) -> Any: ...
def onItemExported(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def postProcessCommand(self, *args, **kwargs) -> Any: ...
def postProcessCommandChanged(self, *args, **kwargs) -> Any: ...
def postProcessedFileTemplate(self, *args, **kwargs) -> Any: ...
def preferredFileExtension(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def resolution(self, *args, **kwargs) -> Any: ...
def resolutionChanged(self, *args, **kwargs) -> Any: ...
def resolveColorspace(self, *args, **kwargs) -> Any: ...
def resolveDepth(self, *args, **kwargs) -> Any: ...
def resolveDepthAsInternalFormat(self, *args, **kwargs) -> Any: ...
def resolveExportFilePaths(self, *args, **kwargs) -> Any: ...
def resolveFileTemplate(self, *args, **kwargs) -> Any: ...
def resolvePostProcessedFileTemplate(self, *args, **kwargs) -> Any: ...
def resolveResolutionSizes(self, *args, **kwargs) -> Any: ...
def resolvedColorspace(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def serializeToString(self, *args, **kwargs) -> Any: ...
def setColorspace(self, *args, **kwargs) -> Any: ...
def setDepth(self, *args, **kwargs) -> Any: ...
def setErrorStringList(self, *args, **kwargs) -> Any: ...
def setExportEnabled(self, *args, **kwargs) -> Any: ...
def setFileOptions(self, *args, **kwargs) -> Any: ...
def setFileTemplate(self, *args, **kwargs) -> Any: ...
def setGeoEntity(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPostProcessCommand(self, *args, **kwargs) -> Any: ...
def setPostProcessedFileTemplate(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setResolution(self, *args, **kwargs) -> Any: ...
def setSourceNode(self, *args, **kwargs) -> Any: ...
def setUvIndexList(self, *args, **kwargs) -> Any: ...
def setWarningStringList(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def sourceColorspace(self, *args, **kwargs) -> Any: ...
def sourceDepth(self, *args, **kwargs) -> Any: ...
def sourceDepthAsInternalFormat(self, *args, **kwargs) -> Any: ...
def sourceNode(self, *args, **kwargs) -> Any: ...
def sourceNodeChanged(self, *args, **kwargs) -> Any: ...
def sourceNodeDepth(self, *args, **kwargs) -> Any: ...
def sourceNodeName(self, *args, **kwargs) -> Any: ...
def sourceResolution(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
def uvIndexList(self, *args, **kwargs) -> Any: ...
def warningStringList(self, *args, **kwargs) -> Any: ...
def warningStringListChanged(self, *args, **kwargs) -> Any: ...
