from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import Flag
from enum import IntEnum
from enum import IntFlag
from enum import ReprEnum
from mari import API
from mari import Lockable
from mari import Metadata

class ChannelDestroyStrategy(IntEnum):
    DESTROY_ALL: ChannelDestroyStrategy = ...
    DESTROY_NONE: ChannelDestroyStrategy = ...
    DESTROY_UNSHARED: ChannelDestroyStrategy = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataFlag(IntFlag):
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataGroupHint(IntFlag):
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MetadataTypeFlag(IntFlag):
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class SystemShaderType(IntEnum):
    SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(*args, **kwargs) -> Any: ...
@staticmethod
def shaderLayeredTypeList(*args, **kwargs) -> Any: ...
@staticmethod
def shaderStandaloneTypeList(*args, **kwargs) -> Any: ...
@staticmethod
def transferChannels(*args, **kwargs) -> Any: ...
def addLocator(self, *args, **kwargs) -> Any: ...
def addVersion(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def boundingBoxLowerBounds(self, *args, **kwargs) -> Any: ...
def boundingBoxUpperBounds(self, *args, **kwargs) -> Any: ...
def boundingSphereCenter(self, *args, **kwargs) -> Any: ...
def boundingSphereRadius(self, *args, **kwargs) -> Any: ...
def channel(self, *args, **kwargs) -> Any: ...
def channelAdded(self, *args, **kwargs) -> Any: ...
def channelCreated(self, *args, **kwargs) -> Any: ...
def channelList(self, *args, **kwargs) -> Any: ...
def channelMadeCurrent(self, *args, **kwargs) -> Any: ...
def channelRemoved(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def completePatchList(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def createChannel(self, *args, **kwargs) -> Any: ...
def createDuplicateChannel(self, *args, **kwargs) -> Any: ...
def createDuplicateShader(self, *args, **kwargs) -> Any: ...
def createGeoChannel(self, *args, **kwargs) -> Any: ...
def createLayeredShader(self, *args, **kwargs) -> Any: ...
def createPtexChannel(self, *args, **kwargs) -> Any: ...
def createStandaloneShader(self, *args, **kwargs) -> Any: ...
def currentChannel(self, *args, **kwargs) -> Any: ...
def currentImageSet(self, *args, **kwargs) -> Any: ...
def currentShader(self, *args, **kwargs) -> Any: ...
def currentVersion(self, *args, **kwargs) -> Any: ...
def currentVersionName(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportAsArchive(self, *args, **kwargs) -> Any: ...
def findChannel(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findGeoChannel(self, *args, **kwargs) -> Any: ...
def findImageSet(self, *args, **kwargs) -> Any: ...
def findShader(self, *args, **kwargs) -> Any: ...
def generateSubdivision(self, *args, **kwargs) -> Any: ...
def geoChannelAdded(self, *args, **kwargs) -> Any: ...
def geoChannelRemoved(self, *args, **kwargs) -> Any: ...
def geoChannels(self, *args, **kwargs) -> Any: ...
def geometryVersionAdded(self, *args, **kwargs) -> Any: ...
def geometryVersionMadeCurrent(self, *args, **kwargs) -> Any: ...
def geometryVersionRemoved(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, *args, **kwargs) -> Any: ...
def hide(self, *args, **kwargs) -> Any: ...
def hideLocator(self, *args, **kwargs) -> Any: ...
def imageSet(self, *args, **kwargs) -> Any: ...
def imageSetAdded(self, *args, **kwargs) -> Any: ...
def imageSetList(self, *args, **kwargs) -> Any: ...
def imageSetMadeCurrent(self, *args, **kwargs) -> Any: ...
def imageSetNames(self, *args, **kwargs) -> Any: ...
def imageSetRemoved(self, *args, **kwargs) -> Any: ...
def importFromArchive(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def is2DPaintObject(self, *args, **kwargs) -> Any: ...
def isLocked(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPtex(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSelected(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isVisible(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def lock(self, *args, **kwargs) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def maximumSubdivisionLevel(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def metadata(self, *args, **kwargs) -> Any: ...
def metadataAsImage(self, *args, **kwargs) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, *args, **kwargs) -> Any: ...
def metadataDescription(self, *args, **kwargs) -> Any: ...
def metadataDisplayName(self, *args, **kwargs) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, *args, **kwargs) -> Any: ...
def metadataIsEnabled(self, *args, **kwargs) -> Any: ...
def metadataItemList(self, *args, **kwargs) -> Any: ...
def metadataMax(self, *args, **kwargs) -> Any: ...
def metadataMin(self, *args, **kwargs) -> Any: ...
def metadataNames(self, *args, **kwargs) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, *args, **kwargs) -> Any: ...
def metadataTypeFlags(self, *args, **kwargs) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def missingGeoChannels(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def name(self, *args, **kwargs) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def nodeGraph(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def patch(self, *args, **kwargs) -> Any: ...
def patchImage(self, *args, **kwargs) -> Any: ...
def patchList(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def remapSubdivisionSettings(self, *args, **kwargs) -> Any: ...
def removeChannel(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeGeoChannel(self, *args, **kwargs) -> Any: ...
def removeMetadata(self, *args, **kwargs) -> Any: ...
def removeShader(self, *args, **kwargs) -> Any: ...
def removeVersion(self, *args, **kwargs) -> Any: ...
def renameVersion(self, *args, **kwargs) -> Any: ...
def resetHandleTransform(self, *args, **kwargs) -> Any: ...
def save(self, *args, **kwargs) -> Any: ...
def selectedPatches(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setCurrentChannel(self, *args, **kwargs) -> Any: ...
def setCurrentImageSet(self, *args, **kwargs) -> Any: ...
def setCurrentShader(self, *args, **kwargs) -> Any: ...
def setCurrentVersion(self, *args, **kwargs) -> Any: ...
def setLocked(self, *args, **kwargs) -> Any: ...
def setMetadata(self, *args, **kwargs) -> Any: ...
def setMetadataDefault(self, *args, **kwargs) -> Any: ...
def setMetadataDescription(self, *args, **kwargs) -> Any: ...
def setMetadataDisplayName(self, *args, **kwargs) -> Any: ...
def setMetadataEnabled(self, *args, **kwargs) -> Any: ...
def setMetadataFlags(self, *args, **kwargs) -> Any: ...
def setMetadataGroupHints(self, *args, **kwargs) -> Any: ...
def setMetadataItemList(self, *args, **kwargs) -> Any: ...
def setMetadataRange(self, *args, **kwargs) -> Any: ...
def setMetadataStep(self, *args, **kwargs) -> Any: ...
def setMetadataTypeFlags(self, *args, **kwargs) -> Any: ...
def setName(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setSelected(self, *args, **kwargs) -> Any: ...
def setSubdivisionLevel(self, *args, **kwargs) -> Any: ...
def setTransform(self, *args, **kwargs) -> Any: ...
def setVisibility(self, *args, **kwargs) -> Any: ...
def shader(self, *args, **kwargs) -> Any: ...
def shaderCreated(self, *args, **kwargs) -> Any: ...
def shaderList(self, *args, **kwargs) -> Any: ...
def shaderMadeCurrent(self, *args, **kwargs) -> Any: ...
def shaderRemoved(self, *args, **kwargs) -> Any: ...
def show(self, *args, **kwargs) -> Any: ...
def showLocator(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def subdivisionBoundaryInterpolateMethod(self, *args, **kwargs) -> Any: ...
def subdivisionCreasing(self, *args, **kwargs) -> Any: ...
def subdivisionFaceVaryingBoundaryInterpolateMethod(self, *args, **kwargs) -> Any: ...
def subdivisionScheme(self, *args, **kwargs) -> Any: ...
def subdivisionSkippedMeshList(self, *args, **kwargs) -> Any: ...
def subdivisionTriangleSubdivisionRule(self, *args, **kwargs) -> Any: ...
def systemShader(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def transform(self, *args, **kwargs) -> Any: ...
def translation(self, *args, **kwargs) -> Any: ...
def unlock(self, *args, **kwargs) -> Any: ...
def uuid(self, *args, **kwargs) -> Any: ...
def version(self, *args, **kwargs) -> Any: ...
def versionList(self, *args, **kwargs) -> Any: ...
def versionNames(self, *args, **kwargs) -> Any: ...
def visibilityChanged(self, *args, **kwargs) -> Any: ...
