from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class CreateSelectionSetOptions(IntEnum):
    SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
    SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class GeometryImportFlags(IntEnum):
    GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
    GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MergeSelectionGroupWithSameNameType(IntEnum):
    MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
    MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MergeType(IntEnum):
    MERGETYPE_JUST_MERGE_NODES: MergeType = ...
    MERGETYPE_SINGLE_MESH: MergeType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class NodeType(IntEnum):
    CAMERA: NodeType = ...
    FACESET: NodeType = ...
    GROUP: NodeType = ...
    POLYMESH: NodeType = ...
    ROOT: NodeType = ...
    SUBDIV: NodeType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OpenSubdivisionBoundaryInterpolation(IntEnum):
    VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OpenSubdivisionCreasingMethod(IntEnum):
    CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
    CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OpenSubdivisionFaceVaryingInterpolation(IntEnum):
    FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OpenSubdivisionSchemeType(IntEnum):
    SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
    SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
    SCHEME_LOOP: OpenSubdivisionSchemeType = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OpenSubdivisionTriangleSubdivision(IntEnum):
    TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
    TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def addLocator(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def current(self, *args, **kwargs) -> Any: ...
def currentLocator(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def duplicateCurrentGeoEntity(self, *args, **kwargs) -> Any: ...
def duplicateGeoEntity(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def entityAdded(self, *args, **kwargs) -> Any: ...
def entityMadeCurrent(self, *args, **kwargs) -> Any: ...
def entityRemoved(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def find(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def geometryOperationList(self, *args, **kwargs) -> Any: ...
def get(self, *args, **kwargs) -> Any: ...
def getAnimationTakes(self, *args, **kwargs) -> Any: ...
def getDefaultAnimationTake(self, *args, **kwargs) -> Any: ...
def getFileContents(self, *args, **kwargs) -> Any: ...
def getFileFrameRange(self, *args, **kwargs) -> Any: ...
def importFromArchive(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def list(self, *args, **kwargs) -> Any: ...
def listLocators(self, *args, **kwargs) -> Any: ...
def load(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def names(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def recalculatePatchBounds(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def remove(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setCurrent(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def supportedReadFormats(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
