from typing import Any

class ShaderCompileResult(IntEnum):
    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

def applyFilter(*args, **kwargs) -> Any: ...
def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def clearError(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createPostFilterCollection(*args, **kwargs) -> Any: ...
def createQuickApplyGLSL(*args, **kwargs) -> Any: ...
def currentPostFilterCollection(*args, **kwargs) -> Any: ...
class currentPostFilterCollectionModified:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
def deletePostFilterCollection(*args, **kwargs) -> Any: ...
def deregisterCustomCubemapFile(*args, **kwargs) -> Any: ...
def deregisterCustomImagemapFile(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def findFilter(*args, **kwargs) -> Any: ...
def findPostFilterCollection(*args, **kwargs) -> Any: ...
def findQuickApplyFilter(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isCurrentGLShaderProgramValid(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isPostProcessingEnabled(*args, **kwargs) -> Any: ...
def isQuickItemType(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def platformInformation(*args, **kwargs) -> Any: ...
class postFilterCollectionAdded:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def postFilterCollectionNames(*args, **kwargs) -> Any: ...
class postFilterCollectionRemoved:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def postFilterCollections(*args, **kwargs) -> Any: ...
class postProcessingEnabled:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerCustomAdjustmentLayerFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomBlendMode(*args, **kwargs) -> Any: ...
def registerCustomCodeFile(*args, **kwargs) -> Any: ...
def registerCustomCubemapFile(*args, **kwargs) -> Any: ...
def registerCustomDiffuseShaderFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomHeaderFile(*args, **kwargs) -> Any: ...
def registerCustomImagemapFile(*args, **kwargs) -> Any: ...
def registerCustomLayeredShaderFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomNodeFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomNodeUpgrade(*args, **kwargs) -> Any: ...
def registerCustomProceduralLayerFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomSpecularShaderFromXMLFile(*args, **kwargs) -> Any: ...
def registerCustomStandaloneShaderFromXMLFile(*args, **kwargs) -> Any: ...
def reloadXMLDefinitions(*args, **kwargs) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeQuickApplyFilter(*args, **kwargs) -> Any: ...
def runGLSLCode(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
class setCurrentPostFilterCollection:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setPostFilterCollection(*args, **kwargs) -> Any: ...
def setPostProcessingEnabled(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
class shaderCompileComplete:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call(Enum):
        BindableProperty: Call
        CreateInstance: Call
        CustomCall: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call

    class Connection(Object):
        def swap(self, *args, **kwargs) -> Any: ...

    def cast(self, *args, **kwargs) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, *args, **kwargs) -> Any: ...
    def classInfoCount(self, *args, **kwargs) -> Any: ...
    def classInfoOffset(self, *args, **kwargs) -> Any: ...
    def className(self, *args, **kwargs) -> Any: ...
    def connectSlotsByName(self, *args, **kwargs) -> Any: ...
    def constructor(self, *args, **kwargs) -> Any: ...
    def constructorCount(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def disconnectOne(self, *args, **kwargs) -> Any: ...
    def enumerator(self, *args, **kwargs) -> Any: ...
    def enumeratorCount(self, *args, **kwargs) -> Any: ...
    def enumeratorOffset(self, *args, **kwargs) -> Any: ...
    def indexOfClassInfo(self, *args, **kwargs) -> Any: ...
    def indexOfConstructor(self, *args, **kwargs) -> Any: ...
    def indexOfEnumerator(self, *args, **kwargs) -> Any: ...
    def indexOfMethod(self, *args, **kwargs) -> Any: ...
    def indexOfProperty(self, *args, **kwargs) -> Any: ...
    def indexOfSignal(self, *args, **kwargs) -> Any: ...
    def indexOfSlot(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def metaType(self, *args, **kwargs) -> Any: ...
    def method(self, *args, **kwargs) -> Any: ...
    def methodCount(self, *args, **kwargs) -> Any: ...
    def methodOffset(self, *args, **kwargs) -> Any: ...
    def newInstance(self, *args, **kwargs) -> Any: ...
    def normalizedSignature(self, *args, **kwargs) -> Any: ...
    def normalizedType(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def propertyCount(self, *args, **kwargs) -> Any: ...
    def propertyOffset(self, *args, **kwargs) -> Any: ...
    def superClass(self, *args, **kwargs) -> Any: ...
    def userProperty(self, *args, **kwargs) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def upgradeExistingShadersAndLayers(*args, **kwargs) -> Any: ...
