from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class ShaderCompileResult(IntEnum):
    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def deregisterCustomCubemapFile(*args, **kwargs) -> Any: ...
@staticmethod
def deregisterCustomImagemapFile(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomAdjustmentLayerFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomBlendMode(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomCodeFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomCubemapFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomDiffuseShaderFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomHeaderFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomImagemapFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomLayeredShaderFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomNodeFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomNodeUpgrade(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomProceduralLayerFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomSpecularShaderFromXMLFile(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomStandaloneShaderFromXMLFile(*args, **kwargs) -> Any: ...
def applyFilter(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def clearError(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def createPostFilterCollection(self, *args, **kwargs) -> Any: ...
def createQuickApplyGLSL(self, *args, **kwargs) -> Any: ...
def currentPostFilterCollection(self, *args, **kwargs) -> Any: ...
def currentPostFilterCollectionModified(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def deletePostFilterCollection(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findFilter(self, *args, **kwargs) -> Any: ...
def findPostFilterCollection(self, *args, **kwargs) -> Any: ...
def findQuickApplyFilter(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isCurrentGLShaderProgramValid(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPostProcessingEnabled(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def platformInformation(self, *args, **kwargs) -> Any: ...
def postFilterCollectionAdded(self, *args, **kwargs) -> Any: ...
def postFilterCollectionNames(self, *args, **kwargs) -> Any: ...
def postFilterCollectionRemoved(self, *args, **kwargs) -> Any: ...
def postFilterCollections(self, *args, **kwargs) -> Any: ...
def postProcessingEnabled(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def reloadXMLDefinitions(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeQuickApplyFilter(self, *args, **kwargs) -> Any: ...
def runGLSLCode(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setCurrentPostFilterCollection(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPostFilterCollection(self, *args, **kwargs) -> Any: ...
def setPostProcessingEnabled(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def shaderCompileComplete(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def upgradeExistingShadersAndLayers(self, *args, **kwargs) -> Any: ...
