from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import SliderBase
from mari import WidgetBase

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def addToLayout(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disable(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def enable(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def hide(self, *args, **kwargs) -> Any: ...
def hideSlider(self, *args, **kwargs) -> Any: ...
def hideValueEdit(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isEnabled(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isVisible(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def logarithmic(self, *args, **kwargs) -> Any: ...
def maximumHeight(self, *args, **kwargs) -> Any: ...
def maximumWidth(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def minimumHeight(self, *args, **kwargs) -> Any: ...
def minimumWidth(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def precision(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def range(self, *args, **kwargs) -> Any: ...
def rangeMax(self, *args, **kwargs) -> Any: ...
def rangeMin(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setEnabled(self, *args, **kwargs) -> Any: ...
def setLogarithmic(self, *args, **kwargs) -> Any: ...
def setMaximumHeight(self, *args, **kwargs) -> Any: ...
def setMaximumWidth(self, *args, **kwargs) -> Any: ...
def setMinimumHeight(self, *args, **kwargs) -> Any: ...
def setMinimumWidth(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPrecision(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setRange(self, *args, **kwargs) -> Any: ...
def setStatusTip(self, *args, **kwargs) -> Any: ...
def setStepSize(self, *args, **kwargs) -> Any: ...
def setToolTip(self, *args, **kwargs) -> Any: ...
def setValue(self, *args, **kwargs) -> Any: ...
def setVisible(self, *args, **kwargs) -> Any: ...
def show(self, *args, **kwargs) -> Any: ...
def showSlider(self, *args, **kwargs) -> Any: ...
def showValueEdit(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def statusTip(self, *args, **kwargs) -> Any: ...
def stepSize(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def toolTip(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def value(self, *args, **kwargs) -> Any: ...
def valueChanged(self, *args, **kwargs) -> Any: ...
