from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class ColorPickerMode(IntEnum):
    COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
    COLOR_PICKER_OCIO: ColorPickerMode = ...
    COLOR_PICKER_RAW: ColorPickerMode = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def colorPickerMode(self, *args, **kwargs) -> Any: ...
def colorPickerModeChanged(self, *args, **kwargs) -> Any: ...
def colorspace(self, *args, **kwargs) -> Any: ...
def colorspaceCount(self, *args, **kwargs) -> Any: ...
def colorspacePrettyNames(self, *args, **kwargs) -> Any: ...
def configDescription(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def currentColorspaceConfig(self, *args, **kwargs) -> Any: ...
def currentColorspaceDefaults(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def defaultConfig(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def get3DLutValuesFromColorSpaceTransform(self, *args, **kwargs) -> Any: ...
def get3DLutValuesFromDisplayViewTransform(self, *args, **kwargs) -> Any: ...
def get3DLutValuesFromFileTransform(self, *args, **kwargs) -> Any: ...
def hasColorspace(self, *args, **kwargs) -> Any: ...
def hasRole(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isConfigValid(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isShaderTransformAccurate(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isStandardConfig(self, *args, **kwargs) -> Any: ...
def isTargetScalar(self, *args, **kwargs) -> Any: ...
def isTransformValid(self, *args, **kwargs) -> Any: ...
def isViewerScalar(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def lutSize(self, *args, **kwargs) -> Any: ...
def lutSizeChanged(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def parseColorspaceFromString(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def registerConfigUiAllowlist(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def role(self, *args, **kwargs) -> Any: ...
def roleCount(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setColorPickerMode(self, *args, **kwargs) -> Any: ...
def setLutSize(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setShaderTransformAccuracy(self, *args, **kwargs) -> Any: ...
def setShaderTransformCode(self, *args, **kwargs) -> Any: ...
def shaderTransformUsesLut(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def standardConfigPath(self, *args, **kwargs) -> Any: ...
def standardConfigs(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def targetScalarChanged(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def toColorspace(self, *args, **kwargs) -> Any: ...
def toPrettyName(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def transformColor(self, *args, **kwargs) -> Any: ...
def transformImage(self, *args, **kwargs) -> Any: ...
def viewerScalarChanged(self, *args, **kwargs) -> Any: ...
