from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class ExportFlags(IntEnum):
    EXPORT_ALPHA: ExportFlags = ...
    EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
    EXPORT_BITANGENT: ExportFlags = ...
    EXPORT_CENTER_POSITIONS: ExportFlags = ...
    EXPORT_GEOMETRY_ID: ExportFlags = ...
    EXPORT_IGNORE_HIDDEN: ExportFlags = ...
    EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
    EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
    EXPORT_MATCH_IMPORT: ExportFlags = ...
    EXPORT_NORMAL: ExportFlags = ...
    EXPORT_PARTICLE_ID: ExportFlags = ...
    EXPORT_PATCH_ID: ExportFlags = ...
    EXPORT_PIXEL_COORDINATE: ExportFlags = ...
    EXPORT_RADIUS: ExportFlags = ...
    EXPORT_TANGENT: ExportFlags = ...
    EXPORT_UV: ExportFlags = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class ImportFlags(IntEnum):
    IMPORT_BLEED_EDGES: ImportFlags = ...
    IMPORT_CENTER_POSITIONS: ImportFlags = ...
    IMPORT_FLATTEN: ImportFlags = ...
    IMPORT_IGNORE_HIDDEN: ImportFlags = ...
    IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class InterpolationMethod(IntEnum):
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
    INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class RangeUnits(IntEnum):
    RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
    RANGE_INFINITE: RangeUnits = ...
    RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class SearchMethod(IntEnum):
    SEARCH_BACKWARD: SearchMethod = ...
    SEARCH_BIDIRECTIONAL: SearchMethod = ...
    SEARCH_FORWARD: SearchMethod = ...
    SEARCH_RADIAL: SearchMethod = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def availableOps(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportGeo(self, *args, **kwargs) -> Any: ...
def exportImageSets(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findOp(self, *args, **kwargs) -> Any: ...
def importImageSets(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def interpolationMethods(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def rangeUnits(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def searchMethods(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def supportedFileFormats(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def transferChannel(self, *args, **kwargs) -> Any: ...
def transferImageSets(self, *args, **kwargs) -> Any: ...
def transferLayers(self, *args, **kwargs) -> Any: ...
def transferNodes(self, *args, **kwargs) -> Any: ...
