from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def canLinkImageInternals(self, *args, **kwargs) -> Any: ...
def canLinkImages(self, *args, **kwargs) -> Any: ...
def canLinkPatchInternals(self, *args, **kwargs) -> Any: ...
def canLinkPatches(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def generateUniqueGroupName(self, *args, **kwargs) -> Any: ...
def groupAdded(self, *args, **kwargs) -> Any: ...
def groupNames(self, *args, **kwargs) -> Any: ...
def groupNamesForImageSet(self, *args, **kwargs) -> Any: ...
def groupRemoved(self, *args, **kwargs) -> Any: ...
def groupRenamed(self, *args, **kwargs) -> Any: ...
def imageGroup(self, *args, **kwargs) -> Any: ...
def imageUnlinked(self, *args, **kwargs) -> Any: ...
def images(self, *args, **kwargs) -> Any: ...
def imagesLinked(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isImageLinked(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isPatchLinked(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def linkImages(self, *args, **kwargs) -> Any: ...
def linkPatches(self, *args, **kwargs) -> Any: ...
def linkSelectedPatches(self, *args, **kwargs) -> Any: ...
def linkedImages(self, *args, **kwargs) -> Any: ...
def linkedPatches(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def patchGroup(self, *args, **kwargs) -> Any: ...
def patches(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def removeGroup(self, *args, **kwargs) -> Any: ...
def renameGroup(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def unlinkImage(self, *args, **kwargs) -> Any: ...
def unlinkPatch(self, *args, **kwargs) -> Any: ...
def unlinkSelectedPatches(self, *args, **kwargs) -> Any: ...
