from typing import Any

class AllowedVersions(IntEnum):
    ANY: AllowedVersions = ...
    ASK: AllowedVersions = ...
    EXACT: AllowedVersions = ...
    OLDER_OR_EXACT: AllowedVersions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MeshOptions(IntEnum):
    FORCE_EMPTY: MeshOptions = ...
    FORCE_PTEX: MeshOptions = ...
    UV_OR_EMPTY: MeshOptions = ...
    UV_OR_PTEX: MeshOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MultipleGeometryOptions(IntEnum):
    KEEP_SEPARATE: MultipleGeometryOptions = ...
    MERGE_GEOMETRIES: MultipleGeometryOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OCIOOptions(IntEnum):
    OCIO_ASK: OCIOOptions = ...
    OCIO_EXACT: OCIOOptions = ...
    OCIO_REMAP: OCIOOptions = ...
    OCIO_RESET: OCIOOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class PtexFaceSizeScheme(IntEnum):
    PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
    PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class PtexFormat(IntEnum):
    PTEXFORMAT_BYTE: PtexFormat = ...
    PTEXFORMAT_FLOAT: PtexFormat = ...
    PTEXFORMAT_HALF: PtexFormat = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class aboutToArchive:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToClose:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToExport:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToExtractArchive:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToOpen:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToSave:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class aboutToSaveNew:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def archive(*args, **kwargs) -> Any: ...
def archiveBackup(*args, **kwargs) -> Any: ...
class archived:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class backupRestored:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def blockSignals(*args, **kwargs) -> Any: ...
def cachePath(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def close(*args, **kwargs) -> Any: ...
class closed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def copy(*args, **kwargs) -> Any: ...
def create(*args, **kwargs) -> Any: ...
class created:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def current(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def duplicate(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
class exported:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class exportedSummary:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def extract(*args, **kwargs) -> Any: ...
class extractedArchive:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def find(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def generateRestoreSuffix(*args, **kwargs) -> Any: ...
def generateUUID(*args, **kwargs) -> Any: ...
def get(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isQuickItemType(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def lastRestorePoint(*args, **kwargs) -> Any: ...
def list(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def names(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def open(*args, **kwargs) -> Any: ...
class opened:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
class projectDuplicated:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def remove(*args, **kwargs) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def rename(*args, **kwargs) -> Any: ...
def repair(*args, **kwargs) -> Any: ...
def restoreBackup(*args, **kwargs) -> Any: ...
def restorePoints(*args, **kwargs) -> Any: ...
def restoreTags(*args, **kwargs) -> Any: ...
class saved:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def selected(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setRestoreSystemTags(*args, **kwargs) -> Any: ...
def showCreateDialog(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call(Enum):
        BindableProperty: Call
        CreateInstance: Call
        CustomCall: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call

    class Connection(Object):
        def swap(self, *args, **kwargs) -> Any: ...

    def cast(self, *args, **kwargs) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, *args, **kwargs) -> Any: ...
    def classInfoCount(self, *args, **kwargs) -> Any: ...
    def classInfoOffset(self, *args, **kwargs) -> Any: ...
    def className(self, *args, **kwargs) -> Any: ...
    def connectSlotsByName(self, *args, **kwargs) -> Any: ...
    def constructor(self, *args, **kwargs) -> Any: ...
    def constructorCount(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def disconnectOne(self, *args, **kwargs) -> Any: ...
    def enumerator(self, *args, **kwargs) -> Any: ...
    def enumeratorCount(self, *args, **kwargs) -> Any: ...
    def enumeratorOffset(self, *args, **kwargs) -> Any: ...
    def indexOfClassInfo(self, *args, **kwargs) -> Any: ...
    def indexOfConstructor(self, *args, **kwargs) -> Any: ...
    def indexOfEnumerator(self, *args, **kwargs) -> Any: ...
    def indexOfMethod(self, *args, **kwargs) -> Any: ...
    def indexOfProperty(self, *args, **kwargs) -> Any: ...
    def indexOfSignal(self, *args, **kwargs) -> Any: ...
    def indexOfSlot(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def metaType(self, *args, **kwargs) -> Any: ...
    def method(self, *args, **kwargs) -> Any: ...
    def methodCount(self, *args, **kwargs) -> Any: ...
    def methodOffset(self, *args, **kwargs) -> Any: ...
    def newInstance(self, *args, **kwargs) -> Any: ...
    def normalizedSignature(self, *args, **kwargs) -> Any: ...
    def normalizedType(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def propertyCount(self, *args, **kwargs) -> Any: ...
    def propertyOffset(self, *args, **kwargs) -> Any: ...
    def superClass(self, *args, **kwargs) -> Any: ...
    def userProperty(self, *args, **kwargs) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def triggerBackup(*args, **kwargs) -> Any: ...
def updateAvailableProjects(*args, **kwargs) -> Any: ...
