from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from enum import Enum
from enum import IntEnum
from enum import ReprEnum
from mari import API

class AllowedVersions(IntEnum):
    ANY: AllowedVersions = ...
    ASK: AllowedVersions = ...
    EXACT: AllowedVersions = ...
    OLDER_OR_EXACT: AllowedVersions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MeshOptions(IntEnum):
    FORCE_EMPTY: MeshOptions = ...
    FORCE_PTEX: MeshOptions = ...
    UV_OR_EMPTY: MeshOptions = ...
    UV_OR_PTEX: MeshOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class MultipleGeometryOptions(IntEnum):
    KEEP_SEPARATE: MultipleGeometryOptions = ...
    MERGE_GEOMETRIES: MultipleGeometryOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class OCIOOptions(IntEnum):
    OCIO_ASK: OCIOOptions = ...
    OCIO_EXACT: OCIOOptions = ...
    OCIO_REMAP: OCIOOptions = ...
    OCIO_RESET: OCIOOptions = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class PtexFaceSizeScheme(IntEnum):
    PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
    PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

class PtexFormat(IntEnum):
    PTEXFORMAT_BYTE: PtexFormat = ...
    PTEXFORMAT_FLOAT: PtexFormat = ...
    PTEXFORMAT_HALF: PtexFormat = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def generateUUID(*args, **kwargs) -> Any: ...
def aboutToArchive(self, *args, **kwargs) -> Any: ...
def aboutToClose(self, *args, **kwargs) -> Any: ...
def aboutToExport(self, *args, **kwargs) -> Any: ...
def aboutToExtractArchive(self, *args, **kwargs) -> Any: ...
def aboutToOpen(self, *args, **kwargs) -> Any: ...
def aboutToSave(self, *args, **kwargs) -> Any: ...
def aboutToSaveNew(self, *args, **kwargs) -> Any: ...
def archive(self, *args, **kwargs) -> Any: ...
def archiveBackup(self, *args, **kwargs) -> Any: ...
def archived(self, *args, **kwargs) -> Any: ...
def backupRestored(self, *args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def cachePath(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def close(self, *args, **kwargs) -> Any: ...
def closed(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def copy(self, *args, **kwargs) -> Any: ...
def create(self, *args, **kwargs) -> Any: ...
def created(self, *args, **kwargs) -> Any: ...
def current(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def duplicate(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exported(self, *args, **kwargs) -> Any: ...
def exportedSummary(self, *args, **kwargs) -> Any: ...
def extract(self, *args, **kwargs) -> Any: ...
def extractedArchive(self, *args, **kwargs) -> Any: ...
def find(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def generateRestoreSuffix(self, *args, **kwargs) -> Any: ...
def get(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def lastRestorePoint(self, *args, **kwargs) -> Any: ...
def list(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def names(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def open(self, *args, **kwargs) -> Any: ...
def opened(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def projectDuplicated(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def remove(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def rename(self, *args, **kwargs) -> Any: ...
def repair(self, *args, **kwargs) -> Any: ...
def restoreBackup(self, *args, **kwargs) -> Any: ...
def restorePoints(self, *args, **kwargs) -> Any: ...
def restoreTags(self, *args, **kwargs) -> Any: ...
def saved(self, *args, **kwargs) -> Any: ...
def selected(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setRestoreSystemTags(self, *args, **kwargs) -> Any: ...
def showCreateDialog(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
def triggerBackup(self, *args, **kwargs) -> Any: ...
def updateAvailableProjects(self, *args, **kwargs) -> Any: ...
