from typing import Any

fdel: member_descriptor
fget: member_descriptor
fset: member_descriptor
def deleter(self, *args, **kwargs) -> Any: ...
def getter(self, *args, **kwargs) -> Any: ...
def setter(self, *args, **kwargs) -> Any: ...
