from typing import Any

def append(self, *args, **kwargs) -> Any: ...
def capacity(self, *args, **kwargs) -> Any: ...
def clear(self, *args, **kwargs) -> Any: ...
def constData(self, *args, **kwargs) -> Any: ...
def data(self, *args, **kwargs) -> Any: ...
def pop_back(self, *args, **kwargs) -> Any: ...
def pop_front(self, *args, **kwargs) -> Any: ...
def prepend(self, *args, **kwargs) -> Any: ...
def push_back(self, *args, **kwargs) -> Any: ...
def push_front(self, *args, **kwargs) -> Any: ...
def removeFirst(self, *args, **kwargs) -> Any: ...
def removeLast(self, *args, **kwargs) -> Any: ...
def reserve(self, *args, **kwargs) -> Any: ...
