from typing import Any
from PySide6.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
cAPIDocPathKey: str = 'C_API_DOCS'
cAPIExamplesPathKey: str = 'CAPI_EXAMPLES'
certificatesPathKey: str = 'CERTIFICATES'
colorPathKey: str = 'COLOR'
configPathKey: str = 'CONFIG'
defaultArchivePathKey: str = 'MARI_DEFAULT_ARCHIVE_PATH'
defaultCameraPathKey: str = 'MARI_DEFAULT_CAMERA_PATH'
defaultExportNodeGraphPathKey: str = 'MARI_DEFAULT_EXPORT_NODE_GRAPH_PATH'
defaultExportPathKey: str = 'MARI_DEFAULT_EXPORT_PATH'
defaultGeometryPathKey: str = 'MARI_DEFAULT_GEOMETRY_PATH'
defaultImagePathKey: str = 'MARI_DEFAULT_IMAGE_PATH'
defaultImportNodeGraphPathKey: str = 'MARI_DEFAULT_IMPORT_NODE_GRAPH_PATH'
defaultImportPathKey: str = 'MARI_DEFAULT_IMPORT_PATH'
defaultRenderPathKey: str = 'MARI_DEFAULT_RENDER_PATH'
defaultShelfPathKey: str = 'MARI_DEFAULT_SHELF_PATH'
examplesPathKey: str = 'EXAMPLES'
gradientPathKey: str = 'GRADIENTS'
helpPathKey: str = 'HELP'
iconPathKey: str = 'ICONS'
imagePathKey: str = 'IMAGES'
logoPathKey: str = 'LOGOS'
lutPathKey: str = 'LUTS'
mediaPathKey: str = 'MEDIA'
miscPathKey: str = 'MISC'
onlineHelpPathKey: str = 'ONLINE_HELP'
qtPluginsPathKey: str = 'QT_PLUGINS'
scriptDocPathKey: str = 'SCRIPT_DOCS'
settingsPathKey: str = 'SETTINGS'
shaderPathKey: str = 'SHADERS'
sysScriptPathKey: str = 'SCRIPTS'
testPathKey: str = 'TESTDATA'
userPathKey: str = 'MARI_USER_PATH'
userPluginsPathKey: str = 'MARI_PLUGINS_PATH'
userScriptPathKey: str = 'MARI_SCRIPT_PATH'
@staticmethod
def bundledUsdPath(*args, **kwargs) -> Any: ...
@staticmethod
def cAPIDocPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def cAPIExamplesPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def certificatesPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def colorPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def configPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def defaultArchivePathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultCameraPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultExportNodeGraphPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultExportPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultGeometryPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultImagePathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultImportNodeGraphPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultImportPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultRenderPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def defaultShelfPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def examplesPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def gradientPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def helpPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def iconPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def imagePathKey(*args, **kwargs) -> Any: ...
@staticmethod
def logoPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def lutPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def mediaPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def miscPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def onlineHelpPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def qtPluginsPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def scriptDocPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def settingsPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def shaderPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def sysScriptPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def testPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def userPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def userPluginsPathKey(*args, **kwargs) -> Any: ...
@staticmethod
def userScriptPathKey(*args, **kwargs) -> Any: ...
def blockSignals(self, *args, **kwargs) -> Any: ...
def childEvent(self, *args, **kwargs) -> Any: ...
def children(self, *args, **kwargs) -> Any: ...
def connectNotify(self, *args, **kwargs) -> Any: ...
def createIcon(self, *args, **kwargs) -> Any: ...
def customEvent(self, *args, **kwargs) -> Any: ...
def customPluginPaths(self, *args, **kwargs) -> Any: ...
def deleteLater(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disableEnviromentKeyValues(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, *args, **kwargs) -> Any: ...
def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
def dumpObjectTree(self, *args, **kwargs) -> Any: ...
def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
def emit(self, *args, **kwargs) -> Any: ...
def event(self, *args, **kwargs) -> Any: ...
def eventFilter(self, *args, **kwargs) -> Any: ...
def exportSequenceTemplate(self, *args, **kwargs) -> Any: ...
def findChild(self, *args, **kwargs) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def flattenedSequenceTemplate(self, *args, **kwargs) -> Any: ...
def importSequenceTemplate(self, *args, **kwargs) -> Any: ...
def inherits(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, *args, **kwargs) -> Any: ...
def isNull(self, *args, **kwargs) -> Any: ...
def isQuickItemType(self, *args, **kwargs) -> Any: ...
def isSignalConnected(self, *args, **kwargs) -> Any: ...
def isWidgetType(self, *args, **kwargs) -> Any: ...
def isWindowType(self, *args, **kwargs) -> Any: ...
def killTimer(self, *args, **kwargs) -> Any: ...
def logPath(self, *args, **kwargs) -> Any: ...
def metaObject(self, *args, **kwargs) -> Any: ...
def moveToThread(self, *args, **kwargs) -> Any: ...
def objectName(self, *args, **kwargs) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self, *args, **kwargs) -> Any: ...
def path(self, *args, **kwargs) -> Any: ...
def pathList(self, *args, **kwargs) -> Any: ...
def property(self, *args, **kwargs) -> Any: ...
def ptexFlattenedSequenceTemplate(self, *args, **kwargs) -> Any: ...
def ptexSequenceTemplate(self, *args, **kwargs) -> Any: ...
def receivers(self, *args, **kwargs) -> Any: ...
def refreshAllPaths(self, *args, **kwargs) -> Any: ...
def refreshPath(self, *args, **kwargs) -> Any: ...
def removeEventFilter(self, *args, **kwargs) -> Any: ...
def sender(self, *args, **kwargs) -> Any: ...
def senderSignalIndex(self, *args, **kwargs) -> Any: ...
def sequenceTemplate(self, *args, **kwargs) -> Any: ...
def sequenceToken(self, *args, **kwargs) -> Any: ...
def setExportSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setFlattenedSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setImportSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setObjectName(self, *args, **kwargs) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setPath(self, *args, **kwargs) -> Any: ...
def setPathList(self, *args, **kwargs) -> Any: ...
def setProperty(self, *args, **kwargs) -> Any: ...
def setPtexFlattenedSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setPtexSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setSequenceTemplate(self, *args, **kwargs) -> Any: ...
def setSequenceToken(self, *args, **kwargs) -> Any: ...
def settingsFilePath(self, *args, **kwargs) -> Any: ...
def showPDF(self, *args, **kwargs) -> Any: ...
def showURL(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self, *args, **kwargs) -> Any: ...
def startTimer(self, *args, **kwargs) -> Any: ...
def thread(self, *args, **kwargs) -> Any: ...
def timerEvent(self, *args, **kwargs) -> Any: ...
def tr(self, *args, **kwargs) -> Any: ...
