from typing import Any

def blockSignals(*args, **kwargs) -> Any: ...
def bundledUsdPath(*args, **kwargs) -> Any: ...
def cAPIDocPathKey(*args, **kwargs) -> Any: ...
def cAPIExamplesPathKey(*args, **kwargs) -> Any: ...
def certificatesPathKey(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def colorPathKey(*args, **kwargs) -> Any: ...
def configPathKey(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createIcon(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def customPluginPaths(*args, **kwargs) -> Any: ...
def defaultArchivePathKey(*args, **kwargs) -> Any: ...
def defaultCameraPathKey(*args, **kwargs) -> Any: ...
def defaultExportNodeGraphPathKey(*args, **kwargs) -> Any: ...
def defaultExportPathKey(*args, **kwargs) -> Any: ...
def defaultGeometryPathKey(*args, **kwargs) -> Any: ...
def defaultImagePathKey(*args, **kwargs) -> Any: ...
def defaultImportNodeGraphPathKey(*args, **kwargs) -> Any: ...
def defaultImportPathKey(*args, **kwargs) -> Any: ...
def defaultRenderPathKey(*args, **kwargs) -> Any: ...
def defaultShelfPathKey(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def disableEnviromentKeyValues(*args, **kwargs) -> Any: ...
def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def examplesPathKey(*args, **kwargs) -> Any: ...
def exportSequenceTemplate(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def flattenedSequenceTemplate(*args, **kwargs) -> Any: ...
def gradientPathKey(*args, **kwargs) -> Any: ...
def helpPathKey(*args, **kwargs) -> Any: ...
def iconPathKey(*args, **kwargs) -> Any: ...
def imagePathKey(*args, **kwargs) -> Any: ...
def importSequenceTemplate(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isQuickItemType(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def logPath(*args, **kwargs) -> Any: ...
def logoPathKey(*args, **kwargs) -> Any: ...
def lutPathKey(*args, **kwargs) -> Any: ...
def mediaPathKey(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def miscPathKey(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def onlineHelpPathKey(*args, **kwargs) -> Any: ...
def parent(*args, **kwargs) -> Any: ...
def path(*args, **kwargs) -> Any: ...
def pathList(*args, **kwargs) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def ptexFlattenedSequenceTemplate(*args, **kwargs) -> Any: ...
def ptexSequenceTemplate(*args, **kwargs) -> Any: ...
def qtPluginsPathKey(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def refreshAllPaths(*args, **kwargs) -> Any: ...
def refreshPath(*args, **kwargs) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def scriptDocPathKey(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def sequenceTemplate(*args, **kwargs) -> Any: ...
def sequenceToken(*args, **kwargs) -> Any: ...
def setExportSequenceTemplate(*args, **kwargs) -> Any: ...
def setFlattenedSequenceTemplate(*args, **kwargs) -> Any: ...
def setImportSequenceTemplate(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setPath(*args, **kwargs) -> Any: ...
def setPathList(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setPtexFlattenedSequenceTemplate(*args, **kwargs) -> Any: ...
def setPtexSequenceTemplate(*args, **kwargs) -> Any: ...
def setSequenceTemplate(*args, **kwargs) -> Any: ...
def setSequenceToken(*args, **kwargs) -> Any: ...
def settingsFilePath(*args, **kwargs) -> Any: ...
def settingsPathKey(*args, **kwargs) -> Any: ...
def shaderPathKey(*args, **kwargs) -> Any: ...
def showPDF(*args, **kwargs) -> Any: ...
def showURL(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call(Enum):
        BindableProperty: Call
        CreateInstance: Call
        CustomCall: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call

    class Connection(Object):
        def swap(self, *args, **kwargs) -> Any: ...

    def cast(self, *args, **kwargs) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, *args, **kwargs) -> Any: ...
    def classInfoCount(self, *args, **kwargs) -> Any: ...
    def classInfoOffset(self, *args, **kwargs) -> Any: ...
    def className(self, *args, **kwargs) -> Any: ...
    def connectSlotsByName(self, *args, **kwargs) -> Any: ...
    def constructor(self, *args, **kwargs) -> Any: ...
    def constructorCount(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def disconnectOne(self, *args, **kwargs) -> Any: ...
    def enumerator(self, *args, **kwargs) -> Any: ...
    def enumeratorCount(self, *args, **kwargs) -> Any: ...
    def enumeratorOffset(self, *args, **kwargs) -> Any: ...
    def indexOfClassInfo(self, *args, **kwargs) -> Any: ...
    def indexOfConstructor(self, *args, **kwargs) -> Any: ...
    def indexOfEnumerator(self, *args, **kwargs) -> Any: ...
    def indexOfMethod(self, *args, **kwargs) -> Any: ...
    def indexOfProperty(self, *args, **kwargs) -> Any: ...
    def indexOfSignal(self, *args, **kwargs) -> Any: ...
    def indexOfSlot(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def metaType(self, *args, **kwargs) -> Any: ...
    def method(self, *args, **kwargs) -> Any: ...
    def methodCount(self, *args, **kwargs) -> Any: ...
    def methodOffset(self, *args, **kwargs) -> Any: ...
    def newInstance(self, *args, **kwargs) -> Any: ...
    def normalizedSignature(self, *args, **kwargs) -> Any: ...
    def normalizedType(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def propertyCount(self, *args, **kwargs) -> Any: ...
    def propertyOffset(self, *args, **kwargs) -> Any: ...
    def superClass(self, *args, **kwargs) -> Any: ...
    def userProperty(self, *args, **kwargs) -> Any: ...

def sysScriptPathKey(*args, **kwargs) -> Any: ...
def testPathKey(*args, **kwargs) -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def userPathKey(*args, **kwargs) -> Any: ...
def userPluginsPathKey(*args, **kwargs) -> Any: ...
def userScriptPathKey(*args, **kwargs) -> Any: ...
