from typing import Any

class SelectionMode(IntEnum):
    SELECTION_MODE_FACES: SelectionMode = ...
    SELECTION_MODE_OBJECTS: SelectionMode = ...
    SELECTION_MODE_PATCHES: SelectionMode = ...
    denominator: getset_descriptor
    imag: getset_descriptor
    numerator: getset_descriptor
    real: getset_descriptor
    def as_integer_ratio(self) -> Any: ...
    def bit_count(self) -> Any: ...
    def bit_length(self) -> Any: ...
    def conjugate(self, *args, **kwargs) -> Any: ...
    def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
    def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createSelectionGroupFromSelection(*args, **kwargs) -> Any: ...
def current(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
class hiddenChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isQuickItemType(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def list(*args, **kwargs) -> Any: ...
class lockedChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def metaObject(*args, **kwargs) -> Any: ...
class modeChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeSelectionGroup(*args, **kwargs) -> Any: ...
def sceneSelectionMode(*args, **kwargs) -> Any: ...
def select(*args, **kwargs) -> Any: ...
class selectModeChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class selectedChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def selection(*args, **kwargs) -> Any: ...
class selectionGroupAdded:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

class selectionGroupRemoved:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setSelectionMode(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call(Enum):
        BindableProperty: Call
        CreateInstance: Call
        CustomCall: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call

    class Connection(Object):
        def swap(self, *args, **kwargs) -> Any: ...

    def cast(self, *args, **kwargs) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, *args, **kwargs) -> Any: ...
    def classInfoCount(self, *args, **kwargs) -> Any: ...
    def classInfoOffset(self, *args, **kwargs) -> Any: ...
    def className(self, *args, **kwargs) -> Any: ...
    def connectSlotsByName(self, *args, **kwargs) -> Any: ...
    def constructor(self, *args, **kwargs) -> Any: ...
    def constructorCount(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def disconnectOne(self, *args, **kwargs) -> Any: ...
    def enumerator(self, *args, **kwargs) -> Any: ...
    def enumeratorCount(self, *args, **kwargs) -> Any: ...
    def enumeratorOffset(self, *args, **kwargs) -> Any: ...
    def indexOfClassInfo(self, *args, **kwargs) -> Any: ...
    def indexOfConstructor(self, *args, **kwargs) -> Any: ...
    def indexOfEnumerator(self, *args, **kwargs) -> Any: ...
    def indexOfMethod(self, *args, **kwargs) -> Any: ...
    def indexOfProperty(self, *args, **kwargs) -> Any: ...
    def indexOfSignal(self, *args, **kwargs) -> Any: ...
    def indexOfSlot(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def metaType(self, *args, **kwargs) -> Any: ...
    def method(self, *args, **kwargs) -> Any: ...
    def methodCount(self, *args, **kwargs) -> Any: ...
    def methodOffset(self, *args, **kwargs) -> Any: ...
    def newInstance(self, *args, **kwargs) -> Any: ...
    def normalizedSignature(self, *args, **kwargs) -> Any: ...
    def normalizedType(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def propertyCount(self, *args, **kwargs) -> Any: ...
    def propertyOffset(self, *args, **kwargs) -> Any: ...
    def superClass(self, *args, **kwargs) -> Any: ...
    def userProperty(self, *args, **kwargs) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
class visibleChanged:
    def connect(self, *args, **kwargs) -> Any: ...
    def disconnect(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...

