from typing import Any
from PySide6.QtCore import QObject
from PySide6.QtGui import QPaintDevice
from PySide6.QtWidgets import QAbstractButton
from PySide6.QtWidgets import QDialog
from PySide6.QtWidgets import QPushButton
from PySide6.QtWidgets import QWidget
from Shiboken import Object

def checkProjectAndGeoValidity() -> Any: ...
def connect(signal, response) -> Any: ...
def createCustomDisplayWidget(display_name, width, height) -> Any: ...
def disconnect(signal, response) -> Any: ...
def execDialog(dlg) -> Any: ...
def getAutoCompletionCandidates(expression) -> Any: ...
def getExistingDirectory(parent = ..., caption = ..., dir = ...) -> Any: ...
def getOpenFileName(parent = ..., caption = ..., dir = ..., filter = ..., selected_filter = ..., options = ...) -> Any: ...
def getSaveFileName(parent = ..., caption = ..., dir = ..., filter = ..., selected_filter = ..., options = ..., save_filename = ...) -> Any: ...
def getUniqueName(name_base, name_list) -> Any: ...
def incName(name) -> Any: ...
def isFileReadable(root, filename) -> Any: ...
def mariDisabledIcon(fileName) -> Any: ...
def mariIcon(fileName) -> Any: ...
def mariPlainIcon(fileName) -> Any: ...
def message(text, title = ..., buttons = ..., icon = ..., details = ...) -> Any: ...
def messageAndLog(text, title = ..., ui = ..., console = ..., log = ...) -> Any: ...
def messageResult(text, title = ..., buttons = ..., icon = ..., details = ...) -> Any: ...
def registerDropDataCallback(callback, mimeType, dropTarget) -> Any: ...
def reloadAll() -> Any: ...
def setTimer(interval_sec, func, single_shot = ...) -> Any: ...
class CustomHelp:
    def getURL(self, obj) -> Any: ...

class Dialog(QDialog):
    class DialogCode(IntEnum):
        Accepted: DialogCode
        Rejected: DialogCode
        denominator: getset_descriptor
        imag: getset_descriptor
        numerator: getset_descriptor
        real: getset_descriptor
        def as_integer_ratio(self) -> Any: ...
        def bit_count(self) -> Any: ...
        def bit_length(self) -> Any: ...
        def conjugate(self, *args, **kwargs) -> Any: ...
        def from_bytes(bytes, byteorder = ..., signed = ...) -> Any: ...
        def to_bytes(self, length = ..., byteorder = ..., signed = ...) -> Any: ...

    class PaintDeviceMetric(Enum):
        PdmDepth: PaintDeviceMetric
        PdmDevicePixelRatio: PaintDeviceMetric
        PdmDevicePixelRatioScaled: PaintDeviceMetric
        PdmDpiX: PaintDeviceMetric
        PdmDpiY: PaintDeviceMetric
        PdmHeight: PaintDeviceMetric
        PdmHeightMM: PaintDeviceMetric
        PdmNumColors: PaintDeviceMetric
        PdmPhysicalDpiX: PaintDeviceMetric
        PdmPhysicalDpiY: PaintDeviceMetric
        PdmWidth: PaintDeviceMetric
        PdmWidthMM: PaintDeviceMetric

    class RenderFlag(Flag):
        DrawChildren: RenderFlag
        DrawWindowBackground: RenderFlag
        IgnoreMask: RenderFlag

    painters: getset_descriptor
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def createWindowContainer(*args, **kwargs) -> Any: ...
    @staticmethod
    def devicePixelRatioFScale(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def find(*args, **kwargs) -> Any: ...
    @staticmethod
    def keyboardGrabber(*args, **kwargs) -> Any: ...
    @staticmethod
    def mouseGrabber(*args, **kwargs) -> Any: ...
    @staticmethod
    def setTabOrder(*args, **kwargs) -> Any: ...
    def accept(self, *args, **kwargs) -> Any: ...
    def acceptDrops(self, *args, **kwargs) -> Any: ...
    def accepted(self, *args, **kwargs) -> Any: ...
    def accessibleDescription(self, *args, **kwargs) -> Any: ...
    def accessibleName(self, *args, **kwargs) -> Any: ...
    def actionEvent(self, *args, **kwargs) -> Any: ...
    def actions(self, *args, **kwargs) -> Any: ...
    def activateWindow(self, *args, **kwargs) -> Any: ...
    def addAction(self, *args, **kwargs) -> Any: ...
    def addActions(self, *args, **kwargs) -> Any: ...
    def adjustPosition(self, *args, **kwargs) -> Any: ...
    def adjustSize(self, *args, **kwargs) -> Any: ...
    def autoFillBackground(self, *args, **kwargs) -> Any: ...
    def backgroundRole(self, *args, **kwargs) -> Any: ...
    def backingStore(self, *args, **kwargs) -> Any: ...
    def baseSize(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, *args, **kwargs) -> Any: ...
    def changeEvent(self, *args, **kwargs) -> Any: ...
    def childAt(self, *args, **kwargs) -> Any: ...
    def childEvent(self, *args, **kwargs) -> Any: ...
    def children(self, *args, **kwargs) -> Any: ...
    def childrenRect(self, *args, **kwargs) -> Any: ...
    def childrenRegion(self, *args, **kwargs) -> Any: ...
    def clearFocus(self, *args, **kwargs) -> Any: ...
    def clearMask(self, *args, **kwargs) -> Any: ...
    def close(self, *args, **kwargs) -> Any: ...
    def closeEvent(self, *args, **kwargs) -> Any: ...
    def colorCount(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, *args, **kwargs) -> Any: ...
    def contentsMargins(self, *args, **kwargs) -> Any: ...
    def contentsRect(self, *args, **kwargs) -> Any: ...
    def contextMenuEvent(self, *args, **kwargs) -> Any: ...
    def contextMenuPolicy(self, *args, **kwargs) -> Any: ...
    def create(self, *args, **kwargs) -> Any: ...
    def createWinId(self, *args, **kwargs) -> Any: ...
    def cursor(self, *args, **kwargs) -> Any: ...
    def customContextMenuRequested(self, *args, **kwargs) -> Any: ...
    def customEvent(self, *args, **kwargs) -> Any: ...
    def deleteLater(self, *args, **kwargs) -> Any: ...
    def depth(self, *args, **kwargs) -> Any: ...
    def destroy(self, *args, **kwargs) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def devType(self, *args, **kwargs) -> Any: ...
    def devicePixelRatio(self, *args, **kwargs) -> Any: ...
    def devicePixelRatioF(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, *args, **kwargs) -> Any: ...
    def done(self, *args, **kwargs) -> Any: ...
    def dragEnterEvent(self, *args, **kwargs) -> Any: ...
    def dragLeaveEvent(self, *args, **kwargs) -> Any: ...
    def dragMoveEvent(self, *args, **kwargs) -> Any: ...
    def dropEvent(self, *args, **kwargs) -> Any: ...
    def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
    def dumpObjectTree(self, *args, **kwargs) -> Any: ...
    def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
    def effectiveWinId(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...
    def ensurePolished(self, *args, **kwargs) -> Any: ...
    def enterEvent(self, *args, **kwargs) -> Any: ...
    def event(self, *args, **kwargs) -> Any: ...
    def eventFilter(self, *args, **kwargs) -> Any: ...
    def exec(self, *args, **kwargs) -> Any: ...
    def exec_(self, *args, **kwargs) -> Any: ...
    def findChild(self, *args, **kwargs) -> Any: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def finished(self, *args, **kwargs) -> Any: ...
    def focusInEvent(self, *args, **kwargs) -> Any: ...
    def focusNextChild(self, *args, **kwargs) -> Any: ...
    def focusNextPrevChild(self, *args, **kwargs) -> Any: ...
    def focusOutEvent(self, *args, **kwargs) -> Any: ...
    def focusPolicy(self, *args, **kwargs) -> Any: ...
    def focusPreviousChild(self, *args, **kwargs) -> Any: ...
    def focusProxy(self, *args, **kwargs) -> Any: ...
    def focusWidget(self, *args, **kwargs) -> Any: ...
    def font(self, *args, **kwargs) -> Any: ...
    def fontInfo(self, *args, **kwargs) -> Any: ...
    def fontMetrics(self, *args, **kwargs) -> Any: ...
    def foregroundRole(self, *args, **kwargs) -> Any: ...
    def frameGeometry(self, *args, **kwargs) -> Any: ...
    def frameSize(self, *args, **kwargs) -> Any: ...
    def geometry(self, *args, **kwargs) -> Any: ...
    def grab(self, *args, **kwargs) -> Any: ...
    def grabGesture(self, *args, **kwargs) -> Any: ...
    def grabKeyboard(self, *args, **kwargs) -> Any: ...
    def grabMouse(self, *args, **kwargs) -> Any: ...
    def grabShortcut(self, *args, **kwargs) -> Any: ...
    def graphicsEffect(self, *args, **kwargs) -> Any: ...
    def graphicsProxyWidget(self, *args, **kwargs) -> Any: ...
    def hasFocus(self, *args, **kwargs) -> Any: ...
    def hasHeightForWidth(self, *args, **kwargs) -> Any: ...
    def hasMouseTracking(self, *args, **kwargs) -> Any: ...
    def hasTabletTracking(self, *args, **kwargs) -> Any: ...
    def height(self, *args, **kwargs) -> Any: ...
    def heightForWidth(self, *args, **kwargs) -> Any: ...
    def heightMM(self, *args, **kwargs) -> Any: ...
    def hide(self, *args, **kwargs) -> Any: ...
    def hideEvent(self, event) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def initPainter(self, *args, **kwargs) -> Any: ...
    def inputMethodEvent(self, *args, **kwargs) -> Any: ...
    def inputMethodHints(self, *args, **kwargs) -> Any: ...
    def inputMethodQuery(self, *args, **kwargs) -> Any: ...
    def insertAction(self, *args, **kwargs) -> Any: ...
    def insertActions(self, *args, **kwargs) -> Any: ...
    def installEventFilter(self, *args, **kwargs) -> Any: ...
    def internalWinId(self, *args, **kwargs) -> Any: ...
    def isActiveWindow(self, *args, **kwargs) -> Any: ...
    def isAncestorOf(self, *args, **kwargs) -> Any: ...
    def isEnabled(self, *args, **kwargs) -> Any: ...
    def isEnabledTo(self, *args, **kwargs) -> Any: ...
    def isFullScreen(self, *args, **kwargs) -> Any: ...
    def isHidden(self, *args, **kwargs) -> Any: ...
    def isLeftToRight(self, *args, **kwargs) -> Any: ...
    def isMaximized(self, *args, **kwargs) -> Any: ...
    def isMinimized(self, *args, **kwargs) -> Any: ...
    def isModal(self, *args, **kwargs) -> Any: ...
    def isQuickItemType(self, *args, **kwargs) -> Any: ...
    def isRightToLeft(self, *args, **kwargs) -> Any: ...
    def isSignalConnected(self, *args, **kwargs) -> Any: ...
    def isSizeGripEnabled(self, *args, **kwargs) -> Any: ...
    def isTopLevel(self, *args, **kwargs) -> Any: ...
    def isVisible(self, *args, **kwargs) -> Any: ...
    def isVisibleTo(self, *args, **kwargs) -> Any: ...
    def isWidgetType(self, *args, **kwargs) -> Any: ...
    def isWindow(self, *args, **kwargs) -> Any: ...
    def isWindowModified(self, *args, **kwargs) -> Any: ...
    def isWindowType(self, *args, **kwargs) -> Any: ...
    def keyPressEvent(self, *args, **kwargs) -> Any: ...
    def keyReleaseEvent(self, *args, **kwargs) -> Any: ...
    def killTimer(self, *args, **kwargs) -> Any: ...
    def layout(self, *args, **kwargs) -> Any: ...
    def layoutDirection(self, *args, **kwargs) -> Any: ...
    def leaveEvent(self, *args, **kwargs) -> Any: ...
    def locale(self, *args, **kwargs) -> Any: ...
    def logicalDpiX(self, *args, **kwargs) -> Any: ...
    def logicalDpiY(self, *args, **kwargs) -> Any: ...
    def lower(self, *args, **kwargs) -> Any: ...
    def mapFrom(self, *args, **kwargs) -> Any: ...
    def mapFromGlobal(self, *args, **kwargs) -> Any: ...
    def mapFromParent(self, *args, **kwargs) -> Any: ...
    def mapTo(self, *args, **kwargs) -> Any: ...
    def mapToGlobal(self, *args, **kwargs) -> Any: ...
    def mapToParent(self, *args, **kwargs) -> Any: ...
    def mask(self, *args, **kwargs) -> Any: ...
    def maximumHeight(self, *args, **kwargs) -> Any: ...
    def maximumSize(self, *args, **kwargs) -> Any: ...
    def maximumWidth(self, *args, **kwargs) -> Any: ...
    def metaObject(self, *args, **kwargs) -> Any: ...
    def metric(self, *args, **kwargs) -> Any: ...
    def minimumHeight(self, *args, **kwargs) -> Any: ...
    def minimumSize(self, *args, **kwargs) -> Any: ...
    def minimumSizeHint(self, *args, **kwargs) -> Any: ...
    def minimumWidth(self, *args, **kwargs) -> Any: ...
    def mouseDoubleClickEvent(self, *args, **kwargs) -> Any: ...
    def mouseMoveEvent(self, *args, **kwargs) -> Any: ...
    def mousePressEvent(self, *args, **kwargs) -> Any: ...
    def mouseReleaseEvent(self, *args, **kwargs) -> Any: ...
    def move(self, *args, **kwargs) -> Any: ...
    def moveEvent(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, *args, **kwargs) -> Any: ...
    def nativeEvent(self, *args, **kwargs) -> Any: ...
    def nativeParentWidget(self, *args, **kwargs) -> Any: ...
    def nextInFocusChain(self, *args, **kwargs) -> Any: ...
    def normalGeometry(self, *args, **kwargs) -> Any: ...
    def objectName(self, *args, **kwargs) -> Any: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def open(self, *args, **kwargs) -> Any: ...
    def overrideWindowFlags(self, *args, **kwargs) -> Any: ...
    def overrideWindowState(self, *args, **kwargs) -> Any: ...
    def paintEngine(self, *args, **kwargs) -> Any: ...
    def paintEvent(self, *args, **kwargs) -> Any: ...
    def paintingActive(self, *args, **kwargs) -> Any: ...
    def palette(self, *args, **kwargs) -> Any: ...
    def parent(self, *args, **kwargs) -> Any: ...
    def parentWidget(self, *args, **kwargs) -> Any: ...
    def physicalDpiX(self, *args, **kwargs) -> Any: ...
    def physicalDpiY(self, *args, **kwargs) -> Any: ...
    def pos(self, *args, **kwargs) -> Any: ...
    def previousInFocusChain(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def raise_(self, *args, **kwargs) -> Any: ...
    def receivers(self, *args, **kwargs) -> Any: ...
    def rect(self, *args, **kwargs) -> Any: ...
    def redirected(self, *args, **kwargs) -> Any: ...
    def reject(self, *args, **kwargs) -> Any: ...
    def rejected(self, *args, **kwargs) -> Any: ...
    def releaseKeyboard(self, *args, **kwargs) -> Any: ...
    def releaseMouse(self, *args, **kwargs) -> Any: ...
    def releaseShortcut(self, *args, **kwargs) -> Any: ...
    def removeAction(self, *args, **kwargs) -> Any: ...
    def removeEventFilter(self, *args, **kwargs) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def repaint(self, *args, **kwargs) -> Any: ...
    def resize(self, *args, **kwargs) -> Any: ...
    def resizeEvent(self, *args, **kwargs) -> Any: ...
    def restoreGeometry(self, *args, **kwargs) -> Any: ...
    def result(self, *args, **kwargs) -> Any: ...
    def saveGeometry(self, *args, **kwargs) -> Any: ...
    def screen(self, *args, **kwargs) -> Any: ...
    def scroll(self, *args, **kwargs) -> Any: ...
    def sender(self, *args, **kwargs) -> Any: ...
    def senderSignalIndex(self, *args, **kwargs) -> Any: ...
    def setAcceptDrops(self, *args, **kwargs) -> Any: ...
    def setAccessibleDescription(self, *args, **kwargs) -> Any: ...
    def setAccessibleName(self, *args, **kwargs) -> Any: ...
    def setAttribute(self, *args, **kwargs) -> Any: ...
    def setAutoFillBackground(self, *args, **kwargs) -> Any: ...
    def setBackgroundRole(self, *args, **kwargs) -> Any: ...
    def setBaseSize(self, *args, **kwargs) -> Any: ...
    def setContentsMargins(self, *args, **kwargs) -> Any: ...
    def setContextMenuPolicy(self, *args, **kwargs) -> Any: ...
    def setCursor(self, *args, **kwargs) -> Any: ...
    def setDisabled(self, *args, **kwargs) -> Any: ...
    def setEnabled(self, *args, **kwargs) -> Any: ...
    def setFixedHeight(self, *args, **kwargs) -> Any: ...
    def setFixedSize(self, *args, **kwargs) -> Any: ...
    def setFixedWidth(self, *args, **kwargs) -> Any: ...
    def setFocus(self, *args, **kwargs) -> Any: ...
    def setFocusPolicy(self, *args, **kwargs) -> Any: ...
    def setFocusProxy(self, *args, **kwargs) -> Any: ...
    def setFont(self, *args, **kwargs) -> Any: ...
    def setForegroundRole(self, *args, **kwargs) -> Any: ...
    def setGeometry(self, *args, **kwargs) -> Any: ...
    def setGraphicsEffect(self, *args, **kwargs) -> Any: ...
    def setHidden(self, *args, **kwargs) -> Any: ...
    def setInputMethodHints(self, *args, **kwargs) -> Any: ...
    def setLayout(self, *args, **kwargs) -> Any: ...
    def setLayoutDirection(self, *args, **kwargs) -> Any: ...
    def setLocale(self, *args, **kwargs) -> Any: ...
    def setMask(self, *args, **kwargs) -> Any: ...
    def setMaximumHeight(self, *args, **kwargs) -> Any: ...
    def setMaximumSize(self, *args, **kwargs) -> Any: ...
    def setMaximumWidth(self, *args, **kwargs) -> Any: ...
    def setMinimumHeight(self, *args, **kwargs) -> Any: ...
    def setMinimumSize(self, *args, **kwargs) -> Any: ...
    def setMinimumWidth(self, *args, **kwargs) -> Any: ...
    def setModal(self, *args, **kwargs) -> Any: ...
    def setMouseTracking(self, *args, **kwargs) -> Any: ...
    def setObjectName(self, *args, **kwargs) -> Any: ...
    def setPalette(self, *args, **kwargs) -> Any: ...
    def setParent(self, *args, **kwargs) -> Any: ...
    def setProperty(self, *args, **kwargs) -> Any: ...
    def setResult(self, *args, **kwargs) -> Any: ...
    def setScreen(self, *args, **kwargs) -> Any: ...
    def setShortcutAutoRepeat(self, *args, **kwargs) -> Any: ...
    def setShortcutEnabled(self, *args, **kwargs) -> Any: ...
    def setSizeGripEnabled(self, *args, **kwargs) -> Any: ...
    def setSizeIncrement(self, *args, **kwargs) -> Any: ...
    def setSizePolicy(self, *args, **kwargs) -> Any: ...
    def setStatusTip(self, *args, **kwargs) -> Any: ...
    def setStyle(self, *args, **kwargs) -> Any: ...
    def setStyleSheet(self, *args, **kwargs) -> Any: ...
    def setTabletTracking(self, *args, **kwargs) -> Any: ...
    def setToolTip(self, *args, **kwargs) -> Any: ...
    def setToolTipDuration(self, *args, **kwargs) -> Any: ...
    def setUpdatesEnabled(self, *args, **kwargs) -> Any: ...
    def setVisible(self, *args, **kwargs) -> Any: ...
    def setWhatsThis(self, *args, **kwargs) -> Any: ...
    def setWindowFilePath(self, *args, **kwargs) -> Any: ...
    def setWindowFlag(self, *args, **kwargs) -> Any: ...
    def setWindowFlags(self, *args, **kwargs) -> Any: ...
    def setWindowIcon(self, *args, **kwargs) -> Any: ...
    def setWindowIconText(self, *args, **kwargs) -> Any: ...
    def setWindowModality(self, *args, **kwargs) -> Any: ...
    def setWindowModified(self, *args, **kwargs) -> Any: ...
    def setWindowOpacity(self, *args, **kwargs) -> Any: ...
    def setWindowRole(self, *args, **kwargs) -> Any: ...
    def setWindowState(self, *args, **kwargs) -> Any: ...
    def setWindowTitle(self, *args, **kwargs) -> Any: ...
    def sharedPainter(self, *args, **kwargs) -> Any: ...
    def show(self, *args, **kwargs) -> Any: ...
    def showEvent(self, event) -> Any: ...
    def showFullScreen(self, *args, **kwargs) -> Any: ...
    def showMaximized(self, *args, **kwargs) -> Any: ...
    def showMinimized(self, *args, **kwargs) -> Any: ...
    def showNormal(self, *args, **kwargs) -> Any: ...
    def signalsBlocked(self, *args, **kwargs) -> Any: ...
    def size(self, *args, **kwargs) -> Any: ...
    def sizeHint(self, *args, **kwargs) -> Any: ...
    def sizeIncrement(self, *args, **kwargs) -> Any: ...
    def sizePolicy(self, *args, **kwargs) -> Any: ...
    def stackUnder(self, *args, **kwargs) -> Any: ...
    def startTimer(self, *args, **kwargs) -> Any: ...
    def statusTip(self, *args, **kwargs) -> Any: ...
    def style(self, *args, **kwargs) -> Any: ...
    def styleSheet(self, *args, **kwargs) -> Any: ...
    def tabletEvent(self, *args, **kwargs) -> Any: ...
    def testAttribute(self, *args, **kwargs) -> Any: ...
    def thread(self, *args, **kwargs) -> Any: ...
    def timerEvent(self, *args, **kwargs) -> Any: ...
    def toolTip(self, *args, **kwargs) -> Any: ...
    def toolTipDuration(self, *args, **kwargs) -> Any: ...
    def topLevelWidget(self, *args, **kwargs) -> Any: ...
    def tr(self, *args, **kwargs) -> Any: ...
    def underMouse(self, *args, **kwargs) -> Any: ...
    def ungrabGesture(self, *args, **kwargs) -> Any: ...
    def unsetCursor(self, *args, **kwargs) -> Any: ...
    def unsetLayoutDirection(self, *args, **kwargs) -> Any: ...
    def unsetLocale(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def updateGeometry(self, *args, **kwargs) -> Any: ...
    def updateMicroFocus(self, *args, **kwargs) -> Any: ...
    def updatesEnabled(self, *args, **kwargs) -> Any: ...
    def visibleRegion(self, *args, **kwargs) -> Any: ...
    def whatsThis(self, *args, **kwargs) -> Any: ...
    def wheelEvent(self, *args, **kwargs) -> Any: ...
    def width(self, *args, **kwargs) -> Any: ...
    def widthMM(self, *args, **kwargs) -> Any: ...
    def winId(self, *args, **kwargs) -> Any: ...
    def window(self, *args, **kwargs) -> Any: ...
    def windowFilePath(self, *args, **kwargs) -> Any: ...
    def windowFlags(self, *args, **kwargs) -> Any: ...
    def windowHandle(self, *args, **kwargs) -> Any: ...
    def windowIcon(self, *args, **kwargs) -> Any: ...
    def windowIconChanged(self, *args, **kwargs) -> Any: ...
    def windowIconText(self, *args, **kwargs) -> Any: ...
    def windowIconTextChanged(self, *args, **kwargs) -> Any: ...
    def windowModality(self, *args, **kwargs) -> Any: ...
    def windowOpacity(self, *args, **kwargs) -> Any: ...
    def windowRole(self, *args, **kwargs) -> Any: ...
    def windowState(self, *args, **kwargs) -> Any: ...
    def windowTitle(self, *args, **kwargs) -> Any: ...
    def windowTitleChanged(self, *args, **kwargs) -> Any: ...
    def windowType(self, *args, **kwargs) -> Any: ...
    def x(self, *args, **kwargs) -> Any: ...
    def y(self, *args, **kwargs) -> Any: ...

class PushButton(QPushButton):
    painters: getset_descriptor
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def createWindowContainer(*args, **kwargs) -> Any: ...
    @staticmethod
    def devicePixelRatioFScale(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def find(*args, **kwargs) -> Any: ...
    @staticmethod
    def keyboardGrabber(*args, **kwargs) -> Any: ...
    @staticmethod
    def mouseGrabber(*args, **kwargs) -> Any: ...
    @staticmethod
    def setTabOrder(*args, **kwargs) -> Any: ...
    def acceptDrops(self, *args, **kwargs) -> Any: ...
    def accessibleDescription(self, *args, **kwargs) -> Any: ...
    def accessibleName(self, *args, **kwargs) -> Any: ...
    def actionEvent(self, *args, **kwargs) -> Any: ...
    def actions(self, *args, **kwargs) -> Any: ...
    def activateWindow(self, *args, **kwargs) -> Any: ...
    def addAction(self, *args, **kwargs) -> Any: ...
    def addActions(self, *args, **kwargs) -> Any: ...
    def adjustSize(self, *args, **kwargs) -> Any: ...
    def animateClick(self, *args, **kwargs) -> Any: ...
    def autoDefault(self, *args, **kwargs) -> Any: ...
    def autoExclusive(self, *args, **kwargs) -> Any: ...
    def autoFillBackground(self, *args, **kwargs) -> Any: ...
    def autoRepeat(self, *args, **kwargs) -> Any: ...
    def autoRepeatDelay(self, *args, **kwargs) -> Any: ...
    def autoRepeatInterval(self, *args, **kwargs) -> Any: ...
    def backgroundRole(self, *args, **kwargs) -> Any: ...
    def backingStore(self, *args, **kwargs) -> Any: ...
    def baseSize(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, *args, **kwargs) -> Any: ...
    def changeEvent(self, *args, **kwargs) -> Any: ...
    def checkStateSet(self, *args, **kwargs) -> Any: ...
    def childAt(self, *args, **kwargs) -> Any: ...
    def childEvent(self, *args, **kwargs) -> Any: ...
    def children(self, *args, **kwargs) -> Any: ...
    def childrenRect(self, *args, **kwargs) -> Any: ...
    def childrenRegion(self, *args, **kwargs) -> Any: ...
    def clearFocus(self, *args, **kwargs) -> Any: ...
    def clearMask(self, *args, **kwargs) -> Any: ...
    def click(self, *args, **kwargs) -> Any: ...
    def clicked(self, *args, **kwargs) -> Any: ...
    def close(self, *args, **kwargs) -> Any: ...
    def closeEvent(self, *args, **kwargs) -> Any: ...
    def colorCount(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, *args, **kwargs) -> Any: ...
    def contentsMargins(self, *args, **kwargs) -> Any: ...
    def contentsRect(self, *args, **kwargs) -> Any: ...
    def contextMenuEvent(self, *args, **kwargs) -> Any: ...
    def contextMenuPolicy(self, *args, **kwargs) -> Any: ...
    def create(self, *args, **kwargs) -> Any: ...
    def createWinId(self, *args, **kwargs) -> Any: ...
    def cursor(self, *args, **kwargs) -> Any: ...
    def customContextMenuRequested(self, *args, **kwargs) -> Any: ...
    def customEvent(self, *args, **kwargs) -> Any: ...
    def deleteLater(self, *args, **kwargs) -> Any: ...
    def depth(self, *args, **kwargs) -> Any: ...
    def destroy(self, *args, **kwargs) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def devType(self, *args, **kwargs) -> Any: ...
    def devicePixelRatio(self, *args, **kwargs) -> Any: ...
    def devicePixelRatioF(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, *args, **kwargs) -> Any: ...
    def dragEnterEvent(self, *args, **kwargs) -> Any: ...
    def dragLeaveEvent(self, *args, **kwargs) -> Any: ...
    def dragMoveEvent(self, *args, **kwargs) -> Any: ...
    def dropEvent(self, *args, **kwargs) -> Any: ...
    def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
    def dumpObjectTree(self, *args, **kwargs) -> Any: ...
    def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
    def effectiveWinId(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...
    def ensurePolished(self, *args, **kwargs) -> Any: ...
    def enterEvent(self, *args, **kwargs) -> Any: ...
    def event(self, *args, **kwargs) -> Any: ...
    def eventFilter(self, *args, **kwargs) -> Any: ...
    def findChild(self, *args, **kwargs) -> Any: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def focusInEvent(self, *args, **kwargs) -> Any: ...
    def focusNextChild(self, *args, **kwargs) -> Any: ...
    def focusNextPrevChild(self, *args, **kwargs) -> Any: ...
    def focusOutEvent(self, *args, **kwargs) -> Any: ...
    def focusPolicy(self, *args, **kwargs) -> Any: ...
    def focusPreviousChild(self, *args, **kwargs) -> Any: ...
    def focusProxy(self, *args, **kwargs) -> Any: ...
    def focusWidget(self, *args, **kwargs) -> Any: ...
    def font(self, *args, **kwargs) -> Any: ...
    def fontInfo(self, *args, **kwargs) -> Any: ...
    def fontMetrics(self, *args, **kwargs) -> Any: ...
    def foregroundRole(self, *args, **kwargs) -> Any: ...
    def frameGeometry(self, *args, **kwargs) -> Any: ...
    def frameSize(self, *args, **kwargs) -> Any: ...
    def geometry(self, *args, **kwargs) -> Any: ...
    def grab(self, *args, **kwargs) -> Any: ...
    def grabGesture(self, *args, **kwargs) -> Any: ...
    def grabKeyboard(self, *args, **kwargs) -> Any: ...
    def grabMouse(self, *args, **kwargs) -> Any: ...
    def grabShortcut(self, *args, **kwargs) -> Any: ...
    def graphicsEffect(self, *args, **kwargs) -> Any: ...
    def graphicsProxyWidget(self, *args, **kwargs) -> Any: ...
    def group(self, *args, **kwargs) -> Any: ...
    def hasFocus(self, *args, **kwargs) -> Any: ...
    def hasHeightForWidth(self, *args, **kwargs) -> Any: ...
    def hasMouseTracking(self, *args, **kwargs) -> Any: ...
    def hasTabletTracking(self, *args, **kwargs) -> Any: ...
    def height(self, *args, **kwargs) -> Any: ...
    def heightForWidth(self, *args, **kwargs) -> Any: ...
    def heightMM(self, *args, **kwargs) -> Any: ...
    def hide(self, *args, **kwargs) -> Any: ...
    def hideEvent(self, *args, **kwargs) -> Any: ...
    def hitButton(self, *args, **kwargs) -> Any: ...
    def icon(self, *args, **kwargs) -> Any: ...
    def iconSize(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def initPainter(self, *args, **kwargs) -> Any: ...
    def initStyleOption(self, *args, **kwargs) -> Any: ...
    def inputMethodEvent(self, *args, **kwargs) -> Any: ...
    def inputMethodHints(self, *args, **kwargs) -> Any: ...
    def inputMethodQuery(self, *args, **kwargs) -> Any: ...
    def insertAction(self, *args, **kwargs) -> Any: ...
    def insertActions(self, *args, **kwargs) -> Any: ...
    def installEventFilter(self, *args, **kwargs) -> Any: ...
    def internalWinId(self, *args, **kwargs) -> Any: ...
    def isActiveWindow(self, *args, **kwargs) -> Any: ...
    def isAncestorOf(self, *args, **kwargs) -> Any: ...
    def isCheckable(self, *args, **kwargs) -> Any: ...
    def isChecked(self, *args, **kwargs) -> Any: ...
    def isDefault(self, *args, **kwargs) -> Any: ...
    def isDown(self, *args, **kwargs) -> Any: ...
    def isEnabled(self, *args, **kwargs) -> Any: ...
    def isEnabledTo(self, *args, **kwargs) -> Any: ...
    def isFlat(self, *args, **kwargs) -> Any: ...
    def isFullScreen(self, *args, **kwargs) -> Any: ...
    def isHidden(self, *args, **kwargs) -> Any: ...
    def isLeftToRight(self, *args, **kwargs) -> Any: ...
    def isMaximized(self, *args, **kwargs) -> Any: ...
    def isMinimized(self, *args, **kwargs) -> Any: ...
    def isModal(self, *args, **kwargs) -> Any: ...
    def isQuickItemType(self, *args, **kwargs) -> Any: ...
    def isRightToLeft(self, *args, **kwargs) -> Any: ...
    def isSignalConnected(self, *args, **kwargs) -> Any: ...
    def isTopLevel(self, *args, **kwargs) -> Any: ...
    def isVisible(self, *args, **kwargs) -> Any: ...
    def isVisibleTo(self, *args, **kwargs) -> Any: ...
    def isWidgetType(self, *args, **kwargs) -> Any: ...
    def isWindow(self, *args, **kwargs) -> Any: ...
    def isWindowModified(self, *args, **kwargs) -> Any: ...
    def isWindowType(self, *args, **kwargs) -> Any: ...
    def keyPressEvent(self, *args, **kwargs) -> Any: ...
    def keyReleaseEvent(self, *args, **kwargs) -> Any: ...
    def killTimer(self, *args, **kwargs) -> Any: ...
    def layout(self, *args, **kwargs) -> Any: ...
    def layoutDirection(self, *args, **kwargs) -> Any: ...
    def leaveEvent(self, *args, **kwargs) -> Any: ...
    def locale(self, *args, **kwargs) -> Any: ...
    def logicalDpiX(self, *args, **kwargs) -> Any: ...
    def logicalDpiY(self, *args, **kwargs) -> Any: ...
    def lower(self, *args, **kwargs) -> Any: ...
    def mapFrom(self, *args, **kwargs) -> Any: ...
    def mapFromGlobal(self, *args, **kwargs) -> Any: ...
    def mapFromParent(self, *args, **kwargs) -> Any: ...
    def mapTo(self, *args, **kwargs) -> Any: ...
    def mapToGlobal(self, *args, **kwargs) -> Any: ...
    def mapToParent(self, *args, **kwargs) -> Any: ...
    def mask(self, *args, **kwargs) -> Any: ...
    def maximumHeight(self, *args, **kwargs) -> Any: ...
    def maximumSize(self, *args, **kwargs) -> Any: ...
    def maximumWidth(self, *args, **kwargs) -> Any: ...
    def menu(self, *args, **kwargs) -> Any: ...
    def metaObject(self, *args, **kwargs) -> Any: ...
    def metric(self, *args, **kwargs) -> Any: ...
    def minimumHeight(self, *args, **kwargs) -> Any: ...
    def minimumSize(self, *args, **kwargs) -> Any: ...
    def minimumSizeHint(self, *args, **kwargs) -> Any: ...
    def minimumWidth(self, *args, **kwargs) -> Any: ...
    def mouseDoubleClickEvent(self, *args, **kwargs) -> Any: ...
    def mouseMoveEvent(self, *args, **kwargs) -> Any: ...
    def mousePressEvent(self, *args, **kwargs) -> Any: ...
    def mouseReleaseEvent(self, *args, **kwargs) -> Any: ...
    def move(self, *args, **kwargs) -> Any: ...
    def moveEvent(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, *args, **kwargs) -> Any: ...
    def nativeEvent(self, *args, **kwargs) -> Any: ...
    def nativeParentWidget(self, *args, **kwargs) -> Any: ...
    def nextCheckState(self, *args, **kwargs) -> Any: ...
    def nextInFocusChain(self, *args, **kwargs) -> Any: ...
    def normalGeometry(self, *args, **kwargs) -> Any: ...
    def objectName(self, *args, **kwargs) -> Any: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def overrideWindowFlags(self, *args, **kwargs) -> Any: ...
    def overrideWindowState(self, *args, **kwargs) -> Any: ...
    def paintEngine(self, *args, **kwargs) -> Any: ...
    def paintEvent(self, *args, **kwargs) -> Any: ...
    def paintingActive(self, *args, **kwargs) -> Any: ...
    def palette(self, *args, **kwargs) -> Any: ...
    def parent(self, *args, **kwargs) -> Any: ...
    def parentWidget(self, *args, **kwargs) -> Any: ...
    def physicalDpiX(self, *args, **kwargs) -> Any: ...
    def physicalDpiY(self, *args, **kwargs) -> Any: ...
    def pos(self, *args, **kwargs) -> Any: ...
    def pressed(self, *args, **kwargs) -> Any: ...
    def previousInFocusChain(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def raise_(self, *args, **kwargs) -> Any: ...
    def receivers(self, *args, **kwargs) -> Any: ...
    def rect(self, *args, **kwargs) -> Any: ...
    def redirected(self, *args, **kwargs) -> Any: ...
    def releaseKeyboard(self, *args, **kwargs) -> Any: ...
    def releaseMouse(self, *args, **kwargs) -> Any: ...
    def releaseShortcut(self, *args, **kwargs) -> Any: ...
    def released(self, *args, **kwargs) -> Any: ...
    def removeAction(self, *args, **kwargs) -> Any: ...
    def removeEventFilter(self, *args, **kwargs) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def repaint(self, *args, **kwargs) -> Any: ...
    def resize(self, *args, **kwargs) -> Any: ...
    def resizeEvent(self, *args, **kwargs) -> Any: ...
    def restoreGeometry(self, *args, **kwargs) -> Any: ...
    def saveGeometry(self, *args, **kwargs) -> Any: ...
    def screen(self, *args, **kwargs) -> Any: ...
    def scroll(self, *args, **kwargs) -> Any: ...
    def sender(self, *args, **kwargs) -> Any: ...
    def senderSignalIndex(self, *args, **kwargs) -> Any: ...
    def setAcceptDrops(self, *args, **kwargs) -> Any: ...
    def setAccessibleDescription(self, *args, **kwargs) -> Any: ...
    def setAccessibleName(self, *args, **kwargs) -> Any: ...
    def setAttribute(self, *args, **kwargs) -> Any: ...
    def setAutoDefault(self, *args, **kwargs) -> Any: ...
    def setAutoExclusive(self, *args, **kwargs) -> Any: ...
    def setAutoFillBackground(self, *args, **kwargs) -> Any: ...
    def setAutoRepeat(self, *args, **kwargs) -> Any: ...
    def setAutoRepeatDelay(self, *args, **kwargs) -> Any: ...
    def setAutoRepeatInterval(self, *args, **kwargs) -> Any: ...
    def setBackgroundRole(self, *args, **kwargs) -> Any: ...
    def setBaseSize(self, *args, **kwargs) -> Any: ...
    def setCheckable(self, *args, **kwargs) -> Any: ...
    def setChecked(self, *args, **kwargs) -> Any: ...
    def setContentsMargins(self, *args, **kwargs) -> Any: ...
    def setContextMenuPolicy(self, *args, **kwargs) -> Any: ...
    def setCursor(self, *args, **kwargs) -> Any: ...
    def setDefault(self, *args, **kwargs) -> Any: ...
    def setDisabled(self, *args, **kwargs) -> Any: ...
    def setDown(self, *args, **kwargs) -> Any: ...
    def setEnabled(self, *args, **kwargs) -> Any: ...
    def setFixedHeight(self, *args, **kwargs) -> Any: ...
    def setFixedSize(self, *args, **kwargs) -> Any: ...
    def setFixedWidth(self, *args, **kwargs) -> Any: ...
    def setFlat(self, *args, **kwargs) -> Any: ...
    def setFocus(self, *args, **kwargs) -> Any: ...
    def setFocusPolicy(self, *args, **kwargs) -> Any: ...
    def setFocusProxy(self, *args, **kwargs) -> Any: ...
    def setFont(self, *args, **kwargs) -> Any: ...
    def setForegroundRole(self, *args, **kwargs) -> Any: ...
    def setGeometry(self, *args, **kwargs) -> Any: ...
    def setGraphicsEffect(self, *args, **kwargs) -> Any: ...
    def setHidden(self, *args, **kwargs) -> Any: ...
    def setIcon(self, *args, **kwargs) -> Any: ...
    def setIconSize(self, *args, **kwargs) -> Any: ...
    def setInputMethodHints(self, *args, **kwargs) -> Any: ...
    def setLayout(self, *args, **kwargs) -> Any: ...
    def setLayoutDirection(self, *args, **kwargs) -> Any: ...
    def setLocale(self, *args, **kwargs) -> Any: ...
    def setMask(self, *args, **kwargs) -> Any: ...
    def setMaximumHeight(self, *args, **kwargs) -> Any: ...
    def setMaximumSize(self, *args, **kwargs) -> Any: ...
    def setMaximumWidth(self, *args, **kwargs) -> Any: ...
    def setMenu(self, *args, **kwargs) -> Any: ...
    def setMinimumHeight(self, *args, **kwargs) -> Any: ...
    def setMinimumSize(self, *args, **kwargs) -> Any: ...
    def setMinimumWidth(self, *args, **kwargs) -> Any: ...
    def setMouseTracking(self, *args, **kwargs) -> Any: ...
    def setObjectName(self, *args, **kwargs) -> Any: ...
    def setPalette(self, *args, **kwargs) -> Any: ...
    def setParent(self, *args, **kwargs) -> Any: ...
    def setProperty(self, *args, **kwargs) -> Any: ...
    def setScreen(self, *args, **kwargs) -> Any: ...
    def setShortcut(self, *args, **kwargs) -> Any: ...
    def setShortcutAutoRepeat(self, *args, **kwargs) -> Any: ...
    def setShortcutEnabled(self, *args, **kwargs) -> Any: ...
    def setSizeIncrement(self, *args, **kwargs) -> Any: ...
    def setSizePolicy(self, *args, **kwargs) -> Any: ...
    def setStatusTip(self, *args, **kwargs) -> Any: ...
    def setStyle(self, *args, **kwargs) -> Any: ...
    def setStyleSheet(self, *args, **kwargs) -> Any: ...
    def setTabletTracking(self, *args, **kwargs) -> Any: ...
    def setText(self, *args, **kwargs) -> Any: ...
    def setToolTip(self, *args, **kwargs) -> Any: ...
    def setToolTipDuration(self, *args, **kwargs) -> Any: ...
    def setUpdatesEnabled(self, *args, **kwargs) -> Any: ...
    def setVisible(self, *args, **kwargs) -> Any: ...
    def setWhatsThis(self, *args, **kwargs) -> Any: ...
    def setWindowFilePath(self, *args, **kwargs) -> Any: ...
    def setWindowFlag(self, *args, **kwargs) -> Any: ...
    def setWindowFlags(self, *args, **kwargs) -> Any: ...
    def setWindowIcon(self, *args, **kwargs) -> Any: ...
    def setWindowIconText(self, *args, **kwargs) -> Any: ...
    def setWindowModality(self, *args, **kwargs) -> Any: ...
    def setWindowModified(self, *args, **kwargs) -> Any: ...
    def setWindowOpacity(self, *args, **kwargs) -> Any: ...
    def setWindowRole(self, *args, **kwargs) -> Any: ...
    def setWindowState(self, *args, **kwargs) -> Any: ...
    def setWindowTitle(self, *args, **kwargs) -> Any: ...
    def sharedPainter(self, *args, **kwargs) -> Any: ...
    def shortcut(self, *args, **kwargs) -> Any: ...
    def show(self, *args, **kwargs) -> Any: ...
    def showEvent(self, *args, **kwargs) -> Any: ...
    def showFullScreen(self, *args, **kwargs) -> Any: ...
    def showMaximized(self, *args, **kwargs) -> Any: ...
    def showMenu(self, *args, **kwargs) -> Any: ...
    def showMinimized(self, *args, **kwargs) -> Any: ...
    def showNormal(self, *args, **kwargs) -> Any: ...
    def signalsBlocked(self, *args, **kwargs) -> Any: ...
    def size(self, *args, **kwargs) -> Any: ...
    def sizeHint(self, *args, **kwargs) -> Any: ...
    def sizeIncrement(self, *args, **kwargs) -> Any: ...
    def sizePolicy(self, *args, **kwargs) -> Any: ...
    def stackUnder(self, *args, **kwargs) -> Any: ...
    def startTimer(self, *args, **kwargs) -> Any: ...
    def statusTip(self, *args, **kwargs) -> Any: ...
    def style(self, *args, **kwargs) -> Any: ...
    def styleSheet(self, *args, **kwargs) -> Any: ...
    def tabletEvent(self, *args, **kwargs) -> Any: ...
    def testAttribute(self, *args, **kwargs) -> Any: ...
    def text(self, *args, **kwargs) -> Any: ...
    def thread(self, *args, **kwargs) -> Any: ...
    def timerEvent(self, *args, **kwargs) -> Any: ...
    def toggle(self, *args, **kwargs) -> Any: ...
    def toggled(self, *args, **kwargs) -> Any: ...
    def toolTip(self, *args, **kwargs) -> Any: ...
    def toolTipDuration(self, *args, **kwargs) -> Any: ...
    def topLevelWidget(self, *args, **kwargs) -> Any: ...
    def tr(self, *args, **kwargs) -> Any: ...
    def underMouse(self, *args, **kwargs) -> Any: ...
    def ungrabGesture(self, *args, **kwargs) -> Any: ...
    def unsetCursor(self, *args, **kwargs) -> Any: ...
    def unsetLayoutDirection(self, *args, **kwargs) -> Any: ...
    def unsetLocale(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def updateGeometry(self, *args, **kwargs) -> Any: ...
    def updateMicroFocus(self, *args, **kwargs) -> Any: ...
    def updatesEnabled(self, *args, **kwargs) -> Any: ...
    def visibleRegion(self, *args, **kwargs) -> Any: ...
    def whatsThis(self, *args, **kwargs) -> Any: ...
    def wheelEvent(self, *args, **kwargs) -> Any: ...
    def width(self, *args, **kwargs) -> Any: ...
    def widthMM(self, *args, **kwargs) -> Any: ...
    def winId(self, *args, **kwargs) -> Any: ...
    def window(self, *args, **kwargs) -> Any: ...
    def windowFilePath(self, *args, **kwargs) -> Any: ...
    def windowFlags(self, *args, **kwargs) -> Any: ...
    def windowHandle(self, *args, **kwargs) -> Any: ...
    def windowIcon(self, *args, **kwargs) -> Any: ...
    def windowIconChanged(self, *args, **kwargs) -> Any: ...
    def windowIconText(self, *args, **kwargs) -> Any: ...
    def windowIconTextChanged(self, *args, **kwargs) -> Any: ...
    def windowModality(self, *args, **kwargs) -> Any: ...
    def windowOpacity(self, *args, **kwargs) -> Any: ...
    def windowRole(self, *args, **kwargs) -> Any: ...
    def windowState(self, *args, **kwargs) -> Any: ...
    def windowTitle(self, *args, **kwargs) -> Any: ...
    def windowTitleChanged(self, *args, **kwargs) -> Any: ...
    def windowType(self, *args, **kwargs) -> Any: ...
    def x(self, *args, **kwargs) -> Any: ...
    def y(self, *args, **kwargs) -> Any: ...

class PushButtonIconSetter(QObject):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    def blockSignals(self, *args, **kwargs) -> Any: ...
    def childEvent(self, *args, **kwargs) -> Any: ...
    def children(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, *args, **kwargs) -> Any: ...
    def customEvent(self, *args, **kwargs) -> Any: ...
    def deleteLater(self, *args, **kwargs) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, *args, **kwargs) -> Any: ...
    def dumpObjectInfo(self, *args, **kwargs) -> Any: ...
    def dumpObjectTree(self, *args, **kwargs) -> Any: ...
    def dynamicPropertyNames(self, *args, **kwargs) -> Any: ...
    def emit(self, *args, **kwargs) -> Any: ...
    def event(self, *args, **kwargs) -> Any: ...
    def eventFilter(self, watched, event) -> Any: ...
    def findChild(self, *args, **kwargs) -> Any: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def inherits(self, *args, **kwargs) -> Any: ...
    def installEventFilter(self, *args, **kwargs) -> Any: ...
    def isQuickItemType(self, *args, **kwargs) -> Any: ...
    def isSignalConnected(self, *args, **kwargs) -> Any: ...
    def isWidgetType(self, *args, **kwargs) -> Any: ...
    def isWindowType(self, *args, **kwargs) -> Any: ...
    def killTimer(self, *args, **kwargs) -> Any: ...
    def metaObject(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, *args, **kwargs) -> Any: ...
    def objectName(self, *args, **kwargs) -> Any: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self, *args, **kwargs) -> Any: ...
    def property(self, *args, **kwargs) -> Any: ...
    def receivers(self, *args, **kwargs) -> Any: ...
    def removeEventFilter(self, *args, **kwargs) -> Any: ...
    def sender(self, *args, **kwargs) -> Any: ...
    def senderSignalIndex(self, *args, **kwargs) -> Any: ...
    def setObjectName(self, *args, **kwargs) -> Any: ...
    def setParent(self, *args, **kwargs) -> Any: ...
    def setProperty(self, *args, **kwargs) -> Any: ...
    def signalsBlocked(self, *args, **kwargs) -> Any: ...
    def startTimer(self, *args, **kwargs) -> Any: ...
    def thread(self, *args, **kwargs) -> Any: ...
    def timerEvent(self, *args, **kwargs) -> Any: ...
    def tr(self, *args, **kwargs) -> Any: ...

