from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShortcutGroup:
    APPLICATION: ShortcutGroup = ...
    NODE_GRAPH: ShortcutGroup = ...
    name: getset_descriptor
    values: dict

APPLICATION: ShortcutGroup = ...
NODE_GRAPH: ShortcutGroup = ...
staticMetaObject: QMetaObject
APPLICATION: ShortcutGroup = ...
NODE_GRAPH: ShortcutGroup = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def actionFromShortcut(self, Shortcut, Group = ...) -> Any: ...
def addToSet(self, SetName, pAction) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def create(self, rIdentifier, rCommand) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disableSet(self, SetName) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def enableSet(self, SetName) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def find(self, rPath) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def get(self, rPath) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def list(self, rPath = ...) -> Any: ...
def loadUserShortcuts(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeFromSet(self, SetName, pAction) -> Any: ...
def removeShortcut(self, Path, Shortcut = ..., Group = ...) -> Any: ...
def removeShortcuts(self, Path, Group = ...) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setShortcut(self, Path, Shortcut, Group = ...) -> Any: ...
def sets(self) -> Any: ...
def shortcut(self, Path, Group = ...) -> Any: ...
def shortcutIsInUse(self, Shortcut, Group = ...) -> Any: ...
def shortcuts(self, Path, Group = ...) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
