from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShortcutGroup:
    APPLICATION: ShortcutGroup = ...
    NODE_GRAPH: ShortcutGroup = ...
    name: getset_descriptor
    values: dict

APPLICATION: ShortcutGroup = ...
NODE_GRAPH: ShortcutGroup = ...
staticMetaObject: QMetaObject
APPLICATION: ShortcutGroup = ...
NODE_GRAPH: ShortcutGroup = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def actionFromShortcut(Shortcut: str, Group = ...) -> str: ...
def addToSet(SetName: str, pAction: mari.Action) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def create(rIdentifier: str, rCommand: str) -> mari.ScriptAction: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disableSet(SetName: str) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def enableSet(SetName: str) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def find(rPath: str) -> mari.Action: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def get(rPath: str) -> mari.Action: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def list(rPath: str = ...) -> typing.List: ...
def loadUserShortcuts() -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeFromSet(SetName: str, pAction: mari.Action) -> Any: ...
def removeShortcut(Path: str, Shortcut: str = ..., Group = ...) -> Any: ...
def removeShortcuts(Path: str, Group = ...) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setShortcut(Path: str, Shortcut: str, Group = ...) -> Any: ...
def sets() -> typing.List: ...
def shortcut(Path: str, Group = ...) -> str: ...
def shortcutIsInUse(Shortcut: str, Group = ...) -> bool: ...
def shortcuts(Path: str, Group = ...) -> typing.List: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
