from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ActionManager(API):
    class ShortcutGroup:
        APPLICATION: ShortcutGroup = ...
        NODE_GRAPH: ShortcutGroup = ...
        name: getset_descriptor
        values: dict

    APPLICATION: ShortcutGroup = ...
    NODE_GRAPH: ShortcutGroup = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def actionFromShortcut(self, Shortcut: str, Group = ...) -> str: ...
    def addToSet(self, SetName: str, pAction: mari.Action) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def create(self, rIdentifier: str, rCommand: str) -> mari.ScriptAction: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disableSet(self, SetName: str) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def enableSet(self, SetName: str) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def find(self, rPath: str) -> mari.Action: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def get(self, rPath: str) -> mari.Action: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def list(self, rPath: str = ...) -> typing.List: ...
    def loadUserShortcuts(self) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeFromSet(self, SetName: str, pAction: mari.Action) -> Any: ...
    def removeShortcut(self, Path: str, Shortcut: str = ..., Group = ...) -> Any: ...
    def removeShortcuts(self, Path: str, Group = ...) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setShortcut(self, Path: str, Shortcut: str, Group = ...) -> Any: ...
    def sets(self) -> typing.List: ...
    def shortcut(self, Path: str, Group = ...) -> str: ...
    def shortcutIsInUse(self, Shortcut: str, Group = ...) -> bool: ...
    def shortcuts(self, Path: str, Group = ...) -> typing.List: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
