from typing import Any

class DropTargetArea:
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    NODE_GRAPH: DropTargetArea = ...
    SHELF: DropTargetArea = ...
    name: getset_descriptor
    values: dict

class ToolBarArea:
    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    name: getset_descriptor
    values: dict

def activateMainWindow() -> Any: ...
def addTab(Name, Widget) -> Any: ...
class autosaveReset:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class autosaveTriggered:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def backgroundJobCaption(JobID) -> Any: ...
def backgroundJobIDs() -> Any: ...
class backgroundJobsRunning:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def blockSignals(*args, **kwargs) -> Any: ...
class canceledProcessing:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def canvasHeight() -> Any: ...
def canvasWidth() -> Any: ...
def captureDesktop() -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def clearScriptOutput() -> Any: ...
def commandPortEnabled() -> Any: ...
def commandPortNumber() -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createCustomDisplayWidget(Name, OffscreenBufferWidth, OffscreenBufferHeight, Widget) -> Any: ...
def createToolBar(Name, Area = ..., IsVisible = ...) -> Any: ...
def currentMeshPathInGeoLoader() -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def decryptString(Passphrase, CypherText) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
def deleteToolBar(Name) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def enableCommandPort(Enabled) -> Any: ...
def encryptString(Passphrase, CypherText) -> Any: ...
class endingProcessing:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def executeDialog(Dialog) -> Any: ...
def exit(ResultCode = ..., ConfirmIfProjectModified = ...) -> Any: ...
class exiting:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def findToolBar(Name) -> Any: ...
class fullScreenChanging:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def geometry() -> Any: ...
def getGeoPluginAttribute(Key) -> Any: ...
def hasPendingPortCommands() -> Any: ...
def inRestrictedVersion() -> Any: ...
def inTerminalMode() -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isBackgroundJobFinished(JobID) -> Any: ...
def isFullScreen() -> Any: ...
def isMaximized() -> Any: ...
def isMinimized() -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isProcessing() -> Any: ...
def isRunning() -> Any: ...
def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled() -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def lastDropData() -> Any: ...
def launchArgs() -> Any: ...
def launchDir() -> Any: ...
class layoutLoaded:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class layoutSaved:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def loadLayout(Filename) -> Any: ...
def log(Message) -> Any: ...
def logFileName() -> Any: ...
def maximize() -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def minimize() -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def numProcessingSteps() -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class onProgress:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def popupsAllowed() -> Any: ...
def processEvents(IncludeInputEvents = ...) -> Any: ...
def progress() -> Any: ...
def progressDescription() -> Any: ...
class progressDescriptionChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def quit(ConfirmIfProjectModified = ...) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerCustomDropMimeType(MimeType, Target) -> Any: ...
def registerGeoPluginWidget(FileExtensions, Widget) -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeTab(Name) -> Any: ...
def restore() -> Any: ...
def restoreCursor() -> Any: ...
def resumeProcessing() -> Any: ...
def saveLayout(Filename) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setActiveTab(Name) -> Any: ...
def setCommandPortNumber(Number) -> Any: ...
def setFixedCanvasSize(Width, Height) -> Any: ...
def setFullScreen(FullScreen) -> Any: ...
def setGeoPluginAttribute(Key, Value) -> Any: ...
def setGeometry(Geom) -> Any: ...
def setNukeConnectionActive(Active, ConnectionInfo = ...) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProgress(Progress) -> Any: ...
def setProgressDescription(Description) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setSuppressPopups(Suppress) -> Any: ...
def setWaitCursor() -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startProcessing(Description, NumSteps = ..., CanCancel = ...) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class startingProcessing:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def stepProgress() -> Any: ...
def stopProcessing() -> Any: ...
def suppressPopups() -> Any: ...
def suspendProcessing() -> Any: ...
def tabNames() -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def toggleFullScreen() -> Any: ...
def toolBar(Name) -> Any: ...
class toolBarsCreated:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def tr(*args, **kwargs) -> Any: ...
def version() -> Any: ...
def wasProcessingCanceled() -> Any: ...
