from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class DropTargetArea:
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    NODE_GRAPH: DropTargetArea = ...
    SHELF: DropTargetArea = ...
    name: getset_descriptor
    values: dict

class ToolBarArea:
    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    name: getset_descriptor
    values: dict

BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
CANVAS: DropTargetArea = ...
IMAGE_MANAGER: DropTargetArea = ...
LAYER_STACK: DropTargetArea = ...
LEFT_TOOLBAR_AREA: ToolBarArea = ...
NODE_GRAPH: DropTargetArea = ...
RIGHT_TOOLBAR_AREA: ToolBarArea = ...
SHELF: DropTargetArea = ...
TOP_TOOLBAR_AREA: ToolBarArea = ...
staticMetaObject: QMetaObject
BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
CANVAS: DropTargetArea = ...
IMAGE_MANAGER: DropTargetArea = ...
LAYER_STACK: DropTargetArea = ...
LEFT_TOOLBAR_AREA: ToolBarArea = ...
NODE_GRAPH: DropTargetArea = ...
RIGHT_TOOLBAR_AREA: ToolBarArea = ...
SHELF: DropTargetArea = ...
TOP_TOOLBAR_AREA: ToolBarArea = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def activateMainWindow(self) -> Any: ...
def addTab(self, Name, Widget) -> Any: ...
def autosaveReset(self, *args, **kwargs) -> Any: ...
def autosaveTriggered(self, *args, **kwargs) -> Any: ...
def backgroundJobCaption(self, JobID) -> Any: ...
def backgroundJobIDs(self) -> Any: ...
def backgroundJobsRunning(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def canceledProcessing(self, *args, **kwargs) -> Any: ...
def canvasHeight(self) -> Any: ...
def canvasWidth(self) -> Any: ...
def captureDesktop(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clearScriptOutput(self) -> Any: ...
def commandPortEnabled(self) -> Any: ...
def commandPortNumber(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createCustomDisplayWidget(self, Name, OffscreenBufferWidth, OffscreenBufferHeight, Widget) -> Any: ...
def createToolBar(self, Name, Area = ..., IsVisible = ...) -> Any: ...
def currentMeshPathInGeoLoader(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def decryptString(self, Passphrase, CypherText) -> Any: ...
def deleteLater(self) -> Any: ...
def deleteToolBar(self, Name) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def enableCommandPort(self, Enabled) -> Any: ...
def encryptString(self, Passphrase, CypherText) -> Any: ...
def endingProcessing(self, *args, **kwargs) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def executeDialog(self, Dialog) -> Any: ...
def exit(self, ResultCode = ..., ConfirmIfProjectModified = ...) -> Any: ...
def exiting(self, *args, **kwargs) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findToolBar(self, Name) -> Any: ...
def fullScreenChanging(self, *args, **kwargs) -> Any: ...
def geometry(self) -> Any: ...
def getGeoPluginAttribute(self, Key) -> Any: ...
def hasPendingPortCommands(self) -> Any: ...
def inRestrictedVersion(self) -> Any: ...
def inTerminalMode(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isBackgroundJobFinished(self, JobID) -> Any: ...
def isFullScreen(self) -> Any: ...
def isMaximized(self) -> Any: ...
def isMinimized(self) -> Any: ...
def isNull(self) -> Any: ...
def isProcessing(self) -> Any: ...
def isRunning(self) -> Any: ...
def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lastDropData(self) -> Any: ...
def launchArgs(self) -> Any: ...
def launchDir(self) -> Any: ...
def layoutLoaded(self, *args, **kwargs) -> Any: ...
def layoutSaved(self, *args, **kwargs) -> Any: ...
def loadLayout(self, Filename) -> Any: ...
def log(self, Message) -> Any: ...
def logFileName(self) -> Any: ...
def maximize(self) -> Any: ...
def metaObject(self) -> Any: ...
def minimize(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def numProcessingSteps(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onProgress(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def popupsAllowed(self) -> Any: ...
def processEvents(self, IncludeInputEvents = ...) -> Any: ...
def progress(self) -> Any: ...
def progressDescription(self) -> Any: ...
def progressDescriptionChanged(self, *args, **kwargs) -> Any: ...
def property(self, name) -> Any: ...
def quit(self, ConfirmIfProjectModified = ...) -> Any: ...
def receivers(self, signal) -> Any: ...
def registerCustomDropMimeType(self, MimeType, Target) -> Any: ...
def registerGeoPluginWidget(self, FileExtensions, Widget) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeTab(self, Name) -> Any: ...
def restore(self) -> Any: ...
def restoreCursor(self) -> Any: ...
def resumeProcessing(self) -> Any: ...
def saveLayout(self, Filename) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setActiveTab(self, Name) -> Any: ...
def setCommandPortNumber(self, Number) -> Any: ...
def setFixedCanvasSize(self, Width, Height) -> Any: ...
def setFullScreen(self, FullScreen) -> Any: ...
def setGeoPluginAttribute(self, Key, Value) -> Any: ...
def setGeometry(self, Geom) -> Any: ...
def setNukeConnectionActive(self, Active, ConnectionInfo = ...) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProgress(self, Progress) -> Any: ...
def setProgressDescription(self, Description) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSuppressPopups(self, Suppress) -> Any: ...
def setWaitCursor(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startProcessing(self, Description, NumSteps = ..., CanCancel = ...) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def startingProcessing(self, *args, **kwargs) -> Any: ...
def stepProgress(self) -> Any: ...
def stopProcessing(self) -> Any: ...
def suppressPopups(self) -> Any: ...
def suspendProcessing(self) -> Any: ...
def tabNames(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toggleFullScreen(self) -> Any: ...
def toolBar(self, Name) -> Any: ...
def toolBarsCreated(self, *args, **kwargs) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def version(self) -> Any: ...
def wasProcessingCanceled(self) -> Any: ...
