from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class DropTargetArea:
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    NODE_GRAPH: DropTargetArea = ...
    SHELF: DropTargetArea = ...
    name: getset_descriptor
    values: dict

class ToolBarArea:
    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    name: getset_descriptor
    values: dict

BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
CANVAS: DropTargetArea = ...
IMAGE_MANAGER: DropTargetArea = ...
LAYER_STACK: DropTargetArea = ...
LEFT_TOOLBAR_AREA: ToolBarArea = ...
NODE_GRAPH: DropTargetArea = ...
RIGHT_TOOLBAR_AREA: ToolBarArea = ...
SHELF: DropTargetArea = ...
TOP_TOOLBAR_AREA: ToolBarArea = ...
staticMetaObject: QMetaObject
BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
CANVAS: DropTargetArea = ...
IMAGE_MANAGER: DropTargetArea = ...
LAYER_STACK: DropTargetArea = ...
LEFT_TOOLBAR_AREA: ToolBarArea = ...
NODE_GRAPH: DropTargetArea = ...
RIGHT_TOOLBAR_AREA: ToolBarArea = ...
SHELF: DropTargetArea = ...
TOP_TOOLBAR_AREA: ToolBarArea = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def activateMainWindow() -> Any: ...
def addTab(Name: str, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
def autosaveReset(*args, **kwargs) -> Any: ...
def autosaveTriggered(*args, **kwargs) -> Any: ...
def backgroundJobCaption(JobID: int) -> str: ...
def backgroundJobIDs() -> typing.List: ...
def backgroundJobsRunning(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def canceledProcessing(*args, **kwargs) -> Any: ...
def canvasHeight() -> int: ...
def canvasWidth() -> int: ...
def captureDesktop() -> PySide2.QtGui.QPixmap: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clearScriptOutput() -> Any: ...
def commandPortEnabled() -> bool: ...
def commandPortNumber() -> int: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createCustomDisplayWidget(Name: str, OffscreenBufferWidth: int, OffscreenBufferHeight: int, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
def createToolBar(Name: str, Area = ..., IsVisible: bool = ...) -> mari.ToolBar: ...
def currentMeshPathInGeoLoader() -> str: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def decryptString(Passphrase: str, CypherText: str) -> str: ...
def deleteLater() -> Any: ...
def deleteToolBar(Name: str) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def enableCommandPort(Enabled: bool) -> Any: ...
def encryptString(Passphrase: str, CypherText: str) -> str: ...
def endingProcessing(*args, **kwargs) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def executeDialog(Dialog: PySide2.QtWidgets.QDialog) -> int: ...
def exit(ResultCode: int = ..., ConfirmIfProjectModified: bool = ...) -> Any: ...
def exiting(*args, **kwargs) -> Any: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def findToolBar(Name: str) -> mari.ToolBar: ...
def fullScreenChanging(*args, **kwargs) -> Any: ...
def geometry() -> PySide2.QtCore.QRect: ...
def getGeoPluginAttribute(Key: str) -> str: ...
def hasPendingPortCommands() -> bool: ...
def inRestrictedVersion() -> bool: ...
def inTerminalMode() -> bool: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isBackgroundJobFinished(JobID: int) -> bool: ...
def isFullScreen() -> bool: ...
def isMaximized() -> bool: ...
def isMinimized() -> bool: ...
def isNull() -> bool: ...
def isProcessing() -> bool: ...
def isRunning() -> bool: ...
def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lastDropData() -> typing.Any: ...
def launchArgs() -> typing.List: ...
def launchDir() -> str: ...
def layoutLoaded(*args, **kwargs) -> Any: ...
def layoutSaved(*args, **kwargs) -> Any: ...
def loadLayout(Filename: str) -> Any: ...
def log(Message: str) -> Any: ...
def logFileName() -> str: ...
def maximize() -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def minimize() -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def numProcessingSteps() -> int: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def onProgress(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def popupsAllowed() -> bool: ...
def processEvents(IncludeInputEvents: bool = ...) -> Any: ...
def progress() -> int: ...
def progressDescription() -> str: ...
def progressDescriptionChanged(*args, **kwargs) -> Any: ...
def property(name: bytes) -> typing.Any: ...
def quit(ConfirmIfProjectModified: bool = ...) -> Any: ...
def receivers(signal: bytes) -> int: ...
def registerCustomDropMimeType(MimeType: str, Target) -> Any: ...
def registerGeoPluginWidget(FileExtensions: typing.Sequence, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeTab(Name: str) -> Any: ...
def restore() -> Any: ...
def restoreCursor() -> Any: ...
def resumeProcessing() -> Any: ...
def saveLayout(Filename: str) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setActiveTab(Name: str) -> Any: ...
def setCommandPortNumber(Number: int) -> Any: ...
def setFixedCanvasSize(Width: int, Height: int) -> Any: ...
def setFullScreen(FullScreen: bool) -> Any: ...
def setGeoPluginAttribute(Key: str, Value: typing.Any) -> Any: ...
def setGeometry(Geom: PySide2.QtCore.QRect) -> Any: ...
def setNukeConnectionActive(Active: bool, ConnectionInfo: str = ...) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProgress(Progress: int) -> Any: ...
def setProgressDescription(Description: str) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setSuppressPopups(Suppress: bool) -> Any: ...
def setWaitCursor() -> Any: ...
def signalsBlocked() -> bool: ...
def startProcessing(Description: str, NumSteps: int = ..., CanCancel: bool = ...) -> Any: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def startingProcessing(*args, **kwargs) -> Any: ...
def stepProgress() -> Any: ...
def stopProcessing() -> Any: ...
def suppressPopups() -> bool: ...
def suspendProcessing() -> Any: ...
def tabNames() -> typing.List: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def toggleFullScreen() -> Any: ...
def toolBar(Name: str) -> mari.ToolBar: ...
def toolBarsCreated(*args, **kwargs) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def version() -> mari.AppVersion: ...
def wasProcessingCanceled() -> bool: ...
