from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Application(API):
    class DropTargetArea:
        CANVAS: DropTargetArea = ...
        IMAGE_MANAGER: DropTargetArea = ...
        LAYER_STACK: DropTargetArea = ...
        NODE_GRAPH: DropTargetArea = ...
        SHELF: DropTargetArea = ...
        name: getset_descriptor
        values: dict

    class ToolBarArea:
        BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
        LEFT_TOOLBAR_AREA: ToolBarArea = ...
        RIGHT_TOOLBAR_AREA: ToolBarArea = ...
        TOP_TOOLBAR_AREA: ToolBarArea = ...
        name: getset_descriptor
        values: dict

    BOTTOM_TOOLBAR_AREA: ToolBarArea = ...
    CANVAS: DropTargetArea = ...
    IMAGE_MANAGER: DropTargetArea = ...
    LAYER_STACK: DropTargetArea = ...
    LEFT_TOOLBAR_AREA: ToolBarArea = ...
    NODE_GRAPH: DropTargetArea = ...
    RIGHT_TOOLBAR_AREA: ToolBarArea = ...
    SHELF: DropTargetArea = ...
    TOP_TOOLBAR_AREA: ToolBarArea = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def activateMainWindow(self) -> Any: ...
    def addTab(self, Name: str, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
    def autosaveReset(self, *args, **kwargs) -> Any: ...
    def autosaveTriggered(self, *args, **kwargs) -> Any: ...
    def backgroundJobCaption(self, JobID: int) -> str: ...
    def backgroundJobIDs(self) -> typing.List: ...
    def backgroundJobsRunning(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def canceledProcessing(self, *args, **kwargs) -> Any: ...
    def canvasHeight(self) -> int: ...
    def canvasWidth(self) -> int: ...
    def captureDesktop(self) -> PySide2.QtGui.QPixmap: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clearScriptOutput(self) -> Any: ...
    def commandPortEnabled(self) -> bool: ...
    def commandPortNumber(self) -> int: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createCustomDisplayWidget(self, Name: str, OffscreenBufferWidth: int, OffscreenBufferHeight: int, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
    def createToolBar(self, Name: str, Area = ..., IsVisible: bool = ...) -> mari.ToolBar: ...
    def currentMeshPathInGeoLoader(self) -> str: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def decryptString(self, Passphrase: str, CypherText: str) -> str: ...
    def deleteLater(self) -> Any: ...
    def deleteToolBar(self, Name: str) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def enableCommandPort(self, Enabled: bool) -> Any: ...
    def encryptString(self, Passphrase: str, CypherText: str) -> str: ...
    def endingProcessing(self, *args, **kwargs) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def executeDialog(self, Dialog: PySide2.QtWidgets.QDialog) -> int: ...
    def exit(self, ResultCode: int = ..., ConfirmIfProjectModified: bool = ...) -> Any: ...
    def exiting(self, *args, **kwargs) -> Any: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def findToolBar(self, Name: str) -> mari.ToolBar: ...
    def fullScreenChanging(self, *args, **kwargs) -> Any: ...
    def geometry(self) -> PySide2.QtCore.QRect: ...
    def getGeoPluginAttribute(self, Key: str) -> str: ...
    def hasPendingPortCommands(self) -> bool: ...
    def inRestrictedVersion(self) -> bool: ...
    def inTerminalMode(self) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isBackgroundJobFinished(self, JobID: int) -> bool: ...
    def isFullScreen(self) -> bool: ...
    def isMaximized(self) -> bool: ...
    def isMinimized(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isProcessing(self) -> bool: ...
    def isRunning(self) -> bool: ...
    def isSafeFeature_BypassUserEnvironmentResourceKeys_Enabled(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lastDropData(self) -> typing.Any: ...
    def launchArgs(self) -> typing.List: ...
    def launchDir(self) -> str: ...
    def layoutLoaded(self, *args, **kwargs) -> Any: ...
    def layoutSaved(self, *args, **kwargs) -> Any: ...
    def loadLayout(self, Filename: str) -> Any: ...
    def log(self, Message: str) -> Any: ...
    def logFileName(self) -> str: ...
    def maximize(self) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def minimize(self) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def numProcessingSteps(self) -> int: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def onProgress(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def popupsAllowed(self) -> bool: ...
    def processEvents(self, IncludeInputEvents: bool = ...) -> Any: ...
    def progress(self) -> int: ...
    def progressDescription(self) -> str: ...
    def progressDescriptionChanged(self, *args, **kwargs) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def quit(self, ConfirmIfProjectModified: bool = ...) -> Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def registerCustomDropMimeType(self, MimeType: str, Target) -> Any: ...
    def registerGeoPluginWidget(self, FileExtensions: typing.Sequence, Widget: PySide2.QtWidgets.QWidget) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeTab(self, Name: str) -> Any: ...
    def restore(self) -> Any: ...
    def restoreCursor(self) -> Any: ...
    def resumeProcessing(self) -> Any: ...
    def saveLayout(self, Filename: str) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setActiveTab(self, Name: str) -> Any: ...
    def setCommandPortNumber(self, Number: int) -> Any: ...
    def setFixedCanvasSize(self, Width: int, Height: int) -> Any: ...
    def setFullScreen(self, FullScreen: bool) -> Any: ...
    def setGeoPluginAttribute(self, Key: str, Value: typing.Any) -> Any: ...
    def setGeometry(self, Geom: PySide2.QtCore.QRect) -> Any: ...
    def setNukeConnectionActive(self, Active: bool, ConnectionInfo: str = ...) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProgress(self, Progress: int) -> Any: ...
    def setProgressDescription(self, Description: str) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSuppressPopups(self, Suppress: bool) -> Any: ...
    def setWaitCursor(self) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startProcessing(self, Description: str, NumSteps: int = ..., CanCancel: bool = ...) -> Any: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def startingProcessing(self, *args, **kwargs) -> Any: ...
    def stepProgress(self) -> Any: ...
    def stopProcessing(self) -> Any: ...
    def suppressPopups(self) -> bool: ...
    def suspendProcessing(self) -> Any: ...
    def tabNames(self) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toggleFullScreen(self) -> Any: ...
    def toolBar(self, Name: str) -> mari.ToolBar: ...
    def toolBarsCreated(self, *args, **kwargs) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def version(self) -> mari.AppVersion: ...
    def wasProcessingCanceled(self) -> bool: ...
