from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Stage:
    ALPHA: Stage = ...
    BETA: Stage = ...
    DEV: Stage = ...
    RELEASE: Stage = ...
    name: getset_descriptor
    values: dict

ALPHA: Stage = ...
BETA: Stage = ...
DEV: Stage = ...
RELEASE: Stage = ...
staticMetaObject: QMetaObject
ALPHA: Stage = ...
BETA: Stage = ...
DEV: Stage = ...
RELEASE: Stage = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def date() -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def feature() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def info() -> str: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isLinux() -> bool: ...
def isMac() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def isWindows() -> bool: ...
def iteration() -> int: ...
def killTimer(id: int) -> Any: ...
def major() -> int: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def minor() -> int: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def number() -> int: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def qt() -> str: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def revision() -> int: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def stage() -> Any: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def string() -> str: ...
def thread() -> PySide2.QtCore.QThread: ...
def time() -> str: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
