from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import Node

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class PortListMode:
    PORT_LIST_COLLAPSED: PortListMode = ...
    PORT_LIST_EXPANDED: PortListMode = ...
    PORT_LIST_GROUPED: PortListMode = ...
    PORT_LIST_ONLY_CONNECTED: PortListMode = ...
    PORT_LIST_T2B: PortListMode = ...
    name: getset_descriptor
    values: dict

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
PORT_LIST_COLLAPSED: PortListMode = ...
PORT_LIST_EXPANDED: PortListMode = ...
PORT_LIST_GROUPED: PortListMode = ...
PORT_LIST_ONLY_CONNECTED: PortListMode = ...
PORT_LIST_T2B: PortListMode = ...
staticMetaObject: QMetaObject
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
PORT_LIST_COLLAPSED: PortListMode = ...
PORT_LIST_EXPANDED: PortListMode = ...
PORT_LIST_GROUPED: PortListMode = ...
PORT_LIST_ONLY_CONNECTED: PortListMode = ...
PORT_LIST_T2B: PortListMode = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def addNodeContext(Name: str, Context: mari.NodeContext) -> Any: ...
def addTag(Tag: str, ForceAdd: bool = ...) -> Any: ...
def attachViewer(InputNumber: int = ...) -> Any: ...
def bake(Width: int, Height: int, Depth: int, FileSpace = ..., ColorConfig: typing.Optional = ..., OutputPortName: str = ...) -> mari.PaintNode: ...
def blockSignals(b: bool) -> bool: ...
def bypassInput(OutputPoint: str = ...) -> int: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def childNodes() -> typing.List: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def connectSignals() -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportToGeoChannel(DestGeoChannel: mari.GeoChannel, OutputPortName: str = ...) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def focusInNodeGraph() -> Any: ...
def getNodeGraphViewContextMeta() -> PySide2.QtCore.QMetaObject: ...
def hasChanged(*args, **kwargs) -> Any: ...
def hasMetadata(Name: str) -> bool: ...
def hasTag(Tag: str) -> bool: ...
def hash(UVIndex: int = ..., IgnoreChildren: bool = ...) -> str: ...
def inherits(classname: bytes) -> bool: ...
def inputConnection(PortName: str) -> typing.List: ...
def inputNode(PortName: str) -> mari.Node: ...
def inputNodeChanged(*args, **kwargs) -> Any: ...
def inputPortCount() -> int: ...
def inputPortName(Index: int) -> str: ...
def inputPortNames() -> typing.List: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isBackdropNode() -> bool: ...
def isBakePointNode() -> bool: ...
def isEnabled() -> bool: ...
def isGeoChannelNode() -> bool: ...
def isGroupNode() -> bool: ...
def isNull() -> bool: ...
def isPaintNode() -> bool: ...
def isSelected() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def nameChanged(*args, **kwargs) -> Any: ...
def nodeContext(Name: str) -> mari.NodeContext: ...
def nodeContextNames() -> typing.List: ...
def nodeGraphPosition() -> PySide2.QtCore.QPointF: ...
def nodeGraphSize() -> PySide2.QtCore.QSizeF: ...
def nodeInformation() -> str: ...
def nodePath() -> str: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def outputNodes(PortName: str = ...) -> typing.List: ...
def outputPortCount() -> int: ...
def outputPortName(Index: int) -> str: ...
def outputPortNames() -> typing.List: ...
def parent() -> PySide2.QtCore.QObject: ...
def parentNodeGraph() -> mari.NodeGraph: ...
def pathKey() -> str: ...
def portListMode() -> Any: ...
def printVersionHashSource() -> Any: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def removeNodeContext(Name: str) -> Any: ...
def removeTag(Tag: str, ForceRemove: bool = ...) -> Any: ...
def selectChildNodes() -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setBypassInput(BypassInput: int) -> Any: ...
def setEnabled(Enabled: bool) -> Any: ...
def setInputNode(PortName: str, NodeToConnect: mari.Node, OutputPortName: str = ...) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setName(NewName: str) -> Any: ...
def setNodeGraphPosition(Position: PySide2.QtCore.QPointF) -> Any: ...
def setNodeGraphSize(Size: PySide2.QtCore.QSizeF) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPortListMode(Mode) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setSelected(Selected: bool) -> Any: ...
def setTypeID(TypeID: str) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def tagList() -> typing.List: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def typeID() -> str: ...
def uuid() -> str: ...
