from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class AnimationMode:
    ANIMATION_ALL: AnimationMode = ...
    ANIMATION_OFF: AnimationMode = ...
    name: getset_descriptor
    values: dict

class OutputMode:
    OUTPUT_CHANNEL: OutputMode = ...
    OUTPUT_GEO_CHANNEL: OutputMode = ...
    OUTPUT_PAINT_NODE: OutputMode = ...
    name: getset_descriptor
    values: dict

class OutputModes:
    pass

class PreviewQuality:
    PREVIEW_HIGH: PreviewQuality = ...
    PREVIEW_LOW: PreviewQuality = ...
    PREVIEW_MEDIUM: PreviewQuality = ...
    name: getset_descriptor
    values: dict

ANIMATION_ALL: AnimationMode = ...
ANIMATION_OFF: AnimationMode = ...
OUTPUT_CHANNEL: OutputMode = ...
OUTPUT_GEO_CHANNEL: OutputMode = ...
OUTPUT_PAINT_NODE: OutputMode = ...
PREVIEW_HIGH: PreviewQuality = ...
PREVIEW_LOW: PreviewQuality = ...
PREVIEW_MEDIUM: PreviewQuality = ...
staticMetaObject: QMetaObject
ANIMATION_ALL: AnimationMode = ...
ANIMATION_OFF: AnimationMode = ...
OUTPUT_CHANNEL: OutputMode = ...
OUTPUT_GEO_CHANNEL: OutputMode = ...
OUTPUT_PAINT_NODE: OutputMode = ...
PREVIEW_HIGH: PreviewQuality = ...
PREVIEW_LOW: PreviewQuality = ...
PREVIEW_MEDIUM: PreviewQuality = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def addBakeItems(self, BakeItems, BakeToVersions, BakeFromVersions) -> Any: ...
def animationMode(self) -> Any: ...
def animationModeChanged(self, *args, **kwargs) -> Any: ...
def bakeItems(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def devices(self) -> Any: ...
def devicesChanged(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def outputChannel(self) -> Any: ...
def outputGeoChannel(self) -> Any: ...
def outputModes(self) -> Any: ...
def outputPaintNode(self) -> Any: ...
def parent(self) -> Any: ...
def previewQuality(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setAnimationMode(self, NewMode) -> Any: ...
def setDevices(self, Devices) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setOutputChannel(self, Enabled) -> Any: ...
def setOutputGeoChannel(self, Enabled) -> Any: ...
def setOutputModes(self, Outputs) -> Any: ...
def setOutputPaintNode(self, Enabled) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPreviewQuality(self, NewMode) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
