from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class BakeItem(Metadata):
    class EdgeBleedMode:
        EDGE_BLEED_OFF: EdgeBleedMode = ...
        EDGE_BLEED_ON_FAST: EdgeBleedMode = ...
        name: getset_descriptor
        values: dict

    class HighPolySearchMode:
        SEARCH_CLOSEST: HighPolySearchMode = ...
        SEARCH_NORMAL_CAGE: HighPolySearchMode = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    EDGE_BLEED_OFF: EdgeBleedMode = ...
    EDGE_BLEED_ON_FAST: EdgeBleedMode = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    SEARCH_CLOSEST: HighPolySearchMode = ...
    SEARCH_NORMAL_CAGE: HighPolySearchMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def cageDistance(self) -> float: ...
    def cageDistanceChanged(self, *args, **kwargs) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def edgeBleedMode(self) -> Any: ...
    def edgeBleedModeChanged(self, *args, **kwargs) -> Any: ...
    def edgeBleedModeList(self) -> typing.List: ...
    def edgeBleedModeString(self, *args, **kwargs) -> Any: ...
    def edgeBleedModeStringChanged(self, *args, **kwargs) -> Any: ...
    def edgeBleedModeStringList(self) -> typing.List: ...
    def edgeBleedModeStringTooltip(self) -> str: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def highPolySearchMode(self) -> Any: ...
    def highPolySearchModeChanged(self, *args, **kwargs) -> Any: ...
    def imageFormat(self) -> Any: ...
    def imageFormatChanged(self, *args, **kwargs) -> Any: ...
    def imageFormatList(self) -> typing.List: ...
    def imageFormatString(self, *args, **kwargs) -> Any: ...
    def imageFormatStringChanged(self, *args, **kwargs) -> Any: ...
    def imageFormatStringList(self) -> typing.List: ...
    def imageFormatStringTooltip(self) -> str: ...
    def imageSize(self) -> PySide2.QtCore.QSize: ...
    def imageSizeChanged(self, *args, **kwargs) -> Any: ...
    def imageSizeString(self, *args, **kwargs) -> Any: ...
    def imageSizeStringChanged(self, *args, **kwargs) -> Any: ...
    def imageSizeStringList(self) -> typing.List: ...
    def imageSizeStringTooltip(self) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def nameTooltip(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def recipe(self) -> mari.BakeRecipe: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCageDistance(self, CageDistance: float) -> Any: ...
    def setEdgeBleedMode(self, EdgeBleedMode) -> Any: ...
    def setEdgeBleedModeString(self, EdgeBleedModeString: str) -> Any: ...
    def setHighPolySearchMode(self, NewMode) -> Any: ...
    def setImageFormat(self, Format) -> Any: ...
    def setImageFormatString(self, ImageFormatString: str) -> Any: ...
    def setImageSize(self, Size: PySide2.QtCore.QSize) -> Any: ...
    def setImageSizeString(self, Size: str) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, Name: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def uuid(self) -> str: ...
