from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def allDevices(self) -> Any: ...
def allRecipes(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isProcessing(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def loadPresets(self, Path) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def newSettings(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onBake(self, Settings) -> Any: ...
def onBakeQuit(self) -> Any: ...
def parent(self) -> Any: ...
def progressError(self, *args, **kwargs) -> Any: ...
def progressIncrement(self, *args, **kwargs) -> Any: ...
def progressStart(self, *args, **kwargs) -> Any: ...
def progressStop(self, *args, **kwargs) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def recipe(self, Name) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def savePresets(self, BakeItems, Path) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
