from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class AnimationMode:
    ANIMATION_ALL: AnimationMode = ...
    ANIMATION_OFF: AnimationMode = ...
    name: getset_descriptor
    values: dict

class OutputMode:
    OUTPUT_CHANNEL: OutputMode = ...
    OUTPUT_GEO_CHANNEL: OutputMode = ...
    OUTPUT_PAINT_NODE: OutputMode = ...
    name: getset_descriptor
    values: dict

class OutputModes:
    pass

class PreviewQuality:
    PREVIEW_HIGH: PreviewQuality = ...
    PREVIEW_LOW: PreviewQuality = ...
    PREVIEW_MEDIUM: PreviewQuality = ...
    name: getset_descriptor
    values: dict

ANIMATION_ALL: AnimationMode = ...
ANIMATION_OFF: AnimationMode = ...
OUTPUT_CHANNEL: OutputMode = ...
OUTPUT_GEO_CHANNEL: OutputMode = ...
OUTPUT_PAINT_NODE: OutputMode = ...
PREVIEW_HIGH: PreviewQuality = ...
PREVIEW_LOW: PreviewQuality = ...
PREVIEW_MEDIUM: PreviewQuality = ...
staticMetaObject: QMetaObject
ANIMATION_ALL: AnimationMode = ...
ANIMATION_OFF: AnimationMode = ...
OUTPUT_CHANNEL: OutputMode = ...
OUTPUT_GEO_CHANNEL: OutputMode = ...
OUTPUT_PAINT_NODE: OutputMode = ...
PREVIEW_HIGH: PreviewQuality = ...
PREVIEW_LOW: PreviewQuality = ...
PREVIEW_MEDIUM: PreviewQuality = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def addBakeItems(BakeItems: typing.Sequence, BakeToVersions: typing.Sequence, BakeFromVersions: typing.Sequence) -> Any: ...
def animationMode() -> Any: ...
def animationModeChanged(*args, **kwargs) -> Any: ...
def bakeItems() -> typing.List: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def devices() -> typing.List: ...
def devicesChanged(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def outputChannel() -> bool: ...
def outputGeoChannel() -> bool: ...
def outputModes() -> mari.OutputModes: ...
def outputPaintNode() -> bool: ...
def parent() -> PySide2.QtCore.QObject: ...
def previewQuality() -> Any: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setAnimationMode(NewMode) -> Any: ...
def setDevices(Devices: typing.Sequence) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setOutputChannel(Enabled: bool) -> Any: ...
def setOutputGeoChannel(Enabled: bool) -> Any: ...
def setOutputModes(Outputs: mari.OutputModes) -> Any: ...
def setOutputPaintNode(Enabled: bool) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPreviewQuality(NewMode) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
