from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class BakeSettings(API):
    class AnimationMode:
        ANIMATION_ALL: AnimationMode = ...
        ANIMATION_OFF: AnimationMode = ...
        name: getset_descriptor
        values: dict

    class OutputMode:
        OUTPUT_CHANNEL: OutputMode = ...
        OUTPUT_GEO_CHANNEL: OutputMode = ...
        OUTPUT_PAINT_NODE: OutputMode = ...
        name: getset_descriptor
        values: dict

    class OutputModes:
        pass

    class PreviewQuality:
        PREVIEW_HIGH: PreviewQuality = ...
        PREVIEW_LOW: PreviewQuality = ...
        PREVIEW_MEDIUM: PreviewQuality = ...
        name: getset_descriptor
        values: dict

    ANIMATION_ALL: AnimationMode = ...
    ANIMATION_OFF: AnimationMode = ...
    OUTPUT_CHANNEL: OutputMode = ...
    OUTPUT_GEO_CHANNEL: OutputMode = ...
    OUTPUT_PAINT_NODE: OutputMode = ...
    PREVIEW_HIGH: PreviewQuality = ...
    PREVIEW_LOW: PreviewQuality = ...
    PREVIEW_MEDIUM: PreviewQuality = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def addBakeItems(self, BakeItems: typing.Sequence, BakeToVersions: typing.Sequence, BakeFromVersions: typing.Sequence) -> Any: ...
    def animationMode(self) -> Any: ...
    def animationModeChanged(self, *args, **kwargs) -> Any: ...
    def bakeItems(self) -> typing.List: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def devices(self) -> typing.List: ...
    def devicesChanged(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def outputChannel(self) -> bool: ...
    def outputGeoChannel(self) -> bool: ...
    def outputModes(self) -> mari.OutputModes: ...
    def outputPaintNode(self) -> bool: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def previewQuality(self) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAnimationMode(self, NewMode) -> Any: ...
    def setDevices(self, Devices: typing.Sequence) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setOutputChannel(self, Enabled: bool) -> Any: ...
    def setOutputGeoChannel(self, Enabled: bool) -> Any: ...
    def setOutputModes(self, Outputs: mari.OutputModes) -> Any: ...
    def setOutputPaintNode(self, Enabled: bool) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPreviewQuality(self, NewMode) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
