from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import Node
from mari import TeleportNode

class BroadcastTeleportNode(TeleportNode):
    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class PortListMode:
        PORT_LIST_COLLAPSED: PortListMode = ...
        PORT_LIST_EXPANDED: PortListMode = ...
        PORT_LIST_GROUPED: PortListMode = ...
        PORT_LIST_ONLY_CONNECTED: PortListMode = ...
        PORT_LIST_T2B: PortListMode = ...
        name: getset_descriptor
        values: dict

    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    PORT_LIST_COLLAPSED: PortListMode = ...
    PORT_LIST_EXPANDED: PortListMode = ...
    PORT_LIST_GROUPED: PortListMode = ...
    PORT_LIST_ONLY_CONNECTED: PortListMode = ...
    PORT_LIST_T2B: PortListMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def addNodeContext(self, Name: str, Context: mari.NodeContext) -> Any: ...
    def addTag(self, Tag: str, ForceAdd: bool = ...) -> Any: ...
    def attachViewer(self, InputNumber: int = ...) -> Any: ...
    def bake(self, Width: int, Height: int, Depth: int, FileSpace = ..., ColorConfig: typing.Optional = ..., OutputPortName: str = ...) -> mari.PaintNode: ...
    def blockSignals(self, b: bool) -> bool: ...
    def bypassInput(self, OutputPoint: str = ...) -> int: ...
    def channelName(self) -> str: ...
    def channelNameChanged(self, *args, **kwargs) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def connectSignals(self) -> Any: ...
    def connectedReceiverNodeList(self) -> typing.List: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportToGeoChannel(self, DestGeoChannel: mari.GeoChannel, OutputPortName: str = ...) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def focusInNodeGraph(self) -> Any: ...
    def getNodeGraphViewContextMeta(self) -> PySide2.QtCore.QMetaObject: ...
    def hasChanged(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def hasTag(self, Tag: str) -> bool: ...
    def hash(self, UVIndex: int = ..., IgnoreChildren: bool = ...) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def inputConnection(self, PortName: str) -> typing.List: ...
    def inputNode(self, PortName: str) -> mari.Node: ...
    def inputNodeChanged(self, *args, **kwargs) -> Any: ...
    def inputPortCount(self) -> int: ...
    def inputPortName(self, Index: int) -> str: ...
    def inputPortNames(self) -> typing.List: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isBackdropNode(self) -> bool: ...
    def isBakePointNode(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isGeoChannelNode(self) -> bool: ...
    def isGroupNode(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isPaintNode(self) -> bool: ...
    def isSelected(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def nodeContext(self, Name: str) -> mari.NodeContext: ...
    def nodeContextNames(self) -> typing.List: ...
    def nodeGraphPosition(self) -> PySide2.QtCore.QPointF: ...
    def nodeGraphSize(self) -> PySide2.QtCore.QSizeF: ...
    def nodeInformation(self) -> str: ...
    def nodePath(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def outputNodes(self, PortName: str = ...) -> typing.List: ...
    def outputPortCount(self) -> int: ...
    def outputPortName(self, Index: int) -> str: ...
    def outputPortNames(self) -> typing.List: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def parentNodeGraph(self) -> mari.NodeGraph: ...
    def pathKey(self) -> str: ...
    def portListMode(self) -> Any: ...
    def printVersionHashSource(self) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def removeNodeContext(self, Name: str) -> Any: ...
    def removeTag(self, Tag: str, ForceRemove: bool = ...) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setBypassInput(self, BypassInput: int) -> Any: ...
    def setChannelName(self, ChannelName: str) -> Any: ...
    def setEnabled(self, Enabled: bool) -> Any: ...
    def setInputNode(self, PortName: str, NodeToConnect: mari.Node, OutputPortName: str = ...) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, NewName: str) -> Any: ...
    def setNodeGraphPosition(self, Position: PySide2.QtCore.QPointF) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPortListMode(self, Mode) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSelected(self, Selected: bool) -> Any: ...
    def setTypeID(self, TypeID: str) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def tagList(self) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def typeID(self) -> str: ...
    def uuid(self) -> str: ...
