from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class Camera(Metadata):
    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class Type:
        ORTHOGRAPHIC: Type = ...
        PERSPECTIVE: Type = ...
        UV: Type = ...
        name: getset_descriptor
        values: dict

    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    ORTHOGRAPHIC: Type = ...
    PERSPECTIVE: Type = ...
    UV: Type = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def adjustClipPlanes(self) -> Any: ...
    def attributeChanged(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def farClip(self, Frame: int = ...) -> float: ...
    def fieldOfView(self, Frame: int = ...) -> float: ...
    def fieldOfViewX(self, Frame: int = ...) -> float: ...
    def fieldOfViewY(self, Frame: int = ...) -> float: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isAnimated(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lookAt(self, Frame: int = ...) -> mari.VectorN: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def moved(self, *args, **kwargs) -> Any: ...
    def name(self) -> str: ...
    def nearClip(self, Frame: int = ...) -> float: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def perspectiveAspectRatio(self) -> float: ...
    def projectionMatrix(self, AspectRatio: float = ..., Frame: int = ...) -> typing.Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def scale(self) -> float: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAnimated(self, Animated: bool) -> Any: ...
    def setFarClip(self, FarClip: float) -> Any: ...
    def setFieldOfView(self, FieldOfView: float) -> Any: ...
    def setFieldOfViewX(self, FieldOfView: float) -> Any: ...
    def setFieldOfViewY(self, FieldOfView: float) -> Any: ...
    def setLookAt(self, pLookAt: mari.VectorN) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, Name: str) -> Any: ...
    def setNearClip(self, NearClip: float) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setScale(self, Scale: float) -> Any: ...
    def setTranslation(self, pLookAt: mari.VectorN) -> Any: ...
    def setType(self, Type) -> Any: ...
    def setUp(self, pLookAt: mari.VectorN) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def translation(self, Frame: int = ...) -> mari.VectorN: ...
    def type(self) -> Any: ...
    def up(self, Frame: int = ...) -> mari.VectorN: ...
    def uuid(self) -> str: ...
    def viewMatrix(self, Frame: int = ...) -> typing.Any: ...
    def viewport(self) -> PySide2.QtCore.QRect: ...
    def viewportAspectRatio(self) -> float: ...
