from typing import Any

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class RenderState:
    Render_Busy: RenderState
    Render_Disabled: RenderState
    Render_Error: RenderState
    Render_Normal: RenderState
    name: getset_descriptor
    values: dict

class aboutToRenderCanvas:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def blockSignals(*args, **kwargs) -> Any: ...
def canResetProperty(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def current() -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def fps() -> Any: ...
def getProperty(*args, **kwargs) -> Any: ...
def hasMetadata(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isSupportedMetadataType(Value) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def list() -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def metadata(*args, **kwargs) -> Any: ...
def metadataAsImage(*args, **kwargs) -> Any: ...
class metadataCreated:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def metadataDefault(*args, **kwargs) -> Any: ...
def metadataDescription(*args, **kwargs) -> Any: ...
def metadataDisplayName(*args, **kwargs) -> Any: ...
class metadataEnabledChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def metadataFlags(*args, **kwargs) -> Any: ...
def metadataIsEnabled(*args, **kwargs) -> Any: ...
def metadataItemList(*args, **kwargs) -> Any: ...
def metadataMax(*args, **kwargs) -> Any: ...
def metadataMin(*args, **kwargs) -> Any: ...
def metadataNames(*args, **kwargs) -> Any: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(*args, **kwargs) -> Any: ...
def metadataTypeFlags(*args, **kwargs) -> Any: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
class normalRenderFinished:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def paintBuffer() -> Any: ...
def parent(*args, **kwargs) -> Any: ...
def pauseShaderCompiles() -> Any: ...
def propertiesList(*args, **kwargs) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def propertyDisplayName(*args, **kwargs) -> Any: ...
def propertyEnumValues(*args, **kwargs) -> Any: ...
def propertyHasMinMax(*args, **kwargs) -> Any: ...
def propertyIsEnum(*args, **kwargs) -> Any: ...
def propertyIsReadOnly(*args, **kwargs) -> Any: ...
def propertyMinMax(*args, **kwargs) -> Any: ...
def propertyTooltip(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeMetadata(*args, **kwargs) -> Any: ...
class renderError:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class renderedCanvas:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class renderedCanvas2:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def resetProperty(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setMetadata(*args, **kwargs) -> Any: ...
def setMetadataDefault(*args, **kwargs) -> Any: ...
def setMetadataDescription(*args, **kwargs) -> Any: ...
def setMetadataDisplayName(*args, **kwargs) -> Any: ...
def setMetadataEnabled(*args, **kwargs) -> Any: ...
def setMetadataFlags(*args, **kwargs) -> Any: ...
def setMetadataGroupHints(*args, **kwargs) -> Any: ...
def setMetadataItemList(*args, **kwargs) -> Any: ...
def setMetadataRange(*args, **kwargs) -> Any: ...
def setMetadataStep(*args, **kwargs) -> Any: ...
def setMetadataTypeFlags(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setPauseShaderCompiles(Pause) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def size() -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def uuid(*args, **kwargs) -> Any: ...
