from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Canvas(API):
    class PickSpace:
        PICKSPACE_PAINTING: PickSpace = ...
        PICKSPACE_SCREEN: PickSpace = ...
        name: getset_descriptor
        values: dict

    PICKSPACE_PAINTING: PickSpace = ...
    PICKSPACE_SCREEN: PickSpace = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def averageColor(self, X: int, Y: int, Width: int, Height: int, Space = ...) -> mari.Color: ...
    def blockSignals(self, b: bool) -> bool: ...
    def camera(self) -> mari.Camera: ...
    def capture(self, Width: int = ..., Height: int = ...) -> PySide2.QtGui.QImage: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def displayPropertyList(self) -> typing.List: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def getDisplayProperty(self, PropertyKey: str) -> typing.Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def pickColor(self, X: int, Y: int, Space = ...) -> mari.Color: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def repaint(self) -> Any: ...
    def requestRepaint(self) -> Any: ...
    def sceneCamera(self) -> mari.Camera: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setDisplayProperty(self, PropertyKey: str, NewValue: typing.Any) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def size(self) -> PySide2.QtCore.QSize: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
