from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class PickSpace:
    PICKSPACE_PAINTING: PickSpace = ...
    PICKSPACE_SCREEN: PickSpace = ...
    name: getset_descriptor
    values: dict

PICKSPACE_PAINTING: PickSpace = ...
PICKSPACE_SCREEN: PickSpace = ...
staticMetaObject: QMetaObject
PICKSPACE_PAINTING: PickSpace = ...
PICKSPACE_SCREEN: PickSpace = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def averageColor(self, X, Y, Width, Height, Space = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def camera(self) -> Any: ...
def capture(self, Width = ..., Height = ...) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def displayPropertyList(self) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def getDisplayProperty(self, PropertyKey) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def pickColor(self, X, Y, Space = ...) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def repaint(self) -> Any: ...
def requestRepaint(self) -> Any: ...
def sceneCamera(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setDisplayProperty(self, PropertyKey, NewValue) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def size(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
