from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ChannelInfo(API):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depth(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def fileSpace(self) -> Any: ...
    def fileTemplate(self) -> str: ...
    def fillColor(self) -> mari.Color: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def height(self) -> int: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def path(self) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def scalarColorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setDepth(self, NewDepth) -> Any: ...
    def setFileSpace(self, FileSpace) -> Any: ...
    def setFileTemplate(self, rTemplate: str) -> Any: ...
    def setFillColor(self, pCol: mari.Color) -> Any: ...
    def setHeight(self, Height: int) -> Any: ...
    def setName(self, rName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPath(self, rPath: str) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setScalarColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setShader(self, rShader: str) -> Any: ...
    def setSize(self, WidthAndHeight: int) -> Any: ...
    def setWidth(self, Width: int) -> Any: ...
    def shader(self) -> str: ...
    def signalsBlocked(self) -> bool: ...
    def size(self) -> int: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def width(self) -> int: ...
