from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import LayerStack
from mari import Metadata

class ClearSelectionFlag:
    CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
    CLEAR_GROUPS: ClearSelectionFlag = ...
    CLEAR_MASK_STACKS: ClearSelectionFlag = ...
    DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
    name: getset_descriptor
    values: dict

class ConvertOption:
    CONVERT_ALL: ConvertOption = ...
    CONVERT_CHANNEL_ONLY: ConvertOption = ...
    name: getset_descriptor
    values: dict

class LayerCreateFlag:
    CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
    DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
    INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
    INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
    MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
    SELECT_NEW_LAYERS: LayerCreateFlag = ...
    name: getset_descriptor
    values: dict

class LayerImportOption:
    CREATE_NEW_LAYERS: LayerImportOption = ...
    OPTION_NOT_SPECIFIED: LayerImportOption = ...
    SKIP_LAYERS: LayerImportOption = ...
    UPDATE_LAYERS: LayerImportOption = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class ResizeMetric:
    RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
    RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
    RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
    name: getset_descriptor
    values: dict

CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
CLEAR_GROUPS: ClearSelectionFlag = ...
CLEAR_MASK_STACKS: ClearSelectionFlag = ...
CONVERT_ALL: ConvertOption = ...
CONVERT_CHANNEL_ONLY: ConvertOption = ...
CREATE_NEW_LAYERS: LayerImportOption = ...
DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
OPTION_NOT_SPECIFIED: LayerImportOption = ...
RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
SELECT_NEW_LAYERS: LayerCreateFlag = ...
SKIP_LAYERS: LayerImportOption = ...
UPDATE_LAYERS: LayerImportOption = ...
staticMetaObject: QMetaObject
CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
CLEAR_GROUPS: ClearSelectionFlag = ...
CLEAR_MASK_STACKS: ClearSelectionFlag = ...
CONVERT_ALL: ConvertOption = ...
CONVERT_CHANNEL_ONLY: ConvertOption = ...
CREATE_NEW_LAYERS: LayerImportOption = ...
DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
OPTION_NOT_SPECIFIED: LayerImportOption = ...
RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
SELECT_NEW_LAYERS: LayerCreateFlag = ...
SKIP_LAYERS: LayerImportOption = ...
UPDATE_LAYERS: LayerImportOption = ...
@staticmethod
def adjustmentLayerTypeList() -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def proceduralLayerTypeList() -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def transferLayers(UVRemap, SourceLayers, SourceGeoVersion, DestinationLayerStack, DestinationGeoVersion, DestinationSize = ..., BleedEdges = ..., FillColor = ..., SourceUVIndices = ..., DestinationUVIndices = ...) -> Any: ...
def bakeTo(self, TargetLayer, SelectedOnly = ...) -> Any: ...
def bleed(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def channelNode(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clearSelection(self, Flags = ...) -> Any: ...
def colorspaceConfig(self) -> Any: ...
def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def convertColorSpaceTo(self, NewColorSpace, Option = ...) -> Any: ...
def convertColorspaceTo(self, OutputColorspace, InputColorspace = ..., Config = ..., Option = ...) -> Any: ...
def createAdjustmentLayer(self, LayerName, PrimaryAdjustmentKey, RefLayer = ..., Flags = ...) -> Any: ...
def createBakePointLayer(self, LayerName, RefLayer = ..., Flags = ...) -> Any: ...
def createChannelLayer(self, LayerName, TargetChannel, RefLayer = ..., Flags = ...) -> Any: ...
def createCustomProceduralLayer(self, LayerName, FilePath, RefLayer = ..., Flags = ...) -> Any: ...
def createGraphLayer(self, LayerName, RefLayer = ..., Flags = ...) -> Any: ...
def createGroupLayer(self, LayerName, RefLayer = ..., Flags = ...) -> Any: ...
def createMaterialLayer(self, LayerName, FilePath, RefLayer = ..., Flags = ...) -> Any: ...
def createMultiChannelGroupLayer(self, LayerName, RefLayer = ..., Flags = ...) -> Any: ...
def createPaintableLayer(self, LayerName, RefLayer = ..., FillColor = ..., Flags = ...) -> Any: ...
def createProceduralLayer(self, LayerName, ProceduralKey, RefLayer = ..., Flags = ...) -> Any: ...
def createShaderLayer(self, LayerName, TargetShader, RefLayer = ..., Flags = ...) -> Any: ...
def createSnapshot(self, Name, ID = ...) -> Any: ...
def currentLayer(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def deleteSnapshot(self, ShotToDelete) -> Any: ...
def depth(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def duplicateLayers(self, LayersToDuplicate = ..., RefLayer = ..., Flags = ...) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportImages(self, PathAndTemplate, Options = ..., UVIndexList = ..., FileOptions = ..., OutputColorConfig = ...) -> Any: ...
def exportImagesFlattened(self, PathAndTemplate, Options = ..., UVIndexList = ..., FileOptions = ..., OutputColorConfig = ...) -> Any: ...
def exportSelectedPatches(self, PathAndTemplate, Options = ..., FileOptions = ..., OutputColorConfig = ...) -> Any: ...
def exportSelectedPatchesFlattened(self, PathAndTemplate, Options = ..., FileOptions = ..., OutputColorConfig = ...) -> Any: ...
def exportToGeoChannel(self, GeoChannelName) -> Any: ...
def fileSpace(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findLayer(self, LayerName) -> Any: ...
def findSnapshotWithID(self, ID) -> Any: ...
def flatten(self) -> Any: ...
def geoEntity(self) -> Any: ...
def groupLayers(self, LayersToGroup = ..., RefLayer = ..., LayerName = ..., Flags = ...) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hash(self, UVIndex = ...) -> Any: ...
def height(self, UVIndex = ...) -> Any: ...
def imageHash(self, UVIndex = ...) -> Any: ...
def importImages(self, PathAndTemplate, ScaleOption = ..., MatchingLayersOption = ..., MismatchingLayersOption = ..., UVIndexList = ..., RemoveAlpha = ..., SourceColorConfig = ...) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isLocked(self) -> Any: ...
def isNull(self) -> Any: ...
def isPtex(self) -> Any: ...
def isShaderStack(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def layer(self, LayerName) -> Any: ...
def layerList(self) -> Any: ...
def layerMadeCurrent(self, *args, **kwargs) -> Any: ...
def lock(self) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def makeCurrent(self) -> Any: ...
def mergeLayers(self, LayersToMerge = ..., RefLayer = ..., Flags = ...) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def metricResize(self, Metric, Value, UVIndexList = ...) -> Any: ...
def moveLayer(self, LayerToMove, RefLayer = ...) -> Any: ...
def moveLayerBelow(self, LayerToMove, RefLayer = ...) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeLayers(self, LayersToRemove = ...) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def resize(self, NewSize, UVIndexList = ...) -> Any: ...
def revertToSnapshot(self, OldSnapshot) -> Any: ...
def scalarColorspaceConfig(self) -> Any: ...
def scalarColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setBleed(self, Bleed) -> Any: ...
def setColorspaceConfig(self, Config) -> Any: ...
def setCurrentLayer(self, NewCurrentLayer) -> Any: ...
def setDepth(self, Depth, Option) -> Any: ...
def setFileSpace(self, FileSpace) -> Any: ...
def setLocked(self, Locked) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, NewName) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setScalarColorspaceConfig(self, Config) -> Any: ...
def shareLayer(self, LayerToShare, RefLayer = ..., Flags = ...) -> Any: ...
def signalsBlocked(self) -> Any: ...
def snapshotAdded(self, *args, **kwargs) -> Any: ...
def snapshotList(self) -> Any: ...
def snapshotRemoved(self, *args, **kwargs) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def ungroupLayers(self, GroupLayersToUngroup = ...) -> Any: ...
def unlock(self) -> Any: ...
def updateUvImageSizes(self) -> Any: ...
def uuid(self) -> Any: ...
def width(self, UVIndex = ...) -> Any: ...
