from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import LayerStack
from mari import Metadata

class Channel(LayerStack):
    class ClearSelectionFlag:
        CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
        CLEAR_GROUPS: ClearSelectionFlag = ...
        CLEAR_MASK_STACKS: ClearSelectionFlag = ...
        DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
        name: getset_descriptor
        values: dict

    class ConvertOption:
        CONVERT_ALL: ConvertOption = ...
        CONVERT_CHANNEL_ONLY: ConvertOption = ...
        name: getset_descriptor
        values: dict

    class LayerCreateFlag:
        CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
        DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
        INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
        INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
        MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
        SELECT_NEW_LAYERS: LayerCreateFlag = ...
        name: getset_descriptor
        values: dict

    class LayerImportOption:
        CREATE_NEW_LAYERS: LayerImportOption = ...
        OPTION_NOT_SPECIFIED: LayerImportOption = ...
        SKIP_LAYERS: LayerImportOption = ...
        UPDATE_LAYERS: LayerImportOption = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class ResizeMetric:
        RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
        RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
        RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
        name: getset_descriptor
        values: dict

    CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
    CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
    CLEAR_GROUPS: ClearSelectionFlag = ...
    CLEAR_MASK_STACKS: ClearSelectionFlag = ...
    CONVERT_ALL: ConvertOption = ...
    CONVERT_CHANNEL_ONLY: ConvertOption = ...
    CREATE_NEW_LAYERS: LayerImportOption = ...
    DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
    DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
    INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
    INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
    MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    OPTION_NOT_SPECIFIED: LayerImportOption = ...
    RESIZE_BY_PATCH_MAXIMUM: ResizeMetric = ...
    RESIZE_BY_TEXELS_PER_UNIT: ResizeMetric = ...
    RESIZE_BY_TEXEL_SIZE: ResizeMetric = ...
    SELECT_NEW_LAYERS: LayerCreateFlag = ...
    SKIP_LAYERS: LayerImportOption = ...
    UPDATE_LAYERS: LayerImportOption = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def adjustmentLayerTypeList() -> typing.List: ...
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def proceduralLayerTypeList() -> typing.List: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def transferLayers(UVRemap: typing.Any, SourceLayers: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationLayerStack: mari.LayerStack, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
    def bakeTo(self, TargetLayer: mari.Layer, SelectedOnly: bool = ...) -> bool: ...
    def bleed(self) -> bool: ...
    def blockSignals(self, b: bool) -> bool: ...
    def channelNode(self) -> mari.ChannelNode: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clearSelection(self, Flags: int = ...) -> Any: ...
    def colorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def convertColorSpaceTo(self, NewColorSpace: str, Option = ...) -> Any: ...
    def convertColorspaceTo(self, OutputColorspace: str, InputColorspace: str = ..., Config: str = ..., Option = ...) -> Any: ...
    def createAdjustmentLayer(self, LayerName: str, PrimaryAdjustmentKey: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createBakePointLayer(self, LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createChannelLayer(self, LayerName: str, TargetChannel: mari.Channel, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createCustomProceduralLayer(self, LayerName: str, FilePath: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createGraphLayer(self, LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createGroupLayer(self, LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createMaterialLayer(self, LayerName: str, FilePath: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createMultiChannelGroupLayer(self, LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createPaintableLayer(self, LayerName: str, RefLayer: typing.Optional = ..., FillColor: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createProceduralLayer(self, LayerName: str, ProceduralKey: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createShaderLayer(self, LayerName: str, TargetShader: mari.Shader, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def createSnapshot(self, Name: str, ID: str = ...) -> mari.Snapshot: ...
    def currentLayer(self) -> mari.Layer: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def deleteSnapshot(self, ShotToDelete: mari.Snapshot) -> Any: ...
    def depth(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def duplicateLayers(self, LayersToDuplicate: typing.Sequence = ..., RefLayer: typing.Optional = ..., Flags: int = ...) -> typing.List: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportImages(self, PathAndTemplate: str, Options: int = ..., UVIndexList: typing.Sequence = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
    def exportImagesFlattened(self, PathAndTemplate: str, Options: int = ..., UVIndexList: typing.Sequence = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
    def exportSelectedPatches(self, PathAndTemplate: str, Options: int = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
    def exportSelectedPatchesFlattened(self, PathAndTemplate: str, Options: int = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
    def exportToGeoChannel(self, GeoChannelName: str) -> bool: ...
    def fileSpace(self) -> Any: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def findLayer(self, LayerName: str) -> mari.Layer: ...
    def findSnapshotWithID(self, ID: str) -> mari.Snapshot: ...
    def flatten(self) -> mari.Layer: ...
    def geoEntity(self) -> mari.GeoEntity: ...
    def groupLayers(self, LayersToGroup: typing.Sequence = ..., RefLayer: typing.Optional = ..., LayerName: str = ..., Flags: int = ...) -> mari.Layer: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def hash(self, UVIndex: int = ...) -> str: ...
    def height(self, UVIndex: int = ...) -> int: ...
    def imageHash(self, UVIndex: int = ...) -> str: ...
    def importImages(self, PathAndTemplate: str, ScaleOption = ..., MatchingLayersOption = ..., MismatchingLayersOption = ..., UVIndexList: typing.Sequence = ..., RemoveAlpha: bool = ..., SourceColorConfig: typing.Optional = ...) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isLocked(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isPtex(self) -> bool: ...
    def isShaderStack(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def layer(self, LayerName: str) -> mari.Layer: ...
    def layerList(self) -> typing.List: ...
    def layerMadeCurrent(self, *args, **kwargs) -> Any: ...
    def lock(self) -> Any: ...
    def lockedChanged(self, *args, **kwargs) -> Any: ...
    def makeCurrent(self) -> Any: ...
    def mergeLayers(self, LayersToMerge: typing.Sequence = ..., RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def metricResize(self, Metric, Value: float, UVIndexList: typing.Sequence = ...) -> Any: ...
    def moveLayer(self, LayerToMove: mari.Layer, RefLayer: typing.Optional = ...) -> Any: ...
    def moveLayerBelow(self, LayerToMove: mari.Layer, RefLayer: typing.Optional = ...) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeLayers(self, LayersToRemove: typing.Sequence = ...) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def resize(self, NewSize, UVIndexList: typing.Sequence = ...) -> Any: ...
    def revertToSnapshot(self, OldSnapshot: mari.Snapshot) -> Any: ...
    def scalarColorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def scalarColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setBleed(self, Bleed: bool) -> Any: ...
    def setColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setCurrentLayer(self, NewCurrentLayer: mari.Layer) -> Any: ...
    def setDepth(self, Depth, Option) -> Any: ...
    def setFileSpace(self, FileSpace) -> Any: ...
    def setLocked(self, Locked: bool) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, NewName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setScalarColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def shareLayer(self, LayerToShare: mari.Layer, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
    def signalsBlocked(self) -> bool: ...
    def snapshotAdded(self, *args, **kwargs) -> Any: ...
    def snapshotList(self) -> typing.List: ...
    def snapshotRemoved(self, *args, **kwargs) -> Any: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def ungroupLayers(self, GroupLayersToUngroup: typing.Sequence = ...) -> Any: ...
    def unlock(self) -> Any: ...
    def updateUvImageSizes(self) -> Any: ...
    def uuid(self) -> str: ...
    def width(self, UVIndex: int = ...) -> int: ...
