from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Clock(API):
    class PlayDirection:
        BACKWARDS: PlayDirection = ...
        FORWARDS: PlayDirection = ...
        name: getset_descriptor
        values: dict

    class RepeatType:
        BOUNCE: RepeatType = ...
        LOOP: RepeatType = ...
        STOP: RepeatType = ...
        name: getset_descriptor
        values: dict

    BACKWARDS: PlayDirection = ...
    BOUNCE: RepeatType = ...
    FORWARDS: PlayDirection = ...
    LOOP: RepeatType = ...
    STOP: RepeatType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def frame(self) -> int: ...
    def frameChanged(self, *args, **kwargs) -> Any: ...
    def frameCount(self) -> int: ...
    def frameRate(self) -> int: ...
    def frameRateChanged(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def loopCount(self) -> int: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def play(self, Direction = ...) -> Any: ...
    def playing(self) -> bool: ...
    def playingChanged(self, *args, **kwargs) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def rangeChanged(self, *args, **kwargs) -> Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def repeatType(self) -> Any: ...
    def reset(self) -> Any: ...
    def rewind(self) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setFrame(self, Frame: int) -> Any: ...
    def setFrameRange(self, Start: int, End: int) -> Any: ...
    def setFrameRate(self, fps: int) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRepeatType(self, Type) -> Any: ...
    def setSourceFrameRate(self, Fps: int) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def sourceFrameRate(self) -> int: ...
    def startFrame(self) -> int: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def stepBack(self) -> Any: ...
    def stepForward(self) -> Any: ...
    def stop(self) -> Any: ...
    def stopFrame(self) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def time(self) -> str: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
