from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class PlayDirection:
    BACKWARDS: PlayDirection = ...
    FORWARDS: PlayDirection = ...
    name: getset_descriptor
    values: dict

class RepeatType:
    BOUNCE: RepeatType = ...
    LOOP: RepeatType = ...
    STOP: RepeatType = ...
    name: getset_descriptor
    values: dict

BACKWARDS: PlayDirection = ...
BOUNCE: RepeatType = ...
FORWARDS: PlayDirection = ...
LOOP: RepeatType = ...
STOP: RepeatType = ...
staticMetaObject: QMetaObject
BACKWARDS: PlayDirection = ...
BOUNCE: RepeatType = ...
FORWARDS: PlayDirection = ...
LOOP: RepeatType = ...
STOP: RepeatType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def frame(self) -> Any: ...
def frameChanged(self, *args, **kwargs) -> Any: ...
def frameCount(self) -> Any: ...
def frameRate(self) -> Any: ...
def frameRateChanged(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def loopCount(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def play(self, Direction = ...) -> Any: ...
def playing(self) -> Any: ...
def playingChanged(self, *args, **kwargs) -> Any: ...
def property(self, name) -> Any: ...
def rangeChanged(self, *args, **kwargs) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def repeatType(self) -> Any: ...
def reset(self) -> Any: ...
def rewind(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setFrame(self, Frame) -> Any: ...
def setFrameRange(self, Start, End) -> Any: ...
def setFrameRate(self, fps) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRepeatType(self, Type) -> Any: ...
def setSourceFrameRate(self, Fps) -> Any: ...
def signalsBlocked(self) -> Any: ...
def sourceFrameRate(self) -> Any: ...
def startFrame(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def stepBack(self) -> Any: ...
def stepForward(self) -> Any: ...
def stop(self) -> Any: ...
def stopFrame(self) -> Any: ...
def thread(self) -> Any: ...
def time(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
