from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceDefaults(API):
    class ColorspaceTarget:
        COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
        COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
        COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
        COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
        COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
        COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
        COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
        COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
        COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
        COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
        name: getset_descriptor
        values: dict

    COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
    COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
    COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
    COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
    COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def availableColorspaces(self, Target = ..., PrettyNames: bool = ...) -> typing.List: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorManagementEnabled(self) -> bool: ...
    def colorspace(self, Target) -> str: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def defaultColorspace(self, Target) -> str: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def fileName(self) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def hasColorspace(self, Colorspace: str) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isFileCustom(self) -> bool: ...
    def isFileValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isValid(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def reset(self) -> Any: ...
    def resolveColorspace(self, Target) -> str: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setColorManagementEnabled(self, Enable: bool) -> Any: ...
    def setColorspace(self, Target, Colorspace: str) -> Any: ...
    def setFileName(self, FileName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
