from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def a(self) -> Any: ...
def b(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exposure(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def g(self) -> Any: ...
def h(self) -> Any: ...
def hsl(self) -> Any: ...
def hsla(self) -> Any: ...
def hsv(self) -> Any: ...
def hsva(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def l(self) -> Any: ...
def lum(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def r(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def rgb(self) -> Any: ...
def rgba(self) -> Any: ...
def s(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setA(self, Alpha) -> Any: ...
def setB(self, Blue) -> Any: ...
def setG(self, Green) -> Any: ...
def setH(self, Hue) -> Any: ...
def setHSL(self, Hue, Saturation, Lightness) -> Any: ...
def setHSLA(self, Hue, Saturation, Lightness, Alpha) -> Any: ...
def setHSV(self, Hue, Saturation, Value) -> Any: ...
def setHSVA(self, Hue, Saturation, Value, Alpha) -> Any: ...
def setL(self, Lightness) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setR(self, Red) -> Any: ...
def setRGB(self, Red, Green, Blue) -> Any: ...
def setRGBA(self, Red, Green, Blue, Alpha) -> Any: ...
def setS(self, Saturation) -> Any: ...
def setV(self, Value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toString(self) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def userReadable(self) -> Any: ...
def v(self) -> Any: ...
