from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceTarget:
    COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
    COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
    COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
    COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
    COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
    name: getset_descriptor
    values: dict

COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
staticMetaObject: QMetaObject
COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def availableColorspaces(self, Target = ..., PrettyNames = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorManagementEnabled(self) -> Any: ...
def colorspace(self, Target) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def defaultColorspace(self, Target) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def fileName(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def hasColorspace(self, Colorspace) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isFileCustom(self) -> Any: ...
def isFileValid(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isValid(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def reset(self) -> Any: ...
def resolveColorspace(self, Target) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setColorManagementEnabled(self, Enable) -> Any: ...
def setColorspace(self, Target, Colorspace) -> Any: ...
def setFileName(self, FileName) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
