from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceConfig(API):
    class ColorspaceStage:
        COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
        COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
        COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
        COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
        name: getset_descriptor
        values: dict

    class ColorspaceType:
        COLORSPACE_TYPE_COUNT: ColorspaceType = ...
        COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
        COLORSPACE_TYPE_INT16: ColorspaceType = ...
        COLORSPACE_TYPE_INT8: ColorspaceType = ...
        name: getset_descriptor
        values: dict

    COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
    COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
    COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
    COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
    COLORSPACE_TYPE_COUNT: ColorspaceType = ...
    COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
    COLORSPACE_TYPE_INT16: ColorspaceType = ...
    COLORSPACE_TYPE_INT8: ColorspaceType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def automaticColorspace(self, Stage) -> str: ...
    def automaticType(self, Stage) -> Any: ...
    def availableColorspaces(self, Stage = ..., PrettyNames: bool = ...) -> typing.List: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorspace(self, Stage) -> str: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def defaultColorspace(self, Stage) -> str: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def fileName(self) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def fromString(self, Str: str) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isColorspaceValid(self, Colorspace: str, Stage = ..., Strict: bool = ...) -> bool: ...
    def isFileCustom(self) -> bool: ...
    def isFileValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isValid(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def raw(self) -> bool: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def reset(self) -> Any: ...
    def resolveColorspace(self, Stage) -> str: ...
    def resolveRaw(self) -> bool: ...
    def scalar(self) -> bool: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAutomaticColorspace(self, Stage, Colorspace: str) -> Any: ...
    def setAutomaticType(self, Stage, Type) -> Any: ...
    def setColorspace(self, Stage, Colorspace: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRaw(self, Enable: bool) -> Any: ...
    def setScalar(self, Enable: bool) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toString(self) -> str: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
