from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Color(API):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def a(self) -> float: ...
    def b(self) -> float: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exposure(self) -> float: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def g(self) -> float: ...
    def h(self) -> float: ...
    def hsl(self) -> typing.List: ...
    def hsla(self) -> typing.List: ...
    def hsv(self) -> typing.List: ...
    def hsva(self) -> typing.List: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def l(self) -> float: ...
    def lum(self) -> float: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def r(self) -> float: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def rgb(self) -> typing.List: ...
    def rgba(self) -> typing.List: ...
    def s(self) -> float: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setA(self, Alpha: float) -> Any: ...
    def setB(self, Blue: float) -> Any: ...
    def setG(self, Green: float) -> Any: ...
    def setH(self, Hue: float) -> Any: ...
    def setHSL(self, Hue: float, Saturation: float, Lightness: float) -> Any: ...
    def setHSLA(self, Hue: float, Saturation: float, Lightness: float, Alpha: float) -> Any: ...
    def setHSV(self, Hue: float, Saturation: float, Value: float) -> Any: ...
    def setHSVA(self, Hue: float, Saturation: float, Value: float, Alpha: float) -> Any: ...
    def setL(self, Lightness: float) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setR(self, Red: float) -> Any: ...
    def setRGB(self, Red: float, Green: float, Blue: float) -> Any: ...
    def setRGBA(self, Red: float, Green: float, Blue: float, Alpha: float) -> Any: ...
    def setS(self, Saturation: float) -> Any: ...
    def setV(self, Value: float) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toString(self) -> str: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def userReadable(self) -> str: ...
    def v(self) -> float: ...
