from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceTarget:
    COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
    COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
    COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
    COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
    COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
    COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
    COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
    name: getset_descriptor
    values: dict

COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
staticMetaObject: QMetaObject
COLORSPACE_TARGET_BLENDING: ColorspaceTarget = ...
COLORSPACE_TARGET_COLOR_PICKER: ColorspaceTarget = ...
COLORSPACE_TARGET_COUNT: ColorspaceTarget = ...
COLORSPACE_TARGET_FLOAT: ColorspaceTarget = ...
COLORSPACE_TARGET_INT16: ColorspaceTarget = ...
COLORSPACE_TARGET_INT8: ColorspaceTarget = ...
COLORSPACE_TARGET_INT_SCALAR: ColorspaceTarget = ...
COLORSPACE_TARGET_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_SCALAR_MONITOR: ColorspaceTarget = ...
COLORSPACE_TARGET_WORKING: ColorspaceTarget = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def availableColorspaces(Target = ..., PrettyNames: bool = ...) -> typing.List: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def colorManagementEnabled() -> bool: ...
def colorspace(Target) -> str: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def defaultColorspace(Target) -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def fileName() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def hasColorspace(Colorspace: str) -> bool: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isFileCustom() -> bool: ...
def isFileValid() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isValid() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def reset() -> Any: ...
def resolveColorspace(Target) -> str: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setColorManagementEnabled(Enable: bool) -> Any: ...
def setColorspace(Target, Colorspace: str) -> Any: ...
def setFileName(FileName: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
