from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceStage:
    COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
    COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
    COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
    COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
    name: getset_descriptor
    values: dict

class ColorspaceType:
    COLORSPACE_TYPE_COUNT: ColorspaceType = ...
    COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
    COLORSPACE_TYPE_INT16: ColorspaceType = ...
    COLORSPACE_TYPE_INT8: ColorspaceType = ...
    name: getset_descriptor
    values: dict

COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
COLORSPACE_TYPE_COUNT: ColorspaceType = ...
COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
COLORSPACE_TYPE_INT16: ColorspaceType = ...
COLORSPACE_TYPE_INT8: ColorspaceType = ...
staticMetaObject: QMetaObject
COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
COLORSPACE_TYPE_COUNT: ColorspaceType = ...
COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
COLORSPACE_TYPE_INT16: ColorspaceType = ...
COLORSPACE_TYPE_INT8: ColorspaceType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def automaticColorspace(Stage) -> str: ...
def automaticType(Stage) -> Any: ...
def availableColorspaces(Stage = ..., PrettyNames: bool = ...) -> typing.List: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def colorspace(Stage) -> str: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def defaultColorspace(Stage) -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def fileName() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def fromString(Str: str) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isColorspaceValid(Colorspace: str, Stage = ..., Strict: bool = ...) -> bool: ...
def isFileCustom() -> bool: ...
def isFileValid() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isValid() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def raw() -> bool: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def reset() -> Any: ...
def resolveColorspace(Stage) -> str: ...
def resolveRaw() -> bool: ...
def scalar() -> bool: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setAutomaticColorspace(Stage, Colorspace: str) -> Any: ...
def setAutomaticType(Stage, Type) -> Any: ...
def setColorspace(Stage, Colorspace: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setRaw(Enable: bool) -> Any: ...
def setScalar(Enable: bool) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def toString() -> str: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
