from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorspaceStage:
    COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
    COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
    COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
    COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
    name: getset_descriptor
    values: dict

class ColorspaceType:
    COLORSPACE_TYPE_COUNT: ColorspaceType = ...
    COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
    COLORSPACE_TYPE_INT16: ColorspaceType = ...
    COLORSPACE_TYPE_INT8: ColorspaceType = ...
    name: getset_descriptor
    values: dict

COLORSPACE_STAGE_COUNT: ColorspaceStage = ...
COLORSPACE_STAGE_NATIVE: ColorspaceStage = ...
COLORSPACE_STAGE_OUTPUT: ColorspaceStage = ...
COLORSPACE_STAGE_WORKING: ColorspaceStage = ...
COLORSPACE_TYPE_COUNT: ColorspaceType = ...
COLORSPACE_TYPE_FLOAT: ColorspaceType = ...
COLORSPACE_TYPE_INT16: ColorspaceType = ...
COLORSPACE_TYPE_INT8: ColorspaceType = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def automaticColorspace(self, Stage) -> Any: ...
def automaticType(self, Stage) -> Any: ...
def availableColorspaces(self, Stage = ..., PrettyNames = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorspace(self, Stage) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def defaultColorspace(self, Stage) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def fileName(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def fromString(self, Str) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isColorspaceValid(self, Colorspace, Stage = ..., Strict = ...) -> Any: ...
def isFileCustom(self) -> Any: ...
def isFileValid(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isValid(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def raw(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def reset(self) -> Any: ...
def resolveColorspace(self, Stage) -> Any: ...
def resolveRaw(self) -> Any: ...
def scalar(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setAutomaticColorspace(self, Stage, Colorspace) -> Any: ...
def setAutomaticType(self, Stage, Type) -> Any: ...
def setColorspace(self, Stage, Colorspace) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRaw(self, Enable) -> Any: ...
def setScalar(self, Enable) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toString(self) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
