from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import GroupNode
from mari import Metadata
from mari import Node

class CustomProceduralType:
    CUSTOMPROCEDURAL_TYPE_COLOR: CustomProceduralType = ...
    CUSTOMPROCEDURAL_TYPE_MASK: CustomProceduralType = ...
    CUSTOMPROCEDURAL_TYPE_SCALAR: CustomProceduralType = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class PortListMode:
    PORT_LIST_COLLAPSED: PortListMode = ...
    PORT_LIST_EXPANDED: PortListMode = ...
    PORT_LIST_GROUPED: PortListMode = ...
    PORT_LIST_ONLY_CONNECTED: PortListMode = ...
    PORT_LIST_T2B: PortListMode = ...
    name: getset_descriptor
    values: dict

CUSTOMPROCEDURAL_TYPE_COLOR: CustomProceduralType = ...
CUSTOMPROCEDURAL_TYPE_MASK: CustomProceduralType = ...
CUSTOMPROCEDURAL_TYPE_SCALAR: CustomProceduralType = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
PORT_LIST_COLLAPSED: PortListMode = ...
PORT_LIST_EXPANDED: PortListMode = ...
PORT_LIST_GROUPED: PortListMode = ...
PORT_LIST_ONLY_CONNECTED: PortListMode = ...
PORT_LIST_T2B: PortListMode = ...
staticMetaObject: QMetaObject
CUSTOMPROCEDURAL_TYPE_COLOR: CustomProceduralType = ...
CUSTOMPROCEDURAL_TYPE_MASK: CustomProceduralType = ...
CUSTOMPROCEDURAL_TYPE_SCALAR: CustomProceduralType = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
PORT_LIST_COLLAPSED: PortListMode = ...
PORT_LIST_EXPANDED: PortListMode = ...
PORT_LIST_GROUPED: PortListMode = ...
PORT_LIST_ONLY_CONNECTED: PortListMode = ...
PORT_LIST_T2B: PortListMode = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def readMetadataFromCustomProceduralFile(CustomProceduralFilePath) -> Any: ...
@staticmethod
def readSystemMetadataFromCustomProceduralFile(CustomProceduralFilePath) -> Any: ...
@staticmethod
def readTagsFromCustomProceduralFile(CustomProceduralFilePath) -> Any: ...
@staticmethod
def readThumbnailFromCustomProceduralFile(CustomProceduralFilePath) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def writeMetadataToCustomProceduralFile(MetadataMap, CustomProceduralFilePath) -> Any: ...
@staticmethod
def writeTagsToCustomProceduralFile(Tags, CustomProceduralFilePath) -> Any: ...
@staticmethod
def writeThumbnailToCustomProceduralFile(Thumbnail, CustomProceduralFilePath) -> Any: ...
def addCustomProceduralTag(self, Tag) -> Any: ...
def addCustomProceduralTags(self, Tags) -> Any: ...
def addNodeContext(self, Name, Context) -> Any: ...
def addTag(self, Tag, ForceAdd = ...) -> Any: ...
def attachViewer(self, InputNumber = ...) -> Any: ...
def bake(self, Width, Height, Depth, FileSpace = ..., ColorConfig = ..., OutputPortName = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def bypassInput(self, OutputPoint = ...) -> Any: ...
def childEvent(self, event) -> Any: ...
def childNodeGraph(self) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def connectSignals(self) -> Any: ...
def convertToCustomProcedural(self) -> Any: ...
def createKnob(self, KnobName, TargetNode, TargetAttributeName, PrettyKnobName = ...) -> Any: ...
def customEvent(self, event) -> Any: ...
def customProceduralTags(self) -> Any: ...
def customProceduralType(self) -> Any: ...
def deleteKnob(self, KnobName, TargetNode, TargetAttributeName) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportCustomProcedural(self, FileName, ThumbnailFileName = ...) -> Any: ...
def exportToGeoChannel(self, DestGeoChannel, OutputPortName = ...) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def focusInNodeGraph(self) -> Any: ...
def geoChannels(self) -> Any: ...
def getNodeGraphViewContextMeta(self) -> Any: ...
def groupInputNode(self, InputName) -> Any: ...
def groupOutputNode(self, OutputName) -> Any: ...
def hasChanged(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hasTag(self, Tag) -> Any: ...
def hash(self, UVIndex = ..., IgnoreChildren = ...) -> Any: ...
def inherits(self, classname) -> Any: ...
def inputConnection(self, PortName) -> Any: ...
def inputNode(self, PortName) -> Any: ...
def inputNodeChanged(self, *args, **kwargs) -> Any: ...
def inputPortCount(self) -> Any: ...
def inputPortName(self, Index) -> Any: ...
def inputPortNames(self) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isBackdropNode(self) -> Any: ...
def isBakePointNode(self) -> Any: ...
def isEnabled(self) -> Any: ...
def isGeoChannelNode(self) -> Any: ...
def isGroupNode(self) -> Any: ...
def isNull(self) -> Any: ...
def isPaintNode(self) -> Any: ...
def isSelected(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def knobList(self) -> Any: ...
def linkKnobs(self, KnobName, TargetKnobNames, PrettyKnobName = ...) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def missingGeoChannels(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def nodeContext(self, Name) -> Any: ...
def nodeContextNames(self) -> Any: ...
def nodeGraphPosition(self) -> Any: ...
def nodeGraphSize(self) -> Any: ...
def nodeInformation(self) -> Any: ...
def nodePath(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def outputNodes(self, PortName = ...) -> Any: ...
def outputPortCount(self) -> Any: ...
def outputPortName(self, Index) -> Any: ...
def outputPortNames(self) -> Any: ...
def parent(self) -> Any: ...
def parentNodeGraph(self) -> Any: ...
def pathKey(self) -> Any: ...
def portListMode(self) -> Any: ...
def printVersionHashSource(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeCustomProceduralTag(self, Tag) -> Any: ...
def removeCustomProceduralTags(self, Tags) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def removeNodeContext(self, Name) -> Any: ...
def removeTag(self, Tag, ForceRemove = ...) -> Any: ...
def renameKnob(self, OldName, NewName) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setBypassInput(self, BypassInput) -> Any: ...
def setCustomProceduralTags(self, CustomProceduralTags) -> Any: ...
def setCustomProceduralType(self, Type) -> Any: ...
def setEnabled(self, Enabled) -> Any: ...
def setInputNode(self, PortName, NodeToConnect, OutputPortName = ...) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, NewName) -> Any: ...
def setNodeGraphPosition(self, Position) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPortListMode(self, Mode) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSelected(self, Selected) -> Any: ...
def setTypeID(self, TypeID) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def tagList(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def typeID(self) -> Any: ...
def uuid(self) -> Any: ...
