from typing import Any
from PySide2.QtCore import QObject
from PySide2.QtGui import QPaintDevice
from PySide2.QtWidgets import QDialog
from PySide2.QtWidgets import QWidget
from Shiboken import Object

class DialogCode:
    Accepted: DialogCode
    Rejected: DialogCode
    name: getset_descriptor
    values: dict

class PaintDeviceMetric:
    PdmDepth: PaintDeviceMetric
    PdmDevicePixelRatio: PaintDeviceMetric
    PdmDevicePixelRatioScaled: PaintDeviceMetric
    PdmDpiX: PaintDeviceMetric
    PdmDpiY: PaintDeviceMetric
    PdmHeight: PaintDeviceMetric
    PdmHeightMM: PaintDeviceMetric
    PdmNumColors: PaintDeviceMetric
    PdmPhysicalDpiX: PaintDeviceMetric
    PdmPhysicalDpiY: PaintDeviceMetric
    PdmWidth: PaintDeviceMetric
    PdmWidthMM: PaintDeviceMetric
    name: getset_descriptor
    values: dict

class RenderFlag:
    DrawChildren: RenderFlag
    DrawWindowBackground: RenderFlag
    IgnoreMask: RenderFlag
    name: getset_descriptor
    values: dict

class RenderFlags:
    pass

Accepted: DialogCode
DrawChildren: RenderFlag
DrawWindowBackground: RenderFlag
IgnoreMask: RenderFlag
PdmDepth: PaintDeviceMetric
PdmDevicePixelRatio: PaintDeviceMetric
PdmDevicePixelRatioScaled: PaintDeviceMetric
PdmDpiX: PaintDeviceMetric
PdmDpiY: PaintDeviceMetric
PdmHeight: PaintDeviceMetric
PdmHeightMM: PaintDeviceMetric
PdmNumColors: PaintDeviceMetric
PdmPhysicalDpiX: PaintDeviceMetric
PdmPhysicalDpiY: PaintDeviceMetric
PdmWidth: PaintDeviceMetric
PdmWidthMM: PaintDeviceMetric
Rejected: DialogCode
painters: getset_descriptor
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def createWindowContainer(window, parent = ..., flags = ...) -> Any: ...
@staticmethod
def devicePixelRatioFScale() -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def find(arg__1) -> Any: ...
@staticmethod
def keyboardGrabber() -> Any: ...
@staticmethod
def mouseGrabber() -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def setTabOrder(arg__1, arg__2) -> Any: ...
def accept(self) -> Any: ...
def acceptDrops(self) -> Any: ...
def accepted(self, *args, **kwargs) -> Any: ...
def accessibleDescription(self) -> Any: ...
def accessibleName(self) -> Any: ...
def actionEvent(self, event) -> Any: ...
def actions(self) -> Any: ...
def activateWindow(self) -> Any: ...
def addAction(self, action) -> Any: ...
def addActions(self, actions) -> Any: ...
def adjustPosition(self, arg__1) -> Any: ...
def adjustSize(self) -> Any: ...
def autoFillBackground(self) -> Any: ...
def backgroundRole(self) -> Any: ...
def backingStore(self) -> Any: ...
def baseSize(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def changeEvent(self, event) -> Any: ...
def childAt(self, *args, **kwargs) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def childrenRect(self) -> Any: ...
def childrenRegion(self) -> Any: ...
def clearFocus(self) -> Any: ...
def clearMask(self) -> Any: ...
def close(self) -> Any: ...
def closeEvent(self, arg__1) -> Any: ...
def colorCount(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def contentsMargins(self) -> Any: ...
def contentsRect(self) -> Any: ...
def contextMenuEvent(self, arg__1) -> Any: ...
def contextMenuPolicy(self) -> Any: ...
def create(self, arg__1 = ..., initializeWindow = ..., destroyOldWindow = ...) -> Any: ...
def createWinId(self) -> Any: ...
def cursor(self) -> Any: ...
def customContextMenuRequested(self, *args, **kwargs) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depth(self) -> Any: ...
def destroy(self, destroyWindow = ..., destroySubWindows = ...) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def devType(self) -> Any: ...
def devicePixelRatio(self) -> Any: ...
def devicePixelRatioF(self) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def done(self, arg__1) -> Any: ...
def dragEnterEvent(self, event) -> Any: ...
def dragLeaveEvent(self, event) -> Any: ...
def dragMoveEvent(self, event) -> Any: ...
def dropEvent(self, event) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def effectiveWinId(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def ensurePolished(self) -> Any: ...
def enterEvent(self, event) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, arg__1, arg__2) -> Any: ...
def exec_(self) -> Any: ...
def extension(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def finished(self, *args, **kwargs) -> Any: ...
def focusInEvent(self, event) -> Any: ...
def focusNextChild(self) -> Any: ...
def focusNextPrevChild(self, next) -> Any: ...
def focusOutEvent(self, event) -> Any: ...
def focusPolicy(self) -> Any: ...
def focusPreviousChild(self) -> Any: ...
def focusProxy(self) -> Any: ...
def focusWidget(self) -> Any: ...
def font(self) -> Any: ...
def fontInfo(self) -> Any: ...
def fontMetrics(self) -> Any: ...
def foregroundRole(self) -> Any: ...
def frameGeometry(self) -> Any: ...
def frameSize(self) -> Any: ...
def geometry(self) -> Any: ...
def getContentsMargins(self) -> Any: ...
def grab(self, rectangle = ...) -> Any: ...
def grabGesture(self, type, flags = ...) -> Any: ...
def grabKeyboard(self) -> Any: ...
def grabMouse(self, *args, **kwargs) -> Any: ...
def grabShortcut(self, key, context = ...) -> Any: ...
def graphicsEffect(self) -> Any: ...
def graphicsProxyWidget(self) -> Any: ...
def hasFocus(self) -> Any: ...
def hasHeightForWidth(self) -> Any: ...
def hasMouseTracking(self) -> Any: ...
def hasTabletTracking(self) -> Any: ...
def height(self) -> Any: ...
def heightForWidth(self, arg__1) -> Any: ...
def heightMM(self) -> Any: ...
def hide(self) -> Any: ...
def hideEvent(self, event) -> Any: ...
def inherits(self, classname) -> Any: ...
def initPainter(self, painter) -> Any: ...
def inputMethodEvent(self, event) -> Any: ...
def inputMethodHints(self) -> Any: ...
def inputMethodQuery(self, arg__1) -> Any: ...
def insertAction(self, before, action) -> Any: ...
def insertActions(self, before, actions) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def internalWinId(self) -> Any: ...
def isActiveWindow(self) -> Any: ...
def isAncestorOf(self, child) -> Any: ...
def isEnabled(self) -> Any: ...
def isEnabledTo(self, arg__1) -> Any: ...
def isEnabledToTLW(self) -> Any: ...
def isFullScreen(self) -> Any: ...
def isHidden(self) -> Any: ...
def isLeftToRight(self) -> Any: ...
def isMaximized(self) -> Any: ...
def isMinimized(self) -> Any: ...
def isModal(self) -> Any: ...
def isRightToLeft(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isSizeGripEnabled(self) -> Any: ...
def isTopLevel(self) -> Any: ...
def isVisible(self) -> Any: ...
def isVisibleTo(self, arg__1) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindow(self) -> Any: ...
def isWindowModified(self) -> Any: ...
def isWindowType(self) -> Any: ...
def keyPressEvent(self, arg__1) -> Any: ...
def keyReleaseEvent(self, event) -> Any: ...
def killTimer(self, id) -> Any: ...
def layout(self) -> Any: ...
def layoutDirection(self) -> Any: ...
def leaveEvent(self, event) -> Any: ...
def locale(self) -> Any: ...
def logicalDpiX(self) -> Any: ...
def logicalDpiY(self) -> Any: ...
def lower(self) -> Any: ...
def mapFrom(self, arg__1, arg__2) -> Any: ...
def mapFromGlobal(self, arg__1) -> Any: ...
def mapFromParent(self, arg__1) -> Any: ...
def mapTo(self, arg__1, arg__2) -> Any: ...
def mapToGlobal(self, arg__1) -> Any: ...
def mapToParent(self, arg__1) -> Any: ...
def mask(self) -> Any: ...
def maximumHeight(self) -> Any: ...
def maximumSize(self) -> Any: ...
def maximumWidth(self) -> Any: ...
def metaObject(self) -> Any: ...
def metric(self, arg__1) -> Any: ...
def minimumHeight(self) -> Any: ...
def minimumSize(self) -> Any: ...
def minimumSizeHint(self) -> Any: ...
def minimumWidth(self) -> Any: ...
def mouseDoubleClickEvent(self, event) -> Any: ...
def mouseMoveEvent(self, event) -> Any: ...
def mousePressEvent(self, event) -> Any: ...
def mouseReleaseEvent(self, event) -> Any: ...
def move(self, *args, **kwargs) -> Any: ...
def moveEvent(self, event) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def nativeEvent(self, eventType, message) -> Any: ...
def nativeParentWidget(self) -> Any: ...
def nextInFocusChain(self) -> Any: ...
def normalGeometry(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def open(self) -> Any: ...
def orientation(self) -> Any: ...
def overrideWindowFlags(self, type) -> Any: ...
def overrideWindowState(self, state) -> Any: ...
def paintEngine(self) -> Any: ...
def paintEvent(self, event) -> Any: ...
def paintingActive(self) -> Any: ...
def palette(self) -> Any: ...
def parent(self) -> Any: ...
def parentWidget(self) -> Any: ...
def physicalDpiX(self) -> Any: ...
def physicalDpiY(self) -> Any: ...
def pos(self) -> Any: ...
def previousInFocusChain(self) -> Any: ...
def property(self, name) -> Any: ...
def raise_(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def rect(self) -> Any: ...
def redirected(self, offset) -> Any: ...
def reject(self) -> Any: ...
def rejected(self, *args, **kwargs) -> Any: ...
def releaseKeyboard(self) -> Any: ...
def releaseMouse(self) -> Any: ...
def releaseShortcut(self, id) -> Any: ...
def removeAction(self, action) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def render(self, *args, **kwargs) -> Any: ...
def repaint(self, *args, **kwargs) -> Any: ...
def resize(self, *args, **kwargs) -> Any: ...
def resizeEvent(self, arg__1) -> Any: ...
def restoreGeometry(self, geometry) -> Any: ...
def result(self) -> Any: ...
def saveGeometry(self) -> Any: ...
def screen(self) -> Any: ...
def scroll(self, *args, **kwargs) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setAcceptDrops(self, on) -> Any: ...
def setAccessibleDescription(self, description) -> Any: ...
def setAccessibleName(self, name) -> Any: ...
def setAttribute(self, arg__1, on = ...) -> Any: ...
def setAutoFillBackground(self, enabled) -> Any: ...
def setBackgroundRole(self, arg__1) -> Any: ...
def setBaseSize(self, *args, **kwargs) -> Any: ...
def setContentsMargins(self, *args, **kwargs) -> Any: ...
def setContextMenuPolicy(self, policy) -> Any: ...
def setCursor(self, arg__1) -> Any: ...
def setDisabled(self, arg__1) -> Any: ...
def setEnabled(self, arg__1) -> Any: ...
def setExtension(self, extension) -> Any: ...
def setFixedHeight(self, h) -> Any: ...
def setFixedSize(self, *args, **kwargs) -> Any: ...
def setFixedWidth(self, w) -> Any: ...
def setFocus(self, *args, **kwargs) -> Any: ...
def setFocusPolicy(self, policy) -> Any: ...
def setFocusProxy(self, arg__1) -> Any: ...
def setFont(self, arg__1) -> Any: ...
def setForegroundRole(self, arg__1) -> Any: ...
def setGeometry(self, *args, **kwargs) -> Any: ...
def setGraphicsEffect(self, effect) -> Any: ...
def setHidden(self, hidden) -> Any: ...
def setInputMethodHints(self, hints) -> Any: ...
def setLayout(self, arg__1) -> Any: ...
def setLayoutDirection(self, direction) -> Any: ...
def setLocale(self, locale) -> Any: ...
def setMask(self, *args, **kwargs) -> Any: ...
def setMaximumHeight(self, maxh) -> Any: ...
def setMaximumSize(self, *args, **kwargs) -> Any: ...
def setMaximumWidth(self, maxw) -> Any: ...
def setMinimumHeight(self, minh) -> Any: ...
def setMinimumSize(self, *args, **kwargs) -> Any: ...
def setMinimumWidth(self, minw) -> Any: ...
def setModal(self, modal) -> Any: ...
def setMouseTracking(self, enable) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setOrientation(self, orientation) -> Any: ...
def setPalette(self, arg__1) -> Any: ...
def setParent(self, *args, **kwargs) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setResult(self, r) -> Any: ...
def setShortcutAutoRepeat(self, id, enable = ...) -> Any: ...
def setShortcutEnabled(self, id, enable = ...) -> Any: ...
def setSizeGripEnabled(self, arg__1) -> Any: ...
def setSizeIncrement(self, *args, **kwargs) -> Any: ...
def setSizePolicy(self, *args, **kwargs) -> Any: ...
def setStatusTip(self, arg__1) -> Any: ...
def setStyle(self, arg__1) -> Any: ...
def setStyleSheet(self, styleSheet) -> Any: ...
def setTabletTracking(self, enable) -> Any: ...
def setToolTip(self, arg__1) -> Any: ...
def setToolTipDuration(self, msec) -> Any: ...
def setUpdatesEnabled(self, enable) -> Any: ...
def setVisible(self, visible) -> Any: ...
def setWhatsThis(self, arg__1) -> Any: ...
def setWindowFilePath(self, filePath) -> Any: ...
def setWindowFlag(self, arg__1, on = ...) -> Any: ...
def setWindowFlags(self, type) -> Any: ...
def setWindowIcon(self, icon) -> Any: ...
def setWindowIconText(self, arg__1) -> Any: ...
def setWindowModality(self, windowModality) -> Any: ...
def setWindowModified(self, arg__1) -> Any: ...
def setWindowOpacity(self, level) -> Any: ...
def setWindowRole(self, arg__1) -> Any: ...
def setWindowState(self, state) -> Any: ...
def setWindowTitle(self, arg__1) -> Any: ...
def sharedPainter(self) -> Any: ...
def show(self) -> Any: ...
def showEvent(self, event) -> Any: ...
def showExtension(self, arg__1) -> Any: ...
def showFullScreen(self) -> Any: ...
def showMaximized(self) -> Any: ...
def showMinimized(self) -> Any: ...
def showNormal(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def size(self) -> Any: ...
def sizeHint(self) -> Any: ...
def sizeIncrement(self) -> Any: ...
def sizePolicy(self) -> Any: ...
def stackUnder(self, arg__1) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def statusTip(self) -> Any: ...
def style(self) -> Any: ...
def styleSheet(self) -> Any: ...
def tabletEvent(self, event) -> Any: ...
def testAttribute(self, arg__1) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toolTip(self) -> Any: ...
def toolTipDuration(self) -> Any: ...
def topLevelWidget(self) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def underMouse(self) -> Any: ...
def ungrabGesture(self, type) -> Any: ...
def unsetCursor(self) -> Any: ...
def unsetLayoutDirection(self) -> Any: ...
def unsetLocale(self) -> Any: ...
def update(self, *args, **kwargs) -> Any: ...
def updateGeometry(self) -> Any: ...
def updateMicroFocus(self) -> Any: ...
def updatesEnabled(self) -> Any: ...
def visibleRegion(self) -> Any: ...
def whatsThis(self) -> Any: ...
def wheelEvent(self, event) -> Any: ...
def width(self) -> Any: ...
def widthMM(self) -> Any: ...
def winId(self) -> Any: ...
def window(self) -> Any: ...
def windowFilePath(self) -> Any: ...
def windowFlags(self) -> Any: ...
def windowHandle(self) -> Any: ...
def windowIcon(self) -> Any: ...
def windowIconChanged(self, *args, **kwargs) -> Any: ...
def windowIconText(self) -> Any: ...
def windowIconTextChanged(self, *args, **kwargs) -> Any: ...
def windowModality(self) -> Any: ...
def windowOpacity(self) -> Any: ...
def windowRole(self) -> Any: ...
def windowState(self) -> Any: ...
def windowTitle(self) -> Any: ...
def windowTitleChanged(self, *args, **kwargs) -> Any: ...
def windowType(self) -> Any: ...
def x(self) -> Any: ...
def y(self) -> Any: ...
