from typing import Any
from PySide2.QtCore import QObject
from PySide2.QtGui import QPaintDevice
from PySide2.QtWidgets import QDialog
from PySide2.QtWidgets import QWidget
from Shiboken import Object

class Dialog(QDialog):
    class DialogCode:
        Accepted: DialogCode
        Rejected: DialogCode
        name: getset_descriptor
        values: dict

    class PaintDeviceMetric:
        PdmDepth: PaintDeviceMetric
        PdmDevicePixelRatio: PaintDeviceMetric
        PdmDevicePixelRatioScaled: PaintDeviceMetric
        PdmDpiX: PaintDeviceMetric
        PdmDpiY: PaintDeviceMetric
        PdmHeight: PaintDeviceMetric
        PdmHeightMM: PaintDeviceMetric
        PdmNumColors: PaintDeviceMetric
        PdmPhysicalDpiX: PaintDeviceMetric
        PdmPhysicalDpiY: PaintDeviceMetric
        PdmWidth: PaintDeviceMetric
        PdmWidthMM: PaintDeviceMetric
        name: getset_descriptor
        values: dict

    class RenderFlag:
        DrawChildren: RenderFlag
        DrawWindowBackground: RenderFlag
        IgnoreMask: RenderFlag
        name: getset_descriptor
        values: dict

    class RenderFlags:
        pass

    Accepted: DialogCode
    DrawChildren: RenderFlag
    DrawWindowBackground: RenderFlag
    IgnoreMask: RenderFlag
    PdmDepth: PaintDeviceMetric
    PdmDevicePixelRatio: PaintDeviceMetric
    PdmDevicePixelRatioScaled: PaintDeviceMetric
    PdmDpiX: PaintDeviceMetric
    PdmDpiY: PaintDeviceMetric
    PdmHeight: PaintDeviceMetric
    PdmHeightMM: PaintDeviceMetric
    PdmNumColors: PaintDeviceMetric
    PdmPhysicalDpiX: PaintDeviceMetric
    PdmPhysicalDpiY: PaintDeviceMetric
    PdmWidth: PaintDeviceMetric
    PdmWidthMM: PaintDeviceMetric
    Rejected: DialogCode
    painters: getset_descriptor
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def createWindowContainer(window: PySide2.QtGui.QWindow, parent: typing.Optional = ..., flags: PySide2.QtCore.WindowFlags = ...) -> PySide2.QtWidgets.QWidget: ...
    @staticmethod
    def devicePixelRatioFScale() -> float: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def find(arg__1: int) -> PySide2.QtWidgets.QWidget: ...
    @staticmethod
    def keyboardGrabber() -> PySide2.QtWidgets.QWidget: ...
    @staticmethod
    def mouseGrabber() -> PySide2.QtWidgets.QWidget: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def setTabOrder(arg__1: PySide2.QtWidgets.QWidget, arg__2: PySide2.QtWidgets.QWidget) -> Any: ...
    def accept(self) -> Any: ...
    def acceptDrops(self) -> bool: ...
    def accepted(self, *args, **kwargs) -> Any: ...
    def accessibleDescription(self) -> str: ...
    def accessibleName(self) -> str: ...
    def actionEvent(self, event: PySide2.QtGui.QActionEvent) -> Any: ...
    def actions(self) -> typing.List: ...
    def activateWindow(self) -> Any: ...
    def addAction(self, action: PySide2.QtWidgets.QAction) -> Any: ...
    def addActions(self, actions: typing.Sequence) -> Any: ...
    def adjustPosition(self, arg__1: PySide2.QtWidgets.QWidget) -> Any: ...
    def adjustSize(self) -> Any: ...
    def autoFillBackground(self) -> bool: ...
    def backgroundRole(self) -> Any: ...
    def backingStore(self) -> PySide2.QtGui.QBackingStore: ...
    def baseSize(self) -> PySide2.QtCore.QSize: ...
    def blockSignals(self, b: bool) -> bool: ...
    def changeEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def childAt(self, *args, **kwargs) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def childrenRect(self) -> PySide2.QtCore.QRect: ...
    def childrenRegion(self) -> PySide2.QtGui.QRegion: ...
    def clearFocus(self) -> Any: ...
    def clearMask(self) -> Any: ...
    def close(self) -> bool: ...
    def closeEvent(self, arg__1: PySide2.QtGui.QCloseEvent) -> Any: ...
    def colorCount(self) -> int: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def contentsMargins(self) -> PySide2.QtCore.QMargins: ...
    def contentsRect(self) -> PySide2.QtCore.QRect: ...
    def contextMenuEvent(self, arg__1: PySide2.QtGui.QContextMenuEvent) -> Any: ...
    def contextMenuPolicy(self) -> Any: ...
    def create(self, arg__1: int = ..., initializeWindow: bool = ..., destroyOldWindow: bool = ...) -> Any: ...
    def createWinId(self) -> Any: ...
    def cursor(self) -> PySide2.QtGui.QCursor: ...
    def customContextMenuRequested(self, *args, **kwargs) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depth(self) -> int: ...
    def destroy(self, destroyWindow: bool = ..., destroySubWindows: bool = ...) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def devType(self) -> int: ...
    def devicePixelRatio(self) -> int: ...
    def devicePixelRatioF(self) -> float: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def done(self, arg__1: int) -> Any: ...
    def dragEnterEvent(self, event: PySide2.QtGui.QDragEnterEvent) -> Any: ...
    def dragLeaveEvent(self, event: PySide2.QtGui.QDragLeaveEvent) -> Any: ...
    def dragMoveEvent(self, event: PySide2.QtGui.QDragMoveEvent) -> Any: ...
    def dropEvent(self, event: PySide2.QtGui.QDropEvent) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def effectiveWinId(self) -> int: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def ensurePolished(self) -> Any: ...
    def enterEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, arg__1: PySide2.QtCore.QObject, arg__2: PySide2.QtCore.QEvent) -> bool: ...
    def exec_(self) -> int: ...
    def extension(self) -> PySide2.QtWidgets.QWidget: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def finished(self, *args, **kwargs) -> Any: ...
    def focusInEvent(self, event: PySide2.QtGui.QFocusEvent) -> Any: ...
    def focusNextChild(self) -> bool: ...
    def focusNextPrevChild(self, next: bool) -> bool: ...
    def focusOutEvent(self, event: PySide2.QtGui.QFocusEvent) -> Any: ...
    def focusPolicy(self) -> Any: ...
    def focusPreviousChild(self) -> bool: ...
    def focusProxy(self) -> PySide2.QtWidgets.QWidget: ...
    def focusWidget(self) -> PySide2.QtWidgets.QWidget: ...
    def font(self) -> PySide2.QtGui.QFont: ...
    def fontInfo(self) -> PySide2.QtGui.QFontInfo: ...
    def fontMetrics(self) -> PySide2.QtGui.QFontMetrics: ...
    def foregroundRole(self) -> Any: ...
    def frameGeometry(self) -> PySide2.QtCore.QRect: ...
    def frameSize(self) -> PySide2.QtCore.QSize: ...
    def geometry(self) -> PySide2.QtCore.QRect: ...
    def getContentsMargins(self) -> typing.Tuple: ...
    def grab(self, rectangle: PySide2.QtCore.QRect = ...) -> PySide2.QtGui.QPixmap: ...
    def grabGesture(self, type, flags: PySide2.QtCore.GestureFlags = ...) -> Any: ...
    def grabKeyboard(self) -> Any: ...
    def grabMouse(self, *args, **kwargs) -> Any: ...
    def grabShortcut(self, key: PySide2.QtGui.QKeySequence, context = ...) -> int: ...
    def graphicsEffect(self) -> PySide2.QtWidgets.QGraphicsEffect: ...
    def graphicsProxyWidget(self) -> PySide2.QtWidgets.QGraphicsProxyWidget: ...
    def hasFocus(self) -> bool: ...
    def hasHeightForWidth(self) -> bool: ...
    def hasMouseTracking(self) -> bool: ...
    def hasTabletTracking(self) -> bool: ...
    def height(self) -> int: ...
    def heightForWidth(self, arg__1: int) -> int: ...
    def heightMM(self) -> int: ...
    def hide(self) -> Any: ...
    def hideEvent(self, event) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def initPainter(self, painter: PySide2.QtGui.QPainter) -> Any: ...
    def inputMethodEvent(self, event: PySide2.QtGui.QInputMethodEvent) -> Any: ...
    def inputMethodHints(self) -> PySide2.QtCore.InputMethodHints: ...
    def inputMethodQuery(self, arg__1) -> typing.Any: ...
    def insertAction(self, before: PySide2.QtWidgets.QAction, action: PySide2.QtWidgets.QAction) -> Any: ...
    def insertActions(self, before: PySide2.QtWidgets.QAction, actions: typing.Sequence) -> Any: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def internalWinId(self) -> int: ...
    def isActiveWindow(self) -> bool: ...
    def isAncestorOf(self, child: PySide2.QtWidgets.QWidget) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isEnabledTo(self, arg__1: PySide2.QtWidgets.QWidget) -> bool: ...
    def isEnabledToTLW(self) -> bool: ...
    def isFullScreen(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def isLeftToRight(self) -> bool: ...
    def isMaximized(self) -> bool: ...
    def isMinimized(self) -> bool: ...
    def isModal(self) -> bool: ...
    def isRightToLeft(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isSizeGripEnabled(self) -> bool: ...
    def isTopLevel(self) -> bool: ...
    def isVisible(self) -> bool: ...
    def isVisibleTo(self, arg__1: PySide2.QtWidgets.QWidget) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindow(self) -> bool: ...
    def isWindowModified(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def keyPressEvent(self, arg__1: PySide2.QtGui.QKeyEvent) -> Any: ...
    def keyReleaseEvent(self, event: PySide2.QtGui.QKeyEvent) -> Any: ...
    def killTimer(self, id: int) -> Any: ...
    def layout(self) -> PySide2.QtWidgets.QLayout: ...
    def layoutDirection(self) -> Any: ...
    def leaveEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def locale(self) -> PySide2.QtCore.QLocale: ...
    def logicalDpiX(self) -> int: ...
    def logicalDpiY(self) -> int: ...
    def lower(self) -> Any: ...
    def mapFrom(self, arg__1: PySide2.QtWidgets.QWidget, arg__2: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mapFromGlobal(self, arg__1: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mapFromParent(self, arg__1: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mapTo(self, arg__1: PySide2.QtWidgets.QWidget, arg__2: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mapToGlobal(self, arg__1: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mapToParent(self, arg__1: PySide2.QtCore.QPoint) -> PySide2.QtCore.QPoint: ...
    def mask(self) -> PySide2.QtGui.QRegion: ...
    def maximumHeight(self) -> int: ...
    def maximumSize(self) -> PySide2.QtCore.QSize: ...
    def maximumWidth(self) -> int: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metric(self, arg__1) -> int: ...
    def minimumHeight(self) -> int: ...
    def minimumSize(self) -> PySide2.QtCore.QSize: ...
    def minimumSizeHint(self) -> PySide2.QtCore.QSize: ...
    def minimumWidth(self) -> int: ...
    def mouseDoubleClickEvent(self, event: PySide2.QtGui.QMouseEvent) -> Any: ...
    def mouseMoveEvent(self, event: PySide2.QtGui.QMouseEvent) -> Any: ...
    def mousePressEvent(self, event: PySide2.QtGui.QMouseEvent) -> Any: ...
    def mouseReleaseEvent(self, event: PySide2.QtGui.QMouseEvent) -> Any: ...
    def move(self, *args, **kwargs) -> Any: ...
    def moveEvent(self, event: PySide2.QtGui.QMoveEvent) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def nativeEvent(self, eventType: PySide2.QtCore.QByteArray, message: int) -> typing.Tuple: ...
    def nativeParentWidget(self) -> PySide2.QtWidgets.QWidget: ...
    def nextInFocusChain(self) -> PySide2.QtWidgets.QWidget: ...
    def normalGeometry(self) -> PySide2.QtCore.QRect: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def open(self) -> Any: ...
    def orientation(self) -> Any: ...
    def overrideWindowFlags(self, type: PySide2.QtCore.WindowFlags) -> Any: ...
    def overrideWindowState(self, state: PySide2.QtCore.WindowStates) -> Any: ...
    def paintEngine(self) -> PySide2.QtGui.QPaintEngine: ...
    def paintEvent(self, event: PySide2.QtGui.QPaintEvent) -> Any: ...
    def paintingActive(self) -> bool: ...
    def palette(self) -> PySide2.QtGui.QPalette: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def parentWidget(self) -> PySide2.QtWidgets.QWidget: ...
    def physicalDpiX(self) -> int: ...
    def physicalDpiY(self) -> int: ...
    def pos(self) -> PySide2.QtCore.QPoint: ...
    def previousInFocusChain(self) -> PySide2.QtWidgets.QWidget: ...
    def property(self, name: bytes) -> typing.Any: ...
    def raise_(self) -> Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def rect(self) -> PySide2.QtCore.QRect: ...
    def redirected(self, offset: PySide2.QtCore.QPoint) -> PySide2.QtGui.QPaintDevice: ...
    def reject(self) -> Any: ...
    def rejected(self, *args, **kwargs) -> Any: ...
    def releaseKeyboard(self) -> Any: ...
    def releaseMouse(self) -> Any: ...
    def releaseShortcut(self, id: int) -> Any: ...
    def removeAction(self, action: PySide2.QtWidgets.QAction) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def render(self, *args, **kwargs) -> Any: ...
    def repaint(self, *args, **kwargs) -> Any: ...
    def resize(self, *args, **kwargs) -> Any: ...
    def resizeEvent(self, arg__1: PySide2.QtGui.QResizeEvent) -> Any: ...
    def restoreGeometry(self, geometry: PySide2.QtCore.QByteArray) -> bool: ...
    def result(self) -> int: ...
    def saveGeometry(self) -> PySide2.QtCore.QByteArray: ...
    def screen(self) -> PySide2.QtGui.QScreen: ...
    def scroll(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAcceptDrops(self, on: bool) -> Any: ...
    def setAccessibleDescription(self, description: str) -> Any: ...
    def setAccessibleName(self, name: str) -> Any: ...
    def setAttribute(self, arg__1, on: bool = ...) -> Any: ...
    def setAutoFillBackground(self, enabled: bool) -> Any: ...
    def setBackgroundRole(self, arg__1) -> Any: ...
    def setBaseSize(self, *args, **kwargs) -> Any: ...
    def setContentsMargins(self, *args, **kwargs) -> Any: ...
    def setContextMenuPolicy(self, policy) -> Any: ...
    def setCursor(self, arg__1: PySide2.QtGui.QCursor) -> Any: ...
    def setDisabled(self, arg__1: bool) -> Any: ...
    def setEnabled(self, arg__1: bool) -> Any: ...
    def setExtension(self, extension: PySide2.QtWidgets.QWidget) -> Any: ...
    def setFixedHeight(self, h: int) -> Any: ...
    def setFixedSize(self, *args, **kwargs) -> Any: ...
    def setFixedWidth(self, w: int) -> Any: ...
    def setFocus(self, *args, **kwargs) -> Any: ...
    def setFocusPolicy(self, policy) -> Any: ...
    def setFocusProxy(self, arg__1: PySide2.QtWidgets.QWidget) -> Any: ...
    def setFont(self, arg__1: PySide2.QtGui.QFont) -> Any: ...
    def setForegroundRole(self, arg__1) -> Any: ...
    def setGeometry(self, *args, **kwargs) -> Any: ...
    def setGraphicsEffect(self, effect: PySide2.QtWidgets.QGraphicsEffect) -> Any: ...
    def setHidden(self, hidden: bool) -> Any: ...
    def setInputMethodHints(self, hints: PySide2.QtCore.InputMethodHints) -> Any: ...
    def setLayout(self, arg__1: PySide2.QtWidgets.QLayout) -> Any: ...
    def setLayoutDirection(self, direction) -> Any: ...
    def setLocale(self, locale: PySide2.QtCore.QLocale) -> Any: ...
    def setMask(self, *args, **kwargs) -> Any: ...
    def setMaximumHeight(self, maxh: int) -> Any: ...
    def setMaximumSize(self, *args, **kwargs) -> Any: ...
    def setMaximumWidth(self, maxw: int) -> Any: ...
    def setMinimumHeight(self, minh: int) -> Any: ...
    def setMinimumSize(self, *args, **kwargs) -> Any: ...
    def setMinimumWidth(self, minw: int) -> Any: ...
    def setModal(self, modal: bool) -> Any: ...
    def setMouseTracking(self, enable: bool) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setOrientation(self, orientation) -> Any: ...
    def setPalette(self, arg__1: PySide2.QtGui.QPalette) -> Any: ...
    def setParent(self, *args, **kwargs) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setResult(self, r: int) -> Any: ...
    def setShortcutAutoRepeat(self, id: int, enable: bool = ...) -> Any: ...
    def setShortcutEnabled(self, id: int, enable: bool = ...) -> Any: ...
    def setSizeGripEnabled(self, arg__1: bool) -> Any: ...
    def setSizeIncrement(self, *args, **kwargs) -> Any: ...
    def setSizePolicy(self, *args, **kwargs) -> Any: ...
    def setStatusTip(self, arg__1: str) -> Any: ...
    def setStyle(self, arg__1: PySide2.QtWidgets.QStyle) -> Any: ...
    def setStyleSheet(self, styleSheet: str) -> Any: ...
    def setTabletTracking(self, enable: bool) -> Any: ...
    def setToolTip(self, arg__1: str) -> Any: ...
    def setToolTipDuration(self, msec: int) -> Any: ...
    def setUpdatesEnabled(self, enable: bool) -> Any: ...
    def setVisible(self, visible: bool) -> Any: ...
    def setWhatsThis(self, arg__1: str) -> Any: ...
    def setWindowFilePath(self, filePath: str) -> Any: ...
    def setWindowFlag(self, arg__1, on: bool = ...) -> Any: ...
    def setWindowFlags(self, type: PySide2.QtCore.WindowFlags) -> Any: ...
    def setWindowIcon(self, icon: PySide2.QtGui.QIcon) -> Any: ...
    def setWindowIconText(self, arg__1: str) -> Any: ...
    def setWindowModality(self, windowModality) -> Any: ...
    def setWindowModified(self, arg__1: bool) -> Any: ...
    def setWindowOpacity(self, level: float) -> Any: ...
    def setWindowRole(self, arg__1: str) -> Any: ...
    def setWindowState(self, state: PySide2.QtCore.WindowStates) -> Any: ...
    def setWindowTitle(self, arg__1: str) -> Any: ...
    def sharedPainter(self) -> PySide2.QtGui.QPainter: ...
    def show(self) -> Any: ...
    def showEvent(self, event) -> Any: ...
    def showExtension(self, arg__1: bool) -> Any: ...
    def showFullScreen(self) -> Any: ...
    def showMaximized(self) -> Any: ...
    def showMinimized(self) -> Any: ...
    def showNormal(self) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def size(self) -> PySide2.QtCore.QSize: ...
    def sizeHint(self) -> PySide2.QtCore.QSize: ...
    def sizeIncrement(self) -> PySide2.QtCore.QSize: ...
    def sizePolicy(self) -> PySide2.QtWidgets.QSizePolicy: ...
    def stackUnder(self, arg__1: PySide2.QtWidgets.QWidget) -> Any: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def statusTip(self) -> str: ...
    def style(self) -> PySide2.QtWidgets.QStyle: ...
    def styleSheet(self) -> str: ...
    def tabletEvent(self, event: PySide2.QtGui.QTabletEvent) -> Any: ...
    def testAttribute(self, arg__1) -> bool: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toolTip(self) -> str: ...
    def toolTipDuration(self) -> int: ...
    def topLevelWidget(self) -> PySide2.QtWidgets.QWidget: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def underMouse(self) -> bool: ...
    def ungrabGesture(self, type) -> Any: ...
    def unsetCursor(self) -> Any: ...
    def unsetLayoutDirection(self) -> Any: ...
    def unsetLocale(self) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
    def updateGeometry(self) -> Any: ...
    def updateMicroFocus(self) -> Any: ...
    def updatesEnabled(self) -> bool: ...
    def visibleRegion(self) -> PySide2.QtGui.QRegion: ...
    def whatsThis(self) -> str: ...
    def wheelEvent(self, event: PySide2.QtGui.QWheelEvent) -> Any: ...
    def width(self) -> int: ...
    def widthMM(self) -> int: ...
    def winId(self) -> int: ...
    def window(self) -> PySide2.QtWidgets.QWidget: ...
    def windowFilePath(self) -> str: ...
    def windowFlags(self) -> PySide2.QtCore.WindowFlags: ...
    def windowHandle(self) -> PySide2.QtGui.QWindow: ...
    def windowIcon(self) -> PySide2.QtGui.QIcon: ...
    def windowIconChanged(self, *args, **kwargs) -> Any: ...
    def windowIconText(self) -> str: ...
    def windowIconTextChanged(self, *args, **kwargs) -> Any: ...
    def windowModality(self) -> Any: ...
    def windowOpacity(self) -> float: ...
    def windowRole(self) -> str: ...
    def windowState(self) -> PySide2.QtCore.WindowStates: ...
    def windowTitle(self) -> str: ...
    def windowTitleChanged(self, *args, **kwargs) -> Any: ...
    def windowType(self) -> Any: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
