from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Light
from mari import Metadata

class EnvironmentLight(Light):
    class CubeImageType:
        TYPE_2D_CROSS: CubeImageType = ...
        TYPE_2D_LATLONG: CubeImageType = ...
        TYPE_3D_CUBEMAP: CubeImageType = ...
        TYPE_GUESS: CubeImageType = ...
        TYPE_NONE: CubeImageType = ...
        name: getset_descriptor
        values: dict

    class FixedTo:
        CAMERA: FixedTo = ...
        SCENE: FixedTo = ...
        name: getset_descriptor
        values: dict

    class ImageUpAxis:
        AXIS_UP_X: ImageUpAxis = ...
        AXIS_UP_Y: ImageUpAxis = ...
        AXIS_UP_Z: ImageUpAxis = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class RotationMode:
        MODE_ROTATE: RotationMode = ...
        MODE_STATIC: RotationMode = ...
        name: getset_descriptor
        values: dict

    AXIS_UP_X: ImageUpAxis = ...
    AXIS_UP_Y: ImageUpAxis = ...
    AXIS_UP_Z: ImageUpAxis = ...
    CAMERA: FixedTo = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    MODE_ROTATE: RotationMode = ...
    MODE_STATIC: RotationMode = ...
    SCENE: FixedTo = ...
    TYPE_2D_CROSS: CubeImageType = ...
    TYPE_2D_LATLONG: CubeImageType = ...
    TYPE_3D_CUBEMAP: CubeImageType = ...
    TYPE_GUESS: CubeImageType = ...
    TYPE_NONE: CubeImageType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def canvasBlur(self) -> float: ...
    def canvasBlurChanged(self, *args, **kwargs) -> Any: ...
    def canvasDisplay(self) -> bool: ...
    def canvasDisplayChanged(self, *args, **kwargs) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clearCubeImageCache(self) -> Any: ...
    def clearLightCache(self) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def cubeImage(self) -> mari.Image: ...
    def cubeImageFilename(self) -> str: ...
    def cubeImageFilenameChanged(self, *args, **kwargs) -> Any: ...
    def cubeImageResolution(self) -> int: ...
    def cubeImageResolutionChanged(self, *args, **kwargs) -> Any: ...
    def cubeImageType(self) -> Any: ...
    def cubeImageTypeChanged(self, *args, **kwargs) -> Any: ...
    def cubeImageUpAxis(self) -> Any: ...
    def cubeImageUpAxisChanged(self, *args, **kwargs) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def fixedTo(self) -> Any: ...
    def fixedToChanged(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def intensity(self) -> float: ...
    def intensityChanged(self, *args, **kwargs) -> Any: ...
    def isEnvironmentLight(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isOn(self) -> bool: ...
    def isPointLight(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def onChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def printLightCacheKeys(self) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def rotationUp(self) -> float: ...
    def rotationUpChanged(self, *args, **kwargs) -> Any: ...
    def rotationUpMode(self) -> Any: ...
    def rotationUpModeChanged(self, *args, **kwargs) -> Any: ...
    def rotationUpSpeed(self) -> float: ...
    def rotationUpSpeedChanged(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCanvasBlur(self, Blur: float) -> Any: ...
    def setCanvasDisplay(self, Display: bool) -> Any: ...
    def setCubeImage(self, rImage: typing.Any, Type) -> Any: ...
    def setCubeImageResolution(self, Resolution: int) -> Any: ...
    def setCubeImageType(self, Type) -> Any: ...
    def setCubeImageUpAxis(self, Axis) -> Any: ...
    def setFixedTo(self, TargetType) -> Any: ...
    def setIntensity(self, Intensity: float) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setOn(self, OnOrOff: bool) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRotationUp(self, Angle: float) -> Any: ...
    def setRotationUpMode(self, Mode) -> Any: ...
    def setRotationUpSpeed(self, Speed: float) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def uuid(self) -> str: ...
