from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Light
from mari import Metadata

class CubeImageType:
    TYPE_2D_CROSS: CubeImageType = ...
    TYPE_2D_LATLONG: CubeImageType = ...
    TYPE_3D_CUBEMAP: CubeImageType = ...
    TYPE_GUESS: CubeImageType = ...
    TYPE_NONE: CubeImageType = ...
    name: getset_descriptor
    values: dict

class FixedTo:
    CAMERA: FixedTo = ...
    SCENE: FixedTo = ...
    name: getset_descriptor
    values: dict

class ImageUpAxis:
    AXIS_UP_X: ImageUpAxis = ...
    AXIS_UP_Y: ImageUpAxis = ...
    AXIS_UP_Z: ImageUpAxis = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class RotationMode:
    MODE_ROTATE: RotationMode = ...
    MODE_STATIC: RotationMode = ...
    name: getset_descriptor
    values: dict

AXIS_UP_X: ImageUpAxis = ...
AXIS_UP_Y: ImageUpAxis = ...
AXIS_UP_Z: ImageUpAxis = ...
CAMERA: FixedTo = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MODE_ROTATE: RotationMode = ...
MODE_STATIC: RotationMode = ...
SCENE: FixedTo = ...
TYPE_2D_CROSS: CubeImageType = ...
TYPE_2D_LATLONG: CubeImageType = ...
TYPE_3D_CUBEMAP: CubeImageType = ...
TYPE_GUESS: CubeImageType = ...
TYPE_NONE: CubeImageType = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def canvasBlur(self) -> Any: ...
def canvasBlurChanged(self, *args, **kwargs) -> Any: ...
def canvasDisplay(self) -> Any: ...
def canvasDisplayChanged(self, *args, **kwargs) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clearCubeImageCache(self) -> Any: ...
def clearLightCache(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def cubeImage(self) -> Any: ...
def cubeImageFilename(self) -> Any: ...
def cubeImageFilenameChanged(self, *args, **kwargs) -> Any: ...
def cubeImageResolution(self) -> Any: ...
def cubeImageResolutionChanged(self, *args, **kwargs) -> Any: ...
def cubeImageType(self) -> Any: ...
def cubeImageTypeChanged(self, *args, **kwargs) -> Any: ...
def cubeImageUpAxis(self) -> Any: ...
def cubeImageUpAxisChanged(self, *args, **kwargs) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def fixedTo(self) -> Any: ...
def fixedToChanged(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def intensity(self) -> Any: ...
def intensityChanged(self, *args, **kwargs) -> Any: ...
def isEnvironmentLight(self) -> Any: ...
def isNull(self) -> Any: ...
def isOn(self) -> Any: ...
def isPointLight(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def printLightCacheKeys(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def rotationUp(self) -> Any: ...
def rotationUpChanged(self, *args, **kwargs) -> Any: ...
def rotationUpMode(self) -> Any: ...
def rotationUpModeChanged(self, *args, **kwargs) -> Any: ...
def rotationUpSpeed(self) -> Any: ...
def rotationUpSpeedChanged(self, *args, **kwargs) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCanvasBlur(self, Blur) -> Any: ...
def setCanvasDisplay(self, Display) -> Any: ...
def setCubeImage(self, rImage, Type) -> Any: ...
def setCubeImageResolution(self, Resolution) -> Any: ...
def setCubeImageType(self, Type) -> Any: ...
def setCubeImageUpAxis(self, Axis) -> Any: ...
def setFixedTo(self, TargetType) -> Any: ...
def setIntensity(self, Intensity) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setOn(self, OnOrOff) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRotationUp(self, Angle) -> Any: ...
def setRotationUpMode(self, Mode) -> Any: ...
def setRotationUpSpeed(self, Speed) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def uuid(self) -> Any: ...
