from typing import Any

class EventCoordinateSpace:
    APPLICATION_SPACE: EventCoordinateSpace = ...
    CANVAS_SPACE: EventCoordinateSpace = ...
    DESKTOP_SPACE: EventCoordinateSpace = ...
    name: getset_descriptor
    values: dict

class EventType:
    KEY_PRESS: EventType = ...
    KEY_RELEASE: EventType = ...
    MOUSE_DOUBLE_CLICK: EventType = ...
    MOUSE_MOVE: EventType = ...
    MOUSE_PRESS: EventType = ...
    MOUSE_RELEASE: EventType = ...
    TABLET_ENTER_PROXIMITY: EventType = ...
    TABLET_LEAVE_PROXIMITY: EventType = ...
    TABLET_MOVE: EventType = ...
    TABLET_PRESS: EventType = ...
    TABLET_RELEASE: EventType = ...
    name: getset_descriptor
    values: dict

class KeyboardModifier:
    ALT_MODIFIER: KeyboardModifier = ...
    CONTROL_MODIFIER: KeyboardModifier = ...
    GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
    KEYPAD_MODIFIER: KeyboardModifier = ...
    META_MODIFIER: KeyboardModifier = ...
    NO_MODIFIER: KeyboardModifier = ...
    SHIFT_MODIFIER: KeyboardModifier = ...
    name: getset_descriptor
    values: dict

class MouseButton:
    LEFT_BUTTON: MouseButton = ...
    MIDDLE_BUTTON: MouseButton = ...
    NO_BUTTON: MouseButton = ...
    RIGHT_BUTTON: MouseButton = ...
    X_BUTTON_1: MouseButton = ...
    X_BUTTON_2: MouseButton = ...
    name: getset_descriptor
    values: dict

def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(pObject, pEvent) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isPlaying() -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
class playbackComplete:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def recordPlay() -> Any: ...
def recordStart(Space = ..., Normalized = ...) -> Any: ...
def recordStop() -> Any: ...
def recordString() -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def sendKeyEvent(Type, Key, Modifiers, AutoRepeat, Msecs = ...) -> Any: ...
def sendMouseEvent(Type, Pos, Button, Buttons, Modifiers, Space = ..., Normalized = ..., Msecs = ..., MoveCursor = ...) -> Any: ...
def sendTabletEvent(Type, Pos, Pressure, Modifiers, Space = ..., Normalized = ..., Msecs = ...) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
