from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class EventCoordinateSpace:
    APPLICATION_SPACE: EventCoordinateSpace = ...
    CANVAS_SPACE: EventCoordinateSpace = ...
    DESKTOP_SPACE: EventCoordinateSpace = ...
    name: getset_descriptor
    values: dict

class EventType:
    KEY_PRESS: EventType = ...
    KEY_RELEASE: EventType = ...
    MOUSE_DOUBLE_CLICK: EventType = ...
    MOUSE_MOVE: EventType = ...
    MOUSE_PRESS: EventType = ...
    MOUSE_RELEASE: EventType = ...
    TABLET_ENTER_PROXIMITY: EventType = ...
    TABLET_LEAVE_PROXIMITY: EventType = ...
    TABLET_MOVE: EventType = ...
    TABLET_PRESS: EventType = ...
    TABLET_RELEASE: EventType = ...
    name: getset_descriptor
    values: dict

class KeyboardModifier:
    ALT_MODIFIER: KeyboardModifier = ...
    CONTROL_MODIFIER: KeyboardModifier = ...
    GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
    KEYPAD_MODIFIER: KeyboardModifier = ...
    META_MODIFIER: KeyboardModifier = ...
    NO_MODIFIER: KeyboardModifier = ...
    SHIFT_MODIFIER: KeyboardModifier = ...
    name: getset_descriptor
    values: dict

class MouseButton:
    LEFT_BUTTON: MouseButton = ...
    MIDDLE_BUTTON: MouseButton = ...
    NO_BUTTON: MouseButton = ...
    RIGHT_BUTTON: MouseButton = ...
    X_BUTTON_1: MouseButton = ...
    X_BUTTON_2: MouseButton = ...
    name: getset_descriptor
    values: dict

ALT_MODIFIER: KeyboardModifier = ...
APPLICATION_SPACE: EventCoordinateSpace = ...
CANVAS_SPACE: EventCoordinateSpace = ...
CONTROL_MODIFIER: KeyboardModifier = ...
DESKTOP_SPACE: EventCoordinateSpace = ...
GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
KEYPAD_MODIFIER: KeyboardModifier = ...
KEY_PRESS: EventType = ...
KEY_RELEASE: EventType = ...
LEFT_BUTTON: MouseButton = ...
META_MODIFIER: KeyboardModifier = ...
MIDDLE_BUTTON: MouseButton = ...
MOUSE_DOUBLE_CLICK: EventType = ...
MOUSE_MOVE: EventType = ...
MOUSE_PRESS: EventType = ...
MOUSE_RELEASE: EventType = ...
NO_BUTTON: MouseButton = ...
NO_MODIFIER: KeyboardModifier = ...
RIGHT_BUTTON: MouseButton = ...
SHIFT_MODIFIER: KeyboardModifier = ...
TABLET_ENTER_PROXIMITY: EventType = ...
TABLET_LEAVE_PROXIMITY: EventType = ...
TABLET_MOVE: EventType = ...
TABLET_PRESS: EventType = ...
TABLET_RELEASE: EventType = ...
X_BUTTON_1: MouseButton = ...
X_BUTTON_2: MouseButton = ...
staticMetaObject: QMetaObject
ALT_MODIFIER: KeyboardModifier = ...
APPLICATION_SPACE: EventCoordinateSpace = ...
CANVAS_SPACE: EventCoordinateSpace = ...
CONTROL_MODIFIER: KeyboardModifier = ...
DESKTOP_SPACE: EventCoordinateSpace = ...
GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
KEYPAD_MODIFIER: KeyboardModifier = ...
KEY_PRESS: EventType = ...
KEY_RELEASE: EventType = ...
LEFT_BUTTON: MouseButton = ...
META_MODIFIER: KeyboardModifier = ...
MIDDLE_BUTTON: MouseButton = ...
MOUSE_DOUBLE_CLICK: EventType = ...
MOUSE_MOVE: EventType = ...
MOUSE_PRESS: EventType = ...
MOUSE_RELEASE: EventType = ...
NO_BUTTON: MouseButton = ...
NO_MODIFIER: KeyboardModifier = ...
RIGHT_BUTTON: MouseButton = ...
SHIFT_MODIFIER: KeyboardModifier = ...
TABLET_ENTER_PROXIMITY: EventType = ...
TABLET_LEAVE_PROXIMITY: EventType = ...
TABLET_MOVE: EventType = ...
TABLET_PRESS: EventType = ...
TABLET_RELEASE: EventType = ...
X_BUTTON_1: MouseButton = ...
X_BUTTON_2: MouseButton = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(pObject: PySide2.QtCore.QObject, pEvent: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isPlaying() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def playbackComplete(*args, **kwargs) -> Any: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def recordPlay() -> Any: ...
def recordStart(Space = ..., Normalized: bool = ...) -> Any: ...
def recordStop() -> Any: ...
def recordString() -> str: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sendKeyEvent(Type, Key: int, Modifiers: int, AutoRepeat: bool, Msecs: int = ...) -> Any: ...
def sendMouseEvent(Type, Pos: PySide2.QtCore.QPointF, Button, Buttons: int, Modifiers: int, Space = ..., Normalized: bool = ..., Msecs: int = ..., MoveCursor: bool = ...) -> Any: ...
def sendTabletEvent(Type, Pos: PySide2.QtCore.QPointF, Pressure: float, Modifiers: int, Space = ..., Normalized: bool = ..., Msecs: int = ...) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
