from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Event(API):
    class EventCoordinateSpace:
        APPLICATION_SPACE: EventCoordinateSpace = ...
        CANVAS_SPACE: EventCoordinateSpace = ...
        DESKTOP_SPACE: EventCoordinateSpace = ...
        name: getset_descriptor
        values: dict

    class EventType:
        KEY_PRESS: EventType = ...
        KEY_RELEASE: EventType = ...
        MOUSE_DOUBLE_CLICK: EventType = ...
        MOUSE_MOVE: EventType = ...
        MOUSE_PRESS: EventType = ...
        MOUSE_RELEASE: EventType = ...
        TABLET_ENTER_PROXIMITY: EventType = ...
        TABLET_LEAVE_PROXIMITY: EventType = ...
        TABLET_MOVE: EventType = ...
        TABLET_PRESS: EventType = ...
        TABLET_RELEASE: EventType = ...
        name: getset_descriptor
        values: dict

    class KeyboardModifier:
        ALT_MODIFIER: KeyboardModifier = ...
        CONTROL_MODIFIER: KeyboardModifier = ...
        GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
        KEYPAD_MODIFIER: KeyboardModifier = ...
        META_MODIFIER: KeyboardModifier = ...
        NO_MODIFIER: KeyboardModifier = ...
        SHIFT_MODIFIER: KeyboardModifier = ...
        name: getset_descriptor
        values: dict

    class MouseButton:
        LEFT_BUTTON: MouseButton = ...
        MIDDLE_BUTTON: MouseButton = ...
        NO_BUTTON: MouseButton = ...
        RIGHT_BUTTON: MouseButton = ...
        X_BUTTON_1: MouseButton = ...
        X_BUTTON_2: MouseButton = ...
        name: getset_descriptor
        values: dict

    ALT_MODIFIER: KeyboardModifier = ...
    APPLICATION_SPACE: EventCoordinateSpace = ...
    CANVAS_SPACE: EventCoordinateSpace = ...
    CONTROL_MODIFIER: KeyboardModifier = ...
    DESKTOP_SPACE: EventCoordinateSpace = ...
    GROUP_SWITCH_MODIFIER: KeyboardModifier = ...
    KEYPAD_MODIFIER: KeyboardModifier = ...
    KEY_PRESS: EventType = ...
    KEY_RELEASE: EventType = ...
    LEFT_BUTTON: MouseButton = ...
    META_MODIFIER: KeyboardModifier = ...
    MIDDLE_BUTTON: MouseButton = ...
    MOUSE_DOUBLE_CLICK: EventType = ...
    MOUSE_MOVE: EventType = ...
    MOUSE_PRESS: EventType = ...
    MOUSE_RELEASE: EventType = ...
    NO_BUTTON: MouseButton = ...
    NO_MODIFIER: KeyboardModifier = ...
    RIGHT_BUTTON: MouseButton = ...
    SHIFT_MODIFIER: KeyboardModifier = ...
    TABLET_ENTER_PROXIMITY: EventType = ...
    TABLET_LEAVE_PROXIMITY: EventType = ...
    TABLET_MOVE: EventType = ...
    TABLET_PRESS: EventType = ...
    TABLET_RELEASE: EventType = ...
    X_BUTTON_1: MouseButton = ...
    X_BUTTON_2: MouseButton = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, pObject: PySide2.QtCore.QObject, pEvent: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isPlaying(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def playbackComplete(self, *args, **kwargs) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def recordPlay(self) -> Any: ...
    def recordStart(self, Space = ..., Normalized: bool = ...) -> Any: ...
    def recordStop(self) -> Any: ...
    def recordString(self) -> str: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sendKeyEvent(self, Type, Key: int, Modifiers: int, AutoRepeat: bool, Msecs: int = ...) -> Any: ...
    def sendMouseEvent(self, Type, Pos: PySide2.QtCore.QPointF, Button, Buttons: int, Modifiers: int, Space = ..., Normalized: bool = ..., Msecs: int = ..., MoveCursor: bool = ...) -> Any: ...
    def sendTabletEvent(self, Type, Pos: PySide2.QtCore.QPointF, Pressure: float, Modifiers: int, Space = ..., Normalized: bool = ..., Msecs: int = ...) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
