from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def sameAsSourceString() -> Any: ...
def addExportItem(self, Item, Entity) -> Any: ...
def allItemsExported(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def checkExportItemIsValid(self, Item, Entity) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorspaceList(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depthList(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportItemList(self, Entity) -> Any: ...
def exportTextures(self, ExportItems, ExportRootPath, Overrides = ..., ShowProgressDialog = ...) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def imageExported(self, *args, **kwargs) -> Any: ...
def imageFileExtensionList(self) -> Any: ...
def imageFileOptions(self, Extension) -> Any: ...
def imageFileOptionsWidget(self, Extension) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def itemAdded(self, *args, **kwargs) -> Any: ...
def itemExported(self, *args, **kwargs) -> Any: ...
def itemRemoved(self, *args, **kwargs) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def postProcessCommandList(self) -> Any: ...
def preferredFileExtension(self, BitDepth) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def registerPostProcessCommand(self, Command) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeExportItem(self, Item) -> Any: ...
def resolutionList(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setImageFileOptions(self, Extension, Options) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPreferredFileExtension(self, BitDepth, Extension) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
