from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
@staticmethod
def sameAsSourceString() -> str: ...
def addExportItem(Item: mari.ExportItem, Entity: mari.GeoEntity) -> Any: ...
def allItemsExported(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def checkExportItemIsValid(Item: mari.ExportItem, Entity: mari.GeoEntity) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def colorspaceList() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def depthList() -> typing.List: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportItemList(Entity: mari.GeoEntity) -> typing.List: ...
def exportTextures(ExportItems: typing.Sequence, ExportRootPath: str, Overrides: typing.Any = ..., ShowProgressDialog: bool = ...) -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def imageExported(*args, **kwargs) -> Any: ...
def imageFileExtensionList() -> typing.List: ...
def imageFileOptions(Extension: str) -> typing.Any: ...
def imageFileOptionsWidget(Extension: str) -> PySide2.QtWidgets.QWidget: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def itemAdded(*args, **kwargs) -> Any: ...
def itemExported(*args, **kwargs) -> Any: ...
def itemRemoved(*args, **kwargs) -> Any: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def postProcessCommandList() -> typing.List: ...
def preferredFileExtension(BitDepth) -> str: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def registerPostProcessCommand(Command: str) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeExportItem(Item: mari.ExportItem) -> Any: ...
def resolutionList() -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setImageFileOptions(Extension: str, Options: typing.Any) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPreferredFileExtension(BitDepth, Extension: str) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
