from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ExportItem(Metadata):
    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorspace(self) -> str: ...
    def colorspaceChanged(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depth(self) -> str: ...
    def depthChanged(self, *args, **kwargs) -> Any: ...
    def deserializeFromString(self, XMLString: str) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def errorStringList(self) -> typing.List: ...
    def errorStringListChanged(self, *args, **kwargs) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportEnabled(self) -> bool: ...
    def exportEnabledChanged(self, *args, **kwargs) -> Any: ...
    def exportedImagesUniform(self) -> bool: ...
    def exportedImagesUniformColor(self) -> mari.Color: ...
    def fileOptions(self) -> typing.Any: ...
    def fileOptionsChanged(self, *args, **kwargs) -> Any: ...
    def fileOptionsString(self) -> str: ...
    def fileTemplate(self) -> str: ...
    def fileTemplateChanged(self, *args, **kwargs) -> Any: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def geoEntity(self) -> mari.GeoEntity: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def imageExported(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def itemExported(self, *args, **kwargs) -> Any: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def onFileOptionsChanged(self, FileOptions: typing.Dict) -> Any: ...
    def onItemExported(self) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def postProcessCommand(self) -> str: ...
    def postProcessCommandChanged(self, *args, **kwargs) -> Any: ...
    def postProcessedFileTemplate(self) -> str: ...
    def preferredFileExtension(self) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def resolution(self) -> str: ...
    def resolutionChanged(self, *args, **kwargs) -> Any: ...
    def resolveColorspace(self) -> str: ...
    def resolveDepth(self) -> Any: ...
    def resolveDepthAsInternalFormat(self) -> int: ...
    def resolveExportFilePaths(self, RootPath: str = ...) -> typing.List: ...
    def resolveFileTemplate(self, Overrides: typing.Any = ...) -> str: ...
    def resolvePostProcessedFileTemplate(self, Overrides: typing.Any = ...) -> str: ...
    def resolveResolutionSizes(self) -> typing.List: ...
    def resolvedColorspace(self) -> str: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def serializeToString(self) -> str: ...
    def setColorspace(self, Colorspace: str) -> Any: ...
    def setDepth(self, Depth: str) -> Any: ...
    def setErrorStringList(self, ErrorStringList: typing.Sequence) -> Any: ...
    def setExportEnabled(self, ExportEnabled: bool) -> Any: ...
    def setFileOptions(self, FileOptions: typing.Any) -> Any: ...
    def setFileTemplate(self, FileTemplate: str) -> Any: ...
    def setGeoEntity(self, Entity: mari.GeoEntity) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPostProcessCommand(self, PostProcessCommand: str) -> Any: ...
    def setPostProcessedFileTemplate(self, PostProcessedFileTemplate: str) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setResolution(self, Resolution: str) -> Any: ...
    def setSourceNode(self, SourceNode: mari.Node) -> Any: ...
    def setUvIndexList(self, UVIndexList: typing.Sequence) -> Any: ...
    def setWarningStringList(self, WarningStringList: typing.Sequence) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def sourceColorspace(self) -> str: ...
    def sourceDepth(self) -> Any: ...
    def sourceDepthAsInternalFormat(self) -> int: ...
    def sourceNode(self) -> mari.Node: ...
    def sourceNodeChanged(self, *args, **kwargs) -> Any: ...
    def sourceNodeDepth(self) -> str: ...
    def sourceNodeName(self) -> str: ...
    def sourceResolution(self) -> str: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def uuid(self) -> str: ...
    def uvIndexList(self) -> typing.List: ...
    def warningStringList(self) -> typing.List: ...
    def warningStringListChanged(self, *args, **kwargs) -> Any: ...
