from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorspace(self) -> Any: ...
def colorspaceChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depth(self) -> Any: ...
def depthChanged(self, *args, **kwargs) -> Any: ...
def deserializeFromString(self, XMLString) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def errorStringList(self) -> Any: ...
def errorStringListChanged(self, *args, **kwargs) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportEnabled(self) -> Any: ...
def exportEnabledChanged(self, *args, **kwargs) -> Any: ...
def exportedImagesUniform(self) -> Any: ...
def exportedImagesUniformColor(self) -> Any: ...
def fileOptions(self) -> Any: ...
def fileOptionsChanged(self, *args, **kwargs) -> Any: ...
def fileOptionsString(self) -> Any: ...
def fileTemplate(self) -> Any: ...
def fileTemplateChanged(self, *args, **kwargs) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def geoEntity(self) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def imageExported(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def itemExported(self, *args, **kwargs) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def onFileOptionsChanged(self, FileOptions) -> Any: ...
def onItemExported(self) -> Any: ...
def parent(self) -> Any: ...
def postProcessCommand(self) -> Any: ...
def postProcessCommandChanged(self, *args, **kwargs) -> Any: ...
def postProcessedFileTemplate(self) -> Any: ...
def preferredFileExtension(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def resolution(self) -> Any: ...
def resolutionChanged(self, *args, **kwargs) -> Any: ...
def resolveColorspace(self) -> Any: ...
def resolveDepth(self) -> Any: ...
def resolveDepthAsInternalFormat(self) -> Any: ...
def resolveExportFilePaths(self, RootPath = ...) -> Any: ...
def resolveFileTemplate(self, Overrides = ...) -> Any: ...
def resolvePostProcessedFileTemplate(self, Overrides = ...) -> Any: ...
def resolveResolutionSizes(self) -> Any: ...
def resolvedColorspace(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def serializeToString(self) -> Any: ...
def setColorspace(self, Colorspace) -> Any: ...
def setDepth(self, Depth) -> Any: ...
def setErrorStringList(self, ErrorStringList) -> Any: ...
def setExportEnabled(self, ExportEnabled) -> Any: ...
def setFileOptions(self, FileOptions) -> Any: ...
def setFileTemplate(self, FileTemplate) -> Any: ...
def setGeoEntity(self, Entity) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPostProcessCommand(self, PostProcessCommand) -> Any: ...
def setPostProcessedFileTemplate(self, PostProcessedFileTemplate) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setResolution(self, Resolution) -> Any: ...
def setSourceNode(self, SourceNode) -> Any: ...
def setUvIndexList(self, UVIndexList) -> Any: ...
def setWarningStringList(self, WarningStringList) -> Any: ...
def signalsBlocked(self) -> Any: ...
def sourceColorspace(self) -> Any: ...
def sourceDepth(self) -> Any: ...
def sourceDepthAsInternalFormat(self) -> Any: ...
def sourceNode(self) -> Any: ...
def sourceNodeChanged(self, *args, **kwargs) -> Any: ...
def sourceNodeDepth(self) -> Any: ...
def sourceNodeName(self) -> Any: ...
def sourceResolution(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def uuid(self) -> Any: ...
def uvIndexList(self) -> Any: ...
def warningStringList(self) -> Any: ...
def warningStringListChanged(self, *args, **kwargs) -> Any: ...
