from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def colorspace() -> str: ...
def colorspaceChanged(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def depth() -> str: ...
def depthChanged(*args, **kwargs) -> Any: ...
def deserializeFromString(XMLString: str) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def errorStringList() -> typing.List: ...
def errorStringListChanged(*args, **kwargs) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportEnabled() -> bool: ...
def exportEnabledChanged(*args, **kwargs) -> Any: ...
def exportedImagesUniform() -> bool: ...
def exportedImagesUniformColor() -> mari.Color: ...
def fileOptions() -> typing.Any: ...
def fileOptionsChanged(*args, **kwargs) -> Any: ...
def fileOptionsString() -> str: ...
def fileTemplate() -> str: ...
def fileTemplateChanged(*args, **kwargs) -> Any: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def geoEntity() -> mari.GeoEntity: ...
def hasMetadata(Name: str) -> bool: ...
def imageExported(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def itemExported(*args, **kwargs) -> Any: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def onFileOptionsChanged(FileOptions: typing.Dict) -> Any: ...
def onItemExported() -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def postProcessCommand() -> str: ...
def postProcessCommandChanged(*args, **kwargs) -> Any: ...
def postProcessedFileTemplate() -> str: ...
def preferredFileExtension() -> str: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def resolution() -> str: ...
def resolutionChanged(*args, **kwargs) -> Any: ...
def resolveColorspace() -> str: ...
def resolveDepth() -> Any: ...
def resolveDepthAsInternalFormat() -> int: ...
def resolveExportFilePaths(RootPath: str = ...) -> typing.List: ...
def resolveFileTemplate(Overrides: typing.Any = ...) -> str: ...
def resolvePostProcessedFileTemplate(Overrides: typing.Any = ...) -> str: ...
def resolveResolutionSizes() -> typing.List: ...
def resolvedColorspace() -> str: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def serializeToString() -> str: ...
def setColorspace(Colorspace: str) -> Any: ...
def setDepth(Depth: str) -> Any: ...
def setErrorStringList(ErrorStringList: typing.Sequence) -> Any: ...
def setExportEnabled(ExportEnabled: bool) -> Any: ...
def setFileOptions(FileOptions: typing.Any) -> Any: ...
def setFileTemplate(FileTemplate: str) -> Any: ...
def setGeoEntity(Entity: mari.GeoEntity) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPostProcessCommand(PostProcessCommand: str) -> Any: ...
def setPostProcessedFileTemplate(PostProcessedFileTemplate: str) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setResolution(Resolution: str) -> Any: ...
def setSourceNode(SourceNode: mari.Node) -> Any: ...
def setUvIndexList(UVIndexList: typing.Sequence) -> Any: ...
def setWarningStringList(WarningStringList: typing.Sequence) -> Any: ...
def signalsBlocked() -> bool: ...
def sourceColorspace() -> str: ...
def sourceDepth() -> Any: ...
def sourceDepthAsInternalFormat() -> int: ...
def sourceNode() -> mari.Node: ...
def sourceNodeChanged(*args, **kwargs) -> Any: ...
def sourceNodeDepth() -> str: ...
def sourceNodeName() -> str: ...
def sourceResolution() -> str: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def uuid() -> str: ...
def uvIndexList() -> typing.List: ...
def warningStringList() -> typing.List: ...
def warningStringListChanged(*args, **kwargs) -> Any: ...
