from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ExportManager(API):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def sameAsSourceString() -> str: ...
    def addExportItem(self, Item: mari.ExportItem, Entity: mari.GeoEntity) -> Any: ...
    def allItemsExported(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def checkExportItemIsValid(self, Item: mari.ExportItem, Entity: mari.GeoEntity) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorspaceList(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depthList(self) -> typing.List: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportItemList(self, Entity: mari.GeoEntity) -> typing.List: ...
    def exportTextures(self, ExportItems: typing.Sequence, ExportRootPath: str, Overrides: typing.Any = ..., ShowProgressDialog: bool = ...) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def imageExported(self, *args, **kwargs) -> Any: ...
    def imageFileExtensionList(self) -> typing.List: ...
    def imageFileOptions(self, Extension: str) -> typing.Any: ...
    def imageFileOptionsWidget(self, Extension: str) -> PySide2.QtWidgets.QWidget: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def itemAdded(self, *args, **kwargs) -> Any: ...
    def itemExported(self, *args, **kwargs) -> Any: ...
    def itemRemoved(self, *args, **kwargs) -> Any: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def postProcessCommandList(self) -> typing.List: ...
    def preferredFileExtension(self, BitDepth) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def registerPostProcessCommand(self, Command: str) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeExportItem(self, Item: mari.ExportItem) -> Any: ...
    def resolutionList(self) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setImageFileOptions(self, Extension: str, Options: typing.Any) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPreferredFileExtension(self, BitDepth, Extension: str) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
