from typing import Any

class appstyle:
    def getApplicationStyleSheet(self, custom_theme = ..., prefix_with_qdialog = ...) -> Any: ...
    def getCurrentTheme(self) -> Any: ...
    def getWidgetColorDefinition(self, color_name, fallback_color_name = ...) -> Any: ...
    def themeBasedOnDefault(self) -> Any: ...

class archive:
    def archiveCurrentProject(self, path) -> Any: ...

class autosave:
    def autosavePaused(self) -> Any: ...
    def setPauseAutosave(self, state) -> Any: ...

class bake:
    def refreshModoBakePresetsList(self) -> Any: ...

class bakePoints:
    def bakeAcrossGeoVersions(self, node = ...) -> Any: ...
    def bakeSelectedBakePoints(self) -> Any: ...
    def optimizeMultiChannelBakePointStreams(self, node = ...) -> Any: ...
    def removeAllBakes(self) -> Any: ...
    def smartBakeAndUpdateAcrossGeoVersions(self) -> Any: ...
    def smartBakeHierarchy(self) -> Any: ...
    def useBake(self, bool) -> Any: ...

class benchmark:
    def createTimer(self) -> Any: ...
    def getAverageFPS(self, wedgeCount = ..., ID = ...) -> Any: ...
    def gpuMemoryUsage(self, subtract_mari_usage = ...) -> Any: ...
    def ramMemoryUsage(self) -> Any: ...

class brush:
    def getDynamicBrushSize(self, tool = ...) -> Any: ...
    def setDynamicBrushSize(self, state, tool = ...) -> Any: ...
    def toggleDynamicBrushSize(self, tool = ...) -> Any: ...
    def toggleSteadyStroke(self) -> Any: ...

class camera:
    def switch_to_ortho_view(self) -> Any: ...
    def switch_to_persp_view(self) -> Any: ...
    def switch_to_split_view(self) -> Any: ...
    def switch_to_uv_view(self) -> Any: ...
    def unproject_channel_to_imagemanager(self) -> Any: ...
    def unproject_layer_to_imagemanager(self) -> Any: ...
    def unproject_view_to_imagemanager(self) -> Any: ...

class channel:
    def channelFromChannelNode(self, geo, channelNode) -> Any: ...
    def check_channels(self) -> Any: ...
    def createChannelFromUDIMTemplate(self) -> Any: ...
    def duplicate_channel(self) -> Any: ...
    def duplicate_nodeNetwork(self, geo, inputNode, inputNodeNodeGraph, StopAfterRadioNodes = ..., RenameChannelIncremental = ..., RenameChannel = ..., newChannelName = ..., offsetX = ..., offsetY = ...) -> Any: ...
    def focusChannelContentInGraph(self, stopAfterRadios = ...) -> Any: ...
    def focusChannelInGraph(self) -> Any: ...
    def lockAllChannels(self) -> Any: ...
    def lockChannel(self) -> Any: ...
    def resizeChannelToUDIMTemplate(self, geo = ..., channel = ...) -> Any: ...
    def saveChannelUDIMTemplate(self, geo = ..., channel = ...) -> Any: ...
    def syncCurrentChannel(self, sourceObject = ..., targetObject = ..., channelName = ...) -> Any: ...
    def unlockAllChannels(self) -> Any: ...
    def unlockChannel(self) -> Any: ...

class content:
    def checkIfShelvesAreUpToDate(self, progressDialog = ...) -> Any: ...
    def installHDRIs(self, progressDialog = ...) -> Any: ...
    def installMaterialPresets(self, closeDialogAfter = ...) -> Any: ...
    def rendermanForMariInstalled(self) -> Any: ...

class dragAndDrop:
    def getLastLayerStackRefLayer(self) -> Any: ...
    def getLastLayerstackDropTarget(self) -> Any: ...
    def getLastNodegraphDropNodeGraph(self) -> Any: ...
    def getLastNodegraphDropPosition(self) -> Any: ...
    def resetLastDropTargets(self) -> Any: ...

class exceptions:
    def getExceptionHandlerClass(self) -> Any: ...
    def log_error(self, message) -> Any: ...

class exportChannel:
    def exportLast(self) -> Any: ...

class help:
    def contactFoundrySupport(self) -> Any: ...
    def createSmartMaskProject(self) -> Any: ...
    def open_LogFile(self) -> Any: ...
    def open_MariUserSettingsFolder(self) -> Any: ...
    def open_online_help(self) -> Any: ...
    def open_pyAPI_help(self) -> Any: ...
    def open_releaseNotes(self) -> Any: ...
    def open_shortcut_help(self) -> Any: ...
    def open_tutorials(self) -> Any: ...
    def send_bug_report(self) -> Any: ...

class history:
    def clearHistory(self) -> Any: ...
    def resumeHistory(self) -> Any: ...

class hotbox:
    def closeHotboxInstances(self) -> Any: ...
    def currentHotboxInstance(self) -> Any: ...
    def showHotbox(self, path = ..., SubmenuBackLink = ..., force = ..., resetPosition = ..., parent_widget = ..., isNodeContextMenu = ...) -> Any: ...

class imageAnnotation:
    def createNewImagNote(self, customPosition = ...) -> Any: ...
    def getImagePath(self, node) -> Any: ...
    def getImageSize(self, imagePath) -> Any: ...
    def getLastImageNote(self) -> Any: ...
    def getProjectThumbnailPath(self) -> Any: ...
    def imageNoteFromFile(self, filePath = ..., initialScale = ..., forceNewNote = ..., customPosition = ..., colorizeImage = ..., color = ..., blendMode = ..., stickyNoteToReplace = ...) -> Any: ...
    def imageNoteFromNode(self, graph = ..., nodelist = ...) -> Any: ...
    def imageNoteFromView(self, scaleFactor = ...) -> Any: ...
    def nodeIsImageNote(self, node) -> Any: ...
    def relinkImageNotePathToProject(self, node) -> Any: ...
    def removeAllImageNotes(self, graph = ..., silent = ...) -> Any: ...
    def setImageOnNote(self, stickyNote, imagePath, sizeX = ..., sizeY = ...) -> Any: ...
    def updateImagePath(self, node, newPath, original_path = ...) -> Any: ...
    def updateImageSize(self, node, newWidth = ..., newHeight = ..., customPosition = ...) -> Any: ...
    def updateScaleFactor(self, node, newFactorPercent, customPosition = ...) -> Any: ...

class imageManager:
    def activateAutoReloadingOnSelectedImages(self) -> Any: ...
    def cleanImageManager(self) -> Any: ...
    def deactivateAllImageAutoReloading(self) -> Any: ...
    def deactivateAutoReloadingOnSelectedImages(self) -> Any: ...
    def disableReferenceImage_onSelectedImages(self) -> Any: ...
    def enableImageAutoReloadOnImageManagerFiles(self, imageList = ...) -> Any: ...
    def enableReferenceImage_onSelectedImages(self) -> Any: ...
    def findImage(self, filePath, is_raw = ..., is_scalar = ...) -> Any: ...
    def imagesInUse(self) -> Any: ...
    def openImageInApplication(self, applicationExecutable) -> Any: ...
    def openImageInDefaultApplication(self) -> Any: ...
    def openImageInFileBrowser(self) -> Any: ...
    def rasterizeVectorImage(self, filePath, colorSpaceConfig, size) -> Any: ...
    def reloadImage(self, imageObject) -> Any: ...
    def reloadSelectedImages(self, svgMode = ...) -> Any: ...
    def reloadSelectedSVGFiles(self) -> Any: ...
    def removeEmptyImageManagerGroups(self) -> Any: ...
    def removeEmptyImageManagerTabs(self) -> Any: ...
    def removeImageManagerTabs(self) -> Any: ...
    def selectedImageGroup(self) -> Any: ...
    def setAutoReloading_onSelectedImages(self, mode) -> Any: ...
    def setGroupColor(self, group_name, color) -> Any: ...
    def setGroupColorFromIcon(self, group_name, icon_path) -> Any: ...
    def setGroupIcon(self, group_name, icon_path, color_code = ...) -> Any: ...
    def setGroupIconFromImageSelection(self) -> Any: ...
    def useImageAsBrushtip(self) -> Any: ...

class imageUtils:
    def darken_image(self, pathImageIconOrPixmap, factor = ..., desaturate = ..., return_QImage = ...) -> Any: ...
    def desaturate_pixmap(self, original_pixmap) -> Any: ...
    def desaturate_qimage(self, original_qimage) -> Any: ...
    def get_ep_icon(self, icon_name, scaledTo = ..., stateAware = ...) -> Any: ...
    def get_ep_pixmap(self, icon_name, scaledTo = ...) -> Any: ...
    def get_mari_icon(self, icon_name, scaledTo = ..., stateAware = ...) -> Any: ...
    def get_mari_pixmap(self, icon_name, scaledTo = ...) -> Any: ...

class layer:
    def addMask(self, mode) -> Any: ...
    def cloneMergeSelectedLayers(self) -> Any: ...
    def convertToPaintable(self) -> Any: ...
    def copyLayerAttributes(self) -> Any: ...
    def copyWithShared(self) -> Any: ...
    def findActiveLayerSelection(self, includeAdjustmentStacks = ..., includeMaskStacks = ..., includeGroupLayers = ..., includeChannelLayers = ..., silentFail = ...) -> Any: ...
    def layerCopy(self) -> Any: ...
    def layerCut(self) -> Any: ...
    def layerPaste(self) -> Any: ...
    def pasteLayerAttributes(self) -> Any: ...
    def pasteWithShared(self) -> Any: ...
    def toggleSelectionLock(self) -> Any: ...
    def toggleSelectionVisibility(self) -> Any: ...
    def toggleUnselectedLock(self) -> Any: ...
    def toggleUnselectedVisibility(self) -> Any: ...

class layout:
    def loadLayoutFromPath(self, Path, LayoutName = ...) -> Any: ...
    def restoreDefaultLayout(self) -> Any: ...
    def saveLayout(self, layoutName, Description = ...) -> Any: ...
    def setLayoutFolderPreference(self, path) -> Any: ...
    def setPaletteOrientationHorizontal(self) -> Any: ...
    def setPaletteOrientationSplitBottom(self) -> Any: ...
    def setPaletteOrientationSplitLeft(self) -> Any: ...
    def setPaletteOrientationSplitRight(self) -> Any: ...
    def setPaletteOrientationSplitTop(self) -> Any: ...
    def setPaletteOrientationVertical(self) -> Any: ...

class lights:
    def rotateEnvironmentLight(self, mode, multiplier) -> Any: ...
    def rotateLightsByAngle(self, angle = ...) -> Any: ...

class matrix:
    def decomposeMatrix(self, matrix) -> Any: ...
    def decomposeMatrixEulerAngles(self, matrix) -> Any: ...
    def decomposeMatrixScale(self, matrix) -> Any: ...
    def decomposeMatrixTranslation(self, matrix) -> Any: ...
    def invertMatrix(self, matrix) -> Any: ...
    def matrixFromVectors(self, rotation = ..., translation = ..., scale = ...) -> Any: ...
    def objectTransformToWorldSpaceMatrix(self, object_scale, object_angles, object_translation) -> Any: ...
    def setTransform(self, obj, transform_matrix, clock_frame = ...) -> Any: ...
    def toEulerAnglesMatrix(self, values) -> Any: ...
    def toScaleEulerAnglesTranslationMatrix(self, scale, angles, translation) -> Any: ...
    def toScaleMatrix(self, values) -> Any: ...
    def toTranslationMatrix(self, values) -> Any: ...
    def worldToObjectTransform(self, world_scale, world_angles, world_translation) -> Any: ...

class node:
    def channelsNodeBelongsTo(self, node_to_find, geo, excludeChannelLayer = ...) -> Any: ...
    def connectNodeToLastNode(self, overwriteExistingConnections = ...) -> Any: ...
    def copyNodeConnections(self, nodeToCopyFrom, nodeToCopyTo, RemoveSourceNode = ...) -> Any: ...
    def current(self, returnFirstSelectedNode = ...) -> Any: ...
    def disconnectAllInputConnections(self, nodelist = ...) -> Any: ...
    def disconnectAllOutputConnections(self, nodelist = ...) -> Any: ...
    def findConnectedNodeOutput(self, graph, node_to_find, skipDots = ..., SpecificOutput = ...) -> Any: ...
    def getAllNodesConnectedToNode(self, targetNode, nodeGraph, GroupContentMode = ..., returnBakePointUpstream = ..., includeTargetNode = ..., GraphGroup_TraverseConnectedOutputOnly = ..., MainGraph_TraverseStreamOnly = ..., IncludeGraphGroupNode = ..., IncludeMaterials = ..., StartStream = ...) -> Any: ...
    def getAllNodesDownstream(self, targetNode, includeTargetNode = ..., traverse_groups = ...) -> Any: ...
    def getMaterialStreamNamesConnectedToChannels(self, node) -> Any: ...
    def getNodeCategory(self, node) -> Any: ...
    def getNodeMaterialStreamName(self, graph, inputNode) -> Any: ...
    def getNodePosition(self, graph, node) -> Any: ...
    def getNodePrettyName(self, node) -> Any: ...
    def inputNode(self, node, nodeport) -> Any: ...
    def moveNodesToPosition(self, graph, nodes, positionList) -> Any: ...
    def nodeName(self, node) -> Any: ...
    def reloadSelected_PaintAndImages(self, silent = ...) -> Any: ...
    def saveNodeAttributes(self, selectedNode) -> Any: ...
    def setInputNode(self, node, portname, NodeToConnect, OutputPortName = ...) -> Any: ...
    def setNodeAttributes(self, selectedNode) -> Any: ...
    def setNodeName(self, node, newName) -> Any: ...
    def smartRenameNode(self, graph, node) -> Any: ...

class nodeLayout:
    def alignNodes_HorizontallyBottom(self, nodelist = ..., defaultToSelection = ..., streamBased = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_HorizontallyTop(self, nodelist = ..., defaultToSelection = ..., streamBased = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_VerticallyLeft(self, nodelist = ..., defaultToSelection = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_VerticallyRight(self, nodelist = ..., defaultToSelection = ..., preventAnimation = ...) -> Any: ...
    def distributeBetweenNodes_Horizontally(self, nodelist) -> Any: ...
    def distributeBetweenNodes_Vertically(self, nodelist) -> Any: ...
    def distributeBetweenSelectedNodes_Horizontally(self) -> Any: ...
    def distributeBetweenSelectedNodes_Vertically(self) -> Any: ...
    def distributeNodesHorizontally(self, nodelist = ..., specificXDistance = ..., backdropOffsetLimit = ...) -> Any: ...
    def distributeNodesVertically(self, nodelist = ..., specificYDistance = ..., backdropOffsetLimit = ...) -> Any: ...
    def layoutNodes(self, graph = ..., nodelist = ...) -> Any: ...

class nodeNavigation:
    def cycleBookmarkNodesBackwards(self) -> Any: ...
    def cycleBookmarkNodesForward(self) -> Any: ...
    def jumpToNextInStream(self, typeIDToFind = ..., customSearch = ...) -> Any: ...
    def jumpToNextSimilarInStream(self) -> Any: ...
    def jumpToNodeInput(self) -> Any: ...
    def jumpToNodeOutput(self) -> Any: ...
    def jumpToPreviousInStream(self, typeIDToFind = ..., customSearch = ...) -> Any: ...
    def jumpToPreviousSimilarInStream(self) -> Any: ...
    def jumpViewToRadioNodeConnection(self) -> Any: ...

class nodeProperties:
    def clearNodePropertiesOnSingleClick_Connections(self) -> Any: ...
    def getPauseNodePropertiesState(self) -> Any: ...
    def initializeNodePropertiesOnSingleClick(self) -> Any: ...
    def initializeNodePropertiesOnSingleClick_onSpecificGeo(self) -> Any: ...
    def pauseNodePropertiesUpdate(self, mode = ...) -> Any: ...
    def updateNodePropertiesOnSelection(self, force = ..., forceOpenPalette = ...) -> Any: ...

class nodeStyle:
    def revertNodeStyle(self, inputNodeList) -> Any: ...
    def setNodeStyle(self, inputNodeList, setColor = ..., setShape = ..., setPixmap = ..., topColor = ..., bottomColor = ..., NodeShape = ..., pixMapPath = ...) -> Any: ...

class nodeUtilities:
    def autoDotInputConnections(self, graph = ..., nodelist = ...) -> Any: ...
    def createMaskFromSelection(self) -> Any: ...
    def createSmartCompareMask(self) -> Any: ...
    def createSmartHeightBlend(self) -> Any: ...
    def createSmartMergeNode(self) -> Any: ...
    def createStickyNoteWithNodeChanges(self, graph = ..., nodelist = ...) -> Any: ...
    def deregisterNodeContextMenu(self, nodeTypeID) -> Any: ...
    def disableBlendColorspaceOnNode(self, node) -> Any: ...
    def getRegisteredNodeContextMenus(self) -> Any: ...
    def optimizeMultiChannelNodes(self, nodelist = ...) -> Any: ...
    def registerNodeContextMenu(self, target, contextMenuPath, classInstance = ...) -> Any: ...
    def removeAllStickyNotesWithNodeChanges(self, graph = ...) -> Any: ...
    def replaceMergeNodesWithBlendNodes(self, useSelection = ..., ignoreColorSpaceBlend = ..., ignoreSwizzle = ..., ignoreAdvnacedBlend = ..., surpressPopup = ...) -> Any: ...
    def setMergeNodeColorSpaceToDisabled(self, node) -> Any: ...
    def setMergeNodeColorspace(self, node, setTo = ...) -> Any: ...

class nodegraph:
    def clearNodegraph(self, currentGeoOnly = ...) -> Any: ...
    def copyNodeAttributes(self, node = ...) -> Any: ...
    def createNodeAtPosition(self, graph, nodeString, positionList) -> Any: ...
    def createNodeDuplicateAtPosition(self, graph, nodes, PositionList, removeOriginalNode = ...) -> Any: ...
    def createNodeDuplicateWithOffset(self, graph, nodes, offsetList, removeOriginalNode = ...) -> Any: ...
    def current(self) -> Any: ...
    def duplicateNodesWithConnections(self, offsetX = ..., offsetY = ...) -> Any: ...
    def duplicate_nodeNetwork(self, geo, inputNode, inputNodeNodeGraph, StopAfterRadioNodes = ..., RenameChannelIncremental = ..., RenameChannel = ..., newChannelName = ..., offsetX = ..., offsetY = ...) -> Any: ...
    def getAllNodesInProject(self, classFilter = ...) -> Any: ...
    def getAllNodesOnGeo(self, geo, classFilter = ...) -> Any: ...
    def getNodesonStream(self, targetNode, includeGroupNode = ..., stream = ...) -> Any: ...
    def getUpstreamNodes(self, graph, destination_node) -> Any: ...
    def lastCreatedNode(self) -> Any: ...
    def recursiveGroupNodeList(self, node_list) -> Any: ...
    def recursiveNodeList(self, node_list) -> Any: ...
    def repeatLastNodeCreation(self) -> Any: ...
    def setNodeAttributes(self, nodelist = ...) -> Any: ...
    def smartRenameNodes(self) -> Any: ...
    def viewerNode(self, graph = ...) -> Any: ...

class nodegraphGrid:
    def decreaseGridHeight(self) -> Any: ...
    def decreaseGridLineOpacity(self) -> Any: ...
    def decreaseGridLineWidth(self) -> Any: ...
    def decreaseGridWidth(self) -> Any: ...
    def increaseGridHeight(self) -> Any: ...
    def increaseGridLineOpacity(self) -> Any: ...
    def increaseGridLineWidth(self) -> Any: ...
    def increaseGridWidth(self) -> Any: ...
    def toggleGridSnap(self) -> Any: ...
    def toggleShowGrid(self) -> Any: ...

class nodegraphPalette:
    def closeCurrentGraphNotification(self) -> Any: ...
    def cursorPositionInNodegraphSpace(self) -> Any: ...
    def cycleNodegraphTabs(self) -> Any: ...
    def enterSubgraph(self) -> Any: ...
    def findNodeAbstractGraphicsView(self) -> Any: ...
    def findNodeGraphContext(self) -> Any: ...
    def findNodeGraphTabWidget(self, returnNoneIfRootGraph = ...) -> Any: ...
    def getCurrentGraphNotification(self) -> Any: ...
    def getNodeGraphEventFilter(self) -> Any: ...
    def get_alt_pressed(self) -> Any: ...
    def get_ctrl_pressed(self) -> Any: ...
    def get_shift_pressed(self) -> Any: ...
    def graphNotification(self, text = ..., auto_close_seconds = ..., width = ..., height = ..., background_color = ..., border = ..., font_size = ...) -> Any: ...
    def leaveSubgraph(self) -> Any: ...
    def setNodegraphContext(self) -> Any: ...
    def setNodegraphTabIndex(self, index) -> Any: ...

class nodegraphSelection:
    def deselectAllNodes(self) -> Any: ...
    def deselectAllNodesExceptBackdrops(self) -> Any: ...
    def getLastNodeSelection(self) -> Any: ...
    def getPreviousNodeSelection(self) -> Any: ...
    def getSelectedNodesOnCurrentGeoRootGraph(self, FirstOnly = ...) -> Any: ...
    def getSelectedNodesOnCurrentGraph(self, FirstOnly = ...) -> Any: ...
    def getSeparateNodeStreams(self, nodelist) -> Any: ...
    def selectAllNodes(self) -> Any: ...
    def selectClosestNodeToCursoAndView(self, viewNodeProperties = ...) -> Any: ...
    def selectClosestNodeToCursor(self, viewNodeProperties = ...) -> Any: ...
    def selectCustomNodes(self, showReport = ...) -> Any: ...
    def selectNodesByType(self, typeOfNode = ..., nodegraph = ..., referenceNode = ...) -> Any: ...
    def selectUpstreamNodes(self, Stream = ...) -> Any: ...
    def selectUpstreamNodes_ignoreRadios(self, Stream = ...) -> Any: ...
    def selectUpstreamNodes_stopAfterRadios(self, Stream = ...) -> Any: ...

class nodegraphStyle:
    def toggleAllowAutoInsert(self) -> Any: ...
    def toggleAllowShakeToExtract(self) -> Any: ...

class object:
    def geoUVIndices(self, currentGeoOnly = ...) -> Any: ...
    def list(self, include_2D_objects = ...) -> Any: ...
    def removeAllGeoChannels(self, geo = ..., silent = ...) -> Any: ...
    def removeObjectVersion(self) -> Any: ...
    def setAllSUBDToHigh(self) -> Any: ...
    def setAllSUBDToLow(self) -> Any: ...
    def setVisibleSUBDToHigh(self) -> Any: ...
    def setVisibleSUBDToLow(self) -> Any: ...
    def unsubdiveGeo(self, geo = ...) -> Any: ...

class ocio:
    def getAvailableColorspaces(self, ocio_filepath, colorspace_defaults) -> Any: ...
    def getOCIOandDefaults(self) -> Any: ...

class patch:
    def applyPatchResolutionTemplate(self, geo = ..., channel = ..., node = ..., forceModeTo = ...) -> Any: ...
    def patchBake_to_imagemanager(self) -> Any: ...
    def resizePatches_onChannelsOrNodes(self, size) -> Any: ...
    def savePatchResolutionTemplate(self, geo = ..., channel = ..., node = ..., forceModeTo = ...) -> Any: ...

class pinnedLayers:
    def collectionPin(self, mode) -> Any: ...
    def emptyPin(self) -> Any: ...
    def quickPin(self, mode) -> Any: ...
    def triggerCollectionPin(self, layerType, layerName, project_uuid, layer_uuid) -> Any: ...
    def triggerQuickPin(self, layerType, layerName, project_uuid, layer_uuid) -> Any: ...

class presetBrowser:
    def closeSmartMaskShelfInstance(self) -> Any: ...
    def resetSmartMaskShelfPositionAndSize(self) -> Any: ...

class project:
    def cleanUpData(self) -> Any: ...
    def getCurrentProjectFolder(self) -> Any: ...
    def getEPProjectDataFolder(self, create_if_not_exist = ...) -> Any: ...
    def mariProjectIsOpen(self) -> Any: ...
    def openCurrentProjectFolder(self) -> Any: ...
    def removeAllSnapshots(self) -> Any: ...

class projectCollections:
    def activateCollection(self, name, hideOthers = ..., filter_text = ...) -> Any: ...
    def addCollection(self, name, color = ...) -> Any: ...
    def assignProjectsToCollection(self, name, projects = ...) -> Any: ...
    def batchAddCollections(self, collections_definitions) -> Any: ...
    def clearFilter(self) -> Any: ...
    def collectionNameExists(self, name) -> Any: ...
    def filterEnabled(self) -> Any: ...
    def filterText(self) -> Any: ...
    def getAllProjectCollections(self) -> Any: ...
    def getCollectionMetadataID(self) -> Any: ...
    def getCollectionsComboBox(self) -> Any: ...
    def getCollectionsWidget(self) -> Any: ...
    def getCurrentCollection(self) -> Any: ...
    def getProjectCollections(self, projects, includeWithoutAssignment = ...) -> Any: ...
    def projectIsPartOfCollection(self, project, name) -> Any: ...
    def refreshCollectionsComboBox(self) -> Any: ...
    def removeCollection(self, name) -> Any: ...
    def removeProjectsFromCollection(self, name, projects = ...) -> Any: ...
    def setAllowDefaultChange(self, state) -> Any: ...
    def setCollectionColor(self, name, color) -> Any: ...
    def setCurrentCollection(self, name) -> Any: ...
    def setFilterEnabled(self, state) -> Any: ...
    def setFilterText(self, filter_text) -> Any: ...
    def showAllProjects(self, filter_text = ...) -> Any: ...

class project_paths:
    def get_projectPath_jsonFile(self) -> Any: ...
    def setProjectPathVariable(self, variable_name, variable_data, set_active = ...) -> Any: ...

class project_template:
    def applyLightInfoFromTemplate(self, templateFilePath) -> Any: ...
    def applyPrefsFromTemplate(self, templateFilePath, excludeList = ..., includeList = ...) -> Any: ...
    def applyProjectorInfoFromTemplate(self, templatePathFile, projectorFolderLocation) -> Any: ...
    def applyViewportInfoFromTemplate(self, templateFilePath) -> Any: ...
    def importLastLightInfoTemplate(self) -> Any: ...
    def importNodesFromTemplate(self, templateFolderPath, clearExisting = ..., currentGeoOnly = ...) -> Any: ...
    def saveLightInfoAsTemplate(self, templateName) -> Any: ...
    def saveNodesFromCurrentGraph(self, templateName, selectedOnly = ..., skipImageData = ...) -> Any: ...
    def savePrefsAsTemplate(self, templateName) -> Any: ...
    def saveProjectInfoAsTemplate(self, templateName) -> Any: ...
    def saveViewportInfoAsTemplate(self, templateName) -> Any: ...

class projectors:
    def moveScanProjectionBlock_left(self) -> Any: ...
    def moveScanProjectionBlock_right(self) -> Any: ...
    def removeAllProjectors(self, silent = ...) -> Any: ...
    def toggleCameraType(self) -> Any: ...
    def updateProjectorCamera(self) -> Any: ...
    def updateProjectorClippingPlanes(self, projector = ..., geo = ...) -> Any: ...

class quickmarks:
    def loadQuickMark(self, ID) -> Any: ...
    def removeQuickMark(self, ID) -> Any: ...
    def setQuickMark(self, ID) -> Any: ...

class radioNodes:
    def convertInputConnectionsToRadios(self, nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertInputConnectionsToTeleporters(self, nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertOutputConnectionsToRadios(self, nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertOutputConnectionsToTeleporters(self, nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def cycleRadioNodeConnections(self) -> Any: ...
    def hideAllRadioNodeConnections(self) -> Any: ...
    def jumpViewToRadioNodeConnection(self) -> Any: ...
    def showAllRadioNodeConnections(self) -> Any: ...
    def toggleRadioNodes(self, node, Force = ..., ForceMode = ...) -> Any: ...
    def toggleSelectedRadioNodesConnection(self) -> Any: ...
    def updateRadioNodes(self, portName, node) -> Any: ...

class resources:
    def extPack_3rdParty_path(self) -> Any: ...
    def extPack_archives_path(self) -> Any: ...
    def extPack_baseShapes_path(self) -> Any: ...
    def extPack_contextMenus_path(self) -> Any: ...
    def extPack_gradients_path(self) -> Any: ...
    def extPack_grunges_path(self) -> Any: ...
    def extPack_hdris_path(self) -> Any: ...
    def extPack_hotboxes_path(self) -> Any: ...
    def extPack_icon_path(self) -> Any: ...
    def extPack_imageNotes_anatomy_path(self) -> Any: ...
    def extPack_imageNotes_materials_path(self) -> Any: ...
    def extPack_imageNotes_path(self) -> Any: ...
    def extPack_imageNotes_shaderStreams_path(self) -> Any: ...
    def extPack_imageNotes_utilities_path(self) -> Any: ...
    def extPack_industrySurfaces_path(self) -> Any: ...
    def extPack_materialpreset_path(self) -> Any: ...
    def extPack_modoBakePresets_path(self) -> Any: ...
    def extPack_nodeContextMenu_path(self) -> Any: ...
    def extPack_object_path(self) -> Any: ...
    def extPack_offlineSplashContent_path(self) -> Any: ...
    def extPack_procedurals_path(self) -> Any: ...
    def extPack_resource_locator(self, alwaysReturnAPath = ...) -> Any: ...
    def extPack_settings_path(self) -> Any: ...
    def extPack_shelf_data_path(self) -> Any: ...
    def extPack_smartmasks_path(self) -> Any: ...
    def extPack_styles_path(self) -> Any: ...
    def extPack_textures_path(self) -> Any: ...
    def extPack_tools_path(self) -> Any: ...
    def mari_settings_locator(self) -> Any: ...

class selection:
    def isolateSelect(self) -> Any: ...
    def showLastHidden(self) -> Any: ...

class selection_group:
    def combineSelectionGroups(self, groupList, newName, removeOld = ...) -> Any: ...
    def complexSearch(self, search, group_list, default_groupmode_list = ..., default_visibility_modelist = ..., limit_visibility_modifier = ..., default_active_modelist = ..., setData = ..., forceInPathSearch = ..., forceInObjectSearch = ..., emptySearchReturnsTrue = ...) -> Any: ...
    def deleteAll(self) -> Any: ...
    def deleteUnused(self) -> Any: ...
    def getVisibilitySets(self) -> Any: ...
    def hideAll(self) -> Any: ...
    def hideUnselected(self) -> Any: ...
    def invertVisibility(self) -> Any: ...
    def lockAll(self) -> Any: ...
    def removeMaterialIDOverride(self, SelectionGroups) -> Any: ...
    def setMaterialIDOverride(self, SelectionGroups, color) -> Any: ...
    def showAll(self) -> Any: ...
    def unlockAll(self) -> Any: ...

class shader:
    def selectLastShader(self) -> Any: ...
    def syncObjectShaderSelection(self) -> Any: ...

class shaderPreset:
    def removeShaderPreset(self) -> Any: ...
    def restoreShaderChannelInputsFromPreset(self) -> Any: ...
    def restoreShaderDefaultInputs(self) -> Any: ...
    def restoreShaderParametersFromPreset(self) -> Any: ...
    def saveShaderPreset(self) -> Any: ...
    def setNodesToShader(self) -> Any: ...

class shading:
    def disableViewport(self, mode) -> Any: ...

class shelf:
    def createItem(self, shelf, item_type, item, ForceImmediateLoad = ...) -> Any: ...
    def deleteAllUserMariShelves(self) -> Any: ...
    def groupShelf(self, shelf, groupname) -> Any: ...

class splashScreen:
    def splashScreenConnectionTimeOut(self) -> Any: ...

class symmetry:
    def activateSymmetryX(self) -> Any: ...
    def activateSymmetryY(self) -> Any: ...
    def activateSymmetryZ(self) -> Any: ...
    def setSymmetryMode(self) -> Any: ...

class toolbar:
    def alignLocatorToView(self) -> Any: ...
    def flipPaintThroughImage_Horizontally(self) -> Any: ...
    def flipPaintThroughImage_Vertically(self) -> Any: ...
    def forceActivateTransformTool(self) -> Any: ...
    def scaleAndCenterLocator(self) -> Any: ...

class utils:
    def TDRCheck(self) -> Any: ...
    def changeFileOwnership(self, path) -> Any: ...
    def closeAllOpenProgressDialogs(self) -> Any: ...
    def copytree(self, src, dst, symlinks = ..., ignore = ..., copy_function = ..., ignore_dangling_symlinks = ...) -> Any: ...
    def correctPath(self, path) -> Any: ...
    def current_notification(self) -> Any: ...
    def delete_current_notification(self, do_not_animate = ...) -> Any: ...
    def findTriggerAction(self, actionpath) -> Any: ...
    def forceFocusReturn(self) -> Any: ...
    def getChildren(self, obj) -> Any: ...
    def getImageAttributeNames(self) -> Any: ...
    def getMariSettingsFolder(self) -> Any: ...
    def getStyle(self, stylefile_name, style_options) -> Any: ...
    def getUIScaleFactor(self) -> Any: ...
    def mariIsShuttingDown(self) -> Any: ...
    def mariMainWindowObject(self) -> Any: ...
    def mariViewport(self) -> Any: ...
    def message(self, text, title = ..., buttons = ..., icon = ..., details = ..., defaultButton = ..., parent = ...) -> Any: ...
    def messageResult(self, text, title = ..., buttons = ..., icon = ..., details = ..., defaultButton = ..., parent = ...) -> Any: ...
    def notification(self, buttons = ..., header_text = ..., info_text = ..., detail_text = ..., min_notifier_width = ..., min_notifier_height = ..., allow_dynamic_notifier_size = ..., header_pointsize = ..., info_pointsize = ..., detail_pointsize = ..., btn_pointsize = ..., notification_type = ..., custom_notification_color = ..., custom_text_color = ..., custom_button_color = ..., notification_color_width = ..., notification_position = ..., notification_animation_type = ..., animation_show_duration = ..., animation_hide_duration = ..., timeout_notification = ..., notification_timeout_length = ..., timeout_progress_color = ..., background_color = ..., distance_from_edge = ..., always_remove_previous_notification = ...) -> Any: ...
    def openFileBrowser(self, path, directoryOnly = ..., iteratePathUntilFound = ...) -> Any: ...
    def progressDialog(self, maxStepsPrimary, showSecondaryBar = ..., maxStepsSecondary = ..., windowTitle = ..., initialInfoMsg = ..., initialStatusMsg = ..., autoClose = ..., showAbortMessage = ..., AbortMsg = ..., AbortTitle = ..., MinWidth = ..., parent = ...) -> Any: ...
    def sanitizeText(self, text, sanitizeSlashes = ..., removeWhiteSpace = ..., customCharacters = ...) -> Any: ...
    def searchInString(self, search_for, search_in) -> Any: ...
    def setting_str_to_bool(self, settings_value, invalid_defaults_to = ...) -> Any: ...
    def shortenText(self, text, characterLimit = ..., shortenStart = ..., short = ...) -> Any: ...
    def stopViewportTracking(self) -> Any: ...
    def windowOffsetPosition(self, useSafeMargin = ..., paddingList = ..., offsetList = ...) -> Any: ...

class version:
    def buildVersion(self) -> Any: ...
    def checkResourceVersion(self) -> Any: ...
    def devToolsVisible(self) -> Any: ...
    def isAlphaVersion(self) -> Any: ...
    def isBetaVersion(self) -> Any: ...
    def isDevVersion(self) -> Any: ...
    def isNewVersionAvailable(self, debugMode = ...) -> Any: ...
    def isReleaseCandidateVersion(self) -> Any: ...
    def launchVersionCheck(self) -> Any: ...
    def majorVersion(self) -> Any: ...
    def mari45OrAbove(self, invert = ...) -> Any: ...
    def mari46OrAbove(self, invert = ...) -> Any: ...
    def mari46v4orAbove(self, invert = ...) -> Any: ...
    def mari47OrAbove(self, invert = ...) -> Any: ...
    def mari47Ov2rAbove(self, invert = ...) -> Any: ...
    def mari48OrAbove(self, invert = ...) -> Any: ...
    def mari48v2OrAbove(self, invert = ...) -> Any: ...
    def mari70v1orAbove(self, invert = ...) -> Any: ...
    def mari70v2orAbove(self, invert = ...) -> Any: ...
    def mari71v1orAbove(self, invert = ...) -> Any: ...
    def mari75v1orAbove(self, invert = ...) -> Any: ...
    def minorVersion(self) -> Any: ...
    def patchVersion(self) -> Any: ...
    def recommendedEPResourceVersion(self) -> Any: ...
    def version(self) -> Any: ...
    def versionAsJson(self, jsonfile = ...) -> Any: ...
    def versionPrettyName(self) -> Any: ...
    def versionTest(self) -> Any: ...

class view:
    def setViewBackgroundTheme(self, theme = ...) -> Any: ...

class web:
    def checkEPAvailability(self) -> Any: ...
    def checkYouTubeAvailability(self) -> Any: ...
    def downloadImageFromWeb(self, url) -> Any: ...
    def getYouTubeThumbnail(self, url) -> Any: ...

