from typing import Any

class appstyle:
    def getApplicationStyleSheet(custom_theme = ..., prefix_with_qdialog = ...) -> Any: ...
    def getCurrentTheme() -> Any: ...
    def getWidgetColorDefinition(color_name, fallback_color_name = ...) -> Any: ...
    def themeBasedOnDefault() -> Any: ...

class archive:
    def archiveCurrentProject(path) -> Any: ...

class autosave:
    def autosavePaused() -> Any: ...
    def setPauseAutosave(state) -> Any: ...

class bake:
    def refreshModoBakePresetsList() -> Any: ...

class bakePoints:
    def bakeAcrossGeoVersions(node = ...) -> Any: ...
    def bakeSelectedBakePoints() -> Any: ...
    def optimizeMultiChannelBakePointStreams(node = ...) -> Any: ...
    def removeAllBakes() -> Any: ...
    def smartBakeAndUpdateAcrossGeoVersions() -> Any: ...
    def smartBakeHierarchy() -> Any: ...
    def useBake(bool) -> Any: ...

class benchmark:
    def createTimer() -> Any: ...
    def getAverageFPS(wedgeCount = ..., ID = ...) -> Any: ...
    def gpuMemoryUsage(subtract_mari_usage = ...) -> Any: ...
    def ramMemoryUsage() -> Any: ...

class brush:
    def getDynamicBrushSize(tool = ...) -> Any: ...
    def setDynamicBrushSize(state, tool = ...) -> Any: ...
    def toggleDynamicBrushSize(tool = ...) -> Any: ...
    def toggleSteadyStroke() -> Any: ...

class camera:
    def switch_to_ortho_view() -> Any: ...
    def switch_to_persp_view() -> Any: ...
    def switch_to_split_view() -> Any: ...
    def switch_to_uv_view() -> Any: ...
    def unproject_channel_to_imagemanager() -> Any: ...
    def unproject_layer_to_imagemanager() -> Any: ...
    def unproject_view_to_imagemanager() -> Any: ...

class channel:
    def channelFromChannelNode(geo, channelNode) -> Any: ...
    def check_channels() -> Any: ...
    def createChannelFromUDIMTemplate() -> Any: ...
    def duplicate_channel() -> Any: ...
    def duplicate_nodeNetwork(geo, inputNode, inputNodeNodeGraph, StopAfterRadioNodes = ..., RenameChannelIncremental = ..., RenameChannel = ..., newChannelName = ..., offsetX = ..., offsetY = ...) -> Any: ...
    def focusChannelContentInGraph(stopAfterRadios = ...) -> Any: ...
    def focusChannelInGraph() -> Any: ...
    def lockAllChannels() -> Any: ...
    def lockChannel() -> Any: ...
    def resizeChannelToUDIMTemplate(geo = ..., channel = ...) -> Any: ...
    def saveChannelUDIMTemplate(geo = ..., channel = ...) -> Any: ...
    def syncCurrentChannel(sourceObject = ..., targetObject = ..., channelName = ...) -> Any: ...
    def unlockAllChannels() -> Any: ...
    def unlockChannel() -> Any: ...

class content:
    def checkIfShelvesAreUpToDate(progressDialog = ...) -> Any: ...
    def installHDRIs(progressDialog = ...) -> Any: ...
    def installMaterialPresets(closeDialogAfter = ...) -> Any: ...
    def rendermanForMariInstalled() -> Any: ...

class dev:
    def generatePythonStubs(target_directory = ...) -> Any: ...

class dragAndDrop:
    def getLastLayerStackRefLayer() -> Any: ...
    def getLastLayerstackDropTarget() -> Any: ...
    def getLastNodegraphDropNodeGraph() -> Any: ...
    def getLastNodegraphDropPosition() -> Any: ...
    def resetLastDropTargets() -> Any: ...

class exceptions:
    def getExceptionHandlerClass() -> Any: ...
    def log_error(message) -> Any: ...

class exportChannel:
    def exportLast() -> Any: ...

class help:
    def contactFoundrySupport() -> Any: ...
    def createSmartMaskProject() -> Any: ...
    def open_LogFile() -> Any: ...
    def open_MariUserSettingsFolder() -> Any: ...
    def open_online_help() -> Any: ...
    def open_pyAPI_help() -> Any: ...
    def open_releaseNotes() -> Any: ...
    def open_shortcut_help() -> Any: ...
    def open_tutorials() -> Any: ...
    def send_bug_report() -> Any: ...

class history:
    def clearHistory() -> Any: ...
    def resumeHistory() -> Any: ...

class hotbox:
    def closeHotboxInstances() -> Any: ...
    def currentHotboxInstance() -> Any: ...
    def showHotbox(path = ..., SubmenuBackLink = ..., force = ..., resetPosition = ..., parent_widget = ..., isNodeContextMenu = ...) -> Any: ...

class imageAnnotation:
    def createNewImagNote(customPosition = ...) -> Any: ...
    def getImagePath(node) -> Any: ...
    def getImageSize(imagePath) -> Any: ...
    def getLastImageNote() -> Any: ...
    def getProjectThumbnailPath() -> Any: ...
    def imageNoteFromFile(filePath = ..., initialScale = ..., forceNewNote = ..., customPosition = ..., colorizeImage = ..., color = ..., blendMode = ..., stickyNoteToReplace = ...) -> Any: ...
    def imageNoteFromNode(graph = ..., nodelist = ...) -> Any: ...
    def imageNoteFromView(scaleFactor = ...) -> Any: ...
    def nodeIsImageNote(node) -> Any: ...
    def relinkImageNotePathToProject(node) -> Any: ...
    def removeAllImageNotes(graph = ..., silent = ...) -> Any: ...
    def setImageOnNote(stickyNote, imagePath, sizeX = ..., sizeY = ...) -> Any: ...
    def updateImagePath(node, newPath, original_path = ...) -> Any: ...
    def updateImageSize(node, newWidth = ..., newHeight = ..., customPosition = ...) -> Any: ...
    def updateScaleFactor(node, newFactorPercent, customPosition = ...) -> Any: ...

class imageManager:
    def activateAutoReloadingOnSelectedImages() -> Any: ...
    def cleanImageManager() -> Any: ...
    def deactivateAllImageAutoReloading() -> Any: ...
    def deactivateAutoReloadingOnSelectedImages() -> Any: ...
    def disableReferenceImage_onSelectedImages() -> Any: ...
    def enableImageAutoReloadOnImageManagerFiles(imageList = ...) -> Any: ...
    def enableReferenceImage_onSelectedImages() -> Any: ...
    def findImage(filePath, is_raw = ..., is_scalar = ...) -> Any: ...
    def imagesInUse() -> Any: ...
    def openImageInApplication(applicationExecutable) -> Any: ...
    def openImageInDefaultApplication() -> Any: ...
    def openImageInFileBrowser() -> Any: ...
    def rasterizeVectorImage(filePath, colorSpaceConfig, size) -> Any: ...
    def reloadImage(imageObject) -> Any: ...
    def reloadSelectedImages(svgMode = ...) -> Any: ...
    def reloadSelectedSVGFiles() -> Any: ...
    def removeEmptyImageManagerGroups() -> Any: ...
    def removeEmptyImageManagerTabs() -> Any: ...
    def removeImageManagerTabs() -> Any: ...
    def selectedImageGroup() -> Any: ...
    def setAutoReloading_onSelectedImages(mode) -> Any: ...
    def setGroupColor(group_name, color) -> Any: ...
    def setGroupColorFromIcon(group_name, icon_path) -> Any: ...
    def setGroupIcon(group_name, icon_path, color_code = ...) -> Any: ...
    def setGroupIconFromImageSelection() -> Any: ...
    def useImageAsBrushtip() -> Any: ...

class imageUtils:
    def darken_image(pathImageIconOrPixmap, factor = ..., desaturate = ..., return_QImage = ...) -> Any: ...
    def desaturate_pixmap(original_pixmap) -> Any: ...
    def desaturate_qimage(original_qimage) -> Any: ...
    def get_ep_icon(icon_name, scaledTo = ..., stateAware = ...) -> Any: ...
    def get_ep_pixmap(icon_name, scaledTo = ...) -> Any: ...
    def get_mari_icon(icon_name, scaledTo = ..., stateAware = ...) -> Any: ...
    def get_mari_pixmap(icon_name, scaledTo = ...) -> Any: ...

class layer:
    def addMask(mode) -> Any: ...
    def cloneMergeSelectedLayers() -> Any: ...
    def convertToPaintable() -> Any: ...
    def copyLayerAttributes() -> Any: ...
    def copyWithShared() -> Any: ...
    def findActiveLayerSelection(includeAdjustmentStacks = ..., includeMaskStacks = ..., includeGroupLayers = ..., includeChannelLayers = ..., silentFail = ...) -> Any: ...
    def layerCopy() -> Any: ...
    def layerCut() -> Any: ...
    def layerPaste() -> Any: ...
    def pasteLayerAttributes() -> Any: ...
    def pasteWithShared() -> Any: ...
    def toggleSelectionLock() -> Any: ...
    def toggleSelectionVisibility() -> Any: ...
    def toggleUnselectedLock() -> Any: ...
    def toggleUnselectedVisibility() -> Any: ...

class layout:
    def loadLayoutFromPath(Path, LayoutName = ...) -> Any: ...
    def restoreDefaultLayout() -> Any: ...
    def saveLayout(layoutName, Description = ...) -> Any: ...
    def setLayoutFolderPreference(path) -> Any: ...
    def setPaletteOrientationHorizontal() -> Any: ...
    def setPaletteOrientationSplitBottom() -> Any: ...
    def setPaletteOrientationSplitLeft() -> Any: ...
    def setPaletteOrientationSplitRight() -> Any: ...
    def setPaletteOrientationSplitTop() -> Any: ...
    def setPaletteOrientationVertical() -> Any: ...

class lights:
    def rotateEnvironmentLight(mode, multiplier) -> Any: ...
    def rotateLightsByAngle(angle = ...) -> Any: ...

class matrix:
    def decomposeMatrix(matrix) -> Any: ...
    def decomposeMatrixEulerAngles(matrix) -> Any: ...
    def decomposeMatrixScale(matrix) -> Any: ...
    def decomposeMatrixTranslation(matrix) -> Any: ...
    def invertMatrix(matrix) -> Any: ...
    def matrixFromVectors(rotation = ..., translation = ..., scale = ...) -> Any: ...
    def objectTransformToWorldSpaceMatrix(object_scale, object_angles, object_translation) -> Any: ...
    def setTransform(obj, transform_matrix, clock_frame = ...) -> Any: ...
    def toEulerAnglesMatrix(values) -> Any: ...
    def toScaleEulerAnglesTranslationMatrix(scale, angles, translation) -> Any: ...
    def toScaleMatrix(values) -> Any: ...
    def toTranslationMatrix(values) -> Any: ...
    def worldToObjectTransform(world_scale, world_angles, world_translation) -> Any: ...

class node:
    def channelsNodeBelongsTo(node_to_find, geo, excludeChannelLayer = ...) -> Any: ...
    def connectNodeToLastNode(overwriteExistingConnections = ...) -> Any: ...
    def copyNodeConnections(nodeToCopyFrom, nodeToCopyTo, RemoveSourceNode = ...) -> Any: ...
    def current(returnFirstSelectedNode = ...) -> Any: ...
    def disconnectAllInputConnections(nodelist = ...) -> Any: ...
    def disconnectAllOutputConnections(nodelist = ...) -> Any: ...
    def findConnectedNodeOutput(graph, node_to_find, skipDots = ..., SpecificOutput = ...) -> Any: ...
    def getAllNodesConnectedToNode(targetNode, nodeGraph, GroupContentMode = ..., returnBakePointUpstream = ..., includeTargetNode = ..., GraphGroup_TraverseConnectedOutputOnly = ..., MainGraph_TraverseStreamOnly = ..., IncludeGraphGroupNode = ..., IncludeMaterials = ..., StartStream = ...) -> Any: ...
    def getAllNodesDownstream(targetNode, includeTargetNode = ..., traverse_groups = ...) -> Any: ...
    def getMaterialStreamNamesConnectedToChannels(node) -> Any: ...
    def getNodeCategory(node) -> Any: ...
    def getNodeMaterialStreamName(graph, inputNode) -> Any: ...
    def getNodePosition(graph, node) -> Any: ...
    def getNodePrettyName(node) -> Any: ...
    def inputNode(node, nodeport) -> Any: ...
    def moveNodesToPosition(graph, nodes, positionList) -> Any: ...
    def nodeName(node) -> Any: ...
    def reloadSelected_PaintAndImages(silent = ...) -> Any: ...
    def saveNodeAttributes(selectedNode) -> Any: ...
    def setInputNode(node, portname, NodeToConnect, OutputPortName = ...) -> Any: ...
    def setNodeAttributes(selectedNode) -> Any: ...
    def setNodeName(node, newName) -> Any: ...
    def smartRenameNode(graph, node) -> Any: ...

class nodeLayout:
    def alignNodes_HorizontallyBottom(nodelist = ..., defaultToSelection = ..., streamBased = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_HorizontallyTop(nodelist = ..., defaultToSelection = ..., streamBased = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_VerticallyLeft(nodelist = ..., defaultToSelection = ..., preventAnimation = ...) -> Any: ...
    def alignNodes_VerticallyRight(nodelist = ..., defaultToSelection = ..., preventAnimation = ...) -> Any: ...
    def distributeBetweenNodes_Horizontally(nodelist) -> Any: ...
    def distributeBetweenNodes_Vertically(nodelist) -> Any: ...
    def distributeBetweenSelectedNodes_Horizontally() -> Any: ...
    def distributeBetweenSelectedNodes_Vertically() -> Any: ...
    def distributeNodesHorizontally(nodelist = ..., specificXDistance = ..., backdropOffsetLimit = ...) -> Any: ...
    def distributeNodesVertically(nodelist = ..., specificYDistance = ..., backdropOffsetLimit = ...) -> Any: ...
    def layoutNodes(graph = ..., nodelist = ...) -> Any: ...

class nodeNavigation:
    def cycleBookmarkNodesBackwards() -> Any: ...
    def cycleBookmarkNodesForward() -> Any: ...
    def jumpToNextInStream(typeIDToFind = ..., customSearch = ...) -> Any: ...
    def jumpToNextSimilarInStream() -> Any: ...
    def jumpToNodeInput() -> Any: ...
    def jumpToNodeOutput() -> Any: ...
    def jumpToPreviousInStream(typeIDToFind = ..., customSearch = ...) -> Any: ...
    def jumpToPreviousSimilarInStream() -> Any: ...
    def jumpViewToRadioNodeConnection() -> Any: ...

class nodeProperties:
    def clearNodePropertiesOnSingleClick_Connections() -> Any: ...
    def getPauseNodePropertiesState() -> Any: ...
    def initializeNodePropertiesOnSingleClick() -> Any: ...
    def initializeNodePropertiesOnSingleClick_onSpecificGeo() -> Any: ...
    def pauseNodePropertiesUpdate(mode = ...) -> Any: ...
    def updateNodePropertiesOnSelection(force = ..., forceOpenPalette = ...) -> Any: ...

class nodeStyle:
    def revertNodeStyle(inputNodeList) -> Any: ...
    def setNodeStyle(inputNodeList, setColor = ..., setShape = ..., setPixmap = ..., topColor = ..., bottomColor = ..., NodeShape = ..., pixMapPath = ...) -> Any: ...

class nodeUtilities:
    def autoDotInputConnections(graph = ..., nodelist = ...) -> Any: ...
    def createMaskFromSelection() -> Any: ...
    def createSmartCompareMask() -> Any: ...
    def createSmartHeightBlend() -> Any: ...
    def createSmartMergeNode() -> Any: ...
    def createStickyNoteWithNodeChanges(graph = ..., nodelist = ...) -> Any: ...
    def deregisterNodeContextMenu(nodeTypeID) -> Any: ...
    def disableBlendColorspaceOnNode(node) -> Any: ...
    def getRegisteredNodeContextMenus() -> Any: ...
    def optimizeMultiChannelNodes(nodelist = ...) -> Any: ...
    def registerNodeContextMenu(target, contextMenuPath, classInstance = ...) -> Any: ...
    def removeAllStickyNotesWithNodeChanges(graph = ...) -> Any: ...
    def replaceMergeNodesWithBlendNodes(useSelection = ..., ignoreColorSpaceBlend = ..., ignoreSwizzle = ..., ignoreAdvnacedBlend = ..., surpressPopup = ...) -> Any: ...
    def setMergeNodeColorSpaceToDisabled(node) -> Any: ...
    def setMergeNodeColorspace(node, setTo = ...) -> Any: ...

class nodegraph:
    def clearNodegraph(currentGeoOnly = ...) -> Any: ...
    def copyNodeAttributes(node = ...) -> Any: ...
    def createNodeAtPosition(graph, nodeString, positionList) -> Any: ...
    def createNodeDuplicateAtPosition(graph, nodes, PositionList, removeOriginalNode = ...) -> Any: ...
    def createNodeDuplicateWithOffset(graph, nodes, offsetList, removeOriginalNode = ...) -> Any: ...
    def current() -> Any: ...
    def duplicateNodesWithConnections(offsetX = ..., offsetY = ...) -> Any: ...
    def duplicate_nodeNetwork(geo, inputNode, inputNodeNodeGraph, StopAfterRadioNodes = ..., RenameChannelIncremental = ..., RenameChannel = ..., newChannelName = ..., offsetX = ..., offsetY = ...) -> Any: ...
    def getAllNodesInProject(classFilter = ...) -> Any: ...
    def getAllNodesOnGeo(geo, classFilter = ...) -> Any: ...
    def getNodesonStream(targetNode, includeGroupNode = ..., stream = ...) -> Any: ...
    def getUpstreamNodes(graph, destination_node) -> Any: ...
    def lastCreatedNode() -> Any: ...
    def recursiveGroupNodeList(node_list) -> Any: ...
    def recursiveNodeList(node_list) -> Any: ...
    def repeatLastNodeCreation() -> Any: ...
    def setNodeAttributes(nodelist = ...) -> Any: ...
    def smartRenameNodes() -> Any: ...
    def viewerNode(graph = ...) -> Any: ...

class nodegraphGrid:
    def decreaseGridHeight() -> Any: ...
    def decreaseGridLineOpacity() -> Any: ...
    def decreaseGridLineWidth() -> Any: ...
    def decreaseGridWidth() -> Any: ...
    def increaseGridHeight() -> Any: ...
    def increaseGridLineOpacity() -> Any: ...
    def increaseGridLineWidth() -> Any: ...
    def increaseGridWidth() -> Any: ...
    def toggleGridSnap() -> Any: ...
    def toggleShowGrid() -> Any: ...

class nodegraphPalette:
    def closeCurrentGraphNotification() -> Any: ...
    def cursorPositionInNodegraphSpace() -> Any: ...
    def cycleNodegraphTabs() -> Any: ...
    def enterSubgraph() -> Any: ...
    def findNodeAbstractGraphicsView() -> Any: ...
    def findNodeGraphContext() -> Any: ...
    def findNodeGraphTabWidget(returnNoneIfRootGraph = ...) -> Any: ...
    def getCurrentGraphNotification() -> Any: ...
    def getNodeGraphEventFilter() -> Any: ...
    def get_alt_pressed() -> Any: ...
    def get_ctrl_pressed() -> Any: ...
    def get_shift_pressed() -> Any: ...
    def graphNotification(text = ..., auto_close_seconds = ..., width = ..., height = ..., background_color = ..., border = ..., font_size = ...) -> Any: ...
    def leaveSubgraph() -> Any: ...
    def setNodegraphContext() -> Any: ...
    def setNodegraphTabIndex(index) -> Any: ...

class nodegraphSelection:
    def deselectAllNodes() -> Any: ...
    def deselectAllNodesExceptBackdrops() -> Any: ...
    def getLastNodeSelection() -> Any: ...
    def getPreviousNodeSelection() -> Any: ...
    def getSelectedNodesOnCurrentGeoRootGraph(FirstOnly = ...) -> Any: ...
    def getSelectedNodesOnCurrentGraph(FirstOnly = ...) -> Any: ...
    def getSeparateNodeStreams(nodelist) -> Any: ...
    def selectAllNodes() -> Any: ...
    def selectClosestNodeToCursoAndView(viewNodeProperties = ...) -> Any: ...
    def selectClosestNodeToCursor(viewNodeProperties = ...) -> Any: ...
    def selectCustomNodes(showReport = ...) -> Any: ...
    def selectNodesByType(typeOfNode = ..., nodegraph = ..., referenceNode = ...) -> Any: ...
    def selectUpstreamNodes(Stream = ...) -> Any: ...
    def selectUpstreamNodes_ignoreRadios(Stream = ...) -> Any: ...
    def selectUpstreamNodes_stopAfterRadios(Stream = ...) -> Any: ...

class nodegraphStyle:
    def toggleAllowAutoInsert() -> Any: ...
    def toggleAllowShakeToExtract() -> Any: ...

class object:
    def geoUVIndices(currentGeoOnly = ...) -> Any: ...
    def list(include_2D_objects = ...) -> Any: ...
    def removeAllGeoChannels(geo = ..., silent = ...) -> Any: ...
    def removeObjectVersion() -> Any: ...
    def setAllSUBDToHigh() -> Any: ...
    def setAllSUBDToLow() -> Any: ...
    def setVisibleSUBDToHigh() -> Any: ...
    def setVisibleSUBDToLow() -> Any: ...
    def unsubdiveGeo(geo = ...) -> Any: ...

class ocio:
    def getAvailableColorspaces(ocio_filepath, colorspace_defaults) -> Any: ...
    def getOCIOandDefaults() -> Any: ...

class patch:
    def applyPatchResolutionTemplate(geo = ..., channel = ..., node = ..., forceModeTo = ...) -> Any: ...
    def patchBake_to_imagemanager() -> Any: ...
    def resizePatches_onChannelsOrNodes(size) -> Any: ...
    def savePatchResolutionTemplate(geo = ..., channel = ..., node = ..., forceModeTo = ...) -> Any: ...

class pinnedLayers:
    def collectionPin(mode) -> Any: ...
    def emptyPin() -> Any: ...
    def quickPin(mode) -> Any: ...
    def triggerCollectionPin(layerType, layerName, project_uuid, layer_uuid) -> Any: ...
    def triggerQuickPin(layerType, layerName, project_uuid, layer_uuid) -> Any: ...

class presetBrowser:
    def closeSmartMaskShelfInstance() -> Any: ...
    def resetSmartMaskShelfPositionAndSize() -> Any: ...

class project:
    def cleanUpData() -> Any: ...
    def getCurrentProjectFolder() -> Any: ...
    def getEPProjectDataFolder(create_if_not_exist = ...) -> Any: ...
    def mariProjectIsOpen() -> Any: ...
    def openCurrentProjectFolder() -> Any: ...
    def removeAllSnapshots() -> Any: ...

class projectCollections:
    def activateCollection(name, hideOthers = ..., filter_text = ...) -> Any: ...
    def addCollection(name, color = ...) -> Any: ...
    def assignProjectsToCollection(name, projects = ...) -> Any: ...
    def batchAddCollections(collections_definitions) -> Any: ...
    def clearFilter() -> Any: ...
    def collectionNameExists(name) -> Any: ...
    def filterEnabled() -> Any: ...
    def filterText() -> Any: ...
    def getAllProjectCollections() -> Any: ...
    def getCollectionMetadataID() -> Any: ...
    def getCollectionsComboBox() -> Any: ...
    def getCollectionsWidget() -> Any: ...
    def getCurrentCollection() -> Any: ...
    def getProjectCollections(projects, includeWithoutAssignment = ...) -> Any: ...
    def projectIsPartOfCollection(project, name) -> Any: ...
    def refreshCollectionsComboBox() -> Any: ...
    def removeCollection(name) -> Any: ...
    def removeProjectsFromCollection(name, projects = ...) -> Any: ...
    def setAllowDefaultChange(state) -> Any: ...
    def setCollectionColor(name, color) -> Any: ...
    def setCurrentCollection(name) -> Any: ...
    def setFilterEnabled(state) -> Any: ...
    def setFilterText(filter_text) -> Any: ...
    def showAllProjects(filter_text = ...) -> Any: ...

class project_paths:
    def get_projectPath_jsonFile() -> Any: ...
    def setProjectPathVariable(variable_name, variable_data, set_active = ...) -> Any: ...

class project_template:
    def applyLightInfoFromTemplate(templateFilePath) -> Any: ...
    def applyPrefsFromTemplate(templateFilePath, excludeList = ..., includeList = ...) -> Any: ...
    def applyProjectorInfoFromTemplate(templatePathFile, projectorFolderLocation) -> Any: ...
    def applyViewportInfoFromTemplate(templateFilePath) -> Any: ...
    def importLastLightInfoTemplate() -> Any: ...
    def importNodesFromTemplate(templateFolderPath, clearExisting = ..., currentGeoOnly = ...) -> Any: ...
    def saveLightInfoAsTemplate(templateName) -> Any: ...
    def saveNodesFromCurrentGraph(templateName, selectedOnly = ..., skipImageData = ...) -> Any: ...
    def savePrefsAsTemplate(templateName) -> Any: ...
    def saveProjectInfoAsTemplate(templateName) -> Any: ...
    def saveViewportInfoAsTemplate(templateName) -> Any: ...

class projectors:
    def moveScanProjectionBlock_left() -> Any: ...
    def moveScanProjectionBlock_right() -> Any: ...
    def removeAllProjectors(silent = ...) -> Any: ...
    def toggleCameraType() -> Any: ...
    def updateProjectorCamera() -> Any: ...
    def updateProjectorClippingPlanes(projector = ..., geo = ...) -> Any: ...

class quickmarks:
    def loadQuickMark(ID) -> Any: ...
    def removeQuickMark(ID) -> Any: ...
    def setQuickMark(ID) -> Any: ...

class radioNodes:
    def convertInputConnectionsToRadios(nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertInputConnectionsToTeleporters(nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertOutputConnectionsToRadios(nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def convertOutputConnectionsToTeleporters(nodelist = ..., minimum_node_distance = ...) -> Any: ...
    def cycleRadioNodeConnections() -> Any: ...
    def hideAllRadioNodeConnections() -> Any: ...
    def jumpViewToRadioNodeConnection() -> Any: ...
    def showAllRadioNodeConnections() -> Any: ...
    def toggleRadioNodes(node, Force = ..., ForceMode = ...) -> Any: ...
    def toggleSelectedRadioNodesConnection() -> Any: ...
    def updateRadioNodes(portName, node) -> Any: ...

class resources:
    def extPack_3rdParty_path() -> Any: ...
    def extPack_archives_path() -> Any: ...
    def extPack_baseShapes_path() -> Any: ...
    def extPack_contextMenus_path() -> Any: ...
    def extPack_gradients_path() -> Any: ...
    def extPack_grunges_path() -> Any: ...
    def extPack_hdris_path() -> Any: ...
    def extPack_hotboxes_path() -> Any: ...
    def extPack_icon_path() -> Any: ...
    def extPack_imageNotes_anatomy_path() -> Any: ...
    def extPack_imageNotes_materials_path() -> Any: ...
    def extPack_imageNotes_path() -> Any: ...
    def extPack_imageNotes_shaderStreams_path() -> Any: ...
    def extPack_imageNotes_utilities_path() -> Any: ...
    def extPack_industrySurfaces_path() -> Any: ...
    def extPack_materialpreset_path() -> Any: ...
    def extPack_modoBakePresets_path() -> Any: ...
    def extPack_nodeContextMenu_path() -> Any: ...
    def extPack_object_path() -> Any: ...
    def extPack_offlineSplashContent_path() -> Any: ...
    def extPack_procedurals_path() -> Any: ...
    def extPack_resource_locator(alwaysReturnAPath = ...) -> Any: ...
    def extPack_settings_path() -> Any: ...
    def extPack_shelf_data_path() -> Any: ...
    def extPack_smartmasks_path() -> Any: ...
    def extPack_styles_path() -> Any: ...
    def extPack_textures_path() -> Any: ...
    def extPack_tools_path() -> Any: ...
    def mari_settings_locator() -> Any: ...

class selection:
    def isolateSelect() -> Any: ...
    def showLastHidden() -> Any: ...

class selection_group:
    def combineSelectionGroups(groupList, newName, removeOld = ...) -> Any: ...
    def complexSearch(search, group_list, default_groupmode_list = ..., default_visibility_modelist = ..., limit_visibility_modifier = ..., default_active_modelist = ..., setData = ..., forceInPathSearch = ..., forceInObjectSearch = ..., emptySearchReturnsTrue = ...) -> Any: ...
    def deleteAll() -> Any: ...
    def deleteUnused() -> Any: ...
    def getVisibilitySets() -> Any: ...
    def hideAll() -> Any: ...
    def hideUnselected() -> Any: ...
    def invertVisibility() -> Any: ...
    def lockAll() -> Any: ...
    def removeMaterialIDOverride(SelectionGroups) -> Any: ...
    def setMaterialIDOverride(SelectionGroups, color) -> Any: ...
    def showAll() -> Any: ...
    def unlockAll() -> Any: ...

class shader:
    def selectLastShader() -> Any: ...
    def syncObjectShaderSelection() -> Any: ...

class shaderPreset:
    def removeShaderPreset() -> Any: ...
    def restoreShaderChannelInputsFromPreset() -> Any: ...
    def restoreShaderDefaultInputs() -> Any: ...
    def restoreShaderParametersFromPreset() -> Any: ...
    def saveShaderPreset() -> Any: ...
    def setNodesToShader() -> Any: ...

class shading:
    def disableViewport(mode) -> Any: ...

class shelf:
    def createItem(shelf, item_type, item, ForceImmediateLoad = ...) -> Any: ...
    def deleteAllUserMariShelves() -> Any: ...
    def groupShelf(shelf, groupname) -> Any: ...

class splashScreen:
    def splashScreenConnectionTimeOut() -> Any: ...

class symmetry:
    def activateSymmetryX() -> Any: ...
    def activateSymmetryY() -> Any: ...
    def activateSymmetryZ() -> Any: ...
    def setSymmetryMode() -> Any: ...

class toolbar:
    def alignLocatorToView() -> Any: ...
    def flipPaintThroughImage_Horizontally() -> Any: ...
    def flipPaintThroughImage_Vertically() -> Any: ...
    def forceActivateTransformTool() -> Any: ...
    def scaleAndCenterLocator() -> Any: ...

class utils:
    def TDRCheck() -> Any: ...
    def changeFileOwnership(path) -> Any: ...
    def closeAllOpenProgressDialogs() -> Any: ...
    def copytree(src, dst, symlinks = ..., ignore = ..., copy_function = ..., ignore_dangling_symlinks = ...) -> Any: ...
    def correctPath(path) -> Any: ...
    def current_notification() -> Any: ...
    def delete_current_notification(do_not_animate = ...) -> Any: ...
    def findTriggerAction(actionpath) -> Any: ...
    def forceFocusReturn() -> Any: ...
    def getChildren(obj) -> Any: ...
    def getImageAttributeNames() -> Any: ...
    def getMariSettingsFolder() -> Any: ...
    def getStyle(stylefile_name, style_options) -> Any: ...
    def getUIScaleFactor() -> Any: ...
    def mariIsShuttingDown() -> Any: ...
    def mariMainWindowObject() -> Any: ...
    def mariViewport() -> Any: ...
    def message(text, title = ..., buttons = ..., icon = ..., details = ..., defaultButton = ..., parent = ...) -> Any: ...
    def messageResult(text, title = ..., buttons = ..., icon = ..., details = ..., defaultButton = ..., parent = ...) -> Any: ...
    def notification(buttons = ..., header_text = ..., info_text = ..., detail_text = ..., min_notifier_width = ..., min_notifier_height = ..., allow_dynamic_notifier_size = ..., header_pointsize = ..., info_pointsize = ..., detail_pointsize = ..., btn_pointsize = ..., notification_type = ..., custom_notification_color = ..., custom_text_color = ..., custom_button_color = ..., notification_color_width = ..., notification_position = ..., notification_animation_type = ..., animation_show_duration = ..., animation_hide_duration = ..., timeout_notification = ..., notification_timeout_length = ..., timeout_progress_color = ..., background_color = ..., distance_from_edge = ..., always_remove_previous_notification = ...) -> Any: ...
    def openFileBrowser(path, directoryOnly = ..., iteratePathUntilFound = ...) -> Any: ...
    def progressDialog(maxStepsPrimary, showSecondaryBar = ..., maxStepsSecondary = ..., windowTitle = ..., initialInfoMsg = ..., initialStatusMsg = ..., autoClose = ..., showAbortMessage = ..., AbortMsg = ..., AbortTitle = ..., MinWidth = ..., parent = ...) -> Any: ...
    def sanitizeText(text, sanitizeSlashes = ..., removeWhiteSpace = ..., customCharacters = ...) -> Any: ...
    def searchInString(search_for, search_in) -> Any: ...
    def setting_str_to_bool(settings_value, invalid_defaults_to = ...) -> Any: ...
    def shortenText(text, characterLimit = ..., shortenStart = ..., short = ...) -> Any: ...
    def stopViewportTracking() -> Any: ...
    def windowOffsetPosition(useSafeMargin = ..., paddingList = ..., offsetList = ...) -> Any: ...

class version:
    def buildVersion() -> Any: ...
    def checkResourceVersion() -> Any: ...
    def devToolsVisible() -> Any: ...
    def isAlphaVersion() -> Any: ...
    def isBetaVersion() -> Any: ...
    def isDevVersion() -> Any: ...
    def isNewVersionAvailable(debugMode = ...) -> Any: ...
    def isReleaseCandidateVersion() -> Any: ...
    def launchVersionCheck() -> Any: ...
    def majorVersion() -> Any: ...
    def mari45OrAbove(invert = ...) -> Any: ...
    def mari46OrAbove(invert = ...) -> Any: ...
    def mari46v4orAbove(invert = ...) -> Any: ...
    def mari47OrAbove(invert = ...) -> Any: ...
    def mari47Ov2rAbove(invert = ...) -> Any: ...
    def mari48OrAbove(invert = ...) -> Any: ...
    def mari48v2OrAbove(invert = ...) -> Any: ...
    def mari70v1orAbove(invert = ...) -> Any: ...
    def mari70v2orAbove(invert = ...) -> Any: ...
    def mari71v1orAbove(invert = ...) -> Any: ...
    def mari75v1orAbove(invert = ...) -> Any: ...
    def minorVersion() -> Any: ...
    def patchVersion() -> Any: ...
    def recommendedEPResourceVersion() -> Any: ...
    def version() -> Any: ...
    def versionAsJson(jsonfile = ...) -> Any: ...
    def versionPrettyName() -> Any: ...
    def versionTest() -> Any: ...

class view:
    def setViewBackgroundTheme(theme = ...) -> Any: ...

class web:
    def checkEPAvailability() -> Any: ...
    def checkYouTubeAvailability() -> Any: ...
    def downloadImageFromWeb(url) -> Any: ...
    def getYouTubeThumbnail(url) -> Any: ...

