from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Type:
    TYPE_CHOOSE_FILE: Type = ...
    TYPE_DIRECTORY: Type = ...
    TYPE_FILE: Type = ...
    TYPE_FILE_AND_DIRECTORY: Type = ...
    TYPE_SAVE_FILE: Type = ...
    TYPE_SINGLE_DIRECTORY: Type = ...
    TYPE_SINGLE_FILE: Type = ...
    name: getset_descriptor
    values: dict

TYPE_CHOOSE_FILE: Type = ...
TYPE_DIRECTORY: Type = ...
TYPE_FILE: Type = ...
TYPE_FILE_AND_DIRECTORY: Type = ...
TYPE_SAVE_FILE: Type = ...
TYPE_SINGLE_DIRECTORY: Type = ...
TYPE_SINGLE_FILE: Type = ...
staticMetaObject: QMetaObject
TYPE_CHOOSE_FILE: Type = ...
TYPE_DIRECTORY: Type = ...
TYPE_FILE: Type = ...
TYPE_FILE_AND_DIRECTORY: Type = ...
TYPE_SAVE_FILE: Type = ...
TYPE_SINGLE_DIRECTORY: Type = ...
TYPE_SINGLE_FILE: Type = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def acceptNonExisting() -> bool: ...
def append(File: str) -> Any: ...
def at(Index: int) -> str: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clear() -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def contains(File: str) -> bool: ...
def count() -> int: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def defaultDirectory() -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def filter() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def insert(Index: int, File: str) -> Any: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isEmpty() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def pathKey() -> str: ...
def pickedFile() -> str: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeAt(Index: int) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setAcceptNonExisting(AcceptNonExisting: bool) -> Any: ...
def setDefaultDirectory(DefaultDirectory: str) -> Any: ...
def setFilter(Filter: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPathKey(PathKey: str) -> Any: ...
def setPickedFile(PickedFile: str) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setType(T) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def type() -> Any: ...
