from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class FileList(API):
    class Type:
        TYPE_CHOOSE_FILE: Type = ...
        TYPE_DIRECTORY: Type = ...
        TYPE_FILE: Type = ...
        TYPE_FILE_AND_DIRECTORY: Type = ...
        TYPE_SAVE_FILE: Type = ...
        TYPE_SINGLE_DIRECTORY: Type = ...
        TYPE_SINGLE_FILE: Type = ...
        name: getset_descriptor
        values: dict

    TYPE_CHOOSE_FILE: Type = ...
    TYPE_DIRECTORY: Type = ...
    TYPE_FILE: Type = ...
    TYPE_FILE_AND_DIRECTORY: Type = ...
    TYPE_SAVE_FILE: Type = ...
    TYPE_SINGLE_DIRECTORY: Type = ...
    TYPE_SINGLE_FILE: Type = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def acceptNonExisting(self) -> bool: ...
    def append(self, File: str) -> Any: ...
    def at(self, Index: int) -> str: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clear(self) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def contains(self, File: str) -> bool: ...
    def count(self) -> int: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def defaultDirectory(self) -> str: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def filter(self) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def insert(self, Index: int, File: str) -> Any: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def pathKey(self) -> str: ...
    def pickedFile(self) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeAt(self, Index: int) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAcceptNonExisting(self, AcceptNonExisting: bool) -> Any: ...
    def setDefaultDirectory(self, DefaultDirectory: str) -> Any: ...
    def setFilter(self, Filter: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPathKey(self, PathKey: str) -> Any: ...
    def setPickedFile(self, PickedFile: str) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setType(self, T) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def type(self) -> Any: ...
