from typing import Any

class CreateSelectionSetOptions:
    SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
    SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
    name: getset_descriptor
    values: dict

class GeometryImportFlags:
    GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
    GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
    name: getset_descriptor
    values: dict

class MergeSelectionGroupWithSameNameType:
    MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
    MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
    name: getset_descriptor
    values: dict

class MergeType:
    MERGETYPE_JUST_MERGE_NODES: MergeType = ...
    MERGETYPE_SINGLE_MESH: MergeType = ...
    name: getset_descriptor
    values: dict

class NodeType:
    CAMERA: NodeType = ...
    FACESET: NodeType = ...
    GROUP: NodeType = ...
    POLYMESH: NodeType = ...
    ROOT: NodeType = ...
    SUBDIV: NodeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionBoundaryInterpolation:
    VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionCreasingMethod:
    CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
    CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionFaceVaryingInterpolation:
    FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionSchemeType:
    SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
    SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
    SCHEME_LOOP: OpenSubdivisionSchemeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionTriangleSubdivision:
    TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
    TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
    name: getset_descriptor
    values: dict

def addLocator(AddAsChildToSelectedObject = ...) -> Any: ...
def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def current() -> Any: ...
def currentLocator() -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def duplicateCurrentGeoEntity(DuplicateShaderNetwork = ...) -> Any: ...
def duplicateGeoEntity(Object, DuplicateShaderNetwork = ...) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
class entityAdded:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class entityMadeCurrent:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

class entityRemoved:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def find(Name) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def geometryOperationList() -> Any: ...
def get(Name) -> Any: ...
def getAnimationTakes(Path) -> Any: ...
def getDefaultAnimationTake(Path) -> Any: ...
def getFileContents(Path) -> Any: ...
def getFileFrameRange(Path, Take = ...) -> Any: ...
def importFromArchive(DirPath) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def list() -> Any: ...
def listLocators() -> Any: ...
def load(Paths, Options = ..., ObjectsToLoad = ..., LoadAsChild = ...) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def names() -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def recalculatePatchBounds() -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerUserData() -> Any: ...
def remove(Name) -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setCurrent(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def supportedReadFormats() -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
