from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Lockable
from mari import Metadata

class ChannelDestroyStrategy:
    DESTROY_ALL: ChannelDestroyStrategy = ...
    DESTROY_NONE: ChannelDestroyStrategy = ...
    DESTROY_UNSHARED: ChannelDestroyStrategy = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SystemShaderType:
    SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
    name: getset_descriptor
    values: dict

DESTROY_ALL: ChannelDestroyStrategy = ...
DESTROY_NONE: ChannelDestroyStrategy = ...
DESTROY_UNSHARED: ChannelDestroyStrategy = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
staticMetaObject: QMetaObject
DESTROY_ALL: ChannelDestroyStrategy = ...
DESTROY_NONE: ChannelDestroyStrategy = ...
DESTROY_UNSHARED: ChannelDestroyStrategy = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
@staticmethod
def shaderLayeredTypeList() -> typing.List: ...
@staticmethod
def shaderStandaloneTypeList() -> typing.List: ...
@staticmethod
def transferChannels(UVRemap: typing.Any, SourceChannels: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
def addLocator() -> mari.LocatorEntity: ...
def addVersion(Paths: typing.Any, Name: str, Options: typing.Any = ...) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def boundingBoxLowerBounds() -> mari.VectorN: ...
def boundingBoxUpperBounds() -> mari.VectorN: ...
def boundingSphereCenter() -> mari.VectorN: ...
def boundingSphereRadius() -> float: ...
def channel(ChannelName: str) -> mari.Channel: ...
def channelAdded(*args, **kwargs) -> Any: ...
def channelCreated(*args, **kwargs) -> Any: ...
def channelList() -> typing.List: ...
def channelMadeCurrent(*args, **kwargs) -> Any: ...
def channelRemoved(*args, **kwargs) -> Any: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def completePatchList() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createChannel(Name: str, Width: int, Height: int, Depth: int, IsShaderStack: bool = ...) -> mari.Channel: ...
def createDuplicateChannel(ChannelToDuplicate: mari.Channel, NewChannelName: str = ...) -> mari.Channel: ...
def createDuplicateShader(ShaderToDuplicate: mari.Shader, NewShaderName: str = ...) -> mari.Shader: ...
def createGeoChannel() -> mari.GeoChannel: ...
def createLayeredShader(Name: str, LayeredType: str) -> mari.Shader: ...
def createPtexChannel(Name: str, Depth: int) -> mari.Channel: ...
def createStandaloneShader(Name: str, StandaloneType: str) -> mari.Shader: ...
def currentChannel() -> mari.Channel: ...
def currentImageSet() -> mari.ImageSet: ...
def currentShader() -> mari.Shader: ...
def currentVersion() -> mari.GeoEntityVersion: ...
def currentVersionName() -> str: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportAsArchive(DirPath: str) -> Any: ...
def findChannel(ChannelName: str) -> mari.Channel: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def findGeoChannel(Alias: str) -> mari.GeoChannel: ...
def findImageSet(rName: str) -> mari.ImageSet: ...
def findShader(Name: str) -> mari.Shader: ...
def generateSubdivision(Options: typing.Dict) -> bool: ...
def geoChannelAdded(*args, **kwargs) -> Any: ...
def geoChannelRemoved(*args, **kwargs) -> Any: ...
def geoChannels() -> typing.List: ...
def geometryVersionAdded(*args, **kwargs) -> Any: ...
def geometryVersionMadeCurrent(*args, **kwargs) -> Any: ...
def geometryVersionRemoved(*args, **kwargs) -> Any: ...
def hasMetadata(Name: str) -> bool: ...
def hide() -> Any: ...
def hideLocator() -> Any: ...
def imageSet(rImageSetName: str) -> mari.ImageSet: ...
def imageSetAdded(*args, **kwargs) -> Any: ...
def imageSetList() -> typing.List: ...
def imageSetMadeCurrent(*args, **kwargs) -> Any: ...
def imageSetNames() -> typing.List: ...
def imageSetRemoved(*args, **kwargs) -> Any: ...
def importFromArchive(DirPath: str) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def is2DPaintObject() -> bool: ...
def isLocked() -> bool: ...
def isNull() -> bool: ...
def isPtex() -> bool: ...
def isSelected() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isVisible() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lock() -> Any: ...
def lockedChanged(*args, **kwargs) -> Any: ...
def maximumSubdivisionLevel() -> int: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def missingGeoChannels() -> typing.List: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def nameChanged(*args, **kwargs) -> Any: ...
def nodeGraph() -> mari.NodeGraph: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def patch(UvIndex: int) -> mari.GeoPatch: ...
def patchImage(Patch: mari.GeoPatch, pImageSet: mari.ImageSet) -> mari.Image: ...
def patchList() -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def remapSubdivisionSettings(Options: typing.Dict) -> Any: ...
def removeChannel(ChannelToRemove: mari.Channel, Strategy = ...) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeGeoChannel(GeoChannelObject: mari.GeoChannel) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def removeShader(ShaderToRemove: mari.Shader, RetractionMode = ...) -> Any: ...
def removeVersion(VersionName: str) -> Any: ...
def renameVersion(OldName: str, NewName: str) -> Any: ...
def resetHandleTransform(Frame: int = ...) -> Any: ...
def save(FileName: str, Format: str = ...) -> Any: ...
def selectedPatches() -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setCurrentChannel(NewCurrentChannel: mari.Channel) -> Any: ...
def setCurrentImageSet(NewCurrentImageSet: typing.Any) -> Any: ...
def setCurrentShader(NewCurrentShader: mari.Shader) -> Any: ...
def setCurrentVersion(VersionName: str) -> Any: ...
def setLocked(Locked: bool) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setName(NewName: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setSelected(Selected: bool) -> Any: ...
def setSubdivisionLevel(Level: int) -> Any: ...
def setTransform(pTransform: mari.Matrix, Frame: int = ...) -> Any: ...
def setVisibility(Visible: bool) -> Any: ...
def shader(Name: str) -> mari.Shader: ...
def shaderCreated(*args, **kwargs) -> Any: ...
def shaderList() -> typing.List: ...
def shaderMadeCurrent(*args, **kwargs) -> Any: ...
def shaderRemoved(*args, **kwargs) -> Any: ...
def show() -> Any: ...
def showLocator() -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def subdivisionBoundaryInterpolateMethod() -> str: ...
def subdivisionCreasing() -> str: ...
def subdivisionFaceVaryingBoundaryInterpolateMethod() -> str: ...
def subdivisionScheme() -> str: ...
def subdivisionSkippedMeshList() -> typing.List: ...
def subdivisionTriangleSubdivisionRule() -> str: ...
def systemShader(Type) -> mari.Shader: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def transform(Frame: int) -> mari.Matrix: ...
def translation(Frame: int = ...) -> mari.VectorN: ...
def unlock() -> Any: ...
def uuid() -> str: ...
def version(VersionName: str) -> mari.GeoEntityVersion: ...
def versionList() -> typing.List: ...
def versionNames() -> typing.List: ...
def visibilityChanged(*args, **kwargs) -> Any: ...
