from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Lockable
from mari import Metadata

class GeoEntity(Lockable):
    class ChannelDestroyStrategy:
        DESTROY_ALL: ChannelDestroyStrategy = ...
        DESTROY_NONE: ChannelDestroyStrategy = ...
        DESTROY_UNSHARED: ChannelDestroyStrategy = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class SystemShaderType:
        SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
        SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
        SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
        SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
        name: getset_descriptor
        values: dict

    DESTROY_ALL: ChannelDestroyStrategy = ...
    DESTROY_NONE: ChannelDestroyStrategy = ...
    DESTROY_UNSHARED: ChannelDestroyStrategy = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def shaderLayeredTypeList() -> typing.List: ...
    @staticmethod
    def shaderStandaloneTypeList() -> typing.List: ...
    @staticmethod
    def transferChannels(UVRemap: typing.Any, SourceChannels: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
    def addLocator(self) -> mari.LocatorEntity: ...
    def addVersion(self, Paths: typing.Any, Name: str, Options: typing.Any = ...) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def boundingBoxLowerBounds(self) -> mari.VectorN: ...
    def boundingBoxUpperBounds(self) -> mari.VectorN: ...
    def boundingSphereCenter(self) -> mari.VectorN: ...
    def boundingSphereRadius(self) -> float: ...
    def channel(self, ChannelName: str) -> mari.Channel: ...
    def channelAdded(self, *args, **kwargs) -> Any: ...
    def channelCreated(self, *args, **kwargs) -> Any: ...
    def channelList(self) -> typing.List: ...
    def channelMadeCurrent(self, *args, **kwargs) -> Any: ...
    def channelRemoved(self, *args, **kwargs) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def completePatchList(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createChannel(self, Name: str, Width: int, Height: int, Depth: int, IsShaderStack: bool = ...) -> mari.Channel: ...
    def createDuplicateChannel(self, ChannelToDuplicate: mari.Channel, NewChannelName: str = ...) -> mari.Channel: ...
    def createDuplicateShader(self, ShaderToDuplicate: mari.Shader, NewShaderName: str = ...) -> mari.Shader: ...
    def createGeoChannel(self) -> mari.GeoChannel: ...
    def createLayeredShader(self, Name: str, LayeredType: str) -> mari.Shader: ...
    def createPtexChannel(self, Name: str, Depth: int) -> mari.Channel: ...
    def createStandaloneShader(self, Name: str, StandaloneType: str) -> mari.Shader: ...
    def currentChannel(self) -> mari.Channel: ...
    def currentImageSet(self) -> mari.ImageSet: ...
    def currentShader(self) -> mari.Shader: ...
    def currentVersion(self) -> mari.GeoEntityVersion: ...
    def currentVersionName(self) -> str: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportAsArchive(self, DirPath: str) -> Any: ...
    def findChannel(self, ChannelName: str) -> mari.Channel: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def findGeoChannel(self, Alias: str) -> mari.GeoChannel: ...
    def findImageSet(self, rName: str) -> mari.ImageSet: ...
    def findShader(self, Name: str) -> mari.Shader: ...
    def generateSubdivision(self, Options: typing.Dict) -> bool: ...
    def geoChannelAdded(self, *args, **kwargs) -> Any: ...
    def geoChannelRemoved(self, *args, **kwargs) -> Any: ...
    def geoChannels(self) -> typing.List: ...
    def geometryVersionAdded(self, *args, **kwargs) -> Any: ...
    def geometryVersionMadeCurrent(self, *args, **kwargs) -> Any: ...
    def geometryVersionRemoved(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def hide(self) -> Any: ...
    def hideLocator(self) -> Any: ...
    def imageSet(self, rImageSetName: str) -> mari.ImageSet: ...
    def imageSetAdded(self, *args, **kwargs) -> Any: ...
    def imageSetList(self) -> typing.List: ...
    def imageSetMadeCurrent(self, *args, **kwargs) -> Any: ...
    def imageSetNames(self) -> typing.List: ...
    def imageSetRemoved(self, *args, **kwargs) -> Any: ...
    def importFromArchive(self, DirPath: str) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def is2DPaintObject(self) -> bool: ...
    def isLocked(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isPtex(self) -> bool: ...
    def isSelected(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isVisible(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lock(self) -> Any: ...
    def lockedChanged(self, *args, **kwargs) -> Any: ...
    def maximumSubdivisionLevel(self) -> int: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def missingGeoChannels(self) -> typing.List: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def nodeGraph(self) -> mari.NodeGraph: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def patch(self, UvIndex: int) -> mari.GeoPatch: ...
    def patchImage(self, Patch: mari.GeoPatch, pImageSet: mari.ImageSet) -> mari.Image: ...
    def patchList(self) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def remapSubdivisionSettings(self, Options: typing.Dict) -> Any: ...
    def removeChannel(self, ChannelToRemove: mari.Channel, Strategy = ...) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeGeoChannel(self, GeoChannelObject: mari.GeoChannel) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def removeShader(self, ShaderToRemove: mari.Shader, RetractionMode = ...) -> Any: ...
    def removeVersion(self, VersionName: str) -> Any: ...
    def renameVersion(self, OldName: str, NewName: str) -> Any: ...
    def resetHandleTransform(self, Frame: int = ...) -> Any: ...
    def save(self, FileName: str, Format: str = ...) -> Any: ...
    def selectedPatches(self) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCurrentChannel(self, NewCurrentChannel: mari.Channel) -> Any: ...
    def setCurrentImageSet(self, NewCurrentImageSet: typing.Any) -> Any: ...
    def setCurrentShader(self, NewCurrentShader: mari.Shader) -> Any: ...
    def setCurrentVersion(self, VersionName: str) -> Any: ...
    def setLocked(self, Locked: bool) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, NewName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSelected(self, Selected: bool) -> Any: ...
    def setSubdivisionLevel(self, Level: int) -> Any: ...
    def setTransform(self, pTransform: mari.Matrix, Frame: int = ...) -> Any: ...
    def setVisibility(self, Visible: bool) -> Any: ...
    def shader(self, Name: str) -> mari.Shader: ...
    def shaderCreated(self, *args, **kwargs) -> Any: ...
    def shaderList(self) -> typing.List: ...
    def shaderMadeCurrent(self, *args, **kwargs) -> Any: ...
    def shaderRemoved(self, *args, **kwargs) -> Any: ...
    def show(self) -> Any: ...
    def showLocator(self) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def subdivisionBoundaryInterpolateMethod(self) -> str: ...
    def subdivisionCreasing(self) -> str: ...
    def subdivisionFaceVaryingBoundaryInterpolateMethod(self) -> str: ...
    def subdivisionScheme(self) -> str: ...
    def subdivisionSkippedMeshList(self) -> typing.List: ...
    def subdivisionTriangleSubdivisionRule(self) -> str: ...
    def systemShader(self, Type) -> mari.Shader: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def transform(self, Frame: int) -> mari.Matrix: ...
    def translation(self, Frame: int = ...) -> mari.VectorN: ...
    def unlock(self) -> Any: ...
    def uuid(self) -> str: ...
    def version(self, VersionName: str) -> mari.GeoEntityVersion: ...
    def versionList(self) -> typing.List: ...
    def versionNames(self) -> typing.List: ...
    def visibilityChanged(self, *args, **kwargs) -> Any: ...
