from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Lockable
from mari import Metadata

class ChannelDestroyStrategy:
    DESTROY_ALL: ChannelDestroyStrategy = ...
    DESTROY_NONE: ChannelDestroyStrategy = ...
    DESTROY_UNSHARED: ChannelDestroyStrategy = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SystemShaderType:
    SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
    SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
    name: getset_descriptor
    values: dict

DESTROY_ALL: ChannelDestroyStrategy = ...
DESTROY_NONE: ChannelDestroyStrategy = ...
DESTROY_UNSHARED: ChannelDestroyStrategy = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
staticMetaObject: QMetaObject
DESTROY_ALL: ChannelDestroyStrategy = ...
DESTROY_NONE: ChannelDestroyStrategy = ...
DESTROY_UNSHARED: ChannelDestroyStrategy = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
SYSTEM_SHADER_CURRENT_CHANNEL: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_LAYER_AND_BELOW: SystemShaderType = ...
SYSTEM_SHADER_CURRENT_PAINT_TARGET: SystemShaderType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def shaderLayeredTypeList() -> Any: ...
@staticmethod
def shaderStandaloneTypeList() -> Any: ...
@staticmethod
def transferChannels(UVRemap, SourceChannels, SourceGeoVersion, DestinationGeoVersion, DestinationSize = ..., BleedEdges = ..., FillColor = ..., SourceUVIndices = ..., DestinationUVIndices = ...) -> Any: ...
def addLocator(self) -> Any: ...
def addVersion(self, Paths, Name, Options = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def boundingBoxLowerBounds(self) -> Any: ...
def boundingBoxUpperBounds(self) -> Any: ...
def boundingSphereCenter(self) -> Any: ...
def boundingSphereRadius(self) -> Any: ...
def channel(self, ChannelName) -> Any: ...
def channelAdded(self, *args, **kwargs) -> Any: ...
def channelCreated(self, *args, **kwargs) -> Any: ...
def channelList(self) -> Any: ...
def channelMadeCurrent(self, *args, **kwargs) -> Any: ...
def channelRemoved(self, *args, **kwargs) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def completePatchList(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createChannel(self, Name, Width, Height, Depth, IsShaderStack = ...) -> Any: ...
def createDuplicateChannel(self, ChannelToDuplicate, NewChannelName = ...) -> Any: ...
def createDuplicateShader(self, ShaderToDuplicate, NewShaderName = ...) -> Any: ...
def createGeoChannel(self) -> Any: ...
def createLayeredShader(self, Name, LayeredType) -> Any: ...
def createPtexChannel(self, Name, Depth) -> Any: ...
def createStandaloneShader(self, Name, StandaloneType) -> Any: ...
def currentChannel(self) -> Any: ...
def currentImageSet(self) -> Any: ...
def currentShader(self) -> Any: ...
def currentVersion(self) -> Any: ...
def currentVersionName(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportAsArchive(self, DirPath) -> Any: ...
def findChannel(self, ChannelName) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findGeoChannel(self, Alias) -> Any: ...
def findImageSet(self, rName) -> Any: ...
def findShader(self, Name) -> Any: ...
def generateSubdivision(self, Options) -> Any: ...
def geoChannelAdded(self, *args, **kwargs) -> Any: ...
def geoChannelRemoved(self, *args, **kwargs) -> Any: ...
def geoChannels(self) -> Any: ...
def geometryVersionAdded(self, *args, **kwargs) -> Any: ...
def geometryVersionMadeCurrent(self, *args, **kwargs) -> Any: ...
def geometryVersionRemoved(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hide(self) -> Any: ...
def hideLocator(self) -> Any: ...
def imageSet(self, rImageSetName) -> Any: ...
def imageSetAdded(self, *args, **kwargs) -> Any: ...
def imageSetList(self) -> Any: ...
def imageSetMadeCurrent(self, *args, **kwargs) -> Any: ...
def imageSetNames(self) -> Any: ...
def imageSetRemoved(self, *args, **kwargs) -> Any: ...
def importFromArchive(self, DirPath) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def is2DPaintObject(self) -> Any: ...
def isLocked(self) -> Any: ...
def isNull(self) -> Any: ...
def isPtex(self) -> Any: ...
def isSelected(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isVisible(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lock(self) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def maximumSubdivisionLevel(self) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def missingGeoChannels(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def nodeGraph(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def patch(self, UvIndex) -> Any: ...
def patchImage(self, Patch, pImageSet) -> Any: ...
def patchList(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def remapSubdivisionSettings(self, Options) -> Any: ...
def removeChannel(self, ChannelToRemove, Strategy = ...) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeGeoChannel(self, GeoChannelObject) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def removeShader(self, ShaderToRemove, RetractionMode = ...) -> Any: ...
def removeVersion(self, VersionName) -> Any: ...
def renameVersion(self, OldName, NewName) -> Any: ...
def resetHandleTransform(self, Frame = ...) -> Any: ...
def save(self, FileName, Format = ...) -> Any: ...
def selectedPatches(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCurrentChannel(self, NewCurrentChannel) -> Any: ...
def setCurrentImageSet(self, NewCurrentImageSet) -> Any: ...
def setCurrentShader(self, NewCurrentShader) -> Any: ...
def setCurrentVersion(self, VersionName) -> Any: ...
def setLocked(self, Locked) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, NewName) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSelected(self, Selected) -> Any: ...
def setSubdivisionLevel(self, Level) -> Any: ...
def setTransform(self, pTransform, Frame = ...) -> Any: ...
def setVisibility(self, Visible) -> Any: ...
def shader(self, Name) -> Any: ...
def shaderCreated(self, *args, **kwargs) -> Any: ...
def shaderList(self) -> Any: ...
def shaderMadeCurrent(self, *args, **kwargs) -> Any: ...
def shaderRemoved(self, *args, **kwargs) -> Any: ...
def show(self) -> Any: ...
def showLocator(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def subdivisionBoundaryInterpolateMethod(self) -> Any: ...
def subdivisionCreasing(self) -> Any: ...
def subdivisionFaceVaryingBoundaryInterpolateMethod(self) -> Any: ...
def subdivisionScheme(self) -> Any: ...
def subdivisionSkippedMeshList(self) -> Any: ...
def subdivisionTriangleSubdivisionRule(self) -> Any: ...
def systemShader(self, Type) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def transform(self, Frame) -> Any: ...
def translation(self, Frame = ...) -> Any: ...
def unlock(self) -> Any: ...
def uuid(self) -> Any: ...
def version(self, VersionName) -> Any: ...
def versionList(self) -> Any: ...
def versionNames(self) -> Any: ...
def visibilityChanged(self, *args, **kwargs) -> Any: ...
