from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class CreateSelectionSetOptions:
    SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
    SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
    name: getset_descriptor
    values: dict

class GeometryImportFlags:
    GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
    GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
    name: getset_descriptor
    values: dict

class MergeSelectionGroupWithSameNameType:
    MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
    MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
    name: getset_descriptor
    values: dict

class MergeType:
    MERGETYPE_JUST_MERGE_NODES: MergeType = ...
    MERGETYPE_SINGLE_MESH: MergeType = ...
    name: getset_descriptor
    values: dict

class NodeType:
    CAMERA: NodeType = ...
    FACESET: NodeType = ...
    GROUP: NodeType = ...
    POLYMESH: NodeType = ...
    ROOT: NodeType = ...
    SUBDIV: NodeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionBoundaryInterpolation:
    VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionCreasingMethod:
    CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
    CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionFaceVaryingInterpolation:
    FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionSchemeType:
    SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
    SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
    SCHEME_LOOP: OpenSubdivisionSchemeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionTriangleSubdivision:
    TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
    TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
    name: getset_descriptor
    values: dict

CAMERA: NodeType = ...
CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
FACESET: NodeType = ...
FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
GROUP: NodeType = ...
MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
MERGETYPE_JUST_MERGE_NODES: MergeType = ...
MERGETYPE_SINGLE_MESH: MergeType = ...
POLYMESH: NodeType = ...
ROOT: NodeType = ...
SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
SCHEME_LOOP: OpenSubdivisionSchemeType = ...
SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
SUBDIV: NodeType = ...
TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
staticMetaObject: QMetaObject
CAMERA: NodeType = ...
CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
FACESET: NodeType = ...
FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
GROUP: NodeType = ...
MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
MERGETYPE_JUST_MERGE_NODES: MergeType = ...
MERGETYPE_SINGLE_MESH: MergeType = ...
POLYMESH: NodeType = ...
ROOT: NodeType = ...
SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
SCHEME_LOOP: OpenSubdivisionSchemeType = ...
SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
SUBDIV: NodeType = ...
TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def addLocator(AddAsChildToSelectedObject: bool = ...) -> mari.LocatorEntity: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def current() -> mari.GeoEntity: ...
def currentLocator() -> mari.LocatorEntity: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def duplicateCurrentGeoEntity(DuplicateShaderNetwork: bool = ...) -> Any: ...
def duplicateGeoEntity(Object: mari.GeoEntity, DuplicateShaderNetwork: bool = ...) -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def entityAdded(*args, **kwargs) -> Any: ...
def entityMadeCurrent(*args, **kwargs) -> Any: ...
def entityRemoved(*args, **kwargs) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def find(Name: str) -> mari.GeoEntity: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def geometryOperationList() -> typing.List: ...
def get(Name: str) -> mari.GeoEntity: ...
def getAnimationTakes(Path: str) -> typing.List: ...
def getDefaultAnimationTake(Path: str) -> str: ...
def getFileContents(Path: str) -> typing.Any: ...
def getFileFrameRange(Path: str, Take: str = ...) -> typing.List: ...
def importFromArchive(DirPath: str) -> mari.GeoEntity: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def list() -> typing.List: ...
def listLocators() -> typing.List: ...
def load(Paths: typing.Any, Options: typing.Any = ..., ObjectsToLoad: typing.Any = ..., LoadAsChild: bool = ...) -> typing.List: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def names() -> typing.List: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def recalculatePatchBounds() -> Any: ...
def receivers(signal: bytes) -> int: ...
def remove(Name: str) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setCurrent(*args, **kwargs) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def supportedReadFormats() -> typing.List: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
