from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class GeoManager(API):
    class CreateSelectionSetOptions:
        SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
        SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
        name: getset_descriptor
        values: dict

    class GeometryImportFlags:
        GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
        GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
        name: getset_descriptor
        values: dict

    class MergeSelectionGroupWithSameNameType:
        MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
        MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
        name: getset_descriptor
        values: dict

    class MergeType:
        MERGETYPE_JUST_MERGE_NODES: MergeType = ...
        MERGETYPE_SINGLE_MESH: MergeType = ...
        name: getset_descriptor
        values: dict

    class NodeType:
        CAMERA: NodeType = ...
        FACESET: NodeType = ...
        GROUP: NodeType = ...
        POLYMESH: NodeType = ...
        ROOT: NodeType = ...
        SUBDIV: NodeType = ...
        name: getset_descriptor
        values: dict

    class OpenSubdivisionBoundaryInterpolation:
        VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
        VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
        VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
        name: getset_descriptor
        values: dict

    class OpenSubdivisionCreasingMethod:
        CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
        CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
        name: getset_descriptor
        values: dict

    class OpenSubdivisionFaceVaryingInterpolation:
        FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
        FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
        FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
        FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
        FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
        FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
        name: getset_descriptor
        values: dict

    class OpenSubdivisionSchemeType:
        SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
        SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
        SCHEME_LOOP: OpenSubdivisionSchemeType = ...
        name: getset_descriptor
        values: dict

    class OpenSubdivisionTriangleSubdivision:
        TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
        TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
        name: getset_descriptor
        values: dict

    CAMERA: NodeType = ...
    CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
    CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
    FACESET: NodeType = ...
    FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
    GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
    GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
    GROUP: NodeType = ...
    MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
    MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
    MERGETYPE_JUST_MERGE_NODES: MergeType = ...
    MERGETYPE_SINGLE_MESH: MergeType = ...
    POLYMESH: NodeType = ...
    ROOT: NodeType = ...
    SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
    SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
    SCHEME_LOOP: OpenSubdivisionSchemeType = ...
    SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
    SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
    SUBDIV: NodeType = ...
    TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
    TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
    VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def addLocator(self, AddAsChildToSelectedObject: bool = ...) -> mari.LocatorEntity: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def current(self) -> mari.GeoEntity: ...
    def currentLocator(self) -> mari.LocatorEntity: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def duplicateCurrentGeoEntity(self, DuplicateShaderNetwork: bool = ...) -> Any: ...
    def duplicateGeoEntity(self, Object: mari.GeoEntity, DuplicateShaderNetwork: bool = ...) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def entityAdded(self, *args, **kwargs) -> Any: ...
    def entityMadeCurrent(self, *args, **kwargs) -> Any: ...
    def entityRemoved(self, *args, **kwargs) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def find(self, Name: str) -> mari.GeoEntity: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def geometryOperationList(self) -> typing.List: ...
    def get(self, Name: str) -> mari.GeoEntity: ...
    def getAnimationTakes(self, Path: str) -> typing.List: ...
    def getDefaultAnimationTake(self, Path: str) -> str: ...
    def getFileContents(self, Path: str) -> typing.Any: ...
    def getFileFrameRange(self, Path: str, Take: str = ...) -> typing.List: ...
    def importFromArchive(self, DirPath: str) -> mari.GeoEntity: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def list(self) -> typing.List: ...
    def listLocators(self) -> typing.List: ...
    def load(self, Paths: typing.Any, Options: typing.Any = ..., ObjectsToLoad: typing.Any = ..., LoadAsChild: bool = ...) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def names(self) -> typing.List: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def recalculatePatchBounds(self) -> Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def remove(self, Name: str) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCurrent(self, *args, **kwargs) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def supportedReadFormats(self) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
