from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class CreateSelectionSetOptions:
    SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
    SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
    name: getset_descriptor
    values: dict

class GeometryImportFlags:
    GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
    GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
    name: getset_descriptor
    values: dict

class MergeSelectionGroupWithSameNameType:
    MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
    MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
    name: getset_descriptor
    values: dict

class MergeType:
    MERGETYPE_JUST_MERGE_NODES: MergeType = ...
    MERGETYPE_SINGLE_MESH: MergeType = ...
    name: getset_descriptor
    values: dict

class NodeType:
    CAMERA: NodeType = ...
    FACESET: NodeType = ...
    GROUP: NodeType = ...
    POLYMESH: NodeType = ...
    ROOT: NodeType = ...
    SUBDIV: NodeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionBoundaryInterpolation:
    VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
    VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionCreasingMethod:
    CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
    CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionFaceVaryingInterpolation:
    FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
    FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionSchemeType:
    SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
    SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
    SCHEME_LOOP: OpenSubdivisionSchemeType = ...
    name: getset_descriptor
    values: dict

class OpenSubdivisionTriangleSubdivision:
    TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
    TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
    name: getset_descriptor
    values: dict

CAMERA: NodeType = ...
CREASE_CHAIKIN: OpenSubdivisionCreasingMethod = ...
CREASE_UNIFORM: OpenSubdivisionCreasingMethod = ...
FACESET: NodeType = ...
FVAR_LINEAR_ALL: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_BOUNDARIES: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_ONLY: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS1: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_CORNERS_PLUS2: OpenSubdivisionFaceVaryingInterpolation = ...
FVAR_LINEAR_NONE: OpenSubdivisionFaceVaryingInterpolation = ...
GEOMETRY_IMPORT_DONT_MERGE_CHILDREN: GeometryImportFlags = ...
GEOMETRY_IMPORT_DONT_SELECT_CHILDREN: GeometryImportFlags = ...
GROUP: NodeType = ...
MERGESELECTIONGROUP_DO_NOT_MERGE: MergeSelectionGroupWithSameNameType = ...
MERGESELECTIONGROUP_MERGE_SELECTIONGROUP_HAVING_SAME_NAME: MergeSelectionGroupWithSameNameType = ...
MERGETYPE_JUST_MERGE_NODES: MergeType = ...
MERGETYPE_SINGLE_MESH: MergeType = ...
POLYMESH: NodeType = ...
ROOT: NodeType = ...
SCHEME_BILINEAR: OpenSubdivisionSchemeType = ...
SCHEME_CATMARK: OpenSubdivisionSchemeType = ...
SCHEME_LOOP: OpenSubdivisionSchemeType = ...
SELECTION_GROUPS_CREATE_FROM_FACE_GROUPS: CreateSelectionSetOptions = ...
SELECTION_GROUPS_DONT_CREATE: CreateSelectionSetOptions = ...
SUBDIV: NodeType = ...
TRI_SUB_CATMARK: OpenSubdivisionTriangleSubdivision = ...
TRI_SUB_SMOOTH: OpenSubdivisionTriangleSubdivision = ...
VTX_BOUNDARY_EDGE_AND_CORNER: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_EDGE_ONLY: OpenSubdivisionBoundaryInterpolation = ...
VTX_BOUNDARY_NONE: OpenSubdivisionBoundaryInterpolation = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def addLocator(self, AddAsChildToSelectedObject = ...) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def current(self) -> Any: ...
def currentLocator(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def duplicateCurrentGeoEntity(self, DuplicateShaderNetwork = ...) -> Any: ...
def duplicateGeoEntity(self, Object, DuplicateShaderNetwork = ...) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def entityAdded(self, *args, **kwargs) -> Any: ...
def entityMadeCurrent(self, *args, **kwargs) -> Any: ...
def entityRemoved(self, *args, **kwargs) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def find(self, Name) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def geometryOperationList(self) -> Any: ...
def get(self, Name) -> Any: ...
def getAnimationTakes(self, Path) -> Any: ...
def getDefaultAnimationTake(self, Path) -> Any: ...
def getFileContents(self, Path) -> Any: ...
def getFileFrameRange(self, Path, Take = ...) -> Any: ...
def importFromArchive(self, DirPath) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def list(self) -> Any: ...
def listLocators(self) -> Any: ...
def load(self, Paths, Options = ..., ObjectsToLoad = ..., LoadAsChild = ...) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def names(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def recalculatePatchBounds(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def remove(self, Name) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCurrent(self, *args, **kwargs) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def supportedReadFormats(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
