from typing import Any

class ShaderCompileResult:
    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    name: getset_descriptor
    values: dict

def applyFilter(Filter) -> Any: ...
def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def clearError() -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createPostFilterCollection(Name) -> Any: ...
def createQuickApplyGLSL(Name, DefinitionsSnippet = ..., BodySnippet = ..., IconPath = ..., DisplayMetadata = ...) -> Any: ...
def currentPostFilterCollection() -> Any: ...
class currentPostFilterCollectionModified:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
def deletePostFilterCollection(Collection) -> Any: ...
def deregisterCustomCubemapFile(UUID) -> Any: ...
def deregisterCustomImagemapFile(UUID) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def findFilter(Name) -> Any: ...
def findPostFilterCollection(Name) -> Any: ...
def findQuickApplyFilter(Name) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isCurrentGLShaderProgramValid() -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isPostProcessingEnabled() -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent(*args, **kwargs) -> Any: ...
def platformInformation() -> Any: ...
class postFilterCollectionAdded:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def postFilterCollectionNames() -> Any: ...
class postFilterCollectionRemoved:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def postFilterCollections() -> Any: ...
class postProcessingEnabled:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerCustomAdjustmentLayerFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomBlendMode(DisplayName, FunctionName, BlendModeCode) -> Any: ...
def registerCustomCodeFile(UUID, FilePath) -> Any: ...
def registerCustomCubemapFile(UUID, FilePath, MinMipSize = ...) -> Any: ...
def registerCustomDiffuseShaderFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomHeaderFile(UUID, FilePath) -> Any: ...
def registerCustomImagemapFile(UUID, FilePath) -> Any: ...
def registerCustomLayeredShaderFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomNodeFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomNodeUpgrade(OldVersionUUID, NewVersionUUID, AttributeRemapping = ..., InputRemapping = ..., OutputRemapping = ...) -> Any: ...
def registerCustomProceduralLayerFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomSpecularShaderFromXMLFile(Name, FilePath) -> Any: ...
def registerCustomStandaloneShaderFromXMLFile(Name, FilePath) -> Any: ...
def registerUserData() -> Any: ...
def reloadXMLDefinitions() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def removeQuickApplyFilter(Filter) -> Any: ...
def runGLSLCode(GLSLCode, Destination, Source = ..., Mask = ..., BlendMode = ..., BlendAmount = ...) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
class setCurrentPostFilterCollection:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setPostFilterCollection(Collection) -> Any: ...
def setPostProcessingEnabled(Enabled) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
class shaderCompileComplete:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def upgradeExistingShadersAndLayers() -> Any: ...
