from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShaderCompileResult:
    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    name: getset_descriptor
    values: dict

SHADER_COMPILE_FAILED: ShaderCompileResult = ...
SHADER_LINK_FAILED: ShaderCompileResult = ...
SHADER_LINK_SUCCESS: ShaderCompileResult = ...
SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def deregisterCustomCubemapFile(UUID) -> Any: ...
@staticmethod
def deregisterCustomImagemapFile(UUID) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomAdjustmentLayerFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomBlendMode(DisplayName, FunctionName, BlendModeCode) -> Any: ...
@staticmethod
def registerCustomCodeFile(UUID, FilePath) -> Any: ...
@staticmethod
def registerCustomCubemapFile(UUID, FilePath, MinMipSize = ...) -> Any: ...
@staticmethod
def registerCustomDiffuseShaderFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomHeaderFile(UUID, FilePath) -> Any: ...
@staticmethod
def registerCustomImagemapFile(UUID, FilePath) -> Any: ...
@staticmethod
def registerCustomLayeredShaderFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomNodeFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomNodeUpgrade(OldVersionUUID, NewVersionUUID, AttributeRemapping = ..., InputRemapping = ..., OutputRemapping = ...) -> Any: ...
@staticmethod
def registerCustomProceduralLayerFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomSpecularShaderFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerCustomStandaloneShaderFromXMLFile(Name, FilePath) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def applyFilter(self, Filter) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clearError(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createPostFilterCollection(self, Name) -> Any: ...
def createQuickApplyGLSL(self, Name, DefinitionsSnippet = ..., BodySnippet = ..., IconPath = ..., DisplayMetadata = ...) -> Any: ...
def currentPostFilterCollection(self) -> Any: ...
def currentPostFilterCollectionModified(self, *args, **kwargs) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def deletePostFilterCollection(self, Collection) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findFilter(self, Name) -> Any: ...
def findPostFilterCollection(self, Name) -> Any: ...
def findQuickApplyFilter(self, Name) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isCurrentGLShaderProgramValid(self) -> Any: ...
def isNull(self) -> Any: ...
def isPostProcessingEnabled(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def platformInformation(self) -> Any: ...
def postFilterCollectionAdded(self, *args, **kwargs) -> Any: ...
def postFilterCollectionNames(self) -> Any: ...
def postFilterCollectionRemoved(self, *args, **kwargs) -> Any: ...
def postFilterCollections(self) -> Any: ...
def postProcessingEnabled(self, *args, **kwargs) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def reloadXMLDefinitions(self) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeQuickApplyFilter(self, Filter) -> Any: ...
def runGLSLCode(self, GLSLCode, Destination, Source = ..., Mask = ..., BlendMode = ..., BlendAmount = ...) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCurrentPostFilterCollection(self, *args, **kwargs) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPostFilterCollection(self, Collection) -> Any: ...
def setPostProcessingEnabled(self, Enabled) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def shaderCompileComplete(self, *args, **kwargs) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def upgradeExistingShadersAndLayers(self) -> Any: ...
