from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShaderCompileResult:
    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    name: getset_descriptor
    values: dict

SHADER_COMPILE_FAILED: ShaderCompileResult = ...
SHADER_LINK_FAILED: ShaderCompileResult = ...
SHADER_LINK_SUCCESS: ShaderCompileResult = ...
SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
staticMetaObject: QMetaObject
SHADER_COMPILE_FAILED: ShaderCompileResult = ...
SHADER_LINK_FAILED: ShaderCompileResult = ...
SHADER_LINK_SUCCESS: ShaderCompileResult = ...
SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def deregisterCustomCubemapFile(UUID: str) -> Any: ...
@staticmethod
def deregisterCustomImagemapFile(UUID: str) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerCustomAdjustmentLayerFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomBlendMode(DisplayName: str, FunctionName: str, BlendModeCode: str) -> Any: ...
@staticmethod
def registerCustomCodeFile(UUID: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomCubemapFile(UUID: str, FilePath: str, MinMipSize: int = ...) -> Any: ...
@staticmethod
def registerCustomDiffuseShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomHeaderFile(UUID: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomImagemapFile(UUID: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomLayeredShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomNodeFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomNodeUpgrade(OldVersionUUID: str, NewVersionUUID: str, AttributeRemapping: typing.Dict = ..., InputRemapping: typing.Dict = ..., OutputRemapping: typing.Dict = ...) -> Any: ...
@staticmethod
def registerCustomProceduralLayerFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomSpecularShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerCustomStandaloneShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def applyFilter(Filter: mari.PostFilter) -> bool: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clearError() -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createPostFilterCollection(Name: str) -> mari.PostFilterCollection: ...
def createQuickApplyGLSL(Name: str, DefinitionsSnippet: str = ..., BodySnippet: str = ..., IconPath: str = ..., DisplayMetadata: bool = ...) -> mari.GLSLFilter: ...
def currentPostFilterCollection() -> mari.PostFilterCollection: ...
def currentPostFilterCollectionModified(*args, **kwargs) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def deletePostFilterCollection(Collection: mari.PostFilterCollection) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def findFilter(Name: str) -> mari.PostFilter: ...
def findPostFilterCollection(Name: str) -> mari.PostFilterCollection: ...
def findQuickApplyFilter(Name: str) -> mari.PostFilter: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isCurrentGLShaderProgramValid() -> bool: ...
def isNull() -> bool: ...
def isPostProcessingEnabled() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def platformInformation() -> typing.Any: ...
def postFilterCollectionAdded(*args, **kwargs) -> Any: ...
def postFilterCollectionNames() -> typing.List: ...
def postFilterCollectionRemoved(*args, **kwargs) -> Any: ...
def postFilterCollections() -> typing.List: ...
def postProcessingEnabled(*args, **kwargs) -> Any: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def reloadXMLDefinitions() -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeQuickApplyFilter(Filter: mari.PostFilter) -> Any: ...
def runGLSLCode(GLSLCode: str, Destination: mari.ImageSet, Source: typing.Optional = ..., Mask: typing.Optional = ..., BlendMode: str = ..., BlendAmount: float = ...) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setCurrentPostFilterCollection(*args, **kwargs) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPostFilterCollection(Collection: mari.PostFilterCollection) -> Any: ...
def setPostProcessingEnabled(Enabled: bool) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def shaderCompileComplete(*args, **kwargs) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def upgradeExistingShadersAndLayers() -> Any: ...
