from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class GLRender(API):
    class ShaderCompileResult:
        SHADER_COMPILE_FAILED: ShaderCompileResult = ...
        SHADER_LINK_FAILED: ShaderCompileResult = ...
        SHADER_LINK_SUCCESS: ShaderCompileResult = ...
        SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
        name: getset_descriptor
        values: dict

    SHADER_COMPILE_FAILED: ShaderCompileResult = ...
    SHADER_LINK_FAILED: ShaderCompileResult = ...
    SHADER_LINK_SUCCESS: ShaderCompileResult = ...
    SHADER_RELOAD_MACROS_FAILED: ShaderCompileResult = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def deregisterCustomCubemapFile(UUID: str) -> Any: ...
    @staticmethod
    def deregisterCustomImagemapFile(UUID: str) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerCustomAdjustmentLayerFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomBlendMode(DisplayName: str, FunctionName: str, BlendModeCode: str) -> Any: ...
    @staticmethod
    def registerCustomCodeFile(UUID: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomCubemapFile(UUID: str, FilePath: str, MinMipSize: int = ...) -> Any: ...
    @staticmethod
    def registerCustomDiffuseShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomHeaderFile(UUID: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomImagemapFile(UUID: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomLayeredShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomNodeFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomNodeUpgrade(OldVersionUUID: str, NewVersionUUID: str, AttributeRemapping: typing.Dict = ..., InputRemapping: typing.Dict = ..., OutputRemapping: typing.Dict = ...) -> Any: ...
    @staticmethod
    def registerCustomProceduralLayerFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomSpecularShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerCustomStandaloneShaderFromXMLFile(Name: str, FilePath: str) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def applyFilter(self, Filter: mari.PostFilter) -> bool: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clearError(self) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createPostFilterCollection(self, Name: str) -> mari.PostFilterCollection: ...
    def createQuickApplyGLSL(self, Name: str, DefinitionsSnippet: str = ..., BodySnippet: str = ..., IconPath: str = ..., DisplayMetadata: bool = ...) -> mari.GLSLFilter: ...
    def currentPostFilterCollection(self) -> mari.PostFilterCollection: ...
    def currentPostFilterCollectionModified(self, *args, **kwargs) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def deletePostFilterCollection(self, Collection: mari.PostFilterCollection) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def findFilter(self, Name: str) -> mari.PostFilter: ...
    def findPostFilterCollection(self, Name: str) -> mari.PostFilterCollection: ...
    def findQuickApplyFilter(self, Name: str) -> mari.PostFilter: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isCurrentGLShaderProgramValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isPostProcessingEnabled(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def platformInformation(self) -> typing.Any: ...
    def postFilterCollectionAdded(self, *args, **kwargs) -> Any: ...
    def postFilterCollectionNames(self) -> typing.List: ...
    def postFilterCollectionRemoved(self, *args, **kwargs) -> Any: ...
    def postFilterCollections(self) -> typing.List: ...
    def postProcessingEnabled(self, *args, **kwargs) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def reloadXMLDefinitions(self) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeQuickApplyFilter(self, Filter: mari.PostFilter) -> Any: ...
    def runGLSLCode(self, GLSLCode: str, Destination: mari.ImageSet, Source: typing.Optional = ..., Mask: typing.Optional = ..., BlendMode: str = ..., BlendAmount: float = ...) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCurrentPostFilterCollection(self, *args, **kwargs) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPostFilterCollection(self, Collection: mari.PostFilterCollection) -> Any: ...
    def setPostProcessingEnabled(self, Enabled: bool) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def shaderCompileComplete(self, *args, **kwargs) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def upgradeExistingShadersAndLayers(self) -> Any: ...
