from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import PostFilter
from mari import PropertySource

class Clamp:
    CLAMP_REPEAT: Clamp = ...
    CLAMP_TO_EDGE: Clamp = ...
    name: getset_descriptor
    values: dict

class Filter:
    FILTER_LINEAR: Filter = ...
    FILTER_MIPMAP_LINEAR: Filter = ...
    FILTER_NEAREST: Filter = ...
    name: getset_descriptor
    values: dict

class Format:
    FORMAT_L: Format = ...
    FORMAT_R: Format = ...
    FORMAT_RGB: Format = ...
    FORMAT_RGBA: Format = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class PostFilterFlags:
    POSTFILTER_ENABLED: PostFilterFlags = ...
    POSTFILTER_REMOVABLE: PostFilterFlags = ...
    name: getset_descriptor
    values: dict

CLAMP_REPEAT: Clamp = ...
CLAMP_TO_EDGE: Clamp = ...
FILTER_LINEAR: Filter = ...
FILTER_MIPMAP_LINEAR: Filter = ...
FILTER_NEAREST: Filter = ...
FORMAT_L: Format = ...
FORMAT_R: Format = ...
FORMAT_RGB: Format = ...
FORMAT_RGBA: Format = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
POSTFILTER_ENABLED: PostFilterFlags = ...
POSTFILTER_REMOVABLE: PostFilterFlags = ...
staticMetaObject: QMetaObject
CLAMP_REPEAT: Clamp = ...
CLAMP_TO_EDGE: Clamp = ...
FILTER_LINEAR: Filter = ...
FILTER_MIPMAP_LINEAR: Filter = ...
FILTER_NEAREST: Filter = ...
FORMAT_L: Format = ...
FORMAT_R: Format = ...
FORMAT_RGB: Format = ...
FORMAT_RGBA: Format = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
POSTFILTER_ENABLED: PostFilterFlags = ...
POSTFILTER_REMOVABLE: PostFilterFlags = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def bodySnippet() -> str: ...
def canResetProperty(PropertyName: str) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def definitionsSnippet() -> str: ...
def deleteLater() -> Any: ...
def deleteTexture(SamplerName: str) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def enabled() -> bool: ...
def enabledChanged(*args, **kwargs) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def flags() -> int: ...
def flagsChanged(*args, **kwargs) -> Any: ...
def getProperty(PropertyName: str) -> typing.Any: ...
def hasMetadata(Name: str) -> bool: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def propertiesList() -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def propertyDisplayName(PropertyName: str) -> str: ...
def propertyEnumValues(PropertyName: str) -> typing.List: ...
def propertyHasMinMax(PropertyName: str) -> bool: ...
def propertyIsEnum(PropertyName: str) -> bool: ...
def propertyIsReadOnly(PropertyName: str) -> bool: ...
def propertyMinMax(PropertyName: str) -> typing.List: ...
def propertyTooltip(PropertyName: str) -> str: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def resetProperty(PropertyName: str) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setBodySnippet(BodySnippet: str) -> Any: ...
def setDefinitionsSnippet(DefinitionsSnippet: str) -> Any: ...
def setEnabled(Enabled: bool) -> Any: ...
def setFlags(Flags: int) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(arg__1: bytes, arg__2: typing.Any) -> Any: ...
def setTexture1D(SamplerName: str, Width: int, DataFormat, Data: typing.Sequence, MinFilter = ..., MagFilter = ..., ClampS = ..., ClampT = ...) -> Any: ...
def setTexture2D(SamplerName: str, Width: int, Height: int, DataFormat, Data: typing.Sequence, MinFilter = ..., MagFilter = ..., ClampS = ..., ClampT = ...) -> Any: ...
def setTexture3D(SamplerName: str, Width: int, Height: int, Depth: int, DataFormat, Data: typing.Sequence, MinFilter = ..., MagFilter = ..., ClampS = ..., ClampT = ..., ClampR = ...) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def updateTexture1D(SamplerName: str, Data: typing.Sequence) -> Any: ...
def updateTexture2D(SamplerName: str, Data: typing.Sequence) -> Any: ...
def updateTexture3D(SamplerName: str, Data: typing.Sequence) -> Any: ...
def uuid() -> str: ...
