from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ImageAlphaProcessing:
    IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    name: getset_descriptor
    values: dict

class ImageColorSpaceConversionType:
    IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
    IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def add(self, ImageToAdd, Name = ...) -> Any: ...
def addCategory(self, CategoryName) -> Any: ...
def addImage(self, ImageToAdd, Name = ...) -> Any: ...
def addImageGroup(self, GroupName) -> Any: ...
def addToImageGroup(self, Images, GroupName) -> Any: ...
def backgroundOpen(self, Path, Config = ..., AlphaProcessing = ..., Name = ..., Category = ...) -> Any: ...
def beginImageLoading(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def categories(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clearTraces(self, PathOrHash) -> Any: ...
def collapseImageGroup(self, GroupName) -> Any: ...
def compressionList(self, Extension) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def currentCategory(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def defaultCompressionMethod(self, Extension) -> Any: ...
def defaultImageFormat(self, BitDepth) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def endImageLoading(self, *args, **kwargs) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def expandImageGroup(self, GroupName) -> Any: ...
def expandedImageGroupList(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def generateCrossMask(self, Width, Height, CrossWidthPercentage, CrossHeightPercentage) -> Any: ...
def getImage(self, Hash) -> Any: ...
def handleProtocol(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def imageGroupList(self) -> Any: ...
def imageLoaded(self, *args, **kwargs) -> Any: ...
def imageOperationList(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def list(self, GroupName = ...) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def open(self, Path, Config = ..., AlphaProcessing = ..., Name = ...) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def protocolSupported(self, Protocol) -> Any: ...
def receivers(self, signal) -> Any: ...
def registerContextAction(self, MenuAction, Category = ..., IconPath = ...) -> Any: ...
def registerProtocolHandler(self, Protocol, Handler) -> Any: ...
def remove(self, ImageToRemove) -> Any: ...
def removeCategory(self, CategoryName) -> Any: ...
def removeContextAction(self, MenuAction, Category = ...) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeFromImageGroup(self, Images) -> Any: ...
def removeImageGroup(self, GroupName, RemoveImages = ...) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def saveImages(self, Images, Path) -> Any: ...
def selectCategory(self, CategoryName) -> Any: ...
def selected(self, GroupName = ...) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setDefaultImageFormat(self, Format, BitDepth) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setTraceEnabled(self, PathOrHash, Enabled = ...) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def supportedReadFormats(self) -> Any: ...
def supportedTextureSizeList(self) -> Any: ...
def supportedWriteFormats(self, InternalFormat = ...) -> Any: ...
def swapQuadrants(self, SourceImage, SwapBack) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def traces(self, PathOrHash) -> Any: ...
def unregisterProtocolHandler(self, Protocol) -> Any: ...
def uuid(self) -> Any: ...
