from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class Depth:
    DEPTH_BYTE: Depth = ...
    DEPTH_FLOAT: Depth = ...
    DEPTH_HALF: Depth = ...
    name: getset_descriptor
    values: dict

class FileSpace:
    FILESPACE_NORMAL: FileSpace = ...
    FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
    FILESPACE_VECTOR: FileSpace = ...
    FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
    name: getset_descriptor
    values: dict

class Format:
    FORMAT_R: Format = ...
    FORMAT_RG: Format = ...
    FORMAT_RGB: Format = ...
    FORMAT_RGBA: Format = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SaveOptions:
    BACKGROUND_EXPORT: SaveOptions = ...
    DEFAULT_OPTIONS: SaveOptions = ...
    DISABLE_SMALL_UNIFORMS: SaveOptions = ...
    ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
    EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
    REMOVE_ALPHA: SaveOptions = ...
    name: getset_descriptor
    values: dict

BACKGROUND_EXPORT: SaveOptions = ...
DEFAULT_OPTIONS: SaveOptions = ...
DEPTH_BYTE: Depth = ...
DEPTH_FLOAT: Depth = ...
DEPTH_HALF: Depth = ...
DISABLE_SMALL_UNIFORMS: SaveOptions = ...
ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
FILESPACE_NORMAL: FileSpace = ...
FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
FILESPACE_VECTOR: FileSpace = ...
FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
FORMAT_R: Format = ...
FORMAT_RG: Format = ...
FORMAT_RGB: Format = ...
FORMAT_RGBA: Format = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
REMOVE_ALPHA: SaveOptions = ...
staticMetaObject: QMetaObject
BACKGROUND_EXPORT: SaveOptions = ...
DEFAULT_OPTIONS: SaveOptions = ...
DEPTH_BYTE: Depth = ...
DEPTH_FLOAT: Depth = ...
DEPTH_HALF: Depth = ...
DISABLE_SMALL_UNIFORMS: SaveOptions = ...
ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
FILESPACE_NORMAL: FileSpace = ...
FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
FILESPACE_VECTOR: FileSpace = ...
FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
FORMAT_R: Format = ...
FORMAT_RG: Format = ...
FORMAT_RGB: Format = ...
FORMAT_RGBA: Format = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
REMOVE_ALPHA: SaveOptions = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def depthAsInternalFormat(Depth) -> int: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def aboutToClose(*args, **kwargs) -> Any: ...
def aboutToExport(*args, **kwargs) -> Any: ...
def aboutToImport(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def category() -> str: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def close() -> Any: ...
def colorspaceConfig() -> mari.ColorspaceConfig: ...
def colorspaceConfigChanged(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def convertColorspaceTo(OutputColorspace: str, InputColorspace: str = ..., Config: str = ...) -> Any: ...
def convertDepth(Depth) -> Any: ...
def copyFrom(SourceImage: mari.Image) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def depth() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exported(*args, **kwargs) -> Any: ...
def filePath() -> str: ...
def fileSpace() -> Any: ...
def fill(FillColor: mari.Color) -> Any: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def hasMetadata(Name: str) -> bool: ...
def hash() -> str: ...
def height(MipMapLevel: int = ...) -> int: ...
def imageGroup() -> str: ...
def imported(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isUniform() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lastExportPath() -> str: ...
def lastExportTime() -> PySide2.QtCore.QDateTime: ...
def lastImportPath() -> str: ...
def lastImportTime() -> PySide2.QtCore.QDateTime: ...
def makeThumbnail() -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def mipMapCount() -> int: ...
def mostRelevantPath() -> str: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def resize(NewSize: PySide2.QtCore.QSize) -> Any: ...
def saveAs(FileName: str, Options: typing.Any = ..., SaveOpts: int = ...) -> Any: ...
def selected() -> bool: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setCategory(Name: str) -> Any: ...
def setColorspaceConfig(Config: mari.ColorspaceConfig) -> Any: ...
def setFileSpace(FileSpace) -> Any: ...
def setImageGroup(GroupName: str) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setName(Name: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setSelected(Select: bool) -> Any: ...
def setUniformColor(pUniformColor: mari.Color) -> Any: ...
def signalsBlocked() -> bool: ...
def size(MipMapLevel: int = ...) -> typing.List: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def thumbnail() -> PySide2.QtGui.QImage: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def transform(Collection: mari.PostFilterCollection) -> bool: ...
def uniformColor() -> mari.Color: ...
def uuid() -> str: ...
def width(MipMapLevel: int = ...) -> int: ...
