from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class Depth:
    DEPTH_BYTE: Depth = ...
    DEPTH_FLOAT: Depth = ...
    DEPTH_HALF: Depth = ...
    name: getset_descriptor
    values: dict

class FileSpace:
    FILESPACE_NORMAL: FileSpace = ...
    FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
    FILESPACE_VECTOR: FileSpace = ...
    FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
    name: getset_descriptor
    values: dict

class Format:
    FORMAT_R: Format = ...
    FORMAT_RG: Format = ...
    FORMAT_RGB: Format = ...
    FORMAT_RGBA: Format = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SaveOptions:
    BACKGROUND_EXPORT: SaveOptions = ...
    DEFAULT_OPTIONS: SaveOptions = ...
    DISABLE_SMALL_UNIFORMS: SaveOptions = ...
    ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
    EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
    REMOVE_ALPHA: SaveOptions = ...
    name: getset_descriptor
    values: dict

BACKGROUND_EXPORT: SaveOptions = ...
DEFAULT_OPTIONS: SaveOptions = ...
DEPTH_BYTE: Depth = ...
DEPTH_FLOAT: Depth = ...
DEPTH_HALF: Depth = ...
DISABLE_SMALL_UNIFORMS: SaveOptions = ...
ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
FILESPACE_NORMAL: FileSpace = ...
FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
FILESPACE_VECTOR: FileSpace = ...
FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
FORMAT_R: Format = ...
FORMAT_RG: Format = ...
FORMAT_RGB: Format = ...
FORMAT_RGBA: Format = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
REMOVE_ALPHA: SaveOptions = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def depthAsInternalFormat(Depth) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def aboutToClose(self, *args, **kwargs) -> Any: ...
def aboutToExport(self, *args, **kwargs) -> Any: ...
def aboutToImport(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def category(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def close(self) -> Any: ...
def colorspaceConfig(self) -> Any: ...
def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def convertColorspaceTo(self, OutputColorspace, InputColorspace = ..., Config = ...) -> Any: ...
def convertDepth(self, Depth) -> Any: ...
def copyFrom(self, SourceImage) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depth(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exported(self, *args, **kwargs) -> Any: ...
def filePath(self) -> Any: ...
def fileSpace(self) -> Any: ...
def fill(self, FillColor) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hash(self) -> Any: ...
def height(self, MipMapLevel = ...) -> Any: ...
def imageGroup(self) -> Any: ...
def imported(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isUniform(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lastExportPath(self) -> Any: ...
def lastExportTime(self) -> Any: ...
def lastImportPath(self) -> Any: ...
def lastImportTime(self) -> Any: ...
def makeThumbnail(self) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def mipMapCount(self) -> Any: ...
def mostRelevantPath(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def resize(self, NewSize) -> Any: ...
def saveAs(self, FileName, Options = ..., SaveOpts = ...) -> Any: ...
def selected(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCategory(self, Name) -> Any: ...
def setColorspaceConfig(self, Config) -> Any: ...
def setFileSpace(self, FileSpace) -> Any: ...
def setImageGroup(self, GroupName) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, Name) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSelected(self, Select) -> Any: ...
def setUniformColor(self, pUniformColor) -> Any: ...
def signalsBlocked(self) -> Any: ...
def size(self, MipMapLevel = ...) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def thumbnail(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def transform(self, Collection) -> Any: ...
def uniformColor(self) -> Any: ...
def uuid(self) -> Any: ...
def width(self, MipMapLevel = ...) -> Any: ...
