from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class Image(Metadata):
    class Depth:
        DEPTH_BYTE: Depth = ...
        DEPTH_FLOAT: Depth = ...
        DEPTH_HALF: Depth = ...
        name: getset_descriptor
        values: dict

    class FileSpace:
        FILESPACE_NORMAL: FileSpace = ...
        FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
        FILESPACE_VECTOR: FileSpace = ...
        FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
        name: getset_descriptor
        values: dict

    class Format:
        FORMAT_R: Format = ...
        FORMAT_RG: Format = ...
        FORMAT_RGB: Format = ...
        FORMAT_RGBA: Format = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class SaveOptions:
        BACKGROUND_EXPORT: SaveOptions = ...
        DEFAULT_OPTIONS: SaveOptions = ...
        DISABLE_SMALL_UNIFORMS: SaveOptions = ...
        ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
        EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
        REMOVE_ALPHA: SaveOptions = ...
        name: getset_descriptor
        values: dict

    BACKGROUND_EXPORT: SaveOptions = ...
    DEFAULT_OPTIONS: SaveOptions = ...
    DEPTH_BYTE: Depth = ...
    DEPTH_FLOAT: Depth = ...
    DEPTH_HALF: Depth = ...
    DISABLE_SMALL_UNIFORMS: SaveOptions = ...
    ENABLE_FULL_PATCH_BLEED: SaveOptions = ...
    EXPORT_UV_MASK_IN_ALPHA: SaveOptions = ...
    FILESPACE_NORMAL: FileSpace = ...
    FILESPACE_NORMAL_Y_FLIP: FileSpace = ...
    FILESPACE_VECTOR: FileSpace = ...
    FILESPACE_VECTOR_Y_FLIP: FileSpace = ...
    FORMAT_R: Format = ...
    FORMAT_RG: Format = ...
    FORMAT_RGB: Format = ...
    FORMAT_RGBA: Format = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    REMOVE_ALPHA: SaveOptions = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def depthAsInternalFormat(Depth) -> int: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def aboutToClose(self, *args, **kwargs) -> Any: ...
    def aboutToExport(self, *args, **kwargs) -> Any: ...
    def aboutToImport(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def category(self) -> str: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def close(self) -> Any: ...
    def colorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def convertColorspaceTo(self, OutputColorspace: str, InputColorspace: str = ..., Config: str = ...) -> Any: ...
    def convertDepth(self, Depth) -> Any: ...
    def copyFrom(self, SourceImage: mari.Image) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depth(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exported(self, *args, **kwargs) -> Any: ...
    def filePath(self) -> str: ...
    def fileSpace(self) -> Any: ...
    def fill(self, FillColor: mari.Color) -> Any: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def hash(self) -> str: ...
    def height(self, MipMapLevel: int = ...) -> int: ...
    def imageGroup(self) -> str: ...
    def imported(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isUniform(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lastExportPath(self) -> str: ...
    def lastExportTime(self) -> PySide2.QtCore.QDateTime: ...
    def lastImportPath(self) -> str: ...
    def lastImportTime(self) -> PySide2.QtCore.QDateTime: ...
    def makeThumbnail(self) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def mipMapCount(self) -> int: ...
    def mostRelevantPath(self) -> str: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def resize(self, NewSize: PySide2.QtCore.QSize) -> Any: ...
    def saveAs(self, FileName: str, Options: typing.Any = ..., SaveOpts: int = ...) -> Any: ...
    def selected(self) -> bool: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCategory(self, Name: str) -> Any: ...
    def setColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setFileSpace(self, FileSpace) -> Any: ...
    def setImageGroup(self, GroupName: str) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, Name: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSelected(self, Select: bool) -> Any: ...
    def setUniformColor(self, pUniformColor: mari.Color) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def size(self, MipMapLevel: int = ...) -> typing.List: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def thumbnail(self) -> PySide2.QtGui.QImage: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def transform(self, Collection: mari.PostFilterCollection) -> bool: ...
    def uniformColor(self) -> mari.Color: ...
    def uuid(self) -> str: ...
    def width(self, MipMapLevel: int = ...) -> int: ...
