from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ImageAlphaProcessing:
    IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    name: getset_descriptor
    values: dict

class ImageColorSpaceConversionType:
    IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
    IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def add(ImageToAdd: mari.Image, Name: str = ...) -> Any: ...
def addCategory(CategoryName: str) -> Any: ...
def addImage(ImageToAdd: PySide2.QtGui.QImage, Name: str = ...) -> mari.Image: ...
def addImageGroup(GroupName: str) -> Any: ...
def addToImageGroup(Images: typing.Sequence, GroupName: str) -> Any: ...
def backgroundOpen(Path: str, Config: typing.Optional = ..., AlphaProcessing = ..., Name: str = ..., Category: str = ...) -> Any: ...
def beginImageLoading(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def categories() -> typing.List: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clearTraces(PathOrHash: str) -> Any: ...
def collapseImageGroup(GroupName: str) -> Any: ...
def compressionList(Extension: str) -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def currentCategory() -> str: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def defaultCompressionMethod(Extension: str) -> str: ...
def defaultImageFormat(BitDepth) -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def endImageLoading(*args, **kwargs) -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def expandImageGroup(GroupName: str) -> Any: ...
def expandedImageGroupList() -> typing.List: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def generateCrossMask(Width: int, Height: int, CrossWidthPercentage: float, CrossHeightPercentage: float) -> mari.Image: ...
def getImage(Hash: str) -> mari.Image: ...
def handleProtocol(*args, **kwargs) -> Any: ...
def hasMetadata(Name: str) -> bool: ...
def imageGroupList() -> typing.List: ...
def imageLoaded(*args, **kwargs) -> Any: ...
def imageOperationList() -> typing.List: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def list(GroupName: str = ...) -> typing.List: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def open(Path: str, Config: typing.Optional = ..., AlphaProcessing = ..., Name: str = ...) -> typing.List: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def protocolSupported(Protocol: str) -> bool: ...
def receivers(signal: bytes) -> int: ...
def registerContextAction(MenuAction: PySide2.QtWidgets.QAction, Category: str = ..., IconPath: str = ...) -> Any: ...
def registerProtocolHandler(Protocol: str, Handler: mari.ImageProtocolHandler) -> bool: ...
def remove(ImageToRemove: mari.Image) -> Any: ...
def removeCategory(CategoryName: str) -> bool: ...
def removeContextAction(MenuAction: PySide2.QtWidgets.QAction, Category: str = ...) -> bool: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeFromImageGroup(Images: typing.Sequence) -> Any: ...
def removeImageGroup(GroupName: str, RemoveImages: bool = ...) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def saveImages(Images: typing.Sequence, Path: str) -> bool: ...
def selectCategory(CategoryName: str) -> bool: ...
def selected(GroupName: str = ...) -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setDefaultImageFormat(Format: str, BitDepth) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setTraceEnabled(PathOrHash: str, Enabled: bool = ...) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def supportedReadFormats() -> typing.List: ...
def supportedTextureSizeList() -> typing.List: ...
def supportedWriteFormats(InternalFormat: int = ...) -> typing.List: ...
def swapQuadrants(SourceImage: mari.Image, SwapBack: bool) -> mari.Image: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def traces(PathOrHash: str) -> typing.List: ...
def unregisterProtocolHandler(Protocol: str) -> Any: ...
def uuid() -> str: ...
