from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Lockable
from mari import Metadata
from mari import Snapshotable

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class ScaleChoice:
    SCALE_THE_IMAGE: ScaleChoice = ...
    SCALE_THE_PATCH: ScaleChoice = ...
    name: getset_descriptor
    values: dict

class Size:
    SIZE_1024: Size = ...
    SIZE_16384: Size = ...
    SIZE_2048: Size = ...
    SIZE_256: Size = ...
    SIZE_32768: Size = ...
    SIZE_4096: Size = ...
    SIZE_512: Size = ...
    SIZE_8192: Size = ...
    SIZE_DOUBLE: Size = ...
    SIZE_HALF: Size = ...
    SIZE_NULL: Size = ...
    name: getset_descriptor
    values: dict

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
SCALE_THE_IMAGE: ScaleChoice = ...
SCALE_THE_PATCH: ScaleChoice = ...
SIZE_1024: Size = ...
SIZE_16384: Size = ...
SIZE_2048: Size = ...
SIZE_256: Size = ...
SIZE_32768: Size = ...
SIZE_4096: Size = ...
SIZE_512: Size = ...
SIZE_8192: Size = ...
SIZE_DOUBLE: Size = ...
SIZE_HALF: Size = ...
SIZE_NULL: Size = ...
staticMetaObject: QMetaObject
@staticmethod
def calculateNewSize(CurrentSize, NewSize) -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def getImportTemplateForEntity(TargetEntity, Title = ..., ImportAllText = ..., HideScaleOptions = ..., HideAlphaOptions = ...) -> Any: ...
@staticmethod
def internalScaleChoiceFromAPI(ScaleOption) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def sizeFromQSize(Size) -> Any: ...
def addKeyFrame(self, FrameNumber) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorspaceConfig(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def convertColorspaceTo(self, OutputColorspace, InputColorspace = ..., Config = ...) -> Any: ...
def createSnapshot(self, Name, ID = ...) -> Any: ...
def customEvent(self, event) -> Any: ...
def defaultKeyFrame(self) -> Any: ...
def deleteLater(self) -> Any: ...
def deleteSnapshot(self, ShotToDelete) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportImages(self, PathAndTemplate, Options = ..., FileOptions = ...) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findSnapshotWithID(self, ID) -> Any: ...
def frameCount(self) -> Any: ...
def frames(self) -> Any: ...
def getImportTemplate(self, Title = ..., ImportAllText = ..., ImportSelectedText = ..., HideScaleOptions = ..., HideAlphaOptions = ...) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hide(self) -> Any: ...
def image(self, UVIndex, Frame = ...) -> Any: ...
def imageCount(self) -> Any: ...
def imageList(self, Frame = ...) -> Any: ...
def importImages(self, ImagePaths, ScaleOption, UVIndexList = ..., RemoveAlpha = ..., SourceColorConfig = ...) -> Any: ...
def importImagesFromDict(self, ImagePaths, ScaleOption, RemoveAlpha = ..., SourceColorConfig = ...) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isAnimated(self) -> Any: ...
def isLocked(self) -> Any: ...
def isNull(self) -> Any: ...
def isPtex(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isVisible(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lock(self) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeKeyFrame(self, FrameNumber) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def resize(self, NewSize, UVIndexList = ...) -> Any: ...
def revertToSnapshot(self, OldSnapshot) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setColorspaceConfig(self, Config) -> Any: ...
def setLocked(self, Locked) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, NewName) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setVisibility(self, Visible) -> Any: ...
def show(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def snapshotAdded(self, *args, **kwargs) -> Any: ...
def snapshotList(self) -> Any: ...
def snapshotRemoved(self, *args, **kwargs) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def supportedWriteFormats(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def unlock(self) -> Any: ...
def uuid(self) -> Any: ...
def uvImageList(self, Frame = ...) -> Any: ...
def uvIndex(self, UvImage) -> Any: ...
def uvIndices(self) -> Any: ...
def visibilityChanged(self, *args, **kwargs) -> Any: ...
