from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ImageManager(Metadata):
    class ImageAlphaProcessing:
        IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
        IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
        name: getset_descriptor
        values: dict

    class ImageColorSpaceConversionType:
        IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
        IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    IMAGE_COLOR_CONVERSION_LINEAR_TO_SRGB: ImageColorSpaceConversionType = ...
    IMAGE_COLOR_CONVERSION_NONE: ImageColorSpaceConversionType = ...
    IMAGE_NO_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    IMAGE_PRE_MULTIPLY_ALPHA: ImageAlphaProcessing = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def add(self, ImageToAdd: mari.Image, Name: str = ...) -> Any: ...
    def addCategory(self, CategoryName: str) -> Any: ...
    def addImage(self, ImageToAdd: PySide2.QtGui.QImage, Name: str = ...) -> mari.Image: ...
    def addImageGroup(self, GroupName: str) -> Any: ...
    def addToImageGroup(self, Images: typing.Sequence, GroupName: str) -> Any: ...
    def backgroundOpen(self, Path: str, Config: typing.Optional = ..., AlphaProcessing = ..., Name: str = ..., Category: str = ...) -> Any: ...
    def beginImageLoading(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def categories(self) -> typing.List: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clearTraces(self, PathOrHash: str) -> Any: ...
    def collapseImageGroup(self, GroupName: str) -> Any: ...
    def compressionList(self, Extension: str) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def currentCategory(self) -> str: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def defaultCompressionMethod(self, Extension: str) -> str: ...
    def defaultImageFormat(self, BitDepth) -> str: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def endImageLoading(self, *args, **kwargs) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def expandImageGroup(self, GroupName: str) -> Any: ...
    def expandedImageGroupList(self) -> typing.List: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def generateCrossMask(self, Width: int, Height: int, CrossWidthPercentage: float, CrossHeightPercentage: float) -> mari.Image: ...
    def getImage(self, Hash: str) -> mari.Image: ...
    def handleProtocol(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def imageGroupList(self) -> typing.List: ...
    def imageLoaded(self, *args, **kwargs) -> Any: ...
    def imageOperationList(self) -> typing.List: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def list(self, GroupName: str = ...) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def open(self, Path: str, Config: typing.Optional = ..., AlphaProcessing = ..., Name: str = ...) -> typing.List: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def protocolSupported(self, Protocol: str) -> bool: ...
    def receivers(self, signal: bytes) -> int: ...
    def registerContextAction(self, MenuAction: PySide2.QtWidgets.QAction, Category: str = ..., IconPath: str = ...) -> Any: ...
    def registerProtocolHandler(self, Protocol: str, Handler: mari.ImageProtocolHandler) -> bool: ...
    def remove(self, ImageToRemove: mari.Image) -> Any: ...
    def removeCategory(self, CategoryName: str) -> bool: ...
    def removeContextAction(self, MenuAction: PySide2.QtWidgets.QAction, Category: str = ...) -> bool: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeFromImageGroup(self, Images: typing.Sequence) -> Any: ...
    def removeImageGroup(self, GroupName: str, RemoveImages: bool = ...) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def saveImages(self, Images: typing.Sequence, Path: str) -> bool: ...
    def selectCategory(self, CategoryName: str) -> bool: ...
    def selected(self, GroupName: str = ...) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setDefaultImageFormat(self, Format: str, BitDepth) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setTraceEnabled(self, PathOrHash: str, Enabled: bool = ...) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def supportedReadFormats(self) -> typing.List: ...
    def supportedTextureSizeList(self) -> typing.List: ...
    def supportedWriteFormats(self, InternalFormat: int = ...) -> typing.List: ...
    def swapQuadrants(self, SourceImage: mari.Image, SwapBack: bool) -> mari.Image: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def traces(self, PathOrHash: str) -> typing.List: ...
    def unregisterProtocolHandler(self, Protocol: str) -> Any: ...
    def uuid(self) -> str: ...
