from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import SliderBase
from mari import WidgetBase

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def addToLayout(Layout: PySide2.QtWidgets.QLayout) -> Any: ...
def blockSignals(Block: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disable() -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def enable() -> Any: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def hide() -> Any: ...
def hideSlider() -> Any: ...
def hideValueEdit() -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isEnabled() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isVisible() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def logarithmic() -> bool: ...
def maximumHeight() -> int: ...
def maximumWidth() -> int: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def minimumHeight() -> int: ...
def minimumWidth() -> int: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def precision() -> int: ...
def property(name: bytes) -> typing.Any: ...
def range(Min: float, Max: float) -> Any: ...
def rangeMax() -> float: ...
def rangeMin() -> float: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setEnabled(Enable: bool) -> Any: ...
def setLogarithmic(IsLogarithmic: bool) -> Any: ...
def setMaximumHeight(Height: int) -> Any: ...
def setMaximumWidth(Width: int) -> Any: ...
def setMinimumHeight(Height: int) -> Any: ...
def setMinimumWidth(Width: int) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPrecision(NumDecimalPlaces: int) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setRange(Min: float, Max: float) -> Any: ...
def setStatusTip(StatusTip: str) -> Any: ...
def setStepSize(StepSize: float) -> Any: ...
def setToolTip(ToolTip: str) -> Any: ...
def setValue(Value: int) -> Any: ...
def setVisible(Visible: bool) -> Any: ...
def show() -> Any: ...
def showSlider() -> Any: ...
def showValueEdit() -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def statusTip() -> str: ...
def stepSize() -> float: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def toolTip() -> str: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def value() -> int: ...
def valueChanged(*args, **kwargs) -> Any: ...
