from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ClearSelectionFlag:
    CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
    CLEAR_GROUPS: ClearSelectionFlag = ...
    CLEAR_MASK_STACKS: ClearSelectionFlag = ...
    DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
    name: getset_descriptor
    values: dict

class LayerCreateFlag:
    CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
    DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
    INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
    INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
    MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
    SELECT_NEW_LAYERS: LayerCreateFlag = ...
    name: getset_descriptor
    values: dict

class LayerImportOption:
    CREATE_NEW_LAYERS: LayerImportOption = ...
    OPTION_NOT_SPECIFIED: LayerImportOption = ...
    SKIP_LAYERS: LayerImportOption = ...
    UPDATE_LAYERS: LayerImportOption = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
CLEAR_GROUPS: ClearSelectionFlag = ...
CLEAR_MASK_STACKS: ClearSelectionFlag = ...
CREATE_NEW_LAYERS: LayerImportOption = ...
DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
OPTION_NOT_SPECIFIED: LayerImportOption = ...
SELECT_NEW_LAYERS: LayerCreateFlag = ...
SKIP_LAYERS: LayerImportOption = ...
UPDATE_LAYERS: LayerImportOption = ...
staticMetaObject: QMetaObject
CLEAR_ADJUSTMENT_STACKS: ClearSelectionFlag = ...
CLEAR_CURRENT_LAYER_SELECTION: LayerCreateFlag = ...
CLEAR_GROUPS: ClearSelectionFlag = ...
CLEAR_MASK_STACKS: ClearSelectionFlag = ...
CREATE_NEW_LAYERS: LayerImportOption = ...
DEFAULT_CLEAR_SELECTION_FLAGS: ClearSelectionFlag = ...
DEFAULT_LAYER_CREATE_FLAGS: LayerCreateFlag = ...
INSERT_NEW_LAYER_ABOVE_SELECTION: LayerCreateFlag = ...
INSERT_NEW_LAYER_BELOW_REF_LAYER: LayerCreateFlag = ...
MAKE_NEW_LAYER_CURRENT: LayerCreateFlag = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
OPTION_NOT_SPECIFIED: LayerImportOption = ...
SELECT_NEW_LAYERS: LayerCreateFlag = ...
SKIP_LAYERS: LayerImportOption = ...
UPDATE_LAYERS: LayerImportOption = ...
@staticmethod
def adjustmentLayerTypeList() -> typing.List: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def proceduralLayerTypeList() -> typing.List: ...
@staticmethod
def registerUserData() -> int: ...
@staticmethod
def transferLayers(UVRemap: typing.Any, SourceLayers: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationLayerStack: mari.LayerStack, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clearSelection(Flags: int = ...) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createAdjustmentLayer(LayerName: str, PrimaryAdjustmentKey: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createBakePointLayer(LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createChannelLayer(LayerName: str, TargetChannel: mari.Channel, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createCustomProceduralLayer(LayerName: str, FilePath: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createGraphLayer(LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createGroupLayer(LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createMaterialLayer(LayerName: str, FilePath: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createMultiChannelGroupLayer(LayerName: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createPaintableLayer(LayerName: str, RefLayer: typing.Optional = ..., FillColor: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createProceduralLayer(LayerName: str, ProceduralKey: str, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def createShaderLayer(LayerName: str, TargetShader: mari.Shader, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def duplicateLayers(LayersToDuplicate: typing.Sequence = ..., RefLayer: typing.Optional = ..., Flags: int = ...) -> typing.List: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportImages(PathAndTemplate: str, Options: int = ..., UVIndexList: typing.Sequence = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
def exportImagesFlattened(PathAndTemplate: str, Options: int = ..., UVIndexList: typing.Sequence = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
def exportSelectedPatches(PathAndTemplate: str, Options: int = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
def exportSelectedPatchesFlattened(PathAndTemplate: str, Options: int = ..., FileOptions: typing.Any = ..., OutputColorConfig: typing.Optional = ...) -> Any: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def findLayer(LayerName: str) -> mari.Layer: ...
def groupLayers(LayersToGroup: typing.Sequence = ..., RefLayer: typing.Optional = ..., LayerName: str = ..., Flags: int = ...) -> mari.Layer: ...
def hasMetadata(Name: str) -> bool: ...
def hash(UVIndex: int = ...) -> str: ...
def imageHash(UVIndex: int = ...) -> str: ...
def importImages(PathAndTemplate: str, ScaleOption = ..., MatchingLayersOption = ..., MismatchingLayersOption = ..., UVIndexList: typing.Sequence = ..., RemoveAlpha: bool = ..., SourceColorConfig: typing.Optional = ...) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def layer(LayerName: str) -> mari.Layer: ...
def layerList() -> typing.List: ...
def mergeLayers(LayersToMerge: typing.Sequence = ..., RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveLayer(LayerToMove: mari.Layer, RefLayer: typing.Optional = ...) -> Any: ...
def moveLayerBelow(LayerToMove: mari.Layer, RefLayer: typing.Optional = ...) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeLayers(LayersToRemove: typing.Sequence = ...) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def shareLayer(LayerToShare: mari.Layer, RefLayer: typing.Optional = ..., Flags: int = ...) -> mari.Layer: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def ungroupLayers(GroupLayersToUngroup: typing.Sequence = ...) -> Any: ...
def uuid() -> str: ...
