from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class LocatorList(API):
    class LocatorListType:
        LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
        LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
        LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
        LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
        LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
        name: getset_descriptor
        values: dict

    LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
    LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
    LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
    LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
    LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def currentLocator(self) -> mari.LocatorEntity: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def internalLocatorList(self) -> typing.Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def locatorType(self) -> Any: ...
    def locatorUUID(self) -> str: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def rotationVector(self) -> mari.VectorN: ...
    def scaleVector(self) -> mari.VectorN: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setCurrentLocator(self, Locator: mari.LocatorEntity) -> Any: ...
    def setCurrentProjector(self, ProjectorEntity: mari.Projector) -> Any: ...
    def setLocatorType(self, Type) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRotationVector(self, Vector: mari.VectorN) -> Any: ...
    def setScaleVector(self, Vector: mari.VectorN) -> Any: ...
    def setShowUI(self, Value: bool) -> Any: ...
    def setTranslationVector(self, Vector: mari.VectorN) -> Any: ...
    def setWorldSpace(self, Value: bool) -> Any: ...
    def showUI(self) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def translationVector(self) -> mari.VectorN: ...
    def worldSpace(self) -> bool: ...
