from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class LocatorListType:
    LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
    LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
    LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
    LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
    LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
    name: getset_descriptor
    values: dict

LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def currentLocator(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def internalLocatorList(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def locatorType(self) -> Any: ...
def locatorUUID(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def rotationVector(self) -> Any: ...
def scaleVector(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setCurrentLocator(self, Locator) -> Any: ...
def setCurrentProjector(self, ProjectorEntity) -> Any: ...
def setLocatorType(self, Type) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRotationVector(self, Vector) -> Any: ...
def setScaleVector(self, Vector) -> Any: ...
def setShowUI(self, Value) -> Any: ...
def setTranslationVector(self, Vector) -> Any: ...
def setWorldSpace(self, Value) -> Any: ...
def showUI(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def translationVector(self) -> Any: ...
def worldSpace(self) -> Any: ...
