from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class LocatorListType:
    LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
    LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
    LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
    LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
    LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
    name: getset_descriptor
    values: dict

LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
staticMetaObject: QMetaObject
LOCATOR_LIST_TYPE_MATRIX: LocatorListType = ...
LOCATOR_LIST_TYPE_PROJECTOR: LocatorListType = ...
LOCATOR_LIST_TYPE_ROTATION: LocatorListType = ...
LOCATOR_LIST_TYPE_SCALE: LocatorListType = ...
LOCATOR_LIST_TYPE_TRANSLATION: LocatorListType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def currentLocator() -> mari.LocatorEntity: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def internalLocatorList() -> typing.Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def locatorType() -> Any: ...
def locatorUUID() -> str: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def rotationVector() -> mari.VectorN: ...
def scaleVector() -> mari.VectorN: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setCurrentLocator(Locator: mari.LocatorEntity) -> Any: ...
def setCurrentProjector(ProjectorEntity: mari.Projector) -> Any: ...
def setLocatorType(Type) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setRotationVector(Vector: mari.VectorN) -> Any: ...
def setScaleVector(Vector: mari.VectorN) -> Any: ...
def setShowUI(Value: bool) -> Any: ...
def setTranslationVector(Vector: mari.VectorN) -> Any: ...
def setWorldSpace(Value: bool) -> Any: ...
def showUI() -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def translationVector() -> mari.VectorN: ...
def worldSpace() -> bool: ...
