from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Layer
from mari import Metadata
from mari import MultiChannelLayer

class MultiChannelMaterialLayer(MultiChannelLayer):
    class AdvancedBlendComponent:
        BLUE_BLEND: AdvancedBlendComponent = ...
        GREEN_BLEND: AdvancedBlendComponent = ...
        GREYSCALE_BLEND: AdvancedBlendComponent = ...
        LUMINANCE_BLEND: AdvancedBlendComponent = ...
        RED_BLEND: AdvancedBlendComponent = ...
        name: getset_descriptor
        values: dict

    class BlendMode:
        ADD: BlendMode = ...
        ADD_NORMAL_MAPS: BlendMode = ...
        BURN_HIGHLIGHTS: BlendMode = ...
        BURN_MIDRANGE: BlendMode = ...
        BURN_SHADOWS: BlendMode = ...
        CLEAR: BlendMode = ...
        COLOR: BlendMode = ...
        COLOR_BURN: BlendMode = ...
        COLOR_DODGE: BlendMode = ...
        CONTRAST: BlendMode = ...
        COPY: BlendMode = ...
        COPY_RGB: BlendMode = ...
        CUSTOM: BlendMode = ...
        DARKEN: BlendMode = ...
        DECONTRAST: BlendMode = ...
        DIFFERENCE: BlendMode = ...
        DIVIDE: BlendMode = ...
        DODGE_HIGHLIGHTS: BlendMode = ...
        DODGE_MIDRANGE: BlendMode = ...
        DODGE_SHADOWS: BlendMode = ...
        EXCLUSION: BlendMode = ...
        HARD_LIGHT: BlendMode = ...
        HARD_MIX: BlendMode = ...
        HUE: BlendMode = ...
        INVERSE_DIFFERENCE: BlendMode = ...
        INVERT: BlendMode = ...
        LIGHTEN: BlendMode = ...
        LUMINANCE: BlendMode = ...
        MIX: BlendMode = ...
        MIX_NORMAL_MAPS: BlendMode = ...
        MULTIPLY: BlendMode = ...
        NUDGE_FLOW_VECTORS: BlendMode = ...
        NUDGE_NORMAL_VECTORS: BlendMode = ...
        OVERLAY: BlendMode = ...
        PAINT_FLOW_VECTORS: BlendMode = ...
        PAINT_NORMAL_VECTORS: BlendMode = ...
        PIN_LIGHT: BlendMode = ...
        REORIENTED_NORMAL_MAPPING: BlendMode = ...
        SATURATION: BlendMode = ...
        SCALE_VECTORS: BlendMode = ...
        SCREEN: BlendMode = ...
        SOFT_LIGHT: BlendMode = ...
        SPONGE_DESATURATE: BlendMode = ...
        SUBTRACT: BlendMode = ...
        VIVID_LIGHT: BlendMode = ...
        name: getset_descriptor
        values: dict

    class BlendType:
        ADVANCED_BLEND: BlendType = ...
        BASIC_BLEND: BlendType = ...
        name: getset_descriptor
        values: dict

    class MaskType:
        FROM_ALPHA: MaskType = ...
        FROM_SELECTION_GROUP: MaskType = ...
        HIDE_ALL: MaskType = ...
        REVEAL_ALL: MaskType = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class SwizzleDestination:
        SWIZZLE_DST_ALPHA: SwizzleDestination = ...
        SWIZZLE_DST_BLUE: SwizzleDestination = ...
        SWIZZLE_DST_GREEN: SwizzleDestination = ...
        SWIZZLE_DST_RED: SwizzleDestination = ...
        name: getset_descriptor
        values: dict

    class SwizzleSource:
        SWIZZLE_SRC_ALPHA: SwizzleSource = ...
        SWIZZLE_SRC_BLUE: SwizzleSource = ...
        SWIZZLE_SRC_GREEN: SwizzleSource = ...
        SWIZZLE_SRC_ONE: SwizzleSource = ...
        SWIZZLE_SRC_RED: SwizzleSource = ...
        SWIZZLE_SRC_ZERO: SwizzleSource = ...
        name: getset_descriptor
        values: dict

    ADD: BlendMode = ...
    ADD_NORMAL_MAPS: BlendMode = ...
    ADVANCED_BLEND: BlendType = ...
    BASIC_BLEND: BlendType = ...
    BLUE_BLEND: AdvancedBlendComponent = ...
    BURN_HIGHLIGHTS: BlendMode = ...
    BURN_MIDRANGE: BlendMode = ...
    BURN_SHADOWS: BlendMode = ...
    CLEAR: BlendMode = ...
    COLOR: BlendMode = ...
    COLOR_BURN: BlendMode = ...
    COLOR_DODGE: BlendMode = ...
    CONTRAST: BlendMode = ...
    COPY: BlendMode = ...
    COPY_RGB: BlendMode = ...
    CUSTOM: BlendMode = ...
    DARKEN: BlendMode = ...
    DECONTRAST: BlendMode = ...
    DIFFERENCE: BlendMode = ...
    DIVIDE: BlendMode = ...
    DODGE_HIGHLIGHTS: BlendMode = ...
    DODGE_MIDRANGE: BlendMode = ...
    DODGE_SHADOWS: BlendMode = ...
    EXCLUSION: BlendMode = ...
    FROM_ALPHA: MaskType = ...
    FROM_SELECTION_GROUP: MaskType = ...
    GREEN_BLEND: AdvancedBlendComponent = ...
    GREYSCALE_BLEND: AdvancedBlendComponent = ...
    HARD_LIGHT: BlendMode = ...
    HARD_MIX: BlendMode = ...
    HIDE_ALL: MaskType = ...
    HUE: BlendMode = ...
    INVERSE_DIFFERENCE: BlendMode = ...
    INVERT: BlendMode = ...
    LIGHTEN: BlendMode = ...
    LUMINANCE: BlendMode = ...
    LUMINANCE_BLEND: AdvancedBlendComponent = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    MIX: BlendMode = ...
    MIX_NORMAL_MAPS: BlendMode = ...
    MULTIPLY: BlendMode = ...
    NUDGE_FLOW_VECTORS: BlendMode = ...
    NUDGE_NORMAL_VECTORS: BlendMode = ...
    OVERLAY: BlendMode = ...
    PAINT_FLOW_VECTORS: BlendMode = ...
    PAINT_NORMAL_VECTORS: BlendMode = ...
    PIN_LIGHT: BlendMode = ...
    RED_BLEND: AdvancedBlendComponent = ...
    REORIENTED_NORMAL_MAPPING: BlendMode = ...
    REVEAL_ALL: MaskType = ...
    SATURATION: BlendMode = ...
    SCALE_VECTORS: BlendMode = ...
    SCREEN: BlendMode = ...
    SOFT_LIGHT: BlendMode = ...
    SPONGE_DESATURATE: BlendMode = ...
    SUBTRACT: BlendMode = ...
    SWIZZLE_DST_ALPHA: SwizzleDestination = ...
    SWIZZLE_DST_BLUE: SwizzleDestination = ...
    SWIZZLE_DST_GREEN: SwizzleDestination = ...
    SWIZZLE_DST_RED: SwizzleDestination = ...
    SWIZZLE_SRC_ALPHA: SwizzleSource = ...
    SWIZZLE_SRC_BLUE: SwizzleSource = ...
    SWIZZLE_SRC_GREEN: SwizzleSource = ...
    SWIZZLE_SRC_ONE: SwizzleSource = ...
    SWIZZLE_SRC_RED: SwizzleSource = ...
    SWIZZLE_SRC_ZERO: SwizzleSource = ...
    VIVID_LIGHT: BlendMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def advancedBlendComponentName(Value) -> str: ...
    @staticmethod
    def blendModeName(BlendModeValue) -> str: ...
    @staticmethod
    def blendTypeName(BlendTypeValue) -> str: ...
    @staticmethod
    def colorTagNames() -> typing.List: ...
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def activeCacheUpToHereParents(self) -> typing.List: ...
    def advancedBlendComponentStr(self) -> str: ...
    def blendAmount(self) -> float: ...
    def blendAmountChanged(self, *args, **kwargs) -> Any: ...
    def blendAmountEnabled(self) -> bool: ...
    def blendComponentChanged(self, *args, **kwargs) -> Any: ...
    def blendMode(self) -> Any: ...
    def blendModeChanged(self, *args, **kwargs) -> Any: ...
    def blendModePath(self) -> str: ...
    def blendModeStr(self) -> str: ...
    def blendType(self) -> Any: ...
    def blendTypeChanged(self, *args, **kwargs) -> Any: ...
    def blendTypeStr(self) -> str: ...
    def blockSignals(self, b: bool) -> bool: ...
    def cacheLayer(self) -> Any: ...
    def cacheStateChanged(self, *args, **kwargs) -> Any: ...
    def cacheUpToHere(self) -> Any: ...
    def cacheUpToHereParents(self) -> typing.List: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def close(self) -> Any: ...
    def colorTag(self) -> str: ...
    def colorTagChanged(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def container(self) -> mari.MultiChannelMaterial: ...
    def convertedToPaint(self, *args, **kwargs) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def getAdvancedBlendComponent(self) -> Any: ...
    def getLayerBelowBlendLut(self) -> typing.Any: ...
    def getThisLayerBlendLut(self) -> typing.Any: ...
    def groupStack(self) -> mari.LayerStack: ...
    def hasCacheUpToHere(self) -> bool: ...
    def hasLayerCache(self) -> bool: ...
    def hasMask(self) -> bool: ...
    def hasMaskCustomProcedural(self) -> bool: ...
    def hasMaskStack(self) -> bool: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def hash(self, UVIndex: int = ...) -> str: ...
    def imageHash(self, UVIndex: int = ...) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isAdjustableLayer(self) -> bool: ...
    def isAdjustmentLayer(self) -> bool: ...
    def isBakePointLayer(self) -> bool: ...
    def isCachedUpToHere(self) -> bool: ...
    def isChannelLayer(self) -> bool: ...
    def isChildOfActiveCacheUpToHere(self) -> bool: ...
    def isChildOfCacheUpToHere(self) -> bool: ...
    def isCustomProceduralLayer(self) -> bool: ...
    def isGraphLayer(self) -> bool: ...
    def isGroupLayer(self) -> bool: ...
    def isLayerCached(self) -> bool: ...
    def isLocked(self) -> bool: ...
    def isMaskEnabled(self) -> bool: ...
    def isModifiable(self) -> bool: ...
    def isMultiChannelGroupLayer(self) -> bool: ...
    def isMultiChannelMaterialLayer(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isPaintableLayer(self) -> bool: ...
    def isProceduralLayer(self) -> bool: ...
    def isSelected(self) -> bool: ...
    def isShaderLayer(self) -> bool: ...
    def isShared(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isVisible(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def layerNode(self) -> mari.Node: ...
    def lockedChanged(self, *args, **kwargs) -> Any: ...
    def makeCurrent(self) -> Any: ...
    def makeMask(self, Mask = ..., Group: typing.Optional = ...) -> mari.ImageSet: ...
    def makeMaskCustomProcedural(self, FileName: str) -> mari.CustomProceduralNode: ...
    def makeMaskStack(self) -> mari.LayerStack: ...
    def maskCreated(self, *args, **kwargs) -> Any: ...
    def maskCustomProceduralNode(self) -> mari.CustomProceduralNode: ...
    def maskImageSet(self) -> mari.ImageSet: ...
    def maskRemoved(self, *args, **kwargs) -> Any: ...
    def maskStack(self) -> mari.LayerStack: ...
    def maskStackCreated(self, *args, **kwargs) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def parents(self) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMask(self) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def selectedChanged(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAdvancedBlendComponent(self, Component) -> Any: ...
    def setBlendAmount(self, BlendAmount: float) -> Any: ...
    def setBlendAmountEnabled(self, Enabled: bool) -> Any: ...
    def setBlendMode(self, BlendModeValue: typing.Any) -> Any: ...
    def setBlendType(self, Type) -> Any: ...
    def setCachedUpToHere(self, Cache: bool) -> Any: ...
    def setColorTag(self, ColorTag: str) -> Any: ...
    def setLayerBelowBlendLut(self, NewLut: mari.LookUpTable) -> Any: ...
    def setLayerCached(self, Cache: bool) -> Any: ...
    def setLocked(self, Locked: bool) -> Any: ...
    def setMaskEnabled(self, Enabled: bool) -> Any: ...
    def setMaskImageSet(self, Mask: mari.ImageSet) -> Any: ...
    def setMaskStack(self, MaskStack: mari.LayerStack) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, NewName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSelected(self, Selected: bool) -> Any: ...
    def setSwizzle(self, Dst, Src) -> Any: ...
    def setThisLayerBlendLut(self, NewLut: mari.LookUpTable) -> Any: ...
    def setVisibility(self, Visible: bool) -> Any: ...
    def siblingSharedLayerList(self) -> typing.List: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def streamName(self) -> str: ...
    def swizzle(self, Dst) -> Any: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def uncacheLayer(self) -> Any: ...
    def uncacheUpToHere(self) -> Any: ...
    def uuid(self) -> str: ...
