from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Layer
from mari import Metadata
from mari import MultiChannelLayer

class AdvancedBlendComponent:
    BLUE_BLEND: AdvancedBlendComponent = ...
    GREEN_BLEND: AdvancedBlendComponent = ...
    GREYSCALE_BLEND: AdvancedBlendComponent = ...
    LUMINANCE_BLEND: AdvancedBlendComponent = ...
    RED_BLEND: AdvancedBlendComponent = ...
    name: getset_descriptor
    values: dict

class BlendMode:
    ADD: BlendMode = ...
    ADD_NORMAL_MAPS: BlendMode = ...
    BURN_HIGHLIGHTS: BlendMode = ...
    BURN_MIDRANGE: BlendMode = ...
    BURN_SHADOWS: BlendMode = ...
    CLEAR: BlendMode = ...
    COLOR: BlendMode = ...
    COLOR_BURN: BlendMode = ...
    COLOR_DODGE: BlendMode = ...
    CONTRAST: BlendMode = ...
    COPY: BlendMode = ...
    COPY_RGB: BlendMode = ...
    CUSTOM: BlendMode = ...
    DARKEN: BlendMode = ...
    DECONTRAST: BlendMode = ...
    DIFFERENCE: BlendMode = ...
    DIVIDE: BlendMode = ...
    DODGE_HIGHLIGHTS: BlendMode = ...
    DODGE_MIDRANGE: BlendMode = ...
    DODGE_SHADOWS: BlendMode = ...
    EXCLUSION: BlendMode = ...
    HARD_LIGHT: BlendMode = ...
    HARD_MIX: BlendMode = ...
    HUE: BlendMode = ...
    INVERSE_DIFFERENCE: BlendMode = ...
    INVERT: BlendMode = ...
    LIGHTEN: BlendMode = ...
    LUMINANCE: BlendMode = ...
    MIX: BlendMode = ...
    MIX_NORMAL_MAPS: BlendMode = ...
    MULTIPLY: BlendMode = ...
    NUDGE_FLOW_VECTORS: BlendMode = ...
    NUDGE_NORMAL_VECTORS: BlendMode = ...
    OVERLAY: BlendMode = ...
    PAINT_FLOW_VECTORS: BlendMode = ...
    PAINT_NORMAL_VECTORS: BlendMode = ...
    PIN_LIGHT: BlendMode = ...
    REORIENTED_NORMAL_MAPPING: BlendMode = ...
    SATURATION: BlendMode = ...
    SCALE_VECTORS: BlendMode = ...
    SCREEN: BlendMode = ...
    SOFT_LIGHT: BlendMode = ...
    SPONGE_DESATURATE: BlendMode = ...
    SUBTRACT: BlendMode = ...
    VIVID_LIGHT: BlendMode = ...
    name: getset_descriptor
    values: dict

class BlendType:
    ADVANCED_BLEND: BlendType = ...
    BASIC_BLEND: BlendType = ...
    name: getset_descriptor
    values: dict

class MaskType:
    FROM_ALPHA: MaskType = ...
    FROM_SELECTION_GROUP: MaskType = ...
    HIDE_ALL: MaskType = ...
    REVEAL_ALL: MaskType = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SwizzleDestination:
    SWIZZLE_DST_ALPHA: SwizzleDestination = ...
    SWIZZLE_DST_BLUE: SwizzleDestination = ...
    SWIZZLE_DST_GREEN: SwizzleDestination = ...
    SWIZZLE_DST_RED: SwizzleDestination = ...
    name: getset_descriptor
    values: dict

class SwizzleSource:
    SWIZZLE_SRC_ALPHA: SwizzleSource = ...
    SWIZZLE_SRC_BLUE: SwizzleSource = ...
    SWIZZLE_SRC_GREEN: SwizzleSource = ...
    SWIZZLE_SRC_ONE: SwizzleSource = ...
    SWIZZLE_SRC_RED: SwizzleSource = ...
    SWIZZLE_SRC_ZERO: SwizzleSource = ...
    name: getset_descriptor
    values: dict

ADD: BlendMode = ...
ADD_NORMAL_MAPS: BlendMode = ...
ADVANCED_BLEND: BlendType = ...
BASIC_BLEND: BlendType = ...
BLUE_BLEND: AdvancedBlendComponent = ...
BURN_HIGHLIGHTS: BlendMode = ...
BURN_MIDRANGE: BlendMode = ...
BURN_SHADOWS: BlendMode = ...
CLEAR: BlendMode = ...
COLOR: BlendMode = ...
COLOR_BURN: BlendMode = ...
COLOR_DODGE: BlendMode = ...
CONTRAST: BlendMode = ...
COPY: BlendMode = ...
COPY_RGB: BlendMode = ...
CUSTOM: BlendMode = ...
DARKEN: BlendMode = ...
DECONTRAST: BlendMode = ...
DIFFERENCE: BlendMode = ...
DIVIDE: BlendMode = ...
DODGE_HIGHLIGHTS: BlendMode = ...
DODGE_MIDRANGE: BlendMode = ...
DODGE_SHADOWS: BlendMode = ...
EXCLUSION: BlendMode = ...
FROM_ALPHA: MaskType = ...
FROM_SELECTION_GROUP: MaskType = ...
GREEN_BLEND: AdvancedBlendComponent = ...
GREYSCALE_BLEND: AdvancedBlendComponent = ...
HARD_LIGHT: BlendMode = ...
HARD_MIX: BlendMode = ...
HIDE_ALL: MaskType = ...
HUE: BlendMode = ...
INVERSE_DIFFERENCE: BlendMode = ...
INVERT: BlendMode = ...
LIGHTEN: BlendMode = ...
LUMINANCE: BlendMode = ...
LUMINANCE_BLEND: AdvancedBlendComponent = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIX: BlendMode = ...
MIX_NORMAL_MAPS: BlendMode = ...
MULTIPLY: BlendMode = ...
NUDGE_FLOW_VECTORS: BlendMode = ...
NUDGE_NORMAL_VECTORS: BlendMode = ...
OVERLAY: BlendMode = ...
PAINT_FLOW_VECTORS: BlendMode = ...
PAINT_NORMAL_VECTORS: BlendMode = ...
PIN_LIGHT: BlendMode = ...
RED_BLEND: AdvancedBlendComponent = ...
REORIENTED_NORMAL_MAPPING: BlendMode = ...
REVEAL_ALL: MaskType = ...
SATURATION: BlendMode = ...
SCALE_VECTORS: BlendMode = ...
SCREEN: BlendMode = ...
SOFT_LIGHT: BlendMode = ...
SPONGE_DESATURATE: BlendMode = ...
SUBTRACT: BlendMode = ...
SWIZZLE_DST_ALPHA: SwizzleDestination = ...
SWIZZLE_DST_BLUE: SwizzleDestination = ...
SWIZZLE_DST_GREEN: SwizzleDestination = ...
SWIZZLE_DST_RED: SwizzleDestination = ...
SWIZZLE_SRC_ALPHA: SwizzleSource = ...
SWIZZLE_SRC_BLUE: SwizzleSource = ...
SWIZZLE_SRC_GREEN: SwizzleSource = ...
SWIZZLE_SRC_ONE: SwizzleSource = ...
SWIZZLE_SRC_RED: SwizzleSource = ...
SWIZZLE_SRC_ZERO: SwizzleSource = ...
VIVID_LIGHT: BlendMode = ...
staticMetaObject: QMetaObject
ADD: BlendMode = ...
ADD_NORMAL_MAPS: BlendMode = ...
ADVANCED_BLEND: BlendType = ...
BASIC_BLEND: BlendType = ...
BLUE_BLEND: AdvancedBlendComponent = ...
BURN_HIGHLIGHTS: BlendMode = ...
BURN_MIDRANGE: BlendMode = ...
BURN_SHADOWS: BlendMode = ...
CLEAR: BlendMode = ...
COLOR: BlendMode = ...
COLOR_BURN: BlendMode = ...
COLOR_DODGE: BlendMode = ...
CONTRAST: BlendMode = ...
COPY: BlendMode = ...
COPY_RGB: BlendMode = ...
CUSTOM: BlendMode = ...
DARKEN: BlendMode = ...
DECONTRAST: BlendMode = ...
DIFFERENCE: BlendMode = ...
DIVIDE: BlendMode = ...
DODGE_HIGHLIGHTS: BlendMode = ...
DODGE_MIDRANGE: BlendMode = ...
DODGE_SHADOWS: BlendMode = ...
EXCLUSION: BlendMode = ...
FROM_ALPHA: MaskType = ...
FROM_SELECTION_GROUP: MaskType = ...
GREEN_BLEND: AdvancedBlendComponent = ...
GREYSCALE_BLEND: AdvancedBlendComponent = ...
HARD_LIGHT: BlendMode = ...
HARD_MIX: BlendMode = ...
HIDE_ALL: MaskType = ...
HUE: BlendMode = ...
INVERSE_DIFFERENCE: BlendMode = ...
INVERT: BlendMode = ...
LIGHTEN: BlendMode = ...
LUMINANCE: BlendMode = ...
LUMINANCE_BLEND: AdvancedBlendComponent = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIX: BlendMode = ...
MIX_NORMAL_MAPS: BlendMode = ...
MULTIPLY: BlendMode = ...
NUDGE_FLOW_VECTORS: BlendMode = ...
NUDGE_NORMAL_VECTORS: BlendMode = ...
OVERLAY: BlendMode = ...
PAINT_FLOW_VECTORS: BlendMode = ...
PAINT_NORMAL_VECTORS: BlendMode = ...
PIN_LIGHT: BlendMode = ...
RED_BLEND: AdvancedBlendComponent = ...
REORIENTED_NORMAL_MAPPING: BlendMode = ...
REVEAL_ALL: MaskType = ...
SATURATION: BlendMode = ...
SCALE_VECTORS: BlendMode = ...
SCREEN: BlendMode = ...
SOFT_LIGHT: BlendMode = ...
SPONGE_DESATURATE: BlendMode = ...
SUBTRACT: BlendMode = ...
SWIZZLE_DST_ALPHA: SwizzleDestination = ...
SWIZZLE_DST_BLUE: SwizzleDestination = ...
SWIZZLE_DST_GREEN: SwizzleDestination = ...
SWIZZLE_DST_RED: SwizzleDestination = ...
SWIZZLE_SRC_ALPHA: SwizzleSource = ...
SWIZZLE_SRC_BLUE: SwizzleSource = ...
SWIZZLE_SRC_GREEN: SwizzleSource = ...
SWIZZLE_SRC_ONE: SwizzleSource = ...
SWIZZLE_SRC_RED: SwizzleSource = ...
SWIZZLE_SRC_ZERO: SwizzleSource = ...
VIVID_LIGHT: BlendMode = ...
@staticmethod
def advancedBlendComponentName(Value) -> str: ...
@staticmethod
def blendModeName(BlendModeValue) -> str: ...
@staticmethod
def blendTypeName(BlendTypeValue) -> str: ...
@staticmethod
def colorTagNames() -> typing.List: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def activeCacheUpToHereParents() -> typing.List: ...
def advancedBlendComponentStr() -> str: ...
def blendAmount() -> float: ...
def blendAmountChanged(*args, **kwargs) -> Any: ...
def blendAmountEnabled() -> bool: ...
def blendComponentChanged(*args, **kwargs) -> Any: ...
def blendMode() -> Any: ...
def blendModeChanged(*args, **kwargs) -> Any: ...
def blendModePath() -> str: ...
def blendModeStr() -> str: ...
def blendType() -> Any: ...
def blendTypeChanged(*args, **kwargs) -> Any: ...
def blendTypeStr() -> str: ...
def blockSignals(b: bool) -> bool: ...
def cacheLayer() -> Any: ...
def cacheStateChanged(*args, **kwargs) -> Any: ...
def cacheUpToHere() -> Any: ...
def cacheUpToHereParents() -> typing.List: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def close() -> Any: ...
def colorTag() -> str: ...
def colorTagChanged(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def container() -> mari.MultiChannelMaterial: ...
def convertedToPaint(*args, **kwargs) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def getAdvancedBlendComponent() -> Any: ...
def getLayerBelowBlendLut() -> typing.Any: ...
def getThisLayerBlendLut() -> typing.Any: ...
def groupStack() -> mari.LayerStack: ...
def hasCacheUpToHere() -> bool: ...
def hasLayerCache() -> bool: ...
def hasMask() -> bool: ...
def hasMaskCustomProcedural() -> bool: ...
def hasMaskStack() -> bool: ...
def hasMetadata(Name: str) -> bool: ...
def hash(UVIndex: int = ...) -> str: ...
def imageHash(UVIndex: int = ...) -> str: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isAdjustableLayer() -> bool: ...
def isAdjustmentLayer() -> bool: ...
def isBakePointLayer() -> bool: ...
def isCachedUpToHere() -> bool: ...
def isChannelLayer() -> bool: ...
def isChildOfActiveCacheUpToHere() -> bool: ...
def isChildOfCacheUpToHere() -> bool: ...
def isCustomProceduralLayer() -> bool: ...
def isGraphLayer() -> bool: ...
def isGroupLayer() -> bool: ...
def isLayerCached() -> bool: ...
def isLocked() -> bool: ...
def isMaskEnabled() -> bool: ...
def isModifiable() -> bool: ...
def isMultiChannelGroupLayer() -> bool: ...
def isMultiChannelMaterialLayer() -> bool: ...
def isNull() -> bool: ...
def isPaintableLayer() -> bool: ...
def isProceduralLayer() -> bool: ...
def isSelected() -> bool: ...
def isShaderLayer() -> bool: ...
def isShared() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isVisible() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def layerNode() -> mari.Node: ...
def lockedChanged(*args, **kwargs) -> Any: ...
def makeCurrent() -> Any: ...
def makeMask(Mask = ..., Group: typing.Optional = ...) -> mari.ImageSet: ...
def makeMaskCustomProcedural(FileName: str) -> mari.CustomProceduralNode: ...
def makeMaskStack() -> mari.LayerStack: ...
def maskCreated(*args, **kwargs) -> Any: ...
def maskCustomProceduralNode() -> mari.CustomProceduralNode: ...
def maskImageSet() -> mari.ImageSet: ...
def maskRemoved(*args, **kwargs) -> Any: ...
def maskStack() -> mari.LayerStack: ...
def maskStackCreated(*args, **kwargs) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def nameChanged(*args, **kwargs) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def parents() -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMask() -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def selectedChanged(*args, **kwargs) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setAdvancedBlendComponent(Component) -> Any: ...
def setBlendAmount(BlendAmount: float) -> Any: ...
def setBlendAmountEnabled(Enabled: bool) -> Any: ...
def setBlendMode(BlendModeValue: typing.Any) -> Any: ...
def setBlendType(Type) -> Any: ...
def setCachedUpToHere(Cache: bool) -> Any: ...
def setColorTag(ColorTag: str) -> Any: ...
def setLayerBelowBlendLut(NewLut: mari.LookUpTable) -> Any: ...
def setLayerCached(Cache: bool) -> Any: ...
def setLocked(Locked: bool) -> Any: ...
def setMaskEnabled(Enabled: bool) -> Any: ...
def setMaskImageSet(Mask: mari.ImageSet) -> Any: ...
def setMaskStack(MaskStack: mari.LayerStack) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setName(NewName: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setSelected(Selected: bool) -> Any: ...
def setSwizzle(Dst, Src) -> Any: ...
def setThisLayerBlendLut(NewLut: mari.LookUpTable) -> Any: ...
def setVisibility(Visible: bool) -> Any: ...
def siblingSharedLayerList() -> typing.List: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def streamName() -> str: ...
def swizzle(Dst) -> Any: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def uncacheLayer() -> Any: ...
def uncacheUpToHere() -> Any: ...
def uuid() -> str: ...
