from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def getAllUpstreamNodes(DestNode: mari.Node) -> typing.List: ...
@staticmethod
def getUpstreamNodes(DestNode: mari.Node) -> typing.List: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
@staticmethod
def swapNodes(NodeA: mari.Node, NodeB: mari.Node) -> Any: ...
@staticmethod
def topologicalSortTo(DestNode: mari.Node, ReverseOrder: bool = ...) -> typing.List: ...
@staticmethod
def transferNodes(UVRemap: typing.Any, SourceNodes: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
@staticmethod
def willConnectionBreakDAG(SourceNode: mari.Node, SourceNodeOutputPort: str, DestNode: mari.Node, DestNodeInputPort: str) -> bool: ...
def addNode(NodeToAdd: mari.Node) -> Any: ...
def autoLayoutNodes(Roots: typing.Sequence) -> Any: ...
def bakeEmptyAndUpdateOutOfDateBakePoints() -> Any: ...
def bakeSelectedBakePoints() -> Any: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createBakePointNode(Width: int, Height: int, Depth: int, FillColor: typing.Optional = ..., FileSpace = ..., ColorConfig: typing.Optional = ...) -> mari.BakePointNode: ...
def createChannelNode(Width: int, Height: int, Depth: int, FileSpace = ..., ColorConfig: typing.Optional = ..., Name: str = ...) -> mari.Node: ...
def createMaterialTemplate(Model: mari.ShaderModel, CreateWithDefaultColors: bool = ...) -> mari.GroupNode: ...
def createMultiChannelBakePointNode(Model: mari.ShaderModel, Width: int, Height: int, Depth: int, StreamSettingsMap: typing.Any = ...) -> mari.GroupNode: ...
def createMultiChannelBottomTransparencyNode(Model: mari.ShaderModel) -> mari.GroupNode: ...
def createMultiChannelMergeNode(Model: mari.ShaderModel) -> mari.GroupNode: ...
def createMultiChannelPaintNode(Model: mari.ShaderModel, Width: int, Height: int, Depth: int, StreamSettingsMap: typing.Any = ...) -> mari.GroupNode: ...
def createNode(Type: str) -> mari.Node: ...
def createPaintNode(Width: int, Height: int, Depth: int, FillColor: typing.Optional = ..., FileSpace = ..., ColorConfig: typing.Optional = ...) -> mari.PaintNode: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def deleteNode(NodeToDelete: mari.Node) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportNodesAsArchive(DirPath: str, Nodes: typing.Sequence, NoDataBlockCopy: bool = ..., UVIndexList: typing.Sequence = ...) -> typing.Dict: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def groupNodes(Nodes: typing.Sequence) -> mari.GroupNode: ...
def hasMetadata(Name: str) -> bool: ...
def importCustomProcedural(FileName: str) -> mari.Node: ...
def importMaterial(FileName: str) -> mari.Node: ...
def importNodesFromArchive(DirPath: str, UuidsToLoad: typing.Sequence, UvIndexMap: typing.Dict) -> typing.List: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def load(FilePath: str) -> typing.List: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def nodeList(IncludeSystemNodes: bool = ...) -> typing.List: ...
def nodeSelectionChanged(*args, **kwargs) -> Any: ...
def nodesFromString(String: str) -> typing.List: ...
def nodesToString(Nodes: typing.Sequence) -> str: ...
def nodesWithTag(Tag: str) -> typing.List: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def parentGeoEntity() -> mari.GeoEntity: ...
def parentGroupNode() -> mari.GroupNode: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def removeNode(NodeToRemove: mari.Node) -> Any: ...
def save(FilePath: str, Nodes: typing.Sequence) -> Any: ...
def selectedNodeList(IncludeSystemNodes: bool = ...) -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setActiveViewerInput(InputNumber: int) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def teleportBroadcastChannelNameList() -> typing.List: ...
def teleportNodeBroadcastingOnChannel(ChannelName: str) -> mari.BroadcastTeleportNode: ...
def teleportNodesListeningToChannel(ChannelName: str) -> typing.List: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def typeList() -> typing.List: ...
def updateSelectedBakePoints() -> Any: ...
def uuid() -> str: ...
def viewerNode() -> mari.Node: ...
