from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class NodeGraph(Metadata):
    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def getAllUpstreamNodes(DestNode: mari.Node) -> typing.List: ...
    @staticmethod
    def getUpstreamNodes(DestNode: mari.Node) -> typing.List: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def swapNodes(NodeA: mari.Node, NodeB: mari.Node) -> Any: ...
    @staticmethod
    def topologicalSortTo(DestNode: mari.Node, ReverseOrder: bool = ...) -> typing.List: ...
    @staticmethod
    def transferNodes(UVRemap: typing.Any, SourceNodes: typing.Sequence, SourceGeoVersion: mari.GeoEntityVersion, DestinationGeoVersion: mari.GeoEntityVersion, DestinationSize = ..., BleedEdges: bool = ..., FillColor: typing.Optional = ..., SourceUVIndices: typing.Sequence = ..., DestinationUVIndices: typing.Sequence = ...) -> typing.List: ...
    @staticmethod
    def willConnectionBreakDAG(SourceNode: mari.Node, SourceNodeOutputPort: str, DestNode: mari.Node, DestNodeInputPort: str) -> bool: ...
    def addNode(self, NodeToAdd: mari.Node) -> Any: ...
    def autoLayoutNodes(self, Roots: typing.Sequence) -> Any: ...
    def bakeEmptyAndUpdateOutOfDateBakePoints(self) -> Any: ...
    def bakeSelectedBakePoints(self) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createBakePointNode(self, Width: int, Height: int, Depth: int, FillColor: typing.Optional = ..., FileSpace = ..., ColorConfig: typing.Optional = ...) -> mari.BakePointNode: ...
    def createChannelNode(self, Width: int, Height: int, Depth: int, FileSpace = ..., ColorConfig: typing.Optional = ..., Name: str = ...) -> mari.Node: ...
    def createMaterialTemplate(self, Model: mari.ShaderModel, CreateWithDefaultColors: bool = ...) -> mari.GroupNode: ...
    def createMultiChannelBakePointNode(self, Model: mari.ShaderModel, Width: int, Height: int, Depth: int, StreamSettingsMap: typing.Any = ...) -> mari.GroupNode: ...
    def createMultiChannelBottomTransparencyNode(self, Model: mari.ShaderModel) -> mari.GroupNode: ...
    def createMultiChannelMergeNode(self, Model: mari.ShaderModel) -> mari.GroupNode: ...
    def createMultiChannelPaintNode(self, Model: mari.ShaderModel, Width: int, Height: int, Depth: int, StreamSettingsMap: typing.Any = ...) -> mari.GroupNode: ...
    def createNode(self, Type: str) -> mari.Node: ...
    def createPaintNode(self, Width: int, Height: int, Depth: int, FillColor: typing.Optional = ..., FileSpace = ..., ColorConfig: typing.Optional = ...) -> mari.PaintNode: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def deleteNode(self, NodeToDelete: mari.Node) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportNodesAsArchive(self, DirPath: str, Nodes: typing.Sequence, NoDataBlockCopy: bool = ..., UVIndexList: typing.Sequence = ...) -> typing.Dict: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def groupNodes(self, Nodes: typing.Sequence) -> mari.GroupNode: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def importCustomProcedural(self, FileName: str) -> mari.Node: ...
    def importMaterial(self, FileName: str) -> mari.Node: ...
    def importNodesFromArchive(self, DirPath: str, UuidsToLoad: typing.Sequence, UvIndexMap: typing.Dict) -> typing.List: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def load(self, FilePath: str) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def nodeList(self, IncludeSystemNodes: bool = ...) -> typing.List: ...
    def nodeSelectionChanged(self, *args, **kwargs) -> Any: ...
    def nodesFromString(self, String: str) -> typing.List: ...
    def nodesToString(self, Nodes: typing.Sequence) -> str: ...
    def nodesWithTag(self, Tag: str) -> typing.List: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def parentGeoEntity(self) -> mari.GeoEntity: ...
    def parentGroupNode(self) -> mari.GroupNode: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def removeNode(self, NodeToRemove: mari.Node) -> Any: ...
    def save(self, FilePath: str, Nodes: typing.Sequence) -> Any: ...
    def selectedNodeList(self, IncludeSystemNodes: bool = ...) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setActiveViewerInput(self, InputNumber: int) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def teleportBroadcastChannelNameList(self) -> typing.List: ...
    def teleportNodeBroadcastingOnChannel(self, ChannelName: str) -> mari.BroadcastTeleportNode: ...
    def teleportNodesListeningToChannel(self, ChannelName: str) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def typeList(self) -> typing.List: ...
    def updateSelectedBakePoints(self) -> Any: ...
    def uuid(self) -> str: ...
    def viewerNode(self) -> mari.Node: ...
