from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def getAllUpstreamNodes(DestNode) -> Any: ...
@staticmethod
def getUpstreamNodes(DestNode) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def swapNodes(NodeA, NodeB) -> Any: ...
@staticmethod
def topologicalSortTo(DestNode, ReverseOrder = ...) -> Any: ...
@staticmethod
def transferNodes(UVRemap, SourceNodes, SourceGeoVersion, DestinationGeoVersion, DestinationSize = ..., BleedEdges = ..., FillColor = ..., SourceUVIndices = ..., DestinationUVIndices = ...) -> Any: ...
@staticmethod
def willConnectionBreakDAG(SourceNode, SourceNodeOutputPort, DestNode, DestNodeInputPort) -> Any: ...
def addNode(self, NodeToAdd) -> Any: ...
def autoLayoutNodes(self, Roots) -> Any: ...
def bakeEmptyAndUpdateOutOfDateBakePoints(self) -> Any: ...
def bakeSelectedBakePoints(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createBakePointNode(self, Width, Height, Depth, FillColor = ..., FileSpace = ..., ColorConfig = ...) -> Any: ...
def createChannelNode(self, Width, Height, Depth, FileSpace = ..., ColorConfig = ..., Name = ...) -> Any: ...
def createMaterialTemplate(self, Model, CreateWithDefaultColors = ...) -> Any: ...
def createMultiChannelBakePointNode(self, Model, Width, Height, Depth, StreamSettingsMap = ...) -> Any: ...
def createMultiChannelBottomTransparencyNode(self, Model) -> Any: ...
def createMultiChannelMergeNode(self, Model) -> Any: ...
def createMultiChannelPaintNode(self, Model, Width, Height, Depth, StreamSettingsMap = ...) -> Any: ...
def createNode(self, Type) -> Any: ...
def createPaintNode(self, Width, Height, Depth, FillColor = ..., FileSpace = ..., ColorConfig = ...) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def deleteNode(self, NodeToDelete) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportNodesAsArchive(self, DirPath, Nodes, NoDataBlockCopy = ..., UVIndexList = ...) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def groupNodes(self, Nodes) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def importCustomProcedural(self, FileName) -> Any: ...
def importMaterial(self, FileName) -> Any: ...
def importNodesFromArchive(self, DirPath, UuidsToLoad, UvIndexMap) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def load(self, FilePath) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def nodeList(self, IncludeSystemNodes = ...) -> Any: ...
def nodeSelectionChanged(self, *args, **kwargs) -> Any: ...
def nodesFromString(self, String) -> Any: ...
def nodesToString(self, Nodes) -> Any: ...
def nodesWithTag(self, Tag) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def parentGeoEntity(self) -> Any: ...
def parentGroupNode(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def removeNode(self, NodeToRemove) -> Any: ...
def save(self, FilePath, Nodes) -> Any: ...
def selectedNodeList(self, IncludeSystemNodes = ...) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setActiveViewerInput(self, InputNumber) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def teleportBroadcastChannelNameList(self) -> Any: ...
def teleportNodeBroadcastingOnChannel(self, ChannelName) -> Any: ...
def teleportNodesListeningToChannel(self, ChannelName) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def typeList(self) -> Any: ...
def updateSelectedBakePoints(self) -> Any: ...
def uuid(self) -> Any: ...
def viewerNode(self) -> Any: ...
