from typing import Any

class ColorPickerMode:
    COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
    COLOR_PICKER_OCIO: ColorPickerMode = ...
    COLOR_PICKER_RAW: ColorPickerMode = ...
    name: getset_descriptor
    values: dict

def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def colorPickerMode() -> Any: ...
class colorPickerModeChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def colorspace(Config, Index) -> Any: ...
def colorspaceCount(Config) -> Any: ...
def colorspacePrettyNames(Config) -> Any: ...
def configDescription(Config) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def currentColorspaceConfig() -> Any: ...
def currentColorspaceDefaults() -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def defaultConfig() -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def get3DLutValuesFromColorSpaceTransform(Config, Input, Output, LutSize) -> Any: ...
def get3DLutValuesFromDisplayViewTransform(Config, Src, View, Display, LutSize) -> Any: ...
def get3DLutValuesFromFileTransform(Config, LutFile, LutSize) -> Any: ...
def hasColorspace(Config, Name) -> Any: ...
def hasRole(Config, Name) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isConfigValid(Config) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isShaderTransformAccurate(Config, InputColorspace, OutputColorspace, LutSize) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isStandardConfig(Name) -> Any: ...
def isTargetScalar() -> Any: ...
def isTransformValid(Config, InputColorspace, OutputColorspace) -> Any: ...
def isViewerScalar() -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def lutSize() -> Any: ...
class lutSizeChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent(*args, **kwargs) -> Any: ...
def parseColorspaceFromString(Config, Str) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerConfigUiAllowlist(ConfigFilePath, Allowlist) -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def role(Config, Index) -> Any: ...
def roleCount(Config) -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setColorPickerMode(Mode) -> Any: ...
def setLutSize(Size) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setShaderTransformAccuracy(Config, InputColorspace, OutputColorspace, MinimumLutSize) -> Any: ...
def setShaderTransformCode(Config, InputColorspace, OutputColorspace, Code) -> Any: ...
def shaderTransformUsesLut(Config, InputColorspace, OutputColorspace) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def standardConfigPath(Config) -> Any: ...
def standardConfigs() -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

class targetScalarChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def toColorspace(Config, Role) -> Any: ...
def toPrettyName(Config, Name) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def transformColor(Config, InputColorspace, OutputColorspace, InputColor) -> Any: ...
def transformImage(Config, InputColorspace, OutputColorspace, InputImage) -> Any: ...
class viewerScalarChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

