from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorPickerMode:
    COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
    COLOR_PICKER_OCIO: ColorPickerMode = ...
    COLOR_PICKER_RAW: ColorPickerMode = ...
    name: getset_descriptor
    values: dict

COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
COLOR_PICKER_OCIO: ColorPickerMode = ...
COLOR_PICKER_RAW: ColorPickerMode = ...
staticMetaObject: QMetaObject
COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
COLOR_PICKER_OCIO: ColorPickerMode = ...
COLOR_PICKER_RAW: ColorPickerMode = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def colorPickerMode(self) -> Any: ...
def colorPickerModeChanged(self, *args, **kwargs) -> Any: ...
def colorspace(self, Config, Index) -> Any: ...
def colorspaceCount(self, Config) -> Any: ...
def colorspacePrettyNames(self, Config) -> Any: ...
def configDescription(self, Config) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def currentColorspaceConfig(self) -> Any: ...
def currentColorspaceDefaults(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def defaultConfig(self) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def get3DLutValuesFromColorSpaceTransform(self, Config, Input, Output, LutSize) -> Any: ...
def get3DLutValuesFromDisplayViewTransform(self, Config, Src, View, Display, LutSize) -> Any: ...
def get3DLutValuesFromFileTransform(self, Config, LutFile, LutSize) -> Any: ...
def hasColorspace(self, Config, Name) -> Any: ...
def hasRole(self, Config, Name) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isConfigValid(self, Config) -> Any: ...
def isNull(self) -> Any: ...
def isShaderTransformAccurate(self, Config, InputColorspace, OutputColorspace, LutSize) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isStandardConfig(self, Name) -> Any: ...
def isTargetScalar(self) -> Any: ...
def isTransformValid(self, Config, InputColorspace, OutputColorspace) -> Any: ...
def isViewerScalar(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lutSize(self) -> Any: ...
def lutSizeChanged(self, *args, **kwargs) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def parseColorspaceFromString(self, Config, Str) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def registerConfigUiAllowlist(self, ConfigFilePath, Allowlist) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def role(self, Config, Index) -> Any: ...
def roleCount(self, Config) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setColorPickerMode(self, Mode) -> Any: ...
def setLutSize(self, Size) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setShaderTransformAccuracy(self, Config, InputColorspace, OutputColorspace, MinimumLutSize) -> Any: ...
def setShaderTransformCode(self, Config, InputColorspace, OutputColorspace, Code) -> Any: ...
def shaderTransformUsesLut(self, Config, InputColorspace, OutputColorspace) -> Any: ...
def signalsBlocked(self) -> Any: ...
def standardConfigPath(self, Config) -> Any: ...
def standardConfigs(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def targetScalarChanged(self, *args, **kwargs) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toColorspace(self, Config, Role) -> Any: ...
def toPrettyName(self, Config, Name) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def transformColor(self, Config, InputColorspace, OutputColorspace, InputColor) -> Any: ...
def transformImage(self, Config, InputColorspace, OutputColorspace, InputImage) -> Any: ...
def viewerScalarChanged(self, *args, **kwargs) -> Any: ...
