from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class OpenColorIO(API):
    class ColorPickerMode:
        COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
        COLOR_PICKER_OCIO: ColorPickerMode = ...
        COLOR_PICKER_RAW: ColorPickerMode = ...
        name: getset_descriptor
        values: dict

    COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
    COLOR_PICKER_OCIO: ColorPickerMode = ...
    COLOR_PICKER_RAW: ColorPickerMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def colorPickerMode(self) -> Any: ...
    def colorPickerModeChanged(self, *args, **kwargs) -> Any: ...
    def colorspace(self, Config: str, Index: int) -> str: ...
    def colorspaceCount(self, Config: str) -> int: ...
    def colorspacePrettyNames(self, Config: str) -> typing.List: ...
    def configDescription(self, Config: str) -> str: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def currentColorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def currentColorspaceDefaults(self) -> mari.ColorspaceDefaults: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def defaultConfig(self) -> str: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def get3DLutValuesFromColorSpaceTransform(self, Config: str, Input: str, Output: str, LutSize: int) -> typing.List: ...
    def get3DLutValuesFromDisplayViewTransform(self, Config: str, Src: str, View: str, Display: str, LutSize: int) -> typing.List: ...
    def get3DLutValuesFromFileTransform(self, Config: str, LutFile: str, LutSize: int) -> typing.List: ...
    def hasColorspace(self, Config: str, Name: str) -> bool: ...
    def hasRole(self, Config: str, Name: str) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isConfigValid(self, Config: str) -> bool: ...
    def isNull(self) -> bool: ...
    def isShaderTransformAccurate(self, Config: str, InputColorspace: str, OutputColorspace: str, LutSize: int) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isStandardConfig(self, Name: str) -> bool: ...
    def isTargetScalar(self) -> bool: ...
    def isTransformValid(self, Config: str, InputColorspace: str, OutputColorspace: str) -> bool: ...
    def isViewerScalar(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lutSize(self) -> int: ...
    def lutSizeChanged(self, *args, **kwargs) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def parseColorspaceFromString(self, Config: str, Str: str) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def registerConfigUiAllowlist(self, ConfigFilePath: str, Allowlist: typing.Sequence) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def role(self, Config: str, Index: int) -> str: ...
    def roleCount(self, Config: str) -> int: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setColorPickerMode(self, Mode) -> Any: ...
    def setLutSize(self, Size: int) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setShaderTransformAccuracy(self, Config: str, InputColorspace: str, OutputColorspace: str, MinimumLutSize: int) -> Any: ...
    def setShaderTransformCode(self, Config: str, InputColorspace: str, OutputColorspace: str, Code: str) -> Any: ...
    def shaderTransformUsesLut(self, Config: str, InputColorspace: str, OutputColorspace: str) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def standardConfigPath(self, Config: str) -> str: ...
    def standardConfigs(self) -> typing.List: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def targetScalarChanged(self, *args, **kwargs) -> Any: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toColorspace(self, Config: str, Role: str) -> str: ...
    def toPrettyName(self, Config: str, Name: str) -> str: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def transformColor(self, Config: str, InputColorspace: str, OutputColorspace: str, InputColor: mari.Color) -> mari.Color: ...
    def transformImage(self, Config: str, InputColorspace: str, OutputColorspace: str, InputImage: mari.Image) -> mari.Image: ...
    def viewerScalarChanged(self, *args, **kwargs) -> Any: ...
