from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ColorPickerMode:
    COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
    COLOR_PICKER_OCIO: ColorPickerMode = ...
    COLOR_PICKER_RAW: ColorPickerMode = ...
    name: getset_descriptor
    values: dict

COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
COLOR_PICKER_OCIO: ColorPickerMode = ...
COLOR_PICKER_RAW: ColorPickerMode = ...
staticMetaObject: QMetaObject
COLOR_PICKER_COLOR_MANAGER: ColorPickerMode = ...
COLOR_PICKER_OCIO: ColorPickerMode = ...
COLOR_PICKER_RAW: ColorPickerMode = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def colorPickerMode() -> Any: ...
def colorPickerModeChanged(*args, **kwargs) -> Any: ...
def colorspace(Config: str, Index: int) -> str: ...
def colorspaceCount(Config: str) -> int: ...
def colorspacePrettyNames(Config: str) -> typing.List: ...
def configDescription(Config: str) -> str: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def currentColorspaceConfig() -> mari.ColorspaceConfig: ...
def currentColorspaceDefaults() -> mari.ColorspaceDefaults: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def defaultConfig() -> str: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def get3DLutValuesFromColorSpaceTransform(Config: str, Input: str, Output: str, LutSize: int) -> typing.List: ...
def get3DLutValuesFromDisplayViewTransform(Config: str, Src: str, View: str, Display: str, LutSize: int) -> typing.List: ...
def get3DLutValuesFromFileTransform(Config: str, LutFile: str, LutSize: int) -> typing.List: ...
def hasColorspace(Config: str, Name: str) -> bool: ...
def hasRole(Config: str, Name: str) -> bool: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isConfigValid(Config: str) -> bool: ...
def isNull() -> bool: ...
def isShaderTransformAccurate(Config: str, InputColorspace: str, OutputColorspace: str, LutSize: int) -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isStandardConfig(Name: str) -> bool: ...
def isTargetScalar() -> bool: ...
def isTransformValid(Config: str, InputColorspace: str, OutputColorspace: str) -> bool: ...
def isViewerScalar() -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lutSize() -> int: ...
def lutSizeChanged(*args, **kwargs) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def parseColorspaceFromString(Config: str, Str: str) -> str: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def registerConfigUiAllowlist(ConfigFilePath: str, Allowlist: typing.Sequence) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def role(Config: str, Index: int) -> str: ...
def roleCount(Config: str) -> int: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setColorPickerMode(Mode) -> Any: ...
def setLutSize(Size: int) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setShaderTransformAccuracy(Config: str, InputColorspace: str, OutputColorspace: str, MinimumLutSize: int) -> Any: ...
def setShaderTransformCode(Config: str, InputColorspace: str, OutputColorspace: str, Code: str) -> Any: ...
def shaderTransformUsesLut(Config: str, InputColorspace: str, OutputColorspace: str) -> bool: ...
def signalsBlocked() -> bool: ...
def standardConfigPath(Config: str) -> str: ...
def standardConfigs() -> typing.List: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def targetScalarChanged(*args, **kwargs) -> Any: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def toColorspace(Config: str, Role: str) -> str: ...
def toPrettyName(Config: str, Name: str) -> str: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def transformColor(Config: str, InputColorspace: str, OutputColorspace: str, InputColor: mari.Color) -> mari.Color: ...
def transformImage(Config: str, InputColorspace: str, OutputColorspace: str, InputImage: mari.Image) -> mari.Image: ...
def viewerScalarChanged(*args, **kwargs) -> Any: ...
