from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import PropertySource

class BufferDepth:
    DEPTH_BYTE: BufferDepth = ...
    DEPTH_FLOAT: BufferDepth = ...
    DEPTH_HALF: BufferDepth = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class Mirroring:
    MIRROR_NONE: Mirroring = ...
    MIRROR_X: Mirroring = ...
    MIRROR_XY: Mirroring = ...
    MIRROR_Y: Mirroring = ...
    name: getset_descriptor
    values: dict

DEPTH_BYTE: BufferDepth = ...
DEPTH_FLOAT: BufferDepth = ...
DEPTH_HALF: BufferDepth = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIRROR_NONE: Mirroring = ...
MIRROR_X: Mirroring = ...
MIRROR_XY: Mirroring = ...
MIRROR_Y: Mirroring = ...
staticMetaObject: QMetaObject
DEPTH_BYTE: BufferDepth = ...
DEPTH_FLOAT: BufferDepth = ...
DEPTH_HALF: BufferDepth = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIRROR_NONE: Mirroring = ...
MIRROR_X: Mirroring = ...
MIRROR_XY: Mirroring = ...
MIRROR_Y: Mirroring = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def aboutToBake(self, *args, **kwargs) -> Any: ...
def aboutToClear(self, *args, **kwargs) -> Any: ...
def bake(self) -> Any: ...
def bakeAndClear(self) -> Any: ...
def baked(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def canResetProperty(self, PropertyName) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clampColors(self) -> Any: ...
def clear(self) -> Any: ...
def cleared(self, *args, **kwargs) -> Any: ...
def compImage(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depth(self) -> Any: ...
def depthChanged(self, *args, **kwargs) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def getPaint(self) -> Any: ...
def getProperty(self, PropertyName) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isDirty(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def loadPaint(self, Paint) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def mirroring(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def pickColor(self, x, y) -> Any: ...
def propertiesList(self) -> Any: ...
def property(self, name) -> Any: ...
def propertyDisplayName(self, PropertyName) -> Any: ...
def propertyEnumValues(self, PropertyName) -> Any: ...
def propertyHasMinMax(self, PropertyName) -> Any: ...
def propertyIsEnum(self, PropertyName) -> Any: ...
def propertyIsReadOnly(self, PropertyName) -> Any: ...
def propertyMinMax(self, PropertyName) -> Any: ...
def propertyTooltip(self, PropertyName) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def resetProperty(self, PropertyName) -> Any: ...
def resolution(self) -> Any: ...
def resolutionChanged(self, *args, **kwargs) -> Any: ...
def restoreContent(self) -> Any: ...
def rotation(self) -> Any: ...
def rotationChanged(self, *args, **kwargs) -> Any: ...
def saveContent(self) -> Any: ...
def savePaint(self) -> Any: ...
def scale(self) -> Any: ...
def scaleChanged(self, *args, **kwargs) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setClampColors(self, ClampColors) -> Any: ...
def setDepth(self, Depth) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setMirroring(self, Mirror) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setPaint(self, PaintImage) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, arg__1, arg__2) -> Any: ...
def setResolution(self, Size) -> Any: ...
def setRotation(self, Angle) -> Any: ...
def setScale(self, Size) -> Any: ...
def setTranslation(self, Translation) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def supportedResolutions(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def translation(self) -> Any: ...
def translationChanged(self, *args, **kwargs) -> Any: ...
def uuid(self) -> Any: ...
