from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import PropertySource

class BufferDepth:
    DEPTH_BYTE: BufferDepth = ...
    DEPTH_FLOAT: BufferDepth = ...
    DEPTH_HALF: BufferDepth = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class Mirroring:
    MIRROR_NONE: Mirroring = ...
    MIRROR_X: Mirroring = ...
    MIRROR_XY: Mirroring = ...
    MIRROR_Y: Mirroring = ...
    name: getset_descriptor
    values: dict

DEPTH_BYTE: BufferDepth = ...
DEPTH_FLOAT: BufferDepth = ...
DEPTH_HALF: BufferDepth = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIRROR_NONE: Mirroring = ...
MIRROR_X: Mirroring = ...
MIRROR_XY: Mirroring = ...
MIRROR_Y: Mirroring = ...
staticMetaObject: QMetaObject
DEPTH_BYTE: BufferDepth = ...
DEPTH_FLOAT: BufferDepth = ...
DEPTH_HALF: BufferDepth = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIRROR_NONE: Mirroring = ...
MIRROR_X: Mirroring = ...
MIRROR_XY: Mirroring = ...
MIRROR_Y: Mirroring = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def aboutToBake(*args, **kwargs) -> Any: ...
def aboutToClear(*args, **kwargs) -> Any: ...
def bake() -> bool: ...
def bakeAndClear() -> bool: ...
def baked(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def canResetProperty(PropertyName: str) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clampColors() -> bool: ...
def clear() -> Any: ...
def cleared(*args, **kwargs) -> Any: ...
def compImage(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def depth() -> Any: ...
def depthChanged(*args, **kwargs) -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def getPaint() -> PySide2.QtGui.QImage: ...
def getProperty(PropertyName: str) -> typing.Any: ...
def hasMetadata(Name: str) -> bool: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isDirty() -> bool: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def loadPaint(Paint: mari.Image) -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def mirroring() -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def pickColor(x: int, y: int) -> mari.Color: ...
def propertiesList() -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def propertyDisplayName(PropertyName: str) -> str: ...
def propertyEnumValues(PropertyName: str) -> typing.List: ...
def propertyHasMinMax(PropertyName: str) -> bool: ...
def propertyIsEnum(PropertyName: str) -> bool: ...
def propertyIsReadOnly(PropertyName: str) -> bool: ...
def propertyMinMax(PropertyName: str) -> typing.List: ...
def propertyTooltip(PropertyName: str) -> str: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def resetProperty(PropertyName: str) -> Any: ...
def resolution() -> PySide2.QtCore.QSize: ...
def resolutionChanged(*args, **kwargs) -> Any: ...
def restoreContent() -> Any: ...
def rotation() -> float: ...
def rotationChanged(*args, **kwargs) -> Any: ...
def saveContent() -> Any: ...
def savePaint() -> mari.Image: ...
def scale() -> PySide2.QtCore.QSizeF: ...
def scaleChanged(*args, **kwargs) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setClampColors(ClampColors: bool) -> Any: ...
def setDepth(Depth) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setMirroring(Mirror) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setPaint(PaintImage: PySide2.QtGui.QImage) -> bool: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(arg__1: bytes, arg__2: typing.Any) -> Any: ...
def setResolution(Size: PySide2.QtCore.QSize) -> bool: ...
def setRotation(Angle: float) -> Any: ...
def setScale(Size: PySide2.QtCore.QSizeF) -> Any: ...
def setTranslation(Translation: PySide2.QtCore.QPointF) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def supportedResolutions() -> typing.List: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def translation() -> PySide2.QtCore.QPointF: ...
def translationChanged(*args, **kwargs) -> Any: ...
def uuid() -> str: ...
