from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata
from mari import PropertySource

class PaintBuffer(PropertySource):
    class BufferDepth:
        DEPTH_BYTE: BufferDepth = ...
        DEPTH_FLOAT: BufferDepth = ...
        DEPTH_HALF: BufferDepth = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    class Mirroring:
        MIRROR_NONE: Mirroring = ...
        MIRROR_X: Mirroring = ...
        MIRROR_XY: Mirroring = ...
        MIRROR_Y: Mirroring = ...
        name: getset_descriptor
        values: dict

    DEPTH_BYTE: BufferDepth = ...
    DEPTH_FLOAT: BufferDepth = ...
    DEPTH_HALF: BufferDepth = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    MIRROR_NONE: Mirroring = ...
    MIRROR_X: Mirroring = ...
    MIRROR_XY: Mirroring = ...
    MIRROR_Y: Mirroring = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def aboutToBake(self, *args, **kwargs) -> Any: ...
    def aboutToClear(self, *args, **kwargs) -> Any: ...
    def bake(self) -> bool: ...
    def bakeAndClear(self) -> bool: ...
    def baked(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def canResetProperty(self, PropertyName: str) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clampColors(self) -> bool: ...
    def clear(self) -> Any: ...
    def cleared(self, *args, **kwargs) -> Any: ...
    def compImage(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depth(self) -> Any: ...
    def depthChanged(self, *args, **kwargs) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def getPaint(self) -> PySide2.QtGui.QImage: ...
    def getProperty(self, PropertyName: str) -> typing.Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isDirty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def loadPaint(self, Paint: mari.Image) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def mirroring(self) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def pickColor(self, x: int, y: int) -> mari.Color: ...
    def propertiesList(self) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def propertyDisplayName(self, PropertyName: str) -> str: ...
    def propertyEnumValues(self, PropertyName: str) -> typing.List: ...
    def propertyHasMinMax(self, PropertyName: str) -> bool: ...
    def propertyIsEnum(self, PropertyName: str) -> bool: ...
    def propertyIsReadOnly(self, PropertyName: str) -> bool: ...
    def propertyMinMax(self, PropertyName: str) -> typing.List: ...
    def propertyTooltip(self, PropertyName: str) -> str: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def resetProperty(self, PropertyName: str) -> Any: ...
    def resolution(self) -> PySide2.QtCore.QSize: ...
    def resolutionChanged(self, *args, **kwargs) -> Any: ...
    def restoreContent(self) -> Any: ...
    def rotation(self) -> float: ...
    def rotationChanged(self, *args, **kwargs) -> Any: ...
    def saveContent(self) -> Any: ...
    def savePaint(self) -> mari.Image: ...
    def scale(self) -> PySide2.QtCore.QSizeF: ...
    def scaleChanged(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setClampColors(self, ClampColors: bool) -> Any: ...
    def setDepth(self, Depth) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setMirroring(self, Mirror) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setPaint(self, PaintImage: PySide2.QtGui.QImage) -> bool: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, arg__1: bytes, arg__2: typing.Any) -> Any: ...
    def setResolution(self, Size: PySide2.QtCore.QSize) -> bool: ...
    def setRotation(self, Angle: float) -> Any: ...
    def setScale(self, Size: PySide2.QtCore.QSizeF) -> Any: ...
    def setTranslation(self, Translation: PySide2.QtCore.QPointF) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def supportedResolutions(self) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def translation(self) -> PySide2.QtCore.QPointF: ...
    def translationChanged(self, *args, **kwargs) -> Any: ...
    def uuid(self) -> str: ...
