from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import WidgetBase

class Palette(WidgetBase):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def addToLayout(self, Layout: PySide2.QtWidgets.QLayout) -> Any: ...
    def blockSignals(self, Block: bool) -> bool: ...
    def bringToFront(self) -> Any: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disable(self) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def enable(self) -> Any: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def fullName(self) -> str: ...
    def helpURL(self) -> str: ...
    def hide(self) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isEnabled(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isVisible(self) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def maximumHeight(self) -> int: ...
    def maximumWidth(self) -> int: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def minimumHeight(self) -> int: ...
    def minimumWidth(self) -> int: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setBodyWidget(self, pBody: PySide2.QtWidgets.QWidget) -> Any: ...
    def setCSHKey(self, Key: str) -> Any: ...
    def setEnabled(self, Enable: bool) -> Any: ...
    def setFocus(self) -> Any: ...
    def setFullName(self, rName: str) -> Any: ...
    def setMaximumHeight(self, Height: int) -> Any: ...
    def setMaximumWidth(self, Width: int) -> Any: ...
    def setMinimumHeight(self, Height: int) -> Any: ...
    def setMinimumWidth(self, Width: int) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setShortName(self, rName: str) -> Any: ...
    def setStatusTip(self, StatusTip: str) -> Any: ...
    def setToolTip(self, ToolTip: str) -> Any: ...
    def setVisible(self, Visible: bool) -> Any: ...
    def shortName(self) -> str: ...
    def show(self) -> Any: ...
    def showInFront(self) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def statusTip(self) -> str: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toolTip(self) -> str: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
