from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ExportFlags:
    EXPORT_ALPHA: ExportFlags = ...
    EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
    EXPORT_BITANGENT: ExportFlags = ...
    EXPORT_CENTER_POSITIONS: ExportFlags = ...
    EXPORT_GEOMETRY_ID: ExportFlags = ...
    EXPORT_IGNORE_HIDDEN: ExportFlags = ...
    EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
    EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
    EXPORT_MATCH_IMPORT: ExportFlags = ...
    EXPORT_NORMAL: ExportFlags = ...
    EXPORT_PARTICLE_ID: ExportFlags = ...
    EXPORT_PATCH_ID: ExportFlags = ...
    EXPORT_PIXEL_COORDINATE: ExportFlags = ...
    EXPORT_RADIUS: ExportFlags = ...
    EXPORT_TANGENT: ExportFlags = ...
    EXPORT_UV: ExportFlags = ...
    name: getset_descriptor
    values: dict

class ImportFlags:
    IMPORT_BLEED_EDGES: ImportFlags = ...
    IMPORT_CENTER_POSITIONS: ImportFlags = ...
    IMPORT_FLATTEN: ImportFlags = ...
    IMPORT_IGNORE_HIDDEN: ImportFlags = ...
    IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
    name: getset_descriptor
    values: dict

class InterpolationMethod:
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
    INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
    name: getset_descriptor
    values: dict

class RangeUnits:
    RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
    RANGE_INFINITE: RangeUnits = ...
    RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
    name: getset_descriptor
    values: dict

class SearchMethod:
    SEARCH_BACKWARD: SearchMethod = ...
    SEARCH_BIDIRECTIONAL: SearchMethod = ...
    SEARCH_FORWARD: SearchMethod = ...
    SEARCH_RADIAL: SearchMethod = ...
    name: getset_descriptor
    values: dict

EXPORT_ALPHA: ExportFlags = ...
EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
EXPORT_BITANGENT: ExportFlags = ...
EXPORT_CENTER_POSITIONS: ExportFlags = ...
EXPORT_GEOMETRY_ID: ExportFlags = ...
EXPORT_IGNORE_HIDDEN: ExportFlags = ...
EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
EXPORT_MATCH_IMPORT: ExportFlags = ...
EXPORT_NORMAL: ExportFlags = ...
EXPORT_PARTICLE_ID: ExportFlags = ...
EXPORT_PATCH_ID: ExportFlags = ...
EXPORT_PIXEL_COORDINATE: ExportFlags = ...
EXPORT_RADIUS: ExportFlags = ...
EXPORT_TANGENT: ExportFlags = ...
EXPORT_UV: ExportFlags = ...
IMPORT_BLEED_EDGES: ImportFlags = ...
IMPORT_CENTER_POSITIONS: ImportFlags = ...
IMPORT_FLATTEN: ImportFlags = ...
IMPORT_IGNORE_HIDDEN: ImportFlags = ...
IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
RANGE_INFINITE: RangeUnits = ...
RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
SEARCH_BACKWARD: SearchMethod = ...
SEARCH_BIDIRECTIONAL: SearchMethod = ...
SEARCH_FORWARD: SearchMethod = ...
SEARCH_RADIAL: SearchMethod = ...
staticMetaObject: QMetaObject
EXPORT_ALPHA: ExportFlags = ...
EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
EXPORT_BITANGENT: ExportFlags = ...
EXPORT_CENTER_POSITIONS: ExportFlags = ...
EXPORT_GEOMETRY_ID: ExportFlags = ...
EXPORT_IGNORE_HIDDEN: ExportFlags = ...
EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
EXPORT_MATCH_IMPORT: ExportFlags = ...
EXPORT_NORMAL: ExportFlags = ...
EXPORT_PARTICLE_ID: ExportFlags = ...
EXPORT_PATCH_ID: ExportFlags = ...
EXPORT_PIXEL_COORDINATE: ExportFlags = ...
EXPORT_RADIUS: ExportFlags = ...
EXPORT_TANGENT: ExportFlags = ...
EXPORT_UV: ExportFlags = ...
IMPORT_BLEED_EDGES: ImportFlags = ...
IMPORT_CENTER_POSITIONS: ImportFlags = ...
IMPORT_FLATTEN: ImportFlags = ...
IMPORT_IGNORE_HIDDEN: ImportFlags = ...
IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
RANGE_INFINITE: RangeUnits = ...
RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
SEARCH_BACKWARD: SearchMethod = ...
SEARCH_BIDIRECTIONAL: SearchMethod = ...
SEARCH_FORWARD: SearchMethod = ...
SEARCH_RADIAL: SearchMethod = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def availableOps(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportGeo(self, FileName, Object, UVImageSizes, Flags, Frame, GeoVersion = ...) -> Any: ...
def exportImageSets(self, FileName, ImageSets, Flags, Frame, UVIndices, GeoVersion = ...) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def findOp(self, Name) -> Any: ...
def importImageSets(self, FileName, ImageSets, Interpolation, Flags, Frame, UVIndices, GeoVersion = ..., SearchRange = ..., SearchUnits = ..., Search = ..., SampleCount = ...) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def interpolationMethods(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def rangeUnits(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def searchMethods(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def supportedFileFormats(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def transferChannel(self, SourceChannel, SourceFrame, SourceUVIndices, DestinationObject, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ..., DestinationSize = ...) -> Any: ...
def transferImageSets(self, SourceImageSets, SourceFrame, SourceUVIndices, DestinationImageSets, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., Search = ..., SampleCount = ..., SourceFlags = ...) -> Any: ...
def transferLayers(self, SourceLayers, SourceFrame, SourceUVIndices, DestinationStack, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ...) -> Any: ...
def transferNodes(self, SourceNodes, SourceFrame, SourceUVIndices, DestinationNodeGraph, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ..., DestinationSize = ...) -> Any: ...
