from typing import Any

class ExportFlags:
    EXPORT_ALPHA: ExportFlags = ...
    EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
    EXPORT_BITANGENT: ExportFlags = ...
    EXPORT_CENTER_POSITIONS: ExportFlags = ...
    EXPORT_GEOMETRY_ID: ExportFlags = ...
    EXPORT_IGNORE_HIDDEN: ExportFlags = ...
    EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
    EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
    EXPORT_MATCH_IMPORT: ExportFlags = ...
    EXPORT_NORMAL: ExportFlags = ...
    EXPORT_PARTICLE_ID: ExportFlags = ...
    EXPORT_PATCH_ID: ExportFlags = ...
    EXPORT_PIXEL_COORDINATE: ExportFlags = ...
    EXPORT_RADIUS: ExportFlags = ...
    EXPORT_TANGENT: ExportFlags = ...
    EXPORT_UV: ExportFlags = ...
    name: getset_descriptor
    values: dict

class ImportFlags:
    IMPORT_BLEED_EDGES: ImportFlags = ...
    IMPORT_CENTER_POSITIONS: ImportFlags = ...
    IMPORT_FLATTEN: ImportFlags = ...
    IMPORT_IGNORE_HIDDEN: ImportFlags = ...
    IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
    name: getset_descriptor
    values: dict

class InterpolationMethod:
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
    INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
    name: getset_descriptor
    values: dict

class RangeUnits:
    RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
    RANGE_INFINITE: RangeUnits = ...
    RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
    name: getset_descriptor
    values: dict

class SearchMethod:
    SEARCH_BACKWARD: SearchMethod = ...
    SEARCH_BIDIRECTIONAL: SearchMethod = ...
    SEARCH_FORWARD: SearchMethod = ...
    SEARCH_RADIAL: SearchMethod = ...
    name: getset_descriptor
    values: dict

def availableOps() -> Any: ...
def blockSignals(*args, **kwargs) -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def exportGeo(FileName, Object, UVImageSizes, Flags, Frame, GeoVersion = ...) -> Any: ...
def exportImageSets(FileName, ImageSets, Flags, Frame, UVIndices, GeoVersion = ...) -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def findOp(Name) -> Any: ...
def importImageSets(FileName, ImageSets, Interpolation, Flags, Frame, UVIndices, GeoVersion = ..., SearchRange = ..., SearchUnits = ..., Search = ..., SampleCount = ...) -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def interpolationMethods() -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
def objectName(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def parent(*args, **kwargs) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def rangeUnits() -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def searchMethods() -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def supportedFileFormats() -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def transferChannel(SourceChannel, SourceFrame, SourceUVIndices, DestinationObject, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ..., DestinationSize = ...) -> Any: ...
def transferImageSets(SourceImageSets, SourceFrame, SourceUVIndices, DestinationImageSets, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., Search = ..., SampleCount = ..., SourceFlags = ...) -> Any: ...
def transferLayers(SourceLayers, SourceFrame, SourceUVIndices, DestinationStack, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ...) -> Any: ...
def transferNodes(SourceNodes, SourceFrame, SourceUVIndices, DestinationNodeGraph, DestinationFrame, DestinationUVIndices, Interpolation, DestinationFlags, SourceGeoVersion = ..., DestinationGeoVersion = ..., SearchRange = ..., SearchUnits = ..., FillColor = ..., Search = ..., SampleCount = ..., SourceFlags = ..., DestinationSize = ...) -> Any: ...
