from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class Particle(API):
    class ExportFlags:
        EXPORT_ALPHA: ExportFlags = ...
        EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
        EXPORT_BITANGENT: ExportFlags = ...
        EXPORT_CENTER_POSITIONS: ExportFlags = ...
        EXPORT_GEOMETRY_ID: ExportFlags = ...
        EXPORT_IGNORE_HIDDEN: ExportFlags = ...
        EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
        EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
        EXPORT_MATCH_IMPORT: ExportFlags = ...
        EXPORT_NORMAL: ExportFlags = ...
        EXPORT_PARTICLE_ID: ExportFlags = ...
        EXPORT_PATCH_ID: ExportFlags = ...
        EXPORT_PIXEL_COORDINATE: ExportFlags = ...
        EXPORT_RADIUS: ExportFlags = ...
        EXPORT_TANGENT: ExportFlags = ...
        EXPORT_UV: ExportFlags = ...
        name: getset_descriptor
        values: dict

    class ImportFlags:
        IMPORT_BLEED_EDGES: ImportFlags = ...
        IMPORT_CENTER_POSITIONS: ImportFlags = ...
        IMPORT_FLATTEN: ImportFlags = ...
        IMPORT_IGNORE_HIDDEN: ImportFlags = ...
        IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
        name: getset_descriptor
        values: dict

    class InterpolationMethod:
        INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
        INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
        INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
        INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
        name: getset_descriptor
        values: dict

    class RangeUnits:
        RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
        RANGE_INFINITE: RangeUnits = ...
        RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
        name: getset_descriptor
        values: dict

    class SearchMethod:
        SEARCH_BACKWARD: SearchMethod = ...
        SEARCH_BIDIRECTIONAL: SearchMethod = ...
        SEARCH_FORWARD: SearchMethod = ...
        SEARCH_RADIAL: SearchMethod = ...
        name: getset_descriptor
        values: dict

    EXPORT_ALPHA: ExportFlags = ...
    EXPORT_AMBIENT_OCCLUSION: ExportFlags = ...
    EXPORT_BITANGENT: ExportFlags = ...
    EXPORT_CENTER_POSITIONS: ExportFlags = ...
    EXPORT_GEOMETRY_ID: ExportFlags = ...
    EXPORT_IGNORE_HIDDEN: ExportFlags = ...
    EXPORT_IGNORE_MEMORY_REQUIREMENT: ExportFlags = ...
    EXPORT_IGNORE_UNSELECTED: ExportFlags = ...
    EXPORT_MATCH_IMPORT: ExportFlags = ...
    EXPORT_NORMAL: ExportFlags = ...
    EXPORT_PARTICLE_ID: ExportFlags = ...
    EXPORT_PATCH_ID: ExportFlags = ...
    EXPORT_PIXEL_COORDINATE: ExportFlags = ...
    EXPORT_RADIUS: ExportFlags = ...
    EXPORT_TANGENT: ExportFlags = ...
    EXPORT_UV: ExportFlags = ...
    IMPORT_BLEED_EDGES: ImportFlags = ...
    IMPORT_CENTER_POSITIONS: ImportFlags = ...
    IMPORT_FLATTEN: ImportFlags = ...
    IMPORT_IGNORE_HIDDEN: ImportFlags = ...
    IMPORT_IGNORE_UNSELECTED: ImportFlags = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SHARPER: InterpolationMethod = ...
    INTERPOLATION_INVERSE_DISTANCE_WEIGHTED_SMOOTHER: InterpolationMethod = ...
    INTERPOLATION_NEAREST_NEIGHBOR: InterpolationMethod = ...
    RANGE_GEO_SIZE_PERCENTAGE: RangeUnits = ...
    RANGE_INFINITE: RangeUnits = ...
    RANGE_WORLD_SPACE_UNITS: RangeUnits = ...
    SEARCH_BACKWARD: SearchMethod = ...
    SEARCH_BIDIRECTIONAL: SearchMethod = ...
    SEARCH_FORWARD: SearchMethod = ...
    SEARCH_RADIAL: SearchMethod = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def availableOps(self) -> typing.List: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportGeo(self, FileName: str, Object: mari.GeoEntity, UVImageSizes: typing.Any, Flags: int, Frame: int, GeoVersion: typing.Optional = ...) -> bool: ...
    def exportImageSets(self, FileName: str, ImageSets: typing.Any, Flags: int, Frame: int, UVIndices: typing.Sequence, GeoVersion: typing.Optional = ...) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def findOp(self, Name: str) -> mari.ParticleOp: ...
    def importImageSets(self, FileName: str, ImageSets: typing.Any, Interpolation, Flags: int, Frame: int, UVIndices: typing.Sequence, GeoVersion: typing.Optional = ..., SearchRange: float = ..., SearchUnits = ..., Search = ..., SampleCount: int = ...) -> bool: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def interpolationMethods(self) -> typing.Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def rangeUnits(self) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def searchMethods(self) -> typing.Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def supportedFileFormats(self) -> typing.List: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def transferChannel(self, SourceChannel: mari.Channel, SourceFrame: int, SourceUVIndices: typing.Sequence, DestinationObject: mari.GeoEntity, DestinationFrame: int, DestinationUVIndices: typing.Sequence, Interpolation, DestinationFlags: int, SourceGeoVersion: typing.Optional = ..., DestinationGeoVersion: typing.Optional = ..., SearchRange: float = ..., SearchUnits = ..., FillColor: typing.Optional = ..., Search = ..., SampleCount: int = ..., SourceFlags: int = ..., DestinationSize = ...) -> mari.Channel: ...
    def transferImageSets(self, SourceImageSets: typing.Sequence, SourceFrame: int, SourceUVIndices: typing.Sequence, DestinationImageSets: typing.Sequence, DestinationFrame: int, DestinationUVIndices: typing.Sequence, Interpolation, DestinationFlags: int, SourceGeoVersion: typing.Optional = ..., DestinationGeoVersion: typing.Optional = ..., SearchRange: float = ..., SearchUnits = ..., Search = ..., SampleCount: int = ..., SourceFlags: int = ...) -> bool: ...
    def transferLayers(self, SourceLayers: typing.Sequence, SourceFrame: int, SourceUVIndices: typing.Sequence, DestinationStack: mari.LayerStack, DestinationFrame: int, DestinationUVIndices: typing.Sequence, Interpolation, DestinationFlags: int, SourceGeoVersion: typing.Optional = ..., DestinationGeoVersion: typing.Optional = ..., SearchRange: float = ..., SearchUnits = ..., FillColor: typing.Optional = ..., Search = ..., SampleCount: int = ..., SourceFlags: int = ...) -> typing.List: ...
    def transferNodes(self, SourceNodes: typing.Sequence, SourceFrame: int, SourceUVIndices: typing.Sequence, DestinationNodeGraph: mari.NodeGraph, DestinationFrame: int, DestinationUVIndices: typing.Sequence, Interpolation, DestinationFlags: int, SourceGeoVersion: typing.Optional = ..., DestinationGeoVersion: typing.Optional = ..., SearchRange: float = ..., SearchUnits = ..., FillColor: typing.Optional = ..., Search = ..., SampleCount: int = ..., SourceFlags: int = ..., DestinationSize = ...) -> typing.List: ...
