from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class PatchLinksManager(API):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def canLinkImageInternals(self, Images: typing.Sequence) -> bool: ...
    def canLinkImages(self, Images: typing.Sequence, GroupName: str) -> bool: ...
    def canLinkPatchInternals(self, Patches: typing.Sequence, pImageSet: mari.ImageSet) -> bool: ...
    def canLinkPatches(self, Patches: typing.Sequence, GroupName: str, pImageSet: mari.ImageSet) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def generateUniqueGroupName(self) -> str: ...
    def groupAdded(self, *args, **kwargs) -> Any: ...
    def groupNames(self) -> typing.List: ...
    def groupNamesForImageSet(self, pImageSet: mari.ImageSet) -> typing.List: ...
    def groupRemoved(self, *args, **kwargs) -> Any: ...
    def groupRenamed(self, *args, **kwargs) -> Any: ...
    def imageGroup(self, Img: mari.Image) -> str: ...
    def imageUnlinked(self, *args, **kwargs) -> Any: ...
    def images(self, GroupName: str) -> typing.List: ...
    def imagesLinked(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isImageLinked(self, Img: mari.Image) -> bool: ...
    def isNull(self) -> bool: ...
    def isPatchLinked(self, Patch: mari.GeoPatch, pImageSet: mari.ImageSet) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def linkImages(self, Images: typing.Sequence, GroupName: str) -> Any: ...
    def linkPatches(self, Patches: typing.Sequence, GroupName: str, pImageSet: mari.ImageSet) -> Any: ...
    def linkSelectedPatches(self, GroupName: str, pImageSet: mari.ImageSet) -> Any: ...
    def linkedImages(self, Img: mari.Image) -> typing.List: ...
    def linkedPatches(self, Patch: mari.GeoPatch, pImageSet: typing.Optional = ...) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def patchGroup(self, Patch: mari.GeoPatch, pImageSet: mari.ImageSet) -> str: ...
    def patches(self, GroupName: str, pImageSet: typing.Optional = ...) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeGroup(self, GroupName: str) -> Any: ...
    def renameGroup(self, OldName: str, NewName: str) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def unlinkImage(self, Img: mari.Image) -> Any: ...
    def unlinkPatch(self, Patch: mari.GeoPatch, pImageSet: mari.ImageSet) -> Any: ...
    def unlinkSelectedPatches(self, pImageSet: mari.ImageSet) -> Any: ...
