from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def canLinkImageInternals(self, Images) -> Any: ...
def canLinkImages(self, Images, GroupName) -> Any: ...
def canLinkPatchInternals(self, Patches, pImageSet) -> Any: ...
def canLinkPatches(self, Patches, GroupName, pImageSet) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def generateUniqueGroupName(self) -> Any: ...
def groupAdded(self, *args, **kwargs) -> Any: ...
def groupNames(self) -> Any: ...
def groupNamesForImageSet(self, pImageSet) -> Any: ...
def groupRemoved(self, *args, **kwargs) -> Any: ...
def groupRenamed(self, *args, **kwargs) -> Any: ...
def imageGroup(self, Img) -> Any: ...
def imageUnlinked(self, *args, **kwargs) -> Any: ...
def images(self, GroupName) -> Any: ...
def imagesLinked(self, *args, **kwargs) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isImageLinked(self, Img) -> Any: ...
def isNull(self) -> Any: ...
def isPatchLinked(self, Patch, pImageSet) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def linkImages(self, Images, GroupName) -> Any: ...
def linkPatches(self, Patches, GroupName, pImageSet) -> Any: ...
def linkSelectedPatches(self, GroupName, pImageSet) -> Any: ...
def linkedImages(self, Img) -> Any: ...
def linkedPatches(self, Patch, pImageSet = ...) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def patchGroup(self, Patch, pImageSet) -> Any: ...
def patches(self, GroupName, pImageSet = ...) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeGroup(self, GroupName) -> Any: ...
def renameGroup(self, OldName, NewName) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def unlinkImage(self, Img) -> Any: ...
def unlinkPatch(self, Patch, pImageSet) -> Any: ...
def unlinkSelectedPatches(self, pImageSet) -> Any: ...
