from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ProjectManager(API):
    class AllowedVersions:
        ANY: AllowedVersions = ...
        ASK: AllowedVersions = ...
        EXACT: AllowedVersions = ...
        OLDER_OR_EXACT: AllowedVersions = ...
        name: getset_descriptor
        values: dict

    class MeshOptions:
        FORCE_EMPTY: MeshOptions = ...
        FORCE_PTEX: MeshOptions = ...
        UV_OR_EMPTY: MeshOptions = ...
        UV_OR_PTEX: MeshOptions = ...
        name: getset_descriptor
        values: dict

    class MultipleGeometryOptions:
        KEEP_SEPARATE: MultipleGeometryOptions = ...
        MERGE_GEOMETRIES: MultipleGeometryOptions = ...
        name: getset_descriptor
        values: dict

    class OCIOOptions:
        OCIO_ASK: OCIOOptions = ...
        OCIO_EXACT: OCIOOptions = ...
        OCIO_REMAP: OCIOOptions = ...
        OCIO_RESET: OCIOOptions = ...
        name: getset_descriptor
        values: dict

    class PtexFaceSizeScheme:
        PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
        PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
        name: getset_descriptor
        values: dict

    class PtexFormat:
        PTEXFORMAT_BYTE: PtexFormat = ...
        PTEXFORMAT_FLOAT: PtexFormat = ...
        PTEXFORMAT_HALF: PtexFormat = ...
        name: getset_descriptor
        values: dict

    ANY: AllowedVersions = ...
    ASK: AllowedVersions = ...
    EXACT: AllowedVersions = ...
    FORCE_EMPTY: MeshOptions = ...
    FORCE_PTEX: MeshOptions = ...
    KEEP_SEPARATE: MultipleGeometryOptions = ...
    MERGE_GEOMETRIES: MultipleGeometryOptions = ...
    OCIO_ASK: OCIOOptions = ...
    OCIO_EXACT: OCIOOptions = ...
    OCIO_REMAP: OCIOOptions = ...
    OCIO_RESET: OCIOOptions = ...
    OLDER_OR_EXACT: AllowedVersions = ...
    PTEXFORMAT_BYTE: PtexFormat = ...
    PTEXFORMAT_FLOAT: PtexFormat = ...
    PTEXFORMAT_HALF: PtexFormat = ...
    PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
    PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
    UV_OR_EMPTY: MeshOptions = ...
    UV_OR_PTEX: MeshOptions = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def generateUUID() -> str: ...
    @staticmethod
    def registerUserData() -> int: ...
    def aboutToArchive(self, *args, **kwargs) -> Any: ...
    def aboutToClose(self, *args, **kwargs) -> Any: ...
    def aboutToExport(self, *args, **kwargs) -> Any: ...
    def aboutToExtractArchive(self, *args, **kwargs) -> Any: ...
    def aboutToOpen(self, *args, **kwargs) -> Any: ...
    def aboutToSave(self, *args, **kwargs) -> Any: ...
    def aboutToSaveNew(self, *args, **kwargs) -> Any: ...
    def archive(self, rUUIDOrName: str, rTargetFileName: str, ArchiveAll: bool = ..., KeepOnError: bool = ...) -> Any: ...
    def archiveBackup(self, UUIDOrName: str, rTargetFileName: str, rSuffix: str = ..., ArchiveAll: bool = ..., KeepOnError: bool = ...) -> Any: ...
    def archived(self, *args, **kwargs) -> Any: ...
    def backupRestored(self, *args, **kwargs) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def cachePath(self) -> str: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def close(self, ConfirmIfModified: bool = ...) -> Any: ...
    def closed(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def copy(self, rUUIDOrName: str) -> mari.ProjectInfo: ...
    def create(self, Name: str, MeshPaths: typing.Any, ChannelsToCreate: typing.Sequence, ChannelsToImport: typing.Sequence = ..., ProjectMetaOptions: typing.Any = ..., ObjectsToLoad: typing.Any = ..., ColorspaceSettings: typing.Optional = ..., UUID: str = ..., GarbageCollectionEnabled: bool = ...) -> Any: ...
    def created(self, *args, **kwargs) -> Any: ...
    def current(self) -> mari.Project: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def duplicate(self, rUUIDOrName: str) -> mari.ProjectInfo: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exported(self, *args, **kwargs) -> Any: ...
    def exportedSummary(self, *args, **kwargs) -> Any: ...
    def extract(self, rFileName: str) -> mari.ProjectInfo: ...
    def extractedArchive(self, *args, **kwargs) -> Any: ...
    def find(self, rUUIDOrName: str) -> mari.ProjectInfo: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def generateRestoreSuffix(self, rTags: typing.Sequence = ...) -> str: ...
    def get(self, rUUIDOrName: str) -> mari.ProjectInfo: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lastRestorePoint(self, rPath: str) -> str: ...
    def list(self) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def names(self) -> typing.List: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def open(self, rUUIDOrName: str, Allowed = ..., OCIO: typing.Any = ..., GarbageCollectionEnabled: bool = ...) -> mari.Project: ...
    def opened(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def projectDuplicated(self, *args, **kwargs) -> Any: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def remove(self, rUUIDOrName: str) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def rename(self, OldName: str, NewName: str) -> Any: ...
    def repair(self, UUIDOrName: str, rSourcePath: str = ..., rSourceSuffix: str = ...) -> Any: ...
    def restoreBackup(self, rPath: str, UUIDOrName: str = ..., Suffix: str = ...) -> mari.ProjectInfo: ...
    def restorePoints(self, rPath: str, rTags: typing.Sequence = ...) -> typing.List: ...
    def restoreTags(self, rPath: str) -> typing.List: ...
    def saved(self, *args, **kwargs) -> Any: ...
    def selected(self) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRestoreSystemTags(self, rTags: typing.Sequence) -> Any: ...
    def showCreateDialog(self) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def triggerBackup(self, rCommands: typing.Sequence = ..., rPaths: typing.Sequence = ..., Force: bool = ..., Threads: int = ...) -> Any: ...
    def updateAvailableProjects(self) -> Any: ...
