from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class Projector(Metadata):
    class BitDepth:
        DEPTH_BYTE: BitDepth = ...
        DEPTH_FLOAT: BitDepth = ...
        DEPTH_HALF: BitDepth = ...
        name: getset_descriptor
        values: dict

    class DepthProjectionMode:
        FRONT: DepthProjectionMode = ...
        THROUGH: DepthProjectionMode = ...
        name: getset_descriptor
        values: dict

    class LightingMode:
        BASIC: LightingMode = ...
        FLAT: LightingMode = ...
        FULL: LightingMode = ...
        name: getset_descriptor
        values: dict

    class MetadataFlag:
        METADATA_EDITABLE: MetadataFlag = ...
        METADATA_REMOVABLE: MetadataFlag = ...
        METADATA_REMOVEABLE: MetadataFlag = ...
        METADATA_SAVED: MetadataFlag = ...
        METADATA_UNDOABLE: MetadataFlag = ...
        METADATA_VISIBLE: MetadataFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataFlags:
        pass

    class MetadataGroupHint:
        METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
        METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
        name: getset_descriptor
        values: dict

    class MetadataGroupHints:
        pass

    class MetadataTypeFlag:
        METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
        METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
        name: getset_descriptor
        values: dict

    class MetadataTypeFlags:
        pass

    BASIC: LightingMode = ...
    DEPTH_BYTE: BitDepth = ...
    DEPTH_FLOAT: BitDepth = ...
    DEPTH_HALF: BitDepth = ...
    FLAT: LightingMode = ...
    FRONT: DepthProjectionMode = ...
    FULL: LightingMode = ...
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    THROUGH: DepthProjectionMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def isSupportedMetadataType(Value: typing.Any) -> bool: ...
    @staticmethod
    def registerUserData() -> int: ...
    def aboutToSaveImage(self, *args, **kwargs) -> Any: ...
    def bitDepth(self) -> Any: ...
    def blockSignals(self, b: bool) -> bool: ...
    def camera(self) -> mari.Camera: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def clampColors(self) -> bool: ...
    def colorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def depthProjectionMode(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportColorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def exportColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def exportOptions(self) -> typing.Any: ...
    def exportPath(self) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def format(self) -> str: ...
    def frameOffset(self) -> int: ...
    def frameOffsetChanged(self, *args, **kwargs) -> Any: ...
    def hasMetadata(self, Name: str) -> bool: ...
    def height(self) -> int: ...
    def importColorspaceConfig(self) -> mari.ColorspaceConfig: ...
    def importColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
    def importFromFile(self, Path: str = ...) -> Any: ...
    def importPath(self) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def lightingMode(self) -> Any: ...
    def makeCurrent(self) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def metadata(self, Name: str) -> typing.Any: ...
    def metadataAsImage(self, Name: str) -> mari.Image: ...
    def metadataCreated(self, *args, **kwargs) -> Any: ...
    def metadataDefault(self, Name: str) -> typing.Any: ...
    def metadataDescription(self, Name: str) -> str: ...
    def metadataDisplayName(self, Name: str) -> str: ...
    def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
    def metadataFlags(self, Name: str) -> mari.MetadataFlags: ...
    def metadataIsEnabled(self, Name: str) -> bool: ...
    def metadataItemList(self, Name: str) -> typing.List: ...
    def metadataMax(self, Name: str) -> typing.Any: ...
    def metadataMin(self, Name: str) -> typing.Any: ...
    def metadataNames(self) -> typing.List: ...
    def metadataRemoved(self, *args, **kwargs) -> Any: ...
    def metadataStep(self, Name: str) -> typing.Any: ...
    def metadataTypeFlags(self, Name: str) -> mari.MetadataTypeFlags: ...
    def metadataValueChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def nameChanged(self, *args, **kwargs) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def paintingMode(self) -> Any: ...
    def paintingModePath(self) -> str: ...
    def paintingModeStr(self) -> str: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def project(self) -> Any: ...
    def projectFromFile(self, Path: str = ...) -> Any: ...
    def projectionMaskNameList(self) -> typing.List: ...
    def projectionMaskProperty(self, MaskName: str, PropertyName: str) -> typing.Any: ...
    def projectionMaskPropertyList(self, MaskName: str) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeMetadata(self, Name: str) -> Any: ...
    def rotation(self) -> float: ...
    def save(self, FileName: str) -> Any: ...
    def scale(self) -> mari.VectorN: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setBitDepth(self, Depth) -> Any: ...
    def setClampColors(self, ClampColors: bool) -> Any: ...
    def setColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setDepthProjectionMode(self, ProjectionMode) -> Any: ...
    def setExportColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setExportOptions(self, Options: typing.Any) -> Any: ...
    def setExportPath(self, Path: str) -> Any: ...
    def setFormat(self, Format: str) -> Any: ...
    def setFrameOffset(self, Offset: int) -> Any: ...
    def setImportColorspaceConfig(self, Config: mari.ColorspaceConfig) -> Any: ...
    def setImportPath(self, Path: str) -> Any: ...
    def setLightingMode(self, NewMode) -> Any: ...
    def setMetadata(self, Name: str, Value: typing.Any) -> Any: ...
    def setMetadataDefault(self, Name: str, Default: typing.Any) -> Any: ...
    def setMetadataDescription(self, Name: str, Description: str) -> Any: ...
    def setMetadataDisplayName(self, Name: str, DisplayName: str) -> Any: ...
    def setMetadataEnabled(self, Name: str, Enabled: bool) -> Any: ...
    def setMetadataFlags(self, Name: str, Flags: mari.MetadataFlags) -> Any: ...
    def setMetadataGroupHints(self, Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
    def setMetadataItemList(self, Name: str, ItemList: typing.Sequence) -> Any: ...
    def setMetadataRange(self, Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
    def setMetadataStep(self, Name: str, Step: typing.Any) -> Any: ...
    def setMetadataTypeFlags(self, Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
    def setName(self, Name: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setPaintingMode(self, PaintingMode: typing.Any) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProjectionMaskProperty(self, MaskName: str, PropertyName: str, Value: typing.Any) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setRotation(self, Rotation: float) -> Any: ...
    def setScale(self, pScale: mari.VectorN) -> Any: ...
    def setSize(self, Width: int, Height: int) -> Any: ...
    def setTranslation(self, pTranslation: mari.VectorN) -> Any: ...
    def setUseShader(self, UseShader: str) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def translation(self) -> mari.VectorN: ...
    def unproject(self, SaveOptions: int = ...) -> Any: ...
    def unprojectToFile(self, Path: str = ..., Options: typing.Any = ..., SaveOptions: int = ...) -> Any: ...
    def useShader(self) -> str: ...
    def useShaderList(self) -> typing.List: ...
    def uuid(self) -> str: ...
    def width(self) -> int: ...
