from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class AllowedVersions:
    ANY: AllowedVersions = ...
    ASK: AllowedVersions = ...
    EXACT: AllowedVersions = ...
    OLDER_OR_EXACT: AllowedVersions = ...
    name: getset_descriptor
    values: dict

class MeshOptions:
    FORCE_EMPTY: MeshOptions = ...
    FORCE_PTEX: MeshOptions = ...
    UV_OR_EMPTY: MeshOptions = ...
    UV_OR_PTEX: MeshOptions = ...
    name: getset_descriptor
    values: dict

class MultipleGeometryOptions:
    KEEP_SEPARATE: MultipleGeometryOptions = ...
    MERGE_GEOMETRIES: MultipleGeometryOptions = ...
    name: getset_descriptor
    values: dict

class OCIOOptions:
    OCIO_ASK: OCIOOptions = ...
    OCIO_EXACT: OCIOOptions = ...
    OCIO_REMAP: OCIOOptions = ...
    OCIO_RESET: OCIOOptions = ...
    name: getset_descriptor
    values: dict

class PtexFaceSizeScheme:
    PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
    PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
    name: getset_descriptor
    values: dict

class PtexFormat:
    PTEXFORMAT_BYTE: PtexFormat = ...
    PTEXFORMAT_FLOAT: PtexFormat = ...
    PTEXFORMAT_HALF: PtexFormat = ...
    name: getset_descriptor
    values: dict

ANY: AllowedVersions = ...
ASK: AllowedVersions = ...
EXACT: AllowedVersions = ...
FORCE_EMPTY: MeshOptions = ...
FORCE_PTEX: MeshOptions = ...
KEEP_SEPARATE: MultipleGeometryOptions = ...
MERGE_GEOMETRIES: MultipleGeometryOptions = ...
OCIO_ASK: OCIOOptions = ...
OCIO_EXACT: OCIOOptions = ...
OCIO_REMAP: OCIOOptions = ...
OCIO_RESET: OCIOOptions = ...
OLDER_OR_EXACT: AllowedVersions = ...
PTEXFORMAT_BYTE: PtexFormat = ...
PTEXFORMAT_FLOAT: PtexFormat = ...
PTEXFORMAT_HALF: PtexFormat = ...
PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
UV_OR_EMPTY: MeshOptions = ...
UV_OR_PTEX: MeshOptions = ...
staticMetaObject: QMetaObject
ANY: AllowedVersions = ...
ASK: AllowedVersions = ...
EXACT: AllowedVersions = ...
FORCE_EMPTY: MeshOptions = ...
FORCE_PTEX: MeshOptions = ...
KEEP_SEPARATE: MultipleGeometryOptions = ...
MERGE_GEOMETRIES: MultipleGeometryOptions = ...
OCIO_ASK: OCIOOptions = ...
OCIO_EXACT: OCIOOptions = ...
OCIO_REMAP: OCIOOptions = ...
OCIO_RESET: OCIOOptions = ...
OLDER_OR_EXACT: AllowedVersions = ...
PTEXFORMAT_BYTE: PtexFormat = ...
PTEXFORMAT_FLOAT: PtexFormat = ...
PTEXFORMAT_HALF: PtexFormat = ...
PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
UV_OR_EMPTY: MeshOptions = ...
UV_OR_PTEX: MeshOptions = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def generateUUID() -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def aboutToArchive(self, *args, **kwargs) -> Any: ...
def aboutToClose(self, *args, **kwargs) -> Any: ...
def aboutToExport(self, *args, **kwargs) -> Any: ...
def aboutToExtractArchive(self, *args, **kwargs) -> Any: ...
def aboutToOpen(self, *args, **kwargs) -> Any: ...
def aboutToSave(self, *args, **kwargs) -> Any: ...
def aboutToSaveNew(self, *args, **kwargs) -> Any: ...
def archive(self, rUUIDOrName, rTargetFileName, ArchiveAll = ..., KeepOnError = ...) -> Any: ...
def archiveBackup(self, UUIDOrName, rTargetFileName, rSuffix = ..., ArchiveAll = ..., KeepOnError = ...) -> Any: ...
def archived(self, *args, **kwargs) -> Any: ...
def backupRestored(self, *args, **kwargs) -> Any: ...
def blockSignals(self, b) -> Any: ...
def cachePath(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def close(self, ConfirmIfModified = ...) -> Any: ...
def closed(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def copy(self, rUUIDOrName) -> Any: ...
def create(self, Name, MeshPaths, ChannelsToCreate, ChannelsToImport = ..., ProjectMetaOptions = ..., ObjectsToLoad = ..., ColorspaceSettings = ..., UUID = ..., GarbageCollectionEnabled = ...) -> Any: ...
def created(self, *args, **kwargs) -> Any: ...
def current(self) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def duplicate(self, rUUIDOrName) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exported(self, *args, **kwargs) -> Any: ...
def exportedSummary(self, *args, **kwargs) -> Any: ...
def extract(self, rFileName) -> Any: ...
def extractedArchive(self, *args, **kwargs) -> Any: ...
def find(self, rUUIDOrName) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def generateRestoreSuffix(self, rTags = ...) -> Any: ...
def get(self, rUUIDOrName) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lastRestorePoint(self, rPath) -> Any: ...
def list(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def names(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def open(self, rUUIDOrName, Allowed = ..., OCIO = ..., GarbageCollectionEnabled = ...) -> Any: ...
def opened(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def projectDuplicated(self, *args, **kwargs) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def remove(self, rUUIDOrName) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def rename(self, OldName, NewName) -> Any: ...
def repair(self, UUIDOrName, rSourcePath = ..., rSourceSuffix = ...) -> Any: ...
def restoreBackup(self, rPath, UUIDOrName = ..., Suffix = ...) -> Any: ...
def restorePoints(self, rPath, rTags = ...) -> Any: ...
def restoreTags(self, rPath) -> Any: ...
def saved(self, *args, **kwargs) -> Any: ...
def selected(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRestoreSystemTags(self, rTags) -> Any: ...
def showCreateDialog(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def triggerBackup(self, rCommands = ..., rPaths = ..., Force = ..., Threads = ...) -> Any: ...
def updateAvailableProjects(self) -> Any: ...
