from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class BitDepth:
    DEPTH_BYTE: BitDepth = ...
    DEPTH_FLOAT: BitDepth = ...
    DEPTH_HALF: BitDepth = ...
    name: getset_descriptor
    values: dict

class DepthProjectionMode:
    FRONT: DepthProjectionMode = ...
    THROUGH: DepthProjectionMode = ...
    name: getset_descriptor
    values: dict

class LightingMode:
    BASIC: LightingMode = ...
    FLAT: LightingMode = ...
    FULL: LightingMode = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

BASIC: LightingMode = ...
DEPTH_BYTE: BitDepth = ...
DEPTH_FLOAT: BitDepth = ...
DEPTH_HALF: BitDepth = ...
FLAT: LightingMode = ...
FRONT: DepthProjectionMode = ...
FULL: LightingMode = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
THROUGH: DepthProjectionMode = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def aboutToSaveImage(self, *args, **kwargs) -> Any: ...
def bitDepth(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def camera(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def clampColors(self) -> Any: ...
def colorspaceConfig(self) -> Any: ...
def colorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def depthProjectionMode(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportColorspaceConfig(self) -> Any: ...
def exportColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def exportOptions(self) -> Any: ...
def exportPath(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def format(self) -> Any: ...
def frameOffset(self) -> Any: ...
def frameOffsetChanged(self, *args, **kwargs) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def height(self) -> Any: ...
def importColorspaceConfig(self) -> Any: ...
def importColorspaceConfigChanged(self, *args, **kwargs) -> Any: ...
def importFromFile(self, Path = ...) -> Any: ...
def importPath(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lightingMode(self) -> Any: ...
def makeCurrent(self) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def paintingMode(self) -> Any: ...
def paintingModePath(self) -> Any: ...
def paintingModeStr(self) -> Any: ...
def parent(self) -> Any: ...
def project(self) -> Any: ...
def projectFromFile(self, Path = ...) -> Any: ...
def projectionMaskNameList(self) -> Any: ...
def projectionMaskProperty(self, MaskName, PropertyName) -> Any: ...
def projectionMaskPropertyList(self, MaskName) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def rotation(self) -> Any: ...
def save(self, FileName) -> Any: ...
def scale(self) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setBitDepth(self, Depth) -> Any: ...
def setClampColors(self, ClampColors) -> Any: ...
def setColorspaceConfig(self, Config) -> Any: ...
def setDepthProjectionMode(self, ProjectionMode) -> Any: ...
def setExportColorspaceConfig(self, Config) -> Any: ...
def setExportOptions(self, Options) -> Any: ...
def setExportPath(self, Path) -> Any: ...
def setFormat(self, Format) -> Any: ...
def setFrameOffset(self, Offset) -> Any: ...
def setImportColorspaceConfig(self, Config) -> Any: ...
def setImportPath(self, Path) -> Any: ...
def setLightingMode(self, NewMode) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, Name) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setPaintingMode(self, PaintingMode) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProjectionMaskProperty(self, MaskName, PropertyName, Value) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setRotation(self, Rotation) -> Any: ...
def setScale(self, pScale) -> Any: ...
def setSize(self, Width, Height) -> Any: ...
def setTranslation(self, pTranslation) -> Any: ...
def setUseShader(self, UseShader) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def translation(self) -> Any: ...
def unproject(self, SaveOptions = ...) -> Any: ...
def unprojectToFile(self, Path = ..., Options = ..., SaveOptions = ...) -> Any: ...
def useShader(self) -> Any: ...
def useShaderList(self) -> Any: ...
def uuid(self) -> Any: ...
def width(self) -> Any: ...
