from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class BitDepth:
    DEPTH_BYTE: BitDepth = ...
    DEPTH_FLOAT: BitDepth = ...
    DEPTH_HALF: BitDepth = ...
    name: getset_descriptor
    values: dict

class DepthProjectionMode:
    FRONT: DepthProjectionMode = ...
    THROUGH: DepthProjectionMode = ...
    name: getset_descriptor
    values: dict

class LightingMode:
    BASIC: LightingMode = ...
    FLAT: LightingMode = ...
    FULL: LightingMode = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

BASIC: LightingMode = ...
DEPTH_BYTE: BitDepth = ...
DEPTH_FLOAT: BitDepth = ...
DEPTH_HALF: BitDepth = ...
FLAT: LightingMode = ...
FRONT: DepthProjectionMode = ...
FULL: LightingMode = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
THROUGH: DepthProjectionMode = ...
staticMetaObject: QMetaObject
BASIC: LightingMode = ...
DEPTH_BYTE: BitDepth = ...
DEPTH_FLOAT: BitDepth = ...
DEPTH_HALF: BitDepth = ...
FLAT: LightingMode = ...
FRONT: DepthProjectionMode = ...
FULL: LightingMode = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
THROUGH: DepthProjectionMode = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value: typing.Any) -> bool: ...
@staticmethod
def registerUserData() -> int: ...
def aboutToSaveImage(*args, **kwargs) -> Any: ...
def bitDepth() -> Any: ...
def blockSignals(b: bool) -> bool: ...
def camera() -> mari.Camera: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def clampColors() -> bool: ...
def colorspaceConfig() -> mari.ColorspaceConfig: ...
def colorspaceConfigChanged(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def depthProjectionMode() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportColorspaceConfig() -> mari.ColorspaceConfig: ...
def exportColorspaceConfigChanged(*args, **kwargs) -> Any: ...
def exportOptions() -> typing.Any: ...
def exportPath() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def format() -> str: ...
def frameOffset() -> int: ...
def frameOffsetChanged(*args, **kwargs) -> Any: ...
def hasMetadata(Name: str) -> bool: ...
def height() -> int: ...
def importColorspaceConfig() -> mari.ColorspaceConfig: ...
def importColorspaceConfigChanged(*args, **kwargs) -> Any: ...
def importFromFile(Path: str = ...) -> Any: ...
def importPath() -> str: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lightingMode() -> Any: ...
def makeCurrent() -> Any: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def metadata(Name: str) -> typing.Any: ...
def metadataAsImage(Name: str) -> mari.Image: ...
def metadataCreated(*args, **kwargs) -> Any: ...
def metadataDefault(Name: str) -> typing.Any: ...
def metadataDescription(Name: str) -> str: ...
def metadataDisplayName(Name: str) -> str: ...
def metadataEnabledChanged(*args, **kwargs) -> Any: ...
def metadataFlags(Name: str) -> mari.MetadataFlags: ...
def metadataIsEnabled(Name: str) -> bool: ...
def metadataItemList(Name: str) -> typing.List: ...
def metadataMax(Name: str) -> typing.Any: ...
def metadataMin(Name: str) -> typing.Any: ...
def metadataNames() -> typing.List: ...
def metadataRemoved(*args, **kwargs) -> Any: ...
def metadataStep(Name: str) -> typing.Any: ...
def metadataTypeFlags(Name: str) -> mari.MetadataTypeFlags: ...
def metadataValueChanged(*args, **kwargs) -> Any: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def name() -> str: ...
def nameChanged(*args, **kwargs) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def paintingMode() -> Any: ...
def paintingModePath() -> str: ...
def paintingModeStr() -> str: ...
def parent() -> PySide2.QtCore.QObject: ...
def project() -> Any: ...
def projectFromFile(Path: str = ...) -> Any: ...
def projectionMaskNameList() -> typing.List: ...
def projectionMaskProperty(MaskName: str, PropertyName: str) -> typing.Any: ...
def projectionMaskPropertyList(MaskName: str) -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeMetadata(Name: str) -> Any: ...
def rotation() -> float: ...
def save(FileName: str) -> Any: ...
def scale() -> mari.VectorN: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setBitDepth(Depth) -> Any: ...
def setClampColors(ClampColors: bool) -> Any: ...
def setColorspaceConfig(Config: mari.ColorspaceConfig) -> Any: ...
def setDepthProjectionMode(ProjectionMode) -> Any: ...
def setExportColorspaceConfig(Config: mari.ColorspaceConfig) -> Any: ...
def setExportOptions(Options: typing.Any) -> Any: ...
def setExportPath(Path: str) -> Any: ...
def setFormat(Format: str) -> Any: ...
def setFrameOffset(Offset: int) -> Any: ...
def setImportColorspaceConfig(Config: mari.ColorspaceConfig) -> Any: ...
def setImportPath(Path: str) -> Any: ...
def setLightingMode(NewMode) -> Any: ...
def setMetadata(Name: str, Value: typing.Any) -> Any: ...
def setMetadataDefault(Name: str, Default: typing.Any) -> Any: ...
def setMetadataDescription(Name: str, Description: str) -> Any: ...
def setMetadataDisplayName(Name: str, DisplayName: str) -> Any: ...
def setMetadataEnabled(Name: str, Enabled: bool) -> Any: ...
def setMetadataFlags(Name: str, Flags: mari.MetadataFlags) -> Any: ...
def setMetadataGroupHints(Name: str, Hints: mari.MetadataGroupHints) -> Any: ...
def setMetadataItemList(Name: str, ItemList: typing.Sequence) -> Any: ...
def setMetadataRange(Name: str, Min: typing.Any, Max: typing.Any) -> Any: ...
def setMetadataStep(Name: str, Step: typing.Any) -> Any: ...
def setMetadataTypeFlags(Name: str, Flags: mari.MetadataTypeFlags) -> Any: ...
def setName(Name: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setPaintingMode(PaintingMode: typing.Any) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProjectionMaskProperty(MaskName: str, PropertyName: str, Value: typing.Any) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setRotation(Rotation: float) -> Any: ...
def setScale(pScale: mari.VectorN) -> Any: ...
def setSize(Width: int, Height: int) -> Any: ...
def setTranslation(pTranslation: mari.VectorN) -> Any: ...
def setUseShader(UseShader: str) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def translation() -> mari.VectorN: ...
def unproject(SaveOptions: int = ...) -> Any: ...
def unprojectToFile(Path: str = ..., Options: typing.Any = ..., SaveOptions: int = ...) -> Any: ...
def useShader() -> str: ...
def useShaderList() -> typing.List: ...
def uuid() -> str: ...
def width() -> int: ...
