from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class AllowedVersions:
    ANY: AllowedVersions = ...
    ASK: AllowedVersions = ...
    EXACT: AllowedVersions = ...
    OLDER_OR_EXACT: AllowedVersions = ...
    name: getset_descriptor
    values: dict

class MeshOptions:
    FORCE_EMPTY: MeshOptions = ...
    FORCE_PTEX: MeshOptions = ...
    UV_OR_EMPTY: MeshOptions = ...
    UV_OR_PTEX: MeshOptions = ...
    name: getset_descriptor
    values: dict

class MultipleGeometryOptions:
    KEEP_SEPARATE: MultipleGeometryOptions = ...
    MERGE_GEOMETRIES: MultipleGeometryOptions = ...
    name: getset_descriptor
    values: dict

class OCIOOptions:
    OCIO_ASK: OCIOOptions = ...
    OCIO_EXACT: OCIOOptions = ...
    OCIO_REMAP: OCIOOptions = ...
    OCIO_RESET: OCIOOptions = ...
    name: getset_descriptor
    values: dict

class PtexFaceSizeScheme:
    PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
    PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
    name: getset_descriptor
    values: dict

class PtexFormat:
    PTEXFORMAT_BYTE: PtexFormat = ...
    PTEXFORMAT_FLOAT: PtexFormat = ...
    PTEXFORMAT_HALF: PtexFormat = ...
    name: getset_descriptor
    values: dict

ANY: AllowedVersions = ...
ASK: AllowedVersions = ...
EXACT: AllowedVersions = ...
FORCE_EMPTY: MeshOptions = ...
FORCE_PTEX: MeshOptions = ...
KEEP_SEPARATE: MultipleGeometryOptions = ...
MERGE_GEOMETRIES: MultipleGeometryOptions = ...
OCIO_ASK: OCIOOptions = ...
OCIO_EXACT: OCIOOptions = ...
OCIO_REMAP: OCIOOptions = ...
OCIO_RESET: OCIOOptions = ...
OLDER_OR_EXACT: AllowedVersions = ...
PTEXFORMAT_BYTE: PtexFormat = ...
PTEXFORMAT_FLOAT: PtexFormat = ...
PTEXFORMAT_HALF: PtexFormat = ...
PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
UV_OR_EMPTY: MeshOptions = ...
UV_OR_PTEX: MeshOptions = ...
staticMetaObject: QMetaObject
ANY: AllowedVersions = ...
ASK: AllowedVersions = ...
EXACT: AllowedVersions = ...
FORCE_EMPTY: MeshOptions = ...
FORCE_PTEX: MeshOptions = ...
KEEP_SEPARATE: MultipleGeometryOptions = ...
MERGE_GEOMETRIES: MultipleGeometryOptions = ...
OCIO_ASK: OCIOOptions = ...
OCIO_EXACT: OCIOOptions = ...
OCIO_REMAP: OCIOOptions = ...
OCIO_RESET: OCIOOptions = ...
OLDER_OR_EXACT: AllowedVersions = ...
PTEXFORMAT_BYTE: PtexFormat = ...
PTEXFORMAT_FLOAT: PtexFormat = ...
PTEXFORMAT_HALF: PtexFormat = ...
PTEX_UNIFORM_SIZE: PtexFaceSizeScheme = ...
PTEX_WORLD_SPACE_DENSITY_SIZE: PtexFaceSizeScheme = ...
UV_OR_EMPTY: MeshOptions = ...
UV_OR_PTEX: MeshOptions = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def generateUUID() -> str: ...
@staticmethod
def registerUserData() -> int: ...
def aboutToArchive(*args, **kwargs) -> Any: ...
def aboutToClose(*args, **kwargs) -> Any: ...
def aboutToExport(*args, **kwargs) -> Any: ...
def aboutToExtractArchive(*args, **kwargs) -> Any: ...
def aboutToOpen(*args, **kwargs) -> Any: ...
def aboutToSave(*args, **kwargs) -> Any: ...
def aboutToSaveNew(*args, **kwargs) -> Any: ...
def archive(rUUIDOrName: str, rTargetFileName: str, ArchiveAll: bool = ..., KeepOnError: bool = ...) -> Any: ...
def archiveBackup(UUIDOrName: str, rTargetFileName: str, rSuffix: str = ..., ArchiveAll: bool = ..., KeepOnError: bool = ...) -> Any: ...
def archived(*args, **kwargs) -> Any: ...
def backupRestored(*args, **kwargs) -> Any: ...
def blockSignals(b: bool) -> bool: ...
def cachePath() -> str: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def close(ConfirmIfModified: bool = ...) -> Any: ...
def closed(*args, **kwargs) -> Any: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def copy(rUUIDOrName: str) -> mari.ProjectInfo: ...
def create(Name: str, MeshPaths: typing.Any, ChannelsToCreate: typing.Sequence, ChannelsToImport: typing.Sequence = ..., ProjectMetaOptions: typing.Any = ..., ObjectsToLoad: typing.Any = ..., ColorspaceSettings: typing.Optional = ..., UUID: str = ..., GarbageCollectionEnabled: bool = ...) -> Any: ...
def created(*args, **kwargs) -> Any: ...
def current() -> mari.Project: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def duplicate(rUUIDOrName: str) -> mari.ProjectInfo: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exported(*args, **kwargs) -> Any: ...
def exportedSummary(*args, **kwargs) -> Any: ...
def extract(rFileName: str) -> mari.ProjectInfo: ...
def extractedArchive(*args, **kwargs) -> Any: ...
def find(rUUIDOrName: str) -> mari.ProjectInfo: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def generateRestoreSuffix(rTags: typing.Sequence = ...) -> str: ...
def get(rUUIDOrName: str) -> mari.ProjectInfo: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def lastRestorePoint(rPath: str) -> str: ...
def list() -> typing.List: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def names() -> typing.List: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def open(rUUIDOrName: str, Allowed = ..., OCIO: typing.Any = ..., GarbageCollectionEnabled: bool = ...) -> mari.Project: ...
def opened(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def projectDuplicated(*args, **kwargs) -> Any: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def remove(rUUIDOrName: str) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def rename(OldName: str, NewName: str) -> Any: ...
def repair(UUIDOrName: str, rSourcePath: str = ..., rSourceSuffix: str = ...) -> Any: ...
def restoreBackup(rPath: str, UUIDOrName: str = ..., Suffix: str = ...) -> mari.ProjectInfo: ...
def restorePoints(rPath: str, rTags: typing.Sequence = ...) -> typing.List: ...
def restoreTags(rPath: str) -> typing.List: ...
def saved(*args, **kwargs) -> Any: ...
def selected() -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setRestoreSystemTags(rTags: typing.Sequence) -> Any: ...
def showCreateDialog() -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def triggerBackup(rCommands: typing.Sequence = ..., rPaths: typing.Sequence = ..., Force: bool = ..., Threads: int = ...) -> Any: ...
def updateAvailableProjects() -> Any: ...
