from typing import Any

fdel: getset_descriptor
fget: getset_descriptor
freset: getset_descriptor
fset: getset_descriptor
def deleter(self, func) -> Any: ...
def getter(self, func) -> Any: ...
def read(self, func) -> Any: ...
def resetter(self, *args, **kwargs) -> Any: ...
def setter(self, func) -> Any: ...
def write(self, func) -> Any: ...
