from typing import Any

fdel: getset_descriptor
fget: getset_descriptor
freset: getset_descriptor
fset: getset_descriptor
def deleter(func: typing.Callable) -> Any: ...
def getter(func: typing.Callable) -> Any: ...
def read(func: typing.Callable) -> Any: ...
def resetter(*args, **kwargs) -> Any: ...
def setter(func: typing.Callable) -> Any: ...
def write(func: typing.Callable) -> Any: ...
