from typing import Any

class Property:
    fdel: getset_descriptor
    fget: getset_descriptor
    freset: getset_descriptor
    fset: getset_descriptor
    def deleter(self, func: typing.Callable) -> Any: ...
    def getter(self, func: typing.Callable) -> Any: ...
    def read(self, func: typing.Callable) -> Any: ...
    def resetter(self, *args, **kwargs) -> Any: ...
    def setter(self, func: typing.Callable) -> Any: ...
    def write(self, func: typing.Callable) -> Any: ...
