from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ResourceInfo(API):
    staticMetaObject: QMetaObject
    @staticmethod
    def bundledUsdPath() -> str: ...
    @staticmethod
    def cAPIDocPathKey() -> str: ...
    @staticmethod
    def cAPIExamplesPathKey() -> str: ...
    @staticmethod
    def certificatesPathKey() -> str: ...
    @staticmethod
    def colorPathKey() -> str: ...
    @staticmethod
    def configPathKey() -> str: ...
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def defaultArchivePathKey() -> str: ...
    @staticmethod
    def defaultCameraPathKey() -> str: ...
    @staticmethod
    def defaultExportNodeGraphPathKey() -> str: ...
    @staticmethod
    def defaultExportPathKey() -> str: ...
    @staticmethod
    def defaultGeometryPathKey() -> str: ...
    @staticmethod
    def defaultImagePathKey() -> str: ...
    @staticmethod
    def defaultImportNodeGraphPathKey() -> str: ...
    @staticmethod
    def defaultImportPathKey() -> str: ...
    @staticmethod
    def defaultRenderPathKey() -> str: ...
    @staticmethod
    def defaultShelfPathKey() -> str: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def examplesPathKey() -> str: ...
    @staticmethod
    def gradientPathKey() -> str: ...
    @staticmethod
    def helpPathKey() -> str: ...
    @staticmethod
    def iconPathKey() -> str: ...
    @staticmethod
    def imagePathKey() -> str: ...
    @staticmethod
    def logoPathKey() -> str: ...
    @staticmethod
    def lutPathKey() -> str: ...
    @staticmethod
    def mediaPathKey() -> str: ...
    @staticmethod
    def miscPathKey() -> str: ...
    @staticmethod
    def onlineHelpPathKey() -> str: ...
    @staticmethod
    def qtPluginsPathKey() -> str: ...
    @staticmethod
    def registerUserData() -> int: ...
    @staticmethod
    def scriptDocPathKey() -> str: ...
    @staticmethod
    def settingsPathKey() -> str: ...
    @staticmethod
    def shaderPathKey() -> str: ...
    @staticmethod
    def sysScriptPathKey() -> str: ...
    @staticmethod
    def testPathKey() -> str: ...
    @staticmethod
    def userPathKey() -> str: ...
    @staticmethod
    def userPluginsPathKey() -> str: ...
    @staticmethod
    def userScriptPathKey() -> str: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createIcon(self, IconFileName: str) -> PySide2.QtGui.QIcon: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def customPluginPaths(self) -> typing.List: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disableEnviromentKeyValues(self) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def exportSequenceTemplate(self) -> str: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def flattenedSequenceTemplate(self) -> str: ...
    def importSequenceTemplate(self) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def logPath(self) -> str: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def path(self, Key: str) -> str: ...
    def pathList(self, Key: str) -> typing.List: ...
    def property(self, name: bytes) -> typing.Any: ...
    def ptexFlattenedSequenceTemplate(self) -> str: ...
    def ptexSequenceTemplate(self) -> str: ...
    def receivers(self, signal: bytes) -> int: ...
    def refreshAllPaths(self) -> Any: ...
    def refreshPath(self, Key: str) -> Any: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def sequenceTemplate(self) -> str: ...
    def sequenceToken(self) -> str: ...
    def setExportSequenceTemplate(self, Name: str) -> Any: ...
    def setFlattenedSequenceTemplate(self, Name: str) -> Any: ...
    def setImportSequenceTemplate(self, Name: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setPath(self, Key: str, NewPath: str) -> Any: ...
    def setPathList(self, Key: str, NewPathList: typing.Sequence) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setPtexFlattenedSequenceTemplate(self, Name: str) -> Any: ...
    def setPtexSequenceTemplate(self, Name: str) -> Any: ...
    def setSequenceTemplate(self, Name: str) -> Any: ...
    def setSequenceToken(self, Token: str) -> Any: ...
    def settingsFilePath(self, Name: str) -> str: ...
    def showPDF(self, Path: str) -> Any: ...
    def showURL(self, Url: str) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
