from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
cAPIDocPathKey: str = 'C_API_DOCS'
cAPIExamplesPathKey: str = 'CAPI_EXAMPLES'
certificatesPathKey: str = 'CERTIFICATES'
colorPathKey: str = 'COLOR'
configPathKey: str = 'CONFIG'
defaultArchivePathKey: str = 'MARI_DEFAULT_ARCHIVE_PATH'
defaultCameraPathKey: str = 'MARI_DEFAULT_CAMERA_PATH'
defaultExportNodeGraphPathKey: str = 'MARI_DEFAULT_EXPORT_NODE_GRAPH_PATH'
defaultExportPathKey: str = 'MARI_DEFAULT_EXPORT_PATH'
defaultGeometryPathKey: str = 'MARI_DEFAULT_GEOMETRY_PATH'
defaultImagePathKey: str = 'MARI_DEFAULT_IMAGE_PATH'
defaultImportNodeGraphPathKey: str = 'MARI_DEFAULT_IMPORT_NODE_GRAPH_PATH'
defaultImportPathKey: str = 'MARI_DEFAULT_IMPORT_PATH'
defaultRenderPathKey: str = 'MARI_DEFAULT_RENDER_PATH'
defaultShelfPathKey: str = 'MARI_DEFAULT_SHELF_PATH'
examplesPathKey: str = 'EXAMPLES'
gradientPathKey: str = 'GRADIENTS'
helpPathKey: str = 'HELP'
iconPathKey: str = 'ICONS'
imagePathKey: str = 'IMAGES'
logoPathKey: str = 'LOGOS'
lutPathKey: str = 'LUTS'
mediaPathKey: str = 'MEDIA'
miscPathKey: str = 'MISC'
onlineHelpPathKey: str = 'ONLINE_HELP'
qtPluginsPathKey: str = 'QT_PLUGINS'
scriptDocPathKey: str = 'SCRIPT_DOCS'
settingsPathKey: str = 'SETTINGS'
shaderPathKey: str = 'SHADERS'
sysScriptPathKey: str = 'SCRIPTS'
testPathKey: str = 'TESTDATA'
userPathKey: str = 'MARI_USER_PATH'
userPluginsPathKey: str = 'MARI_PLUGINS_PATH'
userScriptPathKey: str = 'MARI_SCRIPT_PATH'
@staticmethod
def bundledUsdPath() -> str: ...
@staticmethod
def cAPIDocPathKey() -> str: ...
@staticmethod
def cAPIExamplesPathKey() -> str: ...
@staticmethod
def certificatesPathKey() -> str: ...
@staticmethod
def colorPathKey() -> str: ...
@staticmethod
def configPathKey() -> str: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def defaultArchivePathKey() -> str: ...
@staticmethod
def defaultCameraPathKey() -> str: ...
@staticmethod
def defaultExportNodeGraphPathKey() -> str: ...
@staticmethod
def defaultExportPathKey() -> str: ...
@staticmethod
def defaultGeometryPathKey() -> str: ...
@staticmethod
def defaultImagePathKey() -> str: ...
@staticmethod
def defaultImportNodeGraphPathKey() -> str: ...
@staticmethod
def defaultImportPathKey() -> str: ...
@staticmethod
def defaultRenderPathKey() -> str: ...
@staticmethod
def defaultShelfPathKey() -> str: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def examplesPathKey() -> str: ...
@staticmethod
def gradientPathKey() -> str: ...
@staticmethod
def helpPathKey() -> str: ...
@staticmethod
def iconPathKey() -> str: ...
@staticmethod
def imagePathKey() -> str: ...
@staticmethod
def logoPathKey() -> str: ...
@staticmethod
def lutPathKey() -> str: ...
@staticmethod
def mediaPathKey() -> str: ...
@staticmethod
def miscPathKey() -> str: ...
@staticmethod
def onlineHelpPathKey() -> str: ...
@staticmethod
def qtPluginsPathKey() -> str: ...
@staticmethod
def registerUserData() -> int: ...
@staticmethod
def scriptDocPathKey() -> str: ...
@staticmethod
def settingsPathKey() -> str: ...
@staticmethod
def shaderPathKey() -> str: ...
@staticmethod
def sysScriptPathKey() -> str: ...
@staticmethod
def testPathKey() -> str: ...
@staticmethod
def userPathKey() -> str: ...
@staticmethod
def userPluginsPathKey() -> str: ...
@staticmethod
def userScriptPathKey() -> str: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createIcon(IconFileName: str) -> PySide2.QtGui.QIcon: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def customPluginPaths() -> typing.List: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disableEnviromentKeyValues() -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def exportSequenceTemplate() -> str: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def flattenedSequenceTemplate() -> str: ...
def importSequenceTemplate() -> str: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def logPath() -> str: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def path(Key: str) -> str: ...
def pathList(Key: str) -> typing.List: ...
def property(name: bytes) -> typing.Any: ...
def ptexFlattenedSequenceTemplate() -> str: ...
def ptexSequenceTemplate() -> str: ...
def receivers(signal: bytes) -> int: ...
def refreshAllPaths() -> Any: ...
def refreshPath(Key: str) -> Any: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def sequenceTemplate() -> str: ...
def sequenceToken() -> str: ...
def setExportSequenceTemplate(Name: str) -> Any: ...
def setFlattenedSequenceTemplate(Name: str) -> Any: ...
def setImportSequenceTemplate(Name: str) -> Any: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setPath(Key: str, NewPath: str) -> Any: ...
def setPathList(Key: str, NewPathList: typing.Sequence) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def setPtexFlattenedSequenceTemplate(Name: str) -> Any: ...
def setPtexSequenceTemplate(Name: str) -> Any: ...
def setSequenceTemplate(Name: str) -> Any: ...
def setSequenceToken(Token: str) -> Any: ...
def settingsFilePath(Name: str) -> str: ...
def showPDF(Path: str) -> Any: ...
def showURL(Url: str) -> Any: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
