from typing import Any

def blockSignals(*args, **kwargs) -> Any: ...
def bundledUsdPath() -> Any: ...
def cAPIDocPathKey() -> Any: ...
def cAPIExamplesPathKey() -> Any: ...
def certificatesPathKey() -> Any: ...
def childEvent(*args, **kwargs) -> Any: ...
def children(*args, **kwargs) -> Any: ...
def colorPathKey() -> Any: ...
def configPathKey() -> Any: ...
def connect(*args, **kwargs) -> Any: ...
def connectNotify(*args, **kwargs) -> Any: ...
def createIcon(IconFileName) -> Any: ...
def customEvent(*args, **kwargs) -> Any: ...
def customPluginPaths() -> Any: ...
def defaultArchivePathKey() -> Any: ...
def defaultCameraPathKey() -> Any: ...
def defaultExportNodeGraphPathKey() -> Any: ...
def defaultExportPathKey() -> Any: ...
def defaultGeometryPathKey() -> Any: ...
def defaultImagePathKey() -> Any: ...
def defaultImportNodeGraphPathKey() -> Any: ...
def defaultImportPathKey() -> Any: ...
def defaultRenderPathKey() -> Any: ...
def defaultShelfPathKey() -> Any: ...
def deleteLater(*args, **kwargs) -> Any: ...
class destroyed:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def disableEnviromentKeyValues() -> Any: ...
def disconnect(*args, **kwargs) -> Any: ...
def disconnectNotify(*args, **kwargs) -> Any: ...
def dumpObjectInfo(*args, **kwargs) -> Any: ...
def dumpObjectTree(*args, **kwargs) -> Any: ...
def dynamicPropertyNames(*args, **kwargs) -> Any: ...
def emit(*args, **kwargs) -> Any: ...
def event(*args, **kwargs) -> Any: ...
def eventFilter(*args, **kwargs) -> Any: ...
def examplesPathKey() -> Any: ...
def exportSequenceTemplate() -> Any: ...
def findChild(*args, **kwargs) -> Any: ...
def findChildren(*args, **kwargs) -> Any: ...
def flattenedSequenceTemplate() -> Any: ...
def gradientPathKey() -> Any: ...
def helpPathKey() -> Any: ...
def iconPathKey() -> Any: ...
def imagePathKey() -> Any: ...
def importSequenceTemplate() -> Any: ...
def inherits(*args, **kwargs) -> Any: ...
def installEventFilter(*args, **kwargs) -> Any: ...
def isNull(*args, **kwargs) -> Any: ...
def isSignalConnected(*args, **kwargs) -> Any: ...
def isWidgetType(*args, **kwargs) -> Any: ...
def isWindowType(*args, **kwargs) -> Any: ...
def killTimer(*args, **kwargs) -> Any: ...
def logPath() -> Any: ...
def logoPathKey() -> Any: ...
def lutPathKey() -> Any: ...
def mediaPathKey() -> Any: ...
def metaObject(*args, **kwargs) -> Any: ...
def miscPathKey() -> Any: ...
def moveToThread(*args, **kwargs) -> Any: ...
class objectNameChanged:
    def connect(self, slot, type = ...) -> Any: ...
    def disconnect(self, slot = ...) -> Any: ...
    def emit(self, args) -> Any: ...

def onlineHelpPathKey() -> Any: ...
def parent(*args, **kwargs) -> Any: ...
def path(Key) -> Any: ...
def pathList(Key) -> Any: ...
def property(*args, **kwargs) -> Any: ...
def ptexFlattenedSequenceTemplate() -> Any: ...
def ptexSequenceTemplate() -> Any: ...
def qtPluginsPathKey() -> Any: ...
def receivers(*args, **kwargs) -> Any: ...
def refreshAllPaths() -> Any: ...
def refreshPath(Key) -> Any: ...
def registerUserData() -> Any: ...
def removeEventFilter(*args, **kwargs) -> Any: ...
def scriptDocPathKey() -> Any: ...
def sender(*args, **kwargs) -> Any: ...
def senderSignalIndex(*args, **kwargs) -> Any: ...
def sequenceTemplate() -> Any: ...
def sequenceToken() -> Any: ...
def setExportSequenceTemplate(Name) -> Any: ...
def setFlattenedSequenceTemplate(Name) -> Any: ...
def setImportSequenceTemplate(Name) -> Any: ...
def setObjectName(*args, **kwargs) -> Any: ...
def setParent(*args, **kwargs) -> Any: ...
def setPath(Key, NewPath) -> Any: ...
def setPathList(Key, NewPathList) -> Any: ...
def setProperty(*args, **kwargs) -> Any: ...
def setPtexFlattenedSequenceTemplate(Name) -> Any: ...
def setPtexSequenceTemplate(Name) -> Any: ...
def setSequenceTemplate(Name) -> Any: ...
def setSequenceToken(Token) -> Any: ...
def settingsFilePath(Name) -> Any: ...
def settingsPathKey() -> Any: ...
def shaderPathKey() -> Any: ...
def showPDF(Path) -> Any: ...
def showURL(Url) -> Any: ...
def signalsBlocked(*args, **kwargs) -> Any: ...
def startTimer(*args, **kwargs) -> Any: ...
class staticMetaObject:
    class Call:
        CreateInstance: Call
        IndexOfMethod: Call
        InvokeMetaMethod: Call
        QueryPropertyDesignable: Call
        QueryPropertyEditable: Call
        QueryPropertyScriptable: Call
        QueryPropertyStored: Call
        QueryPropertyUser: Call
        ReadProperty: Call
        RegisterMethodArgumentMetaType: Call
        RegisterPropertyMetaType: Call
        ResetProperty: Call
        WriteProperty: Call
        name: getset_descriptor
        values: dict

    class Connection(Object):
        pass

    def cast(self, obj) -> Any: ...
    def checkConnectArgs(self, *args, **kwargs) -> Any: ...
    def classInfo(self, index) -> Any: ...
    def classInfoCount(self) -> Any: ...
    def classInfoOffset(self) -> Any: ...
    def className(self) -> Any: ...
    def connectSlotsByName(self, o) -> Any: ...
    def constructor(self, index) -> Any: ...
    def constructorCount(self) -> Any: ...
    def disconnect(self, sender, signal_index, receiver, method_index) -> Any: ...
    def disconnectOne(self, sender, signal_index, receiver, method_index) -> Any: ...
    def enumerator(self, index) -> Any: ...
    def enumeratorCount(self) -> Any: ...
    def enumeratorOffset(self) -> Any: ...
    def indexOfClassInfo(self, name) -> Any: ...
    def indexOfConstructor(self, constructor) -> Any: ...
    def indexOfEnumerator(self, name) -> Any: ...
    def indexOfMethod(self, method) -> Any: ...
    def indexOfProperty(self, name) -> Any: ...
    def indexOfSignal(self, signal) -> Any: ...
    def indexOfSlot(self, slot) -> Any: ...
    def inherits(self, metaObject) -> Any: ...
    def invokeMethod(self, *args, **kwargs) -> Any: ...
    def method(self, index) -> Any: ...
    def methodCount(self) -> Any: ...
    def methodOffset(self) -> Any: ...
    def newInstance(self, val0 = ..., val1 = ..., val2 = ..., val3 = ..., val4 = ..., val5 = ..., val6 = ..., val7 = ..., val8 = ..., val9 = ...) -> Any: ...
    def normalizedSignature(self, method) -> Any: ...
    def normalizedType(self, type) -> Any: ...
    def property(self, index) -> Any: ...
    def propertyCount(self) -> Any: ...
    def propertyOffset(self) -> Any: ...
    def superClass(self) -> Any: ...
    def userProperty(self) -> Any: ...

def sysScriptPathKey() -> Any: ...
def testPathKey() -> Any: ...
def thread(*args, **kwargs) -> Any: ...
def timerEvent(*args, **kwargs) -> Any: ...
def tr(*args, **kwargs) -> Any: ...
def userPathKey() -> Any: ...
def userPluginsPathKey() -> Any: ...
def userScriptPathKey() -> Any: ...
