from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

staticMetaObject: QMetaObject
cAPIDocPathKey: str = 'C_API_DOCS'
cAPIExamplesPathKey: str = 'CAPI_EXAMPLES'
certificatesPathKey: str = 'CERTIFICATES'
colorPathKey: str = 'COLOR'
configPathKey: str = 'CONFIG'
defaultArchivePathKey: str = 'MARI_DEFAULT_ARCHIVE_PATH'
defaultCameraPathKey: str = 'MARI_DEFAULT_CAMERA_PATH'
defaultExportNodeGraphPathKey: str = 'MARI_DEFAULT_EXPORT_NODE_GRAPH_PATH'
defaultExportPathKey: str = 'MARI_DEFAULT_EXPORT_PATH'
defaultGeometryPathKey: str = 'MARI_DEFAULT_GEOMETRY_PATH'
defaultImagePathKey: str = 'MARI_DEFAULT_IMAGE_PATH'
defaultImportNodeGraphPathKey: str = 'MARI_DEFAULT_IMPORT_NODE_GRAPH_PATH'
defaultImportPathKey: str = 'MARI_DEFAULT_IMPORT_PATH'
defaultRenderPathKey: str = 'MARI_DEFAULT_RENDER_PATH'
defaultShelfPathKey: str = 'MARI_DEFAULT_SHELF_PATH'
examplesPathKey: str = 'EXAMPLES'
gradientPathKey: str = 'GRADIENTS'
helpPathKey: str = 'HELP'
iconPathKey: str = 'ICONS'
imagePathKey: str = 'IMAGES'
logoPathKey: str = 'LOGOS'
lutPathKey: str = 'LUTS'
mediaPathKey: str = 'MEDIA'
miscPathKey: str = 'MISC'
onlineHelpPathKey: str = 'ONLINE_HELP'
qtPluginsPathKey: str = 'QT_PLUGINS'
scriptDocPathKey: str = 'SCRIPT_DOCS'
settingsPathKey: str = 'SETTINGS'
shaderPathKey: str = 'SHADERS'
sysScriptPathKey: str = 'SCRIPTS'
testPathKey: str = 'TESTDATA'
userPathKey: str = 'MARI_USER_PATH'
userPluginsPathKey: str = 'MARI_PLUGINS_PATH'
userScriptPathKey: str = 'MARI_SCRIPT_PATH'
@staticmethod
def bundledUsdPath() -> Any: ...
@staticmethod
def cAPIDocPathKey() -> Any: ...
@staticmethod
def cAPIExamplesPathKey() -> Any: ...
@staticmethod
def certificatesPathKey() -> Any: ...
@staticmethod
def colorPathKey() -> Any: ...
@staticmethod
def configPathKey() -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def defaultArchivePathKey() -> Any: ...
@staticmethod
def defaultCameraPathKey() -> Any: ...
@staticmethod
def defaultExportNodeGraphPathKey() -> Any: ...
@staticmethod
def defaultExportPathKey() -> Any: ...
@staticmethod
def defaultGeometryPathKey() -> Any: ...
@staticmethod
def defaultImagePathKey() -> Any: ...
@staticmethod
def defaultImportNodeGraphPathKey() -> Any: ...
@staticmethod
def defaultImportPathKey() -> Any: ...
@staticmethod
def defaultRenderPathKey() -> Any: ...
@staticmethod
def defaultShelfPathKey() -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def examplesPathKey() -> Any: ...
@staticmethod
def gradientPathKey() -> Any: ...
@staticmethod
def helpPathKey() -> Any: ...
@staticmethod
def iconPathKey() -> Any: ...
@staticmethod
def imagePathKey() -> Any: ...
@staticmethod
def logoPathKey() -> Any: ...
@staticmethod
def lutPathKey() -> Any: ...
@staticmethod
def mediaPathKey() -> Any: ...
@staticmethod
def miscPathKey() -> Any: ...
@staticmethod
def onlineHelpPathKey() -> Any: ...
@staticmethod
def qtPluginsPathKey() -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
@staticmethod
def scriptDocPathKey() -> Any: ...
@staticmethod
def settingsPathKey() -> Any: ...
@staticmethod
def shaderPathKey() -> Any: ...
@staticmethod
def sysScriptPathKey() -> Any: ...
@staticmethod
def testPathKey() -> Any: ...
@staticmethod
def userPathKey() -> Any: ...
@staticmethod
def userPluginsPathKey() -> Any: ...
@staticmethod
def userScriptPathKey() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createIcon(self, IconFileName) -> Any: ...
def customEvent(self, event) -> Any: ...
def customPluginPaths(self) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disableEnviromentKeyValues(self) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def exportSequenceTemplate(self) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def flattenedSequenceTemplate(self) -> Any: ...
def importSequenceTemplate(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def logPath(self) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def path(self, Key) -> Any: ...
def pathList(self, Key) -> Any: ...
def property(self, name) -> Any: ...
def ptexFlattenedSequenceTemplate(self) -> Any: ...
def ptexSequenceTemplate(self) -> Any: ...
def receivers(self, signal) -> Any: ...
def refreshAllPaths(self) -> Any: ...
def refreshPath(self, Key) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def sequenceTemplate(self) -> Any: ...
def sequenceToken(self) -> Any: ...
def setExportSequenceTemplate(self, Name) -> Any: ...
def setFlattenedSequenceTemplate(self, Name) -> Any: ...
def setImportSequenceTemplate(self, Name) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setPath(self, Key, NewPath) -> Any: ...
def setPathList(self, Key, NewPathList) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setPtexFlattenedSequenceTemplate(self, Name) -> Any: ...
def setPtexSequenceTemplate(self, Name) -> Any: ...
def setSequenceTemplate(self, Name) -> Any: ...
def setSequenceToken(self, Token) -> Any: ...
def settingsFilePath(self, Name) -> Any: ...
def showPDF(self, Path) -> Any: ...
def showURL(self, Url) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
