from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class SelectionGroupManager(API):
    class SelectionMode:
        SELECTION_MODE_FACES: SelectionMode = ...
        SELECTION_MODE_OBJECTS: SelectionMode = ...
        SELECTION_MODE_PATCHES: SelectionMode = ...
        name: getset_descriptor
        values: dict

    SELECTION_MODE_FACES: SelectionMode = ...
    SELECTION_MODE_OBJECTS: SelectionMode = ...
    SELECTION_MODE_PATCHES: SelectionMode = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createSelectionGroupFromSelection(self, name: str) -> Any: ...
    def current(self) -> mari.SelectionGroup: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def hiddenChanged(self, *args, **kwargs) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def list(self) -> typing.List: ...
    def lockedChanged(self, *args, **kwargs) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def modeChanged(self, *args, **kwargs) -> Any: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeSelectionGroup(self, group: mari.SelectionGroup) -> Any: ...
    def sceneSelectionMode(self) -> Any: ...
    def select(self, group: mari.SelectionGroup) -> Any: ...
    def selectModeChanged(self, *args, **kwargs) -> Any: ...
    def selectedChanged(self, *args, **kwargs) -> Any: ...
    def selection(self) -> typing.List: ...
    def selectionGroupAdded(self, *args, **kwargs) -> Any: ...
    def selectionGroupRemoved(self, *args, **kwargs) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setSelectionMode(self, mode) -> Any: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def visibleChanged(self, *args, **kwargs) -> Any: ...
