from typing import Any

def exportSession(exportDir = ..., geoEntities = ..., geoVersions = ..., channels = ..., geoPatches = ..., shaders = ..., images = ..., copyObjectFiles = ..., lights = ..., cameras = ..., projectors = ..., name = ..., template = ..., finishedCallback = ...) -> Any: ...
def getRegisteredFunction(method = ...) -> Any: ...
def importChannels() -> Any: ...
def importNodeGraphs() -> Any: ...
def importSession(sessionFilePath = ..., geoEntities = ..., finishedCallback = ...) -> Any: ...
def importShaders() -> Any: ...
def registerFunction(method = ..., callFunction = ...) -> Any: ...
