from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import AdjustableLayer
from mari import Layer
from mari import Metadata

class AdvancedBlendComponent:
    BLUE_BLEND: AdvancedBlendComponent = ...
    GREEN_BLEND: AdvancedBlendComponent = ...
    GREYSCALE_BLEND: AdvancedBlendComponent = ...
    LUMINANCE_BLEND: AdvancedBlendComponent = ...
    RED_BLEND: AdvancedBlendComponent = ...
    name: getset_descriptor
    values: dict

class BlendMode:
    ADD: BlendMode = ...
    ADD_NORMAL_MAPS: BlendMode = ...
    BURN_HIGHLIGHTS: BlendMode = ...
    BURN_MIDRANGE: BlendMode = ...
    BURN_SHADOWS: BlendMode = ...
    CLEAR: BlendMode = ...
    COLOR: BlendMode = ...
    COLOR_BURN: BlendMode = ...
    COLOR_DODGE: BlendMode = ...
    CONTRAST: BlendMode = ...
    COPY: BlendMode = ...
    COPY_RGB: BlendMode = ...
    CUSTOM: BlendMode = ...
    DARKEN: BlendMode = ...
    DECONTRAST: BlendMode = ...
    DIFFERENCE: BlendMode = ...
    DIVIDE: BlendMode = ...
    DODGE_HIGHLIGHTS: BlendMode = ...
    DODGE_MIDRANGE: BlendMode = ...
    DODGE_SHADOWS: BlendMode = ...
    EXCLUSION: BlendMode = ...
    HARD_LIGHT: BlendMode = ...
    HARD_MIX: BlendMode = ...
    HUE: BlendMode = ...
    INVERSE_DIFFERENCE: BlendMode = ...
    INVERT: BlendMode = ...
    LIGHTEN: BlendMode = ...
    LUMINANCE: BlendMode = ...
    MIX: BlendMode = ...
    MIX_NORMAL_MAPS: BlendMode = ...
    MULTIPLY: BlendMode = ...
    NUDGE_FLOW_VECTORS: BlendMode = ...
    NUDGE_NORMAL_VECTORS: BlendMode = ...
    OVERLAY: BlendMode = ...
    PAINT_FLOW_VECTORS: BlendMode = ...
    PAINT_NORMAL_VECTORS: BlendMode = ...
    PIN_LIGHT: BlendMode = ...
    REORIENTED_NORMAL_MAPPING: BlendMode = ...
    SATURATION: BlendMode = ...
    SCALE_VECTORS: BlendMode = ...
    SCREEN: BlendMode = ...
    SOFT_LIGHT: BlendMode = ...
    SPONGE_DESATURATE: BlendMode = ...
    SUBTRACT: BlendMode = ...
    VIVID_LIGHT: BlendMode = ...
    name: getset_descriptor
    values: dict

class BlendType:
    ADVANCED_BLEND: BlendType = ...
    BASIC_BLEND: BlendType = ...
    name: getset_descriptor
    values: dict

class MaskType:
    FROM_ALPHA: MaskType = ...
    FROM_SELECTION_GROUP: MaskType = ...
    HIDE_ALL: MaskType = ...
    REVEAL_ALL: MaskType = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

class SwizzleDestination:
    SWIZZLE_DST_ALPHA: SwizzleDestination = ...
    SWIZZLE_DST_BLUE: SwizzleDestination = ...
    SWIZZLE_DST_GREEN: SwizzleDestination = ...
    SWIZZLE_DST_RED: SwizzleDestination = ...
    name: getset_descriptor
    values: dict

class SwizzleSource:
    SWIZZLE_SRC_ALPHA: SwizzleSource = ...
    SWIZZLE_SRC_BLUE: SwizzleSource = ...
    SWIZZLE_SRC_GREEN: SwizzleSource = ...
    SWIZZLE_SRC_ONE: SwizzleSource = ...
    SWIZZLE_SRC_RED: SwizzleSource = ...
    SWIZZLE_SRC_ZERO: SwizzleSource = ...
    name: getset_descriptor
    values: dict

ADD: BlendMode = ...
ADD_NORMAL_MAPS: BlendMode = ...
ADVANCED_BLEND: BlendType = ...
BASIC_BLEND: BlendType = ...
BLUE_BLEND: AdvancedBlendComponent = ...
BURN_HIGHLIGHTS: BlendMode = ...
BURN_MIDRANGE: BlendMode = ...
BURN_SHADOWS: BlendMode = ...
CLEAR: BlendMode = ...
COLOR: BlendMode = ...
COLOR_BURN: BlendMode = ...
COLOR_DODGE: BlendMode = ...
CONTRAST: BlendMode = ...
COPY: BlendMode = ...
COPY_RGB: BlendMode = ...
CUSTOM: BlendMode = ...
DARKEN: BlendMode = ...
DECONTRAST: BlendMode = ...
DIFFERENCE: BlendMode = ...
DIVIDE: BlendMode = ...
DODGE_HIGHLIGHTS: BlendMode = ...
DODGE_MIDRANGE: BlendMode = ...
DODGE_SHADOWS: BlendMode = ...
EXCLUSION: BlendMode = ...
FROM_ALPHA: MaskType = ...
FROM_SELECTION_GROUP: MaskType = ...
GREEN_BLEND: AdvancedBlendComponent = ...
GREYSCALE_BLEND: AdvancedBlendComponent = ...
HARD_LIGHT: BlendMode = ...
HARD_MIX: BlendMode = ...
HIDE_ALL: MaskType = ...
HUE: BlendMode = ...
INVERSE_DIFFERENCE: BlendMode = ...
INVERT: BlendMode = ...
LIGHTEN: BlendMode = ...
LUMINANCE: BlendMode = ...
LUMINANCE_BLEND: AdvancedBlendComponent = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
MIX: BlendMode = ...
MIX_NORMAL_MAPS: BlendMode = ...
MULTIPLY: BlendMode = ...
NUDGE_FLOW_VECTORS: BlendMode = ...
NUDGE_NORMAL_VECTORS: BlendMode = ...
OVERLAY: BlendMode = ...
PAINT_FLOW_VECTORS: BlendMode = ...
PAINT_NORMAL_VECTORS: BlendMode = ...
PIN_LIGHT: BlendMode = ...
RED_BLEND: AdvancedBlendComponent = ...
REORIENTED_NORMAL_MAPPING: BlendMode = ...
REVEAL_ALL: MaskType = ...
SATURATION: BlendMode = ...
SCALE_VECTORS: BlendMode = ...
SCREEN: BlendMode = ...
SOFT_LIGHT: BlendMode = ...
SPONGE_DESATURATE: BlendMode = ...
SUBTRACT: BlendMode = ...
SWIZZLE_DST_ALPHA: SwizzleDestination = ...
SWIZZLE_DST_BLUE: SwizzleDestination = ...
SWIZZLE_DST_GREEN: SwizzleDestination = ...
SWIZZLE_DST_RED: SwizzleDestination = ...
SWIZZLE_SRC_ALPHA: SwizzleSource = ...
SWIZZLE_SRC_BLUE: SwizzleSource = ...
SWIZZLE_SRC_GREEN: SwizzleSource = ...
SWIZZLE_SRC_ONE: SwizzleSource = ...
SWIZZLE_SRC_RED: SwizzleSource = ...
SWIZZLE_SRC_ZERO: SwizzleSource = ...
VIVID_LIGHT: BlendMode = ...
staticMetaObject: QMetaObject
@staticmethod
def advancedBlendComponentName(Value) -> Any: ...
@staticmethod
def blendModeName(BlendModeValue) -> Any: ...
@staticmethod
def blendTypeName(BlendTypeValue) -> Any: ...
@staticmethod
def colorTagNames() -> Any: ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def activeCacheUpToHereParents(self) -> Any: ...
def adjustmentStack(self) -> Any: ...
def advancedBlendComponentStr(self) -> Any: ...
def blendAmount(self) -> Any: ...
def blendAmountChanged(self, *args, **kwargs) -> Any: ...
def blendAmountEnabled(self) -> Any: ...
def blendComponentChanged(self, *args, **kwargs) -> Any: ...
def blendMode(self) -> Any: ...
def blendModeChanged(self, *args, **kwargs) -> Any: ...
def blendModePath(self) -> Any: ...
def blendModeStr(self) -> Any: ...
def blendType(self) -> Any: ...
def blendTypeChanged(self, *args, **kwargs) -> Any: ...
def blendTypeStr(self) -> Any: ...
def blockSignals(self, b) -> Any: ...
def cacheLayer(self) -> Any: ...
def cacheStateChanged(self, *args, **kwargs) -> Any: ...
def cacheUpToHere(self) -> Any: ...
def cacheUpToHereParents(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def close(self) -> Any: ...
def colorTag(self) -> Any: ...
def colorTagChanged(self, *args, **kwargs) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def convertedToPaint(self, *args, **kwargs) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def getAdvancedBlendComponent(self) -> Any: ...
def getLayerBelowBlendLut(self) -> Any: ...
def getThisLayerBlendLut(self) -> Any: ...
def groupStack(self) -> Any: ...
def hasAdjustmentStack(self) -> Any: ...
def hasCacheUpToHere(self) -> Any: ...
def hasLayerCache(self) -> Any: ...
def hasMask(self) -> Any: ...
def hasMaskCustomProcedural(self) -> Any: ...
def hasMaskStack(self) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def hash(self, UVIndex = ...) -> Any: ...
def imageHash(self, UVIndex = ...) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isAdjustableLayer(self) -> Any: ...
def isAdjustmentLayer(self) -> Any: ...
def isAdjustmentStackEnabled(self) -> Any: ...
def isBakePointLayer(self) -> Any: ...
def isCachedUpToHere(self) -> Any: ...
def isChannelLayer(self) -> Any: ...
def isChildOfActiveCacheUpToHere(self) -> Any: ...
def isChildOfCacheUpToHere(self) -> Any: ...
def isCustomProceduralLayer(self) -> Any: ...
def isGraphLayer(self) -> Any: ...
def isGroupLayer(self) -> Any: ...
def isLayerCached(self) -> Any: ...
def isLocked(self) -> Any: ...
def isMaskEnabled(self) -> Any: ...
def isModifiable(self) -> Any: ...
def isMultiChannelGroupLayer(self) -> Any: ...
def isMultiChannelMaterialLayer(self) -> Any: ...
def isNull(self) -> Any: ...
def isPaintableLayer(self) -> Any: ...
def isProceduralLayer(self) -> Any: ...
def isSelected(self) -> Any: ...
def isShaderLayer(self) -> Any: ...
def isShared(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isVisible(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def layerNode(self) -> Any: ...
def lockedChanged(self, *args, **kwargs) -> Any: ...
def makeAdjustmentStack(self) -> Any: ...
def makeCurrent(self) -> Any: ...
def makeMask(self, Mask = ..., Group = ...) -> Any: ...
def makeMaskCustomProcedural(self, FileName) -> Any: ...
def makeMaskStack(self) -> Any: ...
def maskCreated(self, *args, **kwargs) -> Any: ...
def maskCustomProceduralNode(self) -> Any: ...
def maskImageSet(self) -> Any: ...
def maskRemoved(self, *args, **kwargs) -> Any: ...
def maskStack(self) -> Any: ...
def maskStackCreated(self, *args, **kwargs) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def parents(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeAdjustmentStack(self) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMask(self) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def selectedChanged(self, *args, **kwargs) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setAdjustmentStackEnabled(self, Enabled) -> Any: ...
def setAdvancedBlendComponent(self, Component) -> Any: ...
def setBlendAmount(self, BlendAmount) -> Any: ...
def setBlendAmountEnabled(self, Enabled) -> Any: ...
def setBlendMode(self, BlendModeValue) -> Any: ...
def setBlendType(self, Type) -> Any: ...
def setCachedUpToHere(self, Cache) -> Any: ...
def setColorTag(self, ColorTag) -> Any: ...
def setLayerBelowBlendLut(self, NewLut) -> Any: ...
def setLayerCached(self, Cache) -> Any: ...
def setLocked(self, Locked) -> Any: ...
def setMaskEnabled(self, Enabled) -> Any: ...
def setMaskImageSet(self, Mask) -> Any: ...
def setMaskStack(self, MaskStack) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, NewName) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSelected(self, Selected) -> Any: ...
def setSwizzle(self, Dst, Src) -> Any: ...
def setThisLayerBlendLut(self, NewLut) -> Any: ...
def setVisibility(self, Visible) -> Any: ...
def shader(self) -> Any: ...
def siblingSharedLayerList(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def swizzle(self, Dst) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def uncacheLayer(self) -> Any: ...
def uncacheUpToHere(self) -> Any: ...
def uuid(self) -> Any: ...
