from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Metadata

class ChannelSetMode:
    EXTEND_INVISIBLE: ChannelSetMode = ...
    EXTEND_VISIBLE: ChannelSetMode = ...
    NONE: ChannelSetMode = ...
    REMOVE_CONVERT: ChannelSetMode = ...
    REMOVE_DISCONNECT: ChannelSetMode = ...
    name: getset_descriptor
    values: dict

class MetadataFlag:
    METADATA_EDITABLE: MetadataFlag = ...
    METADATA_REMOVABLE: MetadataFlag = ...
    METADATA_REMOVEABLE: MetadataFlag = ...
    METADATA_SAVED: MetadataFlag = ...
    METADATA_UNDOABLE: MetadataFlag = ...
    METADATA_VISIBLE: MetadataFlag = ...
    name: getset_descriptor
    values: dict

class MetadataFlags:
    pass

class MetadataGroupHint:
    METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
    METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
    name: getset_descriptor
    values: dict

class MetadataGroupHints:
    pass

class MetadataTypeFlag:
    METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
    METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
    name: getset_descriptor
    values: dict

class MetadataTypeFlags:
    pass

EXTEND_INVISIBLE: ChannelSetMode = ...
EXTEND_VISIBLE: ChannelSetMode = ...
METADATA_EDITABLE: MetadataFlag = ...
METADATA_GROUP_HINT_DISPLAY: MetadataGroupHint = ...
METADATA_GROUP_HINT_SORTABLE: MetadataGroupHint = ...
METADATA_REMOVABLE: MetadataFlag = ...
METADATA_REMOVEABLE: MetadataFlag = ...
METADATA_SAVED: MetadataFlag = ...
METADATA_TYPE_FLAG_COLOR_SCALAR: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_FLOAT_LOGARITHMIC: MetadataTypeFlag = ...
METADATA_TYPE_FLAG_STRING_MULTILINE: MetadataTypeFlag = ...
METADATA_UNDOABLE: MetadataFlag = ...
METADATA_VISIBLE: MetadataFlag = ...
NONE: ChannelSetMode = ...
REMOVE_CONVERT: ChannelSetMode = ...
REMOVE_DISCONNECT: ChannelSetMode = ...
staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def isSupportedMetadataType(Value) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def channelList(self) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def diffuseType(self) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def getParameter(self, ParameterName) -> Any: ...
def hasMetadata(self, Name) -> Any: ...
def inherits(self, classname) -> Any: ...
def inputList(self) -> Any: ...
def inputNameList(self) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isInputForShaderStacks(self, InputName) -> Any: ...
def isLayeredShader(self) -> Any: ...
def isLocked(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isStackShader(self) -> Any: ...
def isSystemShader(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def layeredType(self) -> Any: ...
def makeCurrent(self) -> Any: ...
def metaObject(self) -> Any: ...
def metadata(self, Name) -> Any: ...
def metadataAsImage(self, Name) -> Any: ...
def metadataCreated(self, *args, **kwargs) -> Any: ...
def metadataDefault(self, Name) -> Any: ...
def metadataDescription(self, Name) -> Any: ...
def metadataDisplayName(self, Name) -> Any: ...
def metadataEnabledChanged(self, *args, **kwargs) -> Any: ...
def metadataFlags(self, Name) -> Any: ...
def metadataIsEnabled(self, Name) -> Any: ...
def metadataItemList(self, Name) -> Any: ...
def metadataMax(self, Name) -> Any: ...
def metadataMin(self, Name) -> Any: ...
def metadataNames(self) -> Any: ...
def metadataRemoved(self, *args, **kwargs) -> Any: ...
def metadataStep(self, Name) -> Any: ...
def metadataTypeFlags(self, Name) -> Any: ...
def metadataValueChanged(self, *args, **kwargs) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def name(self) -> Any: ...
def nameChanged(self, *args, **kwargs) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parameterNameList(self) -> Any: ...
def parameterValueChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeMetadata(self, Name) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setInput(self, InputName, Input, SetMode = ...) -> Any: ...
def setMetadata(self, Name, Value) -> Any: ...
def setMetadataDefault(self, Name, Default) -> Any: ...
def setMetadataDescription(self, Name, Description) -> Any: ...
def setMetadataDisplayName(self, Name, DisplayName) -> Any: ...
def setMetadataEnabled(self, Name, Enabled) -> Any: ...
def setMetadataFlags(self, Name, Flags) -> Any: ...
def setMetadataGroupHints(self, Name, Hints) -> Any: ...
def setMetadataItemList(self, Name, ItemList) -> Any: ...
def setMetadataRange(self, Name, Min, Max) -> Any: ...
def setMetadataStep(self, Name, Step) -> Any: ...
def setMetadataTypeFlags(self, Name, Flags) -> Any: ...
def setName(self, Name) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParameter(self, ParameterName, NewValue) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def shaderModel(self) -> Any: ...
def shaderNode(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def specularType(self) -> Any: ...
def standaloneType(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def uuid(self) -> Any: ...
