from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShelfItemType:
    SHELF_ITEM_BRUSH: ShelfItemType = ...
    SHELF_ITEM_COLOR: ShelfItemType = ...
    SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_IMAGE: ShelfItemType = ...
    SHELF_ITEM_MATERIAL: ShelfItemType = ...
    SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
    SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
    SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_SCRIPT: ShelfItemType = ...
    SHELF_ITEM_UNKNOWN: ShelfItemType = ...
    name: getset_descriptor
    values: dict

SHELF_ITEM_BRUSH: ShelfItemType = ...
SHELF_ITEM_COLOR: ShelfItemType = ...
SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_IMAGE: ShelfItemType = ...
SHELF_ITEM_MATERIAL: ShelfItemType = ...
SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_SCRIPT: ShelfItemType = ...
SHELF_ITEM_UNKNOWN: ShelfItemType = ...
staticMetaObject: QMetaObject
SHELF_ITEM_BRUSH: ShelfItemType = ...
SHELF_ITEM_COLOR: ShelfItemType = ...
SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_IMAGE: ShelfItemType = ...
SHELF_ITEM_MATERIAL: ShelfItemType = ...
SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_SCRIPT: ShelfItemType = ...
SHELF_ITEM_UNKNOWN: ShelfItemType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> int: ...
def blockSignals(b: bool) -> bool: ...
def childEvent(event: PySide2.QtCore.QChildEvent) -> Any: ...
def children() -> typing.List: ...
def connectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def createShelf(ShelfName: str) -> mari.Shelf: ...
def customEvent(event: PySide2.QtCore.QEvent) -> Any: ...
def deleteLater() -> Any: ...
def destroyed(*args, **kwargs) -> Any: ...
def disconnectNotify(signal: PySide2.QtCore.QMetaMethod) -> Any: ...
def dumpObjectInfo() -> Any: ...
def dumpObjectTree() -> Any: ...
def dynamicPropertyNames() -> typing.List: ...
def emit(arg__1: bytes, args) -> bool: ...
def event(event: PySide2.QtCore.QEvent) -> bool: ...
def eventFilter(watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
def find(Name: str) -> mari.Shelf: ...
def findChild(arg__1: type, arg__2: str = ...) -> object: ...
def findChildren(*args, **kwargs) -> Any: ...
def groupShelf(ShelfToGroup: mari.Shelf, GroupPath: str) -> Any: ...
def inherits(classname: bytes) -> bool: ...
def installEventFilter(filterObj: PySide2.QtCore.QObject) -> Any: ...
def isNull() -> bool: ...
def isSignalConnected(signal: PySide2.QtCore.QMetaMethod) -> bool: ...
def isWidgetType() -> bool: ...
def isWindowType() -> bool: ...
def killTimer(id: int) -> Any: ...
def list() -> typing.List: ...
def loadShelvesFromDirectory(Path: str) -> typing.List: ...
def metaObject() -> PySide2.QtCore.QMetaObject: ...
def moveToThread(thread: PySide2.QtCore.QThread) -> Any: ...
def names() -> typing.List: ...
def objectName() -> str: ...
def objectNameChanged(*args, **kwargs) -> Any: ...
def parent() -> PySide2.QtCore.QObject: ...
def property(name: bytes) -> typing.Any: ...
def receivers(signal: bytes) -> int: ...
def removeEventFilter(obj: PySide2.QtCore.QObject) -> Any: ...
def removeShelf(ShelfToRemove: mari.Shelf) -> bool: ...
def search(SearchKeyword: str, Shelves: typing.Sequence) -> typing.List: ...
def sender() -> PySide2.QtCore.QObject: ...
def senderSignalIndex() -> int: ...
def setObjectName(name: str) -> Any: ...
def setParent(parent: PySide2.QtCore.QObject) -> Any: ...
def setProperty(name: bytes, value: typing.Any) -> bool: ...
def signalsBlocked() -> bool: ...
def startTimer(interval: int, timerType = ...) -> int: ...
def thread() -> PySide2.QtCore.QThread: ...
def timerEvent(event: PySide2.QtCore.QTimerEvent) -> Any: ...
def tr(arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
def ungroupShelf(ShelfToUngroup: mari.Shelf) -> Any: ...
