from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShelfItemType:
    SHELF_ITEM_BRUSH: ShelfItemType = ...
    SHELF_ITEM_COLOR: ShelfItemType = ...
    SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_IMAGE: ShelfItemType = ...
    SHELF_ITEM_MATERIAL: ShelfItemType = ...
    SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
    SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
    SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_SCRIPT: ShelfItemType = ...
    SHELF_ITEM_UNKNOWN: ShelfItemType = ...
    name: getset_descriptor
    values: dict

SHELF_ITEM_BRUSH: ShelfItemType = ...
SHELF_ITEM_COLOR: ShelfItemType = ...
SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_IMAGE: ShelfItemType = ...
SHELF_ITEM_MATERIAL: ShelfItemType = ...
SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_SCRIPT: ShelfItemType = ...
SHELF_ITEM_UNKNOWN: ShelfItemType = ...
staticMetaObject: QMetaObject
SHELF_ITEM_BRUSH: ShelfItemType = ...
SHELF_ITEM_COLOR: ShelfItemType = ...
SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_IMAGE: ShelfItemType = ...
SHELF_ITEM_MATERIAL: ShelfItemType = ...
SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
SHELF_ITEM_SCRIPT: ShelfItemType = ...
SHELF_ITEM_UNKNOWN: ShelfItemType = ...
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def blockSignals(self, b) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def createShelf(self, ShelfName) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def find(self, Name) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def groupShelf(self, ShelfToGroup, GroupPath) -> Any: ...
def inherits(self, classname) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def list(self) -> Any: ...
def loadShelvesFromDirectory(self, Path) -> Any: ...
def metaObject(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def names(self) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def removeShelf(self, ShelfToRemove) -> Any: ...
def search(self, SearchKeyword, Shelves) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def signalsBlocked(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def ungroupShelf(self, ShelfToUngroup) -> Any: ...
