from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API

class ShelfManager(API):
    class ShelfItemType:
        SHELF_ITEM_BRUSH: ShelfItemType = ...
        SHELF_ITEM_COLOR: ShelfItemType = ...
        SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
        SHELF_ITEM_IMAGE: ShelfItemType = ...
        SHELF_ITEM_MATERIAL: ShelfItemType = ...
        SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
        SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
        SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
        SHELF_ITEM_SCRIPT: ShelfItemType = ...
        SHELF_ITEM_UNKNOWN: ShelfItemType = ...
        name: getset_descriptor
        values: dict

    SHELF_ITEM_BRUSH: ShelfItemType = ...
    SHELF_ITEM_COLOR: ShelfItemType = ...
    SHELF_ITEM_COLOR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_IMAGE: ShelfItemType = ...
    SHELF_ITEM_MATERIAL: ShelfItemType = ...
    SHELF_ITEM_NODE_GRAPH: ShelfItemType = ...
    SHELF_ITEM_PROCEDURAL_MASK: ShelfItemType = ...
    SHELF_ITEM_SCALAR_PROCEDURAL: ShelfItemType = ...
    SHELF_ITEM_SCRIPT: ShelfItemType = ...
    SHELF_ITEM_UNKNOWN: ShelfItemType = ...
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def createShelf(self, ShelfName: str) -> mari.Shelf: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def find(self, Name: str) -> mari.Shelf: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def groupShelf(self, ShelfToGroup: mari.Shelf, GroupPath: str) -> Any: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def list(self) -> typing.List: ...
    def loadShelvesFromDirectory(self, Path: str) -> typing.List: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def names(self) -> typing.List: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeShelf(self, ShelfToRemove: mari.Shelf) -> bool: ...
    def search(self, SearchKeyword: str, Shelves: typing.Sequence) -> typing.List: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def ungroupShelf(self, ShelfToUngroup: mari.Shelf) -> Any: ...
