from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import Action

class ShelfItem(Action):
    staticMetaObject: QMetaObject
    @staticmethod
    def connect(*args, **kwargs) -> Any: ...
    @staticmethod
    def disconnect(*args, **kwargs) -> Any: ...
    @staticmethod
    def registerUserData() -> int: ...
    def addToSet(self, SetName: str) -> Any: ...
    def autoRepeat(self) -> bool: ...
    def blockSignals(self, b: bool) -> bool: ...
    def childEvent(self, event: PySide2.QtCore.QChildEvent) -> Any: ...
    def children(self) -> typing.List: ...
    def connectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def customEvent(self, event: PySide2.QtCore.QEvent) -> Any: ...
    def data(self) -> typing.Any: ...
    def deleteLater(self) -> Any: ...
    def destroyed(self, *args, **kwargs) -> Any: ...
    def disconnectNotify(self, signal: PySide2.QtCore.QMetaMethod) -> Any: ...
    def dumpObjectInfo(self) -> Any: ...
    def dumpObjectTree(self) -> Any: ...
    def dynamicPropertyNames(self) -> typing.List: ...
    def emit(self, arg__1: bytes, args) -> bool: ...
    def event(self, event: PySide2.QtCore.QEvent) -> bool: ...
    def eventFilter(self, watched: PySide2.QtCore.QObject, event: PySide2.QtCore.QEvent) -> bool: ...
    def findChild(self, arg__1: type, arg__2: str = ...) -> object: ...
    def findChildren(self, *args, **kwargs) -> Any: ...
    def iconPath(self) -> str: ...
    def inherits(self, classname: bytes) -> bool: ...
    def installEventFilter(self, filterObj: PySide2.QtCore.QObject) -> Any: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isSignalConnected(self, signal: PySide2.QtCore.QMetaMethod) -> bool: ...
    def isWidgetType(self) -> bool: ...
    def isWindowType(self) -> bool: ...
    def killTimer(self, id: int) -> Any: ...
    def metaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def moveToThread(self, thread: PySide2.QtCore.QThread) -> Any: ...
    def name(self) -> str: ...
    def objectName(self) -> str: ...
    def objectNameChanged(self, *args, **kwargs) -> Any: ...
    def parent(self) -> PySide2.QtCore.QObject: ...
    def path(self) -> str: ...
    def property(self, name: bytes) -> typing.Any: ...
    def receivers(self, signal: bytes) -> int: ...
    def removeEventFilter(self, obj: PySide2.QtCore.QObject) -> Any: ...
    def removeFromSet(self, SetName: str) -> Any: ...
    def removeShortcut(self, Group = ...) -> Any: ...
    def saveAs(self, rFileName: str) -> Any: ...
    def sender(self) -> PySide2.QtCore.QObject: ...
    def senderSignalIndex(self) -> int: ...
    def setAutoRepeat(self, AutoRepeat: bool) -> Any: ...
    def setCheckable(self, Checkable: bool) -> Any: ...
    def setChecked(self, Checked: bool) -> Any: ...
    def setData(self, Data: typing.Any) -> Any: ...
    def setEnabled(self, Enabled: bool) -> Any: ...
    def setIconPath(self, IconPath: str) -> Any: ...
    def setName(self, NewName: str) -> Any: ...
    def setObjectName(self, name: str) -> Any: ...
    def setParent(self, parent: PySide2.QtCore.QObject) -> Any: ...
    def setProperty(self, name: bytes, value: typing.Any) -> bool: ...
    def setShortcut(self, rString: str, Group = ...) -> Any: ...
    def setStatusTip(self, StatusTip: str) -> Any: ...
    def setTags(self, Tags: typing.Sequence) -> Any: ...
    def setText(self, NewText: str) -> Any: ...
    def setThumbnail(self, Thumbnail: PySide2.QtGui.QImage) -> Any: ...
    def setToolTip(self, ToolTip: str) -> Any: ...
    def setWhatsThis(self, WhatsThis: str) -> Any: ...
    def shortcut(self, Group = ...) -> str: ...
    def signalsBlocked(self) -> bool: ...
    def startTimer(self, interval: int, timerType = ...) -> int: ...
    def statusTip(self) -> str: ...
    def tags(self) -> typing.List: ...
    def text(self) -> str: ...
    def thread(self) -> PySide2.QtCore.QThread: ...
    def thumbnail(self) -> PySide2.QtGui.QImage: ...
    def timerEvent(self, event: PySide2.QtCore.QTimerEvent) -> Any: ...
    def toolTip(self) -> str: ...
    def tr(self, arg__1: bytes, arg__2: bytes = ..., arg__3: int = ...) -> str: ...
    def trigger(self) -> Any: ...
    def triggered(self, *args, **kwargs) -> Any: ...
    def type(self) -> Any: ...
    def whatsThis(self) -> str: ...
