from typing import Any

class SignalInstance:
    def connect(self, slot: object, type: typing.Optional = ...) -> Any: ...
    def disconnect(self, slot: typing.Optional = ...) -> Any: ...
    def emit(self, args: typing.Any) -> Any: ...
