from typing import Any
from PySide2.QtCore import QObject
from Shiboken import Object
from mari import API
from mari import WidgetBase

staticMetaObject: QMetaObject
@staticmethod
def connect(*args, **kwargs) -> Any: ...
@staticmethod
def disconnect(*args, **kwargs) -> Any: ...
@staticmethod
def registerUserData() -> Any: ...
def actionsList(self) -> Any: ...
def addAction(self, Path, Pos = ..., Removable = ...) -> Any: ...
def addActionBefore(self, Path, InsertBefore = ..., Removable = ...) -> Any: ...
def addActionList(self, Actions, Removable) -> Any: ...
def addActionObject(self, Object) -> Any: ...
def addSeparator(self) -> Any: ...
def addToLayout(self, Layout) -> Any: ...
def addWidget(self, *args, **kwargs) -> Any: ...
def blockSignals(self, Block) -> Any: ...
def childEvent(self, event) -> Any: ...
def children(self) -> Any: ...
def connectNotify(self, signal) -> Any: ...
def customEvent(self, event) -> Any: ...
def deleteLater(self) -> Any: ...
def destroyed(self, *args, **kwargs) -> Any: ...
def disable(self) -> Any: ...
def disconnectNotify(self, signal) -> Any: ...
def dumpObjectInfo(self) -> Any: ...
def dumpObjectTree(self) -> Any: ...
def dynamicPropertyNames(self) -> Any: ...
def emit(self, arg__1, args) -> Any: ...
def enable(self) -> Any: ...
def event(self, event) -> Any: ...
def eventFilter(self, watched, event) -> Any: ...
def findChild(self, arg__1, arg__2 = ...) -> Any: ...
def findChildren(self, *args, **kwargs) -> Any: ...
def hide(self) -> Any: ...
def inherits(self, classname) -> Any: ...
def insertAction(self, PathBefore, PathAction, Removable = ...) -> Any: ...
def insertSeparator(self, Path) -> Any: ...
def insertWidget(self, *args, **kwargs) -> Any: ...
def installEventFilter(self, filterObj) -> Any: ...
def isEnabled(self) -> Any: ...
def isLocked(self) -> Any: ...
def isNull(self) -> Any: ...
def isSignalConnected(self, signal) -> Any: ...
def isVisible(self) -> Any: ...
def isWidgetType(self) -> Any: ...
def isWindowType(self) -> Any: ...
def killTimer(self, id) -> Any: ...
def lock(self) -> Any: ...
def maximumHeight(self) -> Any: ...
def maximumWidth(self) -> Any: ...
def metaObject(self) -> Any: ...
def minimumHeight(self) -> Any: ...
def minimumWidth(self) -> Any: ...
def moveToThread(self, thread) -> Any: ...
def objectName(self) -> Any: ...
def objectNameChanged(self, *args, **kwargs) -> Any: ...
def parent(self) -> Any: ...
def property(self, name) -> Any: ...
def receivers(self, signal) -> Any: ...
def removeEventFilter(self, obj) -> Any: ...
def sender(self) -> Any: ...
def senderSignalIndex(self) -> Any: ...
def setEnabled(self, Enable) -> Any: ...
def setLocked(self, Locked) -> Any: ...
def setMaximumHeight(self, Height) -> Any: ...
def setMaximumWidth(self, Width) -> Any: ...
def setMinimumHeight(self, Height) -> Any: ...
def setMinimumWidth(self, Width) -> Any: ...
def setObjectName(self, name) -> Any: ...
def setParent(self, parent) -> Any: ...
def setProperty(self, name, value) -> Any: ...
def setSpacing(self, Spacing) -> Any: ...
def setStatusTip(self, StatusTip) -> Any: ...
def setToolTip(self, ToolTip) -> Any: ...
def setVisibile(self, Visible) -> Any: ...
def setVisible(self, Visible) -> Any: ...
def show(self) -> Any: ...
def signalsBlocked(self) -> Any: ...
def spacing(self) -> Any: ...
def startTimer(self, interval, timerType = ...) -> Any: ...
def statusTip(self) -> Any: ...
def thread(self) -> Any: ...
def timerEvent(self, event) -> Any: ...
def toolTip(self) -> Any: ...
def tr(self, arg__1, arg__2 = ..., arg__3 = ...) -> Any: ...
def unlock(self) -> Any: ...
